### ISSUE TITLE
Item Name inventory [bug] 

### ISSUE THREAD

**Issue by ad1rie1** [YetiForceCompany/YetiForceCRM#10001]
# 🐞 bug report

### ⁉️ Describe the bug
Hello, 

When i set the itemname field non mandatory in setting : 
![image](https://user-images.githubusercontent.com/1949622/54823518-65f0b000-4ca8-11e9-89ff-36b9bb8f61a8.png)

it is mandatory in edit mode when you save  :
![image](https://user-images.githubusercontent.com/1949622/54823447-2e820380-4ca8-11e9-9fa0-8802ab9f935a.png)
 

### 🔥 How to trigger the error

1. Go to 'Managing an advanced bloc'
2. Click on 'Item name' and set it non mandatory
3. Go to the module and add new item, when you finish and clic save, you cannot save because mandatory itemname field

### 👎 Actual Behavior
Error and cannot save

### 👍 Expected Behavior
without product selected it can be saved

### 🌍  Your Environment **
i'm on Yetiforce 5.1

**Comment by adudekyeti** [comment]
Hi,
You have tooltip information next to select:
_"Applies to the entire record. If 'No' is selected, the record can be saved without any inventory lines"_
So if you want to save record without products you have to remove all inventory lines. Otherwise is not possible to save inventory product without name.

**Comment by ad1rie1** [comment]
Oh ok,  can you send me some advice to create simple inventory system without link to a module; ? 
I has thinking about fix each line created to a default shadow product and hide the name field. 

are you, in the code, an another method to do the same thing ?
