### ISSUE TITLE
[bug] Generated PDF's are huge

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10017]
Super basic PDF without text and with one little table (3 row and 3 columns) is 440 kb. It is not too much a bit? and again, in version 5.1 still cannot define borders colors using GUI. Can it be fixed to be like it suppose to be?

**Comment by rafalpospiech** [comment]
This is because full font files are included in the pdf file, we have plans to include only a specific subset of characters that are used in the document, but we do not know yet when we will release the update for that.

For borders you have already created another issue so write border specific questions there https://github.com/YetiForceCompany/YetiForceCRM/issues/10003

**Comment by waran70** [comment]
On the list of fonts, I have only DejaVu...

**Comment by rafalpospiech** [comment]
so?
