### ISSUE TITLE
same smtp server not work on yetiforce crm but  work on vtiger crm

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1005]
I set up the same setting of the outgoing server:
smtp.163.com
state003@163.com
470201
on vtiger crm:
![qq 20150603100256](https://cloud.githubusercontent.com/assets/12697896/7951453/fd1d783e-09d9-11e5-815e-e81350b3f25e.png)
on yetiforce crm:
![qq 20150603100124](https://cloud.githubusercontent.com/assets/12697896/7951466/16cd9ee4-09da-11e5-9960-f1239511cc06.png)

**Comment by bpabiszczak** [comment]
There is not much we can do with such issue, because we know nothing about the server and whether both applications are in the same location and what can be found in logs. I suggest you to read these articles:

https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/115-debugging.html 
Why is the field “From email” empty? Put the same email address as in username.
Try out the address, e.g. protocol://yourserver:port

**Comment by 1250572980** [comment]
I set the both application at the same location.how to get  debug log,like vtiger?

**Comment by 1250572980** [comment]
I set the both application at the same location.how to get  debug log,like vtiger?

**Comment by 1250572980** [comment]
I set the both application at the same location.how to get  debug log,like vtiger?

**Comment by waw555** [comment]
Use ssl://smtp.163.com:465

**Comment by 1250572980** [comment]
I find the problem is the smpt server must be same as the [your-support name] email.
like as:
![snip20150604_3](https://cloud.githubusercontent.com/assets/12697896/7965073/b411d1ca-0a4d-11e5-9e44-a869ff7899d5.png)
![snip20150604_4](https://cloud.githubusercontent.com/assets/12697896/7965099/f3960532-0a4d-11e5-9c90-70638e08f9a4.png)
how to set the [your-support name] email?

**Comment by 1250572980** [comment]
sorry,I find the setting.
![snip20150604_5](https://cloud.githubusercontent.com/assets/12697896/7965226/bd339bb6-0a4e-11e5-9bed-fde5be31dd42.png)

**Comment by mariuszkrzaczkowski** [comment]
Try to set this email address in your profile for which you are making this operation
