### ISSUE TITLE
Relation Error Again

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1013]
1.i ve created a new module
2.linked it with contacts 
3.at new module i can see the related contact(pic 1) and (pic 2)
4.When i am going to check the contact if the relation is good with the new contact
nothing there....empty (pic 3)
![pic1](https://cloud.githubusercontent.com/assets/6897502/7989004/43e0f294-0aef-11e5-9eea-b68b6dc24f93.jpg)
![pic2](https://cloud.githubusercontent.com/assets/6897502/7989007/49228290-0aef-11e5-932b-e46cdcca60e8.jpg)
![pic3](https://cloud.githubusercontent.com/assets/6897502/7989012/4fbb7dd2-0aef-11e5-8068-24711ca122e5.jpg)

**Comment by eptapsyxos** [comment]
I give you some more information
when i am selecting the new module
i see nothing as a mention above 
(pic4)
But if i pressed the add record pop up the window to create a new record(from the new module)
nothing happens...
![pic4](https://cloud.githubusercontent.com/assets/6897502/7989080/cec8f352-0aef-11e5-957c-daef5a5e36a4.jpg)
![pic5](https://cloud.githubusercontent.com/assets/6897502/7989109/00394ac2-0af0-11e5-8887-aa140961d860.jpg)


THEN I AM CHECKING BACK THE RECORD LIST OF THE NEW MODULE and the RECORD EXISTS!!!

**Comment by amicheals** [comment]
I think I have the same issue.

I add a custom field in the organization module called Owner. Owner is a related 1:M to module Contacts.

If I add a name in the "Owner" field from the organizations page, it creates the contact. However, the contact created does not show under the related tab Contacts in the organizations module.

However, the contact was create properly.

**Comment by mariuszkrzaczkowski** [comment]
I did a simple test I added two modules:
[RelOneToMany](https://test.yetiforce.com/index.php?module=RelOneToMany&view=List&parent=44)
[RelManyToMany](https://test.yetiforce.com/index.php?module=RelManyToMany&view=List&parent=44)

Added relationships:
RelOneToMany and Contacts - 1:M
RelManyToMany and Contacts - M:M

Added records, and shows correctly, it can improperly created relationships?

**Comment by eptapsyxos** [comment]
I made the same relationship with the same module with both ways the same time and that is occurred the error.

**Comment by bpabiszczak** [comment]
You need to provide a step-by-step description how we can reproduce this error on our testing version. If it works properly on the testing version, then you install WAMP and the latest version of YF. If you reproduce this error, you provide a step-by-step description, details about your environment and tell us how we can trigger it. If you migrated the system, you also need to describe it.

If someting doesn’t work on your installation, but everything is all right on ours and you aren’t able to describe how we can trigger it, then we won’t be able to help you because it might be related to a specific installation and caused by many circumstances. In this case, I would recommend you an individual analysis of the problem.
