### ISSUE TITLE
HTML/WYSIWYG widget

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1014]
An enhancement request.

Can there be a html widget where we can write custom messages or enter html or messages for different roles?

**Comment by bpabiszczak** [comment]
1. At the moment there is no such functionality but you can write it yourself. 
2. We don’t plan to add it because such info can be transferred in various ways [e.g. via email, task, ticket]. 
3. In the future there will be a more complex possibility to manage orders [it will be possible to assign them to roles].
