### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1015]
If you select to another as PDF, a menu appears in the logo area

![menubug](https://cloud.githubusercontent.com/assets/1402355/8000224/350d74ea-0b71-11e5-86c9-b989275c85ba.JPG)

**Comment by bpabiszczak** [comment]
Currently, our developers update the system to the latest version of Bootstrap 3.3.4, their changes can be seen for example here: https://github.com/YetiForceCompany/YetiForceCRM/commits/LAB-RS, and what I can see there were changes made in the menu on Friday: https://github.com/YetiForceCompany/YetiForceCRM/commit/0d00c4e57f19aa596095b3b7a5b1015ae6637be0. We want YetiForce to meet the standards and to be responsive. New version should manipulate menu in an easier way.

I will close this issue for now, because changes have been made, if a new version has problems with the menu, please reopen the issue.
