### ISSUE TITLE
[Question] portal user password email template.

### ISSUE THREAD

**Issue by hoeyer** [YetiForceCompany/YetiForceCRM#10160]
Hi there,

I am trying to find the TAG for password that i can add to the email template "Customer Portal Login Details"

I have tried to go through code, demo sites, developer sites and even checked the Vtiger site, but i have not been able to find the tag to add the users portal password to the email template.

Anyone out there able to help me with the right TAG?

thanks for your help.

**Comment by acsinsurancegroup** [comment]
Go to Email Templates http or s://yoururl/public_html/index.php?module=EmailTemplates&view=List&mid=146&parent=170 and look for the Customer Portal Login Details. This email will automatically go out once you have set it up properly. Obviously you would need to check the Portal User box in the contacts section. This should have been a checkable box in the Accounts section as well. You should see tag information once you open up that template. In my system it's record Number N10 hope that helps.

**Comment by hoeyer** [comment]
@acsinsurancegroup 
Thanks for your reply.

sorry my description was not god enough.

what I am missing is the actual TAG used to insert the password into the E-mail.

Please see attached screenshot of the template, as you can see the "password" has no TAG after it and i cant seem to find where the password TAG is.

![our template](https://user-images.githubusercontent.com/12031667/56015100-137b4000-5cf8-11e9-93b1-e976db631ae6.jpg)

**Comment by acsinsurancegroup** [comment]
@hoeyer You're welcome, sorry it didn't help. I'm assuming you created a test contact record with your information and clicked the Portal User box and the email you received didn't contain the password right?

You do know where to create the Portal login information in the Settings menu and how to setup the API stuff as well?

Sorry just trying to obtain as much info to better assist.

**Comment by hoeyer** [comment]
Hi @acsinsurancegroup 
Thanks again, nice of you to keep trying.

I have recorded a vid where i demonstrate what I mean.

https://share.vidyard.com/watch/PWWWkwGiE48oW2kBSTaFf6

it is not that the email is not sent, i have not configured the Cron job yet, as you can see when i open the actual email content, the password is not there. as you also see in the beginning of the movie, i have the template open and there is noget password "TAG" som there would never be a password added to the email. therefore I assume this is missing.

regaring setting up the API, i must say, that i have not done this yet, i have the customer portal running, but i have not yet configured much else then the URLs in the config files within the portal config folder.

**Comment by acsinsurancegroup** [comment]
@hoeyer Ahh ok I gotcha know. Thanks for the visual that helps along with the additional information. Here's what you would need to do.

Since you already have the actual customer portal installed and running, just make sure you do the following:

Step 1 - Open up the API config file in the root directory of your crm. Ex: http or s://www.yourcrmurl/config/Api.php and make sure that lines 20 & 21 are like this:

	/** List of active services. Available: dav, webservices, webservice */
	public static $enabledServices = [dav, webservices, webservice];

Step 2 - Make sure you normally check the Portal User box in the Contacts section of the CRM itself. (I seen you did this in your video)

Step 3 - Go to the Admin settings panel inside the CRM platform. The actual Portal User account is now created manually by you inside the Integration tab. This is a two step process. The first is:

Open up Under Integrations / Web service - Applications and click on Add key. You will need to name your portal something and then type your portal Url and create a password for the connection (not for your user) and make sure the Status box is ticked and click save.

The second part is still under Integrations / Web service this time go under users and click on Add record. Here is where you will create the actual user for the portal itself. You will then in the Server label connect the actual Portal that you created in the first part and set the Status to Active. Under login that's where you are creating the login credentials for the User that will be getting access and same on password. Then select Permissions based on user under Type and your language of preference and finally select the User who will be gaining access to the Portal. Yes, all Portal users will need to have an actual User account.

Step 4 - Is setting up your Cron jobs to run within your server administration panel. 

Now, what I would do is since you are manually creating the access anyway, I would just directly email the User with their login unless this is not feasible.

Or you could try this string $(translate : Users|Password)$: $(params : password)$ which you may have to lay with to see which one will generate the actual password into your email. Keep in mind that the system will not do this automatically for you unless you have setup your email template and cron jobs.

Hope all that leads you to a successful outcome.

**Comment by hoeyer** [comment]
Hi again,
Just to let you know, i finally got CRM and the portal working.
originally i tried getting things to work with Nginx instead og apache, this turned out to be not the best idea.
So i startede over, new Ubuntu server, Apache2 and so on.

I all seems to work just fine now, though i am getting a few issues with template mailfunctions. this might be my own mistake since i have been removing modules from the CRM software.

thanks for your help.
