### ISSUE TITLE
[Question] Will Yetiforce move more toward accounting?          

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10223]
Most of us know the advantages of OpenERP (Odoo) and Yetifirce. Combining functionality
will mass-kill all competitors. Shure that is not easy but.. is there any working plan of expanding accounting functionalities? Obviously, without reporting module this won't work... so it like a question about both ways...
No plans, close ticket pls

**Comment by PercyP** [comment]
Agree would definitely make it the best CRM

**Comment by KatarzynaUlichnowska** [comment]
@PercyP Isn't YetiForce the best yet? ;)

@ waran70, in this case, we aren't talking about CRM anymore, but about ERP ... creating ERP has one important disadvantage - it enforces compliance with tax law in a given country. We think it will be possible with future YetiForce partners.

In fact, we are constantly moving towards ERP, because we don't have much to do in the area of CRM (except for making YetiForce more intuitive). This month:
- we have improved the Correcting Invoices module,
- we have expanded the PDF so that you can dynamically generate a table with products and services,
- we have improved the calculation of taxes, discounts, and margins on financial documents,
- and probably many other things that I don't remember.

Our goal is to build a complete system, so we expand it in many dimensions, also towards ERP.

**Comment by PercyP** [comment]
@KatarzynaUlichnowska 
Yes :) which is why I am sticking at it.

Many CRMs have integrations with the specialist accounting software like Quickbooks, Sage etc. I know a couple of these work with vtiger. Maybe rather than building it in to the CRM it would be a better route to integrate with those 3rd parties - that way you don't have the headache of dealing with different tax laws. Plus they are integrated with banking apps to.
