### ISSUE TITLE
[bug] PDF table size

### ISSUE THREAD

**Issue by panos-stavrianos** [YetiForceCompany/YetiForceCRM#10222]
Hello everyone, i am facing a situation with the pdf invoice. 
To reproduce just create two products, one with a small name and one with a big one, then export an invoice pdf. The template is only $(custom : ProductsTableLongVersion)$
Using the small name it works nicely
![small name](https://user-images.githubusercontent.com/20128753/56463211-236de080-63d8-11e9-8c41-10237f740747.png)
but with the big name this happens
![big name](https://user-images.githubusercontent.com/20128753/56463218-46989000-63d8-11e9-8392-4051d27d867c.png)
Are there any suggestions on how to resolve this?

**Comment by rafalpospiech** [comment]
I confirm, when some text inside a table cell is wrapped, for example, by `<strong>`, the width of this cell field is not calculated quite well.

**Comment by rafalpospiech** [comment]
fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/10245

**Comment by panos-stavrianos** [comment]
Awesome! Thank you so much!

**Comment by rtorrescodes** [comment]
![Captura](https://user-images.githubusercontent.com/28415396/63066368-6136cd80-becf-11e9-9f3d-ac19fdba641e.JPG)

Hello, can some one help me please? im goint nuts with this same issue. I uploaded latest yetiforcepdf folder to the 5.1.0 online yeticrm version but this keeps happening. I dont know how to update with this issue fixed in #10245 

I also have another problem just like the screenshot i send. Table dosent get full width. If i fix this, content may be better displayed too. It also looks better to have full width as all tables.   

Please help. Thanks

**Comment by rtorrescodes** [comment]
I noticed it only happens with long descriptions or product titles. How can i try this fixed version?

**Comment by panos-stavrianos** [comment]
The width problem happened to me also... I did a clean install after the fix and it worked nicely. 
Side-note: I also try to update first but since I had a really old version and I probably didn't follow the update procedure correctly, i mess everything up. So make sure you follow all the steps and take backups
