### ISSUE TITLE
Date Range picker custom field

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10290]
Hi, 
I have created two fields now: Available from and Available Upto-----date fields.
Now when I have added these two fields in my search filter.
Now when I search I can only get results, If I give the exact date which matches the date in the  above two fields, but I want to see results when I provide a date between these two dates ( Available from & available upto). 

For example If a user is availbale from 30th april to 5th may, and if i provide a date say 2nd may, then I see the record.

So how to connect these two date fields, if not is there a way to put a date range in a single date filed.

Thanks

**Comment by davide-alghi** [comment]
Hi,
you can achieve that by filter conditions.
I know ... you have to modify conditions every time, anyway it works.

![Date Range picker custom field](https://user-images.githubusercontent.com/48508691/56880903-c8cf2700-6a5e-11e9-9ae7-2aa76b9f7dc6.jpg)

**Comment by indrabhusanroy** [comment]
Hi, thanks for understanding and quick reply.
I have tried this and this work but only for provided date for example 2nd may, but this is not possible when there are too many records. Basically if a user is available from a certain date to a another date & I provide a date which is between these two dates, I will see the record.

**Comment by davide-alghi** [comment]
My previous post contains an imprecision: because "before" and "after" comparators mean, respectively,
"less then" and "greater the" (without equals): that proposal needs to be
![Date Range picker custom field 01](https://user-images.githubusercontent.com/48508691/56902804-503a8b80-6a9b-11e9-9b6a-b5014e872adf.jpg)

**to include user time range edges too**.
PS: I added an always true condition on "Record number" field to get two groups (it seems that without a condition there, groups are not correctly saved: I'll check whether it's a bug) :((

Anyway ... please, let me to explain if I understood: your custom module contains some kind of users (maybe operators or something else).
So ...
 - each user have one or more availability date ranges (records) into custom module
 - your needs are to get all users (records) whose time range covers a specific day (or it intersects a days range)

if this is all and it's correct then my previous proposal get all users whose time range covers a specific day.
Following conditions get all users available on 2019-05-02
	
	"Available from" before 2019-05-02 AND "Available upto" after 2019-05-02
	
	from <= 2019-05-02 AND 2019-05-02 <= upto

![Date Range picker custom field 01](https://user-images.githubusercontent.com/48508691/56902804-503a8b80-6a9b-11e9-9b6a-b5014e872adf.jpg)



Otherwise to get users with at least one availability day into a specific days range [2019-05-08, 2019-05-12]

	"Available from" before 2019-05-12 AND "Available upto" after 2019-05-08
	
	from <= 2019-05-12 AND 2019-05-08 <= upto

![Date Range picker custom field 02](https://user-images.githubusercontent.com/48508691/56903092-ebcbfc00-6a9b-11e9-8506-50aaa22406ca.jpg)

If what I understood is wrong, please provide an example

**Comment by indrabhusanroy** [comment]
Yes you are correct upto a certain point.

I have two kinds of users:

1. Biologist who have to provide their availability. This availability is a range of dates. Say one user is available from jan 5 to jan 30. Another user can be available from march 30 to august 24 and so on there can be any number of combinations.

2. Clients who will search these biologist by providing any date to filter out.

But in your example above you have used a particular date to create the filter which cannot be done here  as there can be nay number of combinations of availability.
