### ISSUE TITLE
Round cube error "Server Error: STATUS: Server Unavailable. 15"

### ISSUE THREAD

**Issue by vinithsv** [YetiForceCompany/YetiForceCRM#1038]
hai , i have an issue related to roundcube in yetiforce CRM . When i login using my exchange credentials its showing "Server Error: STATUS: Server Unavailable. 15". Is this related to my IMAP if so please let me know what changes i have to make in the Exchange server.
Thanks you

**Comment by bpabiszczak** [comment]
Unfortunately, we don’t have any Exchange servers and we are unable to verify it so we can’t tell you how you should configure it.

We recommend you to see if the configuration works with a regular mailbox [e.g. set up free hosting] and also verify your configuration with an email client, e.g. Thunderbird in order to see if it works [excluding the fact that the problem is related only to YF]. Have a look at logs, contact your server administrator and he will tell you what he sees in Exchange logs.
