### ISSUE TITLE
[Question] How to Disable "Opportunity" and "Calculation"

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10472]
Hi.

I would like to disable the "Opportunity" and "calculations" tab in Quote.

If I do this via the Module selector, the workflow as selecting a preloaded Account is marked grey and I cannot add any details on it.

I wish to disable these two features but still be able to autoload an Account

**Comment by joelbcampos** [comment]
![capture-10](https://user-images.githubusercontent.com/29610537/58081926-3aaa1480-7bb6-11e9-85dd-85361c2de2ea.gif)

**Comment by MyBlissIT** [comment]
I have been doing it exactly like this. The grey background on "Account" after your edited both fields does not allow me to enter any data on the "Account" tab or column. This is the workflow I need to disable.

**Comment by joelbcampos** [comment]
You must activate the developer mode so that it appears below the field that is what you can do with it, once active you go back into the field and a drop-down will appear that includes the posivilidad to modify the field to the editable field, currently it You have a non-editable field.

https://github.com/YetiForceCompany/YetiForceCRM/blob/e3a2dbce628600e4fba11a36475dec866a8f4801/config/developer.php#L18

**Comment by davide-alghi** [comment]
Hi guys,

goal: **reduce sale process starting from Quotes**
PS: I suggest not activate dev-mode

my suggestion below (I splitted ani-gif in two parts because github file size limit)

![issue_10472_1](https://user-images.githubusercontent.com/48508691/58185824-12084480-7cb4-11e9-8f68-e838a9bb106c.gif)

![issue_10472_2](https://user-images.githubusercontent.com/48508691/58185875-24827e00-7cb4-11e9-9b8c-4d1e58a35518.gif)

**Comment by MyBlissIT** [comment]
Thank you @davide-alghi , your version worked wonders. Thanks to you to also @joelbcampos for your willingness
