### ISSUE TITLE
Suggestion: A simple way of handing migration and customized code changes

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1052]
As most of us know, implementing YetiForceCRM (or any other CRM system) will rarely go without code changes. Currently most systems, including YetiForceCRM do not offer a simple approach to dealing with code customizations which makes migration often a huge burden (and a significant cost position).

Here is a rather simple solution to address the challenge:

1.Define the directories which contain code that is user modifiable (pobably the modules, the languages, the layouts, and the includes directories)
2.Adjust the directory structure by creating a directory 'parent' and move all user modifiable directories to that 'parent' directory' and add a version number to each of the files
3.Create an empty 'child' directory (a directory which will hold all modified files)
4.Change the inclusion (require_once) of files from the modifiable directories as follows, illustrated for modules/Leads/Leads.php
4.1.If child/modules/Leads/Leads.php does not exist, include parent/modules/Leads/Leads.php
4.2.If child/modules/Leads/Leads.php exists, check if it has the same version number as parent/modules/Leads/Leads.php
4.2.1.If the version number is the same, include child/modules/Leads/Leads.php
4.2.2.If the version number is different, display an error message indicating an potential incompatibility problem

When a user wants to modify a given file, for example modules/Leads/Leads.php, he will copy the file from parent/modules/Leads/Leads.php to child/modules/Leads/Leads.php and make the necessary modifications (the version number in the child directory must not be changed).

Now when the system is updated, if the Leads.php file is not changed in the update, there is no need to adjust the customization, otherwise the user will be required to make approporiate changes. It would be event possible during the update process to display to administrator all the 'parent' files which have been changed in the modified version and for which a customed 'child' version was created.

I am convinced that this approach would be simple to implement and free many users from code related migration headaches.

**Comment by waran70** [comment]
Agree

**Comment by eptapsyxos** [comment]
Nice documentation thank you very much for your effort.

**Comment by bpabiszczak** [comment]
Look here:
1. 91c717232790ae656455a5a3fc6fac45fe2ade2c
2. 337c4aa50d25956a9c5abc120394ec51eaa4ce24
3. 4da2c73061a1e963d2f402a5398291ee31a9878a
4. 20f295faf75271247bfa05acadd84e0ed7cef44d

This week we will write documentations how it works.

**Comment by diderich** [comment]
That solution, I believe goes into the right direction. But:
1. I would prefer to have the code for handling custom includes in one place and not scattered around modules.
2. Your solution is missing a cross-check if the custom modules are still consistent with the not customized code. Having to manually check each customization after an update is not a viable option.

**Comment by bpabiszczak** [comment]
It’s impossible that customized code doesn’t require the verification of engine changes.

We have just added:

1. Overwriting of translations [single values in a language file] – it works in the way you wanted.

2. Overwriting of layouts [unfortunately, the entire file that will be overwritten needs to be copied] - if you have an idea how to update a fragment, we are open to your suggestions.

3. Overwriting of module files in which you are at the moment [this works within a module].

In the future we will add a possibility to overwrite any file by using vglobal. To do it, we have to eliminate fixed inclusion of files in the entire system and switch the loading logic to AutoLoader. Unfortunately, this will take some time so atm it’s without it. However, if you have time, you can help us with it ;]

**Comment by diderich** [comment]
As a simple ad-hoc solution, it would be great if each file in the would have in its code a version number specific to the file, one that is increased each time a change is made to the file and the change published. Ths could be a simple as a comment with "// File Version: 1234"
This would allow to check if a customized version is still in line with the master or if there were changes in the master file. If I customize a file X.php with version 1234, I can simply check with any subsequent release of my customization is still up to date by verifying that the master file X.php still has version 1234. If it were to have a new version number, e.g. 1235, I would need to change my customization.
Without such a mechanism it would be very hard and time consuming to find out if my customization is still in line with the master version (as a simple comparison of the master and customized version will always give differences).

**Comment by bpabiszczak** [comment]
It is technically impossible, many files are mass modified [e.g. as a result of the change of coding or EOL], some of the new functionalities are libraries with thousands of files. The thing that you need is in fact WinMerge, it is used for comparing various file and folder versions [we use it for defining which changes we need to introduce from Vtiger]. Additionally, there would be many errors in case a developer forgets to change version number [from time to time they already forget about it] so it would only make things more difficult.

To sum up the discussion:
1. Some of the mechanisms, which make it easier to modify the engine, have already been added and they provide new options. 
2. Some of the mechanisms that are also required will be added in the future because it is necessary to make some changes within the engine [remove include from all files in order to leave autoloader/loader on its own]. We will add it, but we are unable to specify when because it will depend how much our community or how much we need it. 
3. I don’t think the idea with numbering system is a good one. If you think differently, please open a new issue and provide pros and cons of this solution. It would be great to see other projects where it was successful. With this info we will be able to approach this subject better.
