### ISSUE TITLE
Discussion: The meaning of Accounts (currently translated Organizations)

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1063]
Katarzyna Ulichnowska writes "In my opinion the English translation of the Accounts module should be Accounts, not Organizations."

If the logic is that an "opportunity / sale / ..." relates 1:1 to an "Account", then there is a need for a separate module "Organization" because an oranization may have multiple "Accounts", for example different departments, and an "Account" may have different "Contacts" as can an "Organization".
- An "Account" would be associated with 1 "Oranization" and 0:n "Contacts"
- A "Contact" would be associated with 0:1 "Organizations" and 0:n "Accounts"
- An "Organization" would be associated with 0:n "Accounts" and 0:n "Contacts"

In that sense of the definition of "Account", what should a "Lead" translate to? In a puristic way, a "Lead" should be similar to an account in the sense that it can be related to 1:n "Contacts" and 0:n "Organizations". There would be a 1:1 translation of "Lead" to "Account", that is the relationships to "Contacts" and "Organizations" would be migrated / copied.

This definition of "Account" makes the sales process very clear. But it is an open question for me whether the concept of an "Account" is really needed as its main purpose is to serve as an aggregation for relationships between "Contacts"+"Organizations" and stages in the sales process (Opportunity, Sales Order, Invoice, Project, ...)?

**Comment by bpabiszczak** [comment]
On 20/05/15 10:39, Błażej Pabiszczak wrote:
In general, we aim to have something called EDI. I don’t remember any
documents ever assigned to individuals. Documents are issues for
companies, then this document is sent as it had been specified in the
contract and a specific department processes it. There are certain
procedures in companies to record an invoice. Even if there is a person
assigned to an invoice that we issues, we never know who it is. The only
think we know is to whom we sent it to [nothing more] so the only thing
that you would use this field for is to know to whom you sent an invoice
and who can be contacted.


I am not sure EDI has anything to do with it. That is just a method for
processing data between applications, not about the way you manipulate
that data in one application.

Customer Relationship Management software is there to manage
relationships with your customers, and that customer, to all intents and
purposes on a practical level, is the Contact/Consumer, not the Company.

Documents such as Invoices do indeed legally bind companies, but when
you are dealing with sales, you negotiate with a Contact who is acting
on behalf of the company, and therefore communication is directed to
that person.

When I was a Sales Rep (i.e Representative of my Company) I did not go
to see a 'Company'. I saw a rep of that company. That is who I dealt
with, not 'the Company' itself, even though they are the legal entity.

Sales is about a person to person relationship and a CRM is
fundamentally there to track that relationship and its activity.

I have been watching the progress of Yeti from a distance as a possible
replacement for our current vtiger and had been impressed to date.

I have just been playing on the test version at test.yetiforce.com to
see the effect of the 'Contacts' link removal as this would affect us
massively.

Something seems a little odd in your logic.

I cannot create an Opportunity or SO or Invoice and link it to a
particular Contact from the new document.

But if I go to the Contact it shows related fields (assuming they have
been created somewhere) and allows me to create one of the documents
directly from the Contact. That is illogical. Either it is linked or it
isn't ?

For us there is absolutely no way that we could work with this. All of
our documents are based on the Contact. They are the person that you
deal with when making a sale. Not the Company (although they are
obviously linked). We assess sales on both the Company and the individual.

When a customer phones, we don't search by company but by Contact. When
we invoice a company, they are the referenced by Contact so the their
Company knows who placed the order (and so do we). We can see what
Opportunities/SOs/Invoices etc are linked to that Contact. The 'Company'
is almost an irrelevance. The Contact is king. They are the ones that
make the buying decisions, even if by proxy back to a committee or other
body.

We have numerous clients with multiple offices. We need to decide per
Contact where communications go. We also have multiple Contacts within
one organisation.

We may want to invoice to where the Contact is, or possibly where the
Organization is - they could be different, and depending on the
situation the address may vary.

(On a side note we currently have a similar situation with Vendors where
goods get shipped direct to client and not us which takes some work to
get around. We would love to see Vendors having multiple Contacts the
same way as Organisations do and the ability to ship to a Contact
Address, not just our own)

I cannot understand the logic of your decision and you still haven't
really explained it very well. It makes real no sense. It may suit if
you are selling online, or elsewhere where there is no real relationship
with a customer, but in our case we deal personally with every single
customer. Removing flexibility and making blind assumptions is not a
good move IMHO.

Yes, I am sure the code change could be reverted, but who knows when you
may decide to remove other code that it depends on completely ? As
another mentioned, it is far better to add an option switch than just
remove the function.

I personally hope that you revert your decision. Yeti is good, but now
completely unusable for us. And it seems from list comments that we may
not be alone.

B. Rgds
John

**Comment by bpabiszczak** [comment]
Stacey

Welcome John :-) 

I do agree with you and tried explain that too. Yeti should come back to the worldwide approved model.
It is simply what we can learn in faculty of marketing, management etc.
Saying that it can be done easily is obviously blinding eyes. 
Developers and 90% or more users will require ties for PO, SO, Quotation, Invoice with contacts. 
I also agree with Katarzyna from other post that Organizations should be renamed to Accounts as this will be more readable.
Accounts are either Organizations or private customers and both can have set of contacts responsible for various documents what we can assign as we need to.

Two of my customers are in the marketing fields for many years and they get very surprised seeing latest test version of YF.

**Comment by reetp** [comment]
:-)

Naming conventions are just that. We all have pet loves and hates.

I never liked the vTiger change to Orgs but c'est la vie - it's just a name

'Accounts' seem more finance orientated. By all means have Orgs, Accounts, relate them all - no problems. Just don't break relationships. FBook works because of the tangled web it weaves. It's all about connections.

I believe there used to be a vtiger plugin that used to allow many to many relationships because, just as in real life, there is no one single relationship that covers all bases.

For me the Contacts thing is the single biggest issue, and I can't think of any organisations that I know that would feel any different. It's a complete blocker for me, end of story.

As I also mentioned, Vendors is a major pain in vTiger - we might be dealing with 3 or 4 people minimum with some of our suppliers - hard to note who you talked with etc etc. That needs a separate "Vendor Contacts" IMHO.

Business is a people thing still. People talk, buy, and sell, to other people. The companies are just the legal entities and instruments we use to limit our liabilities when we get it wrong :-)

Ultimately a CRM is a people management system.

**Comment by waran70** [comment]
That's correct John.

**Comment by KatarzynaUlichnowska** [comment]
From Doug:

Not to pile on...
But I coach people and companies in sales and process management. 
www.Sandler.com

The new process is unusable for most people and I would NOT recommend Yeti to my clients.
I have been looking at a vtiger migration for myself and our clients.  That can not progress under the new model.

From Ian:
I do like option where we can add unlimited contacts (related list) to entity module (such invoice etc) to let them see document in their Customer Portal. It great function which can be spread around all modules including projects down to tasks (however it not works yet in CP), but linking one-to-one contacts or organizations is crucial.

**Comment by kpaulaha** [comment]
We had to go back to vtiger with customers who collect leads with webforms, needing of cource both name of company and contact.

**Comment by SkavenKF** [comment]
Hi Yetiforce team

due to a current project in which I participate (Introduction of a B2B CRM in one of the Germany's largest utilities ;-), i was currently not really to me to deal with the current version 2.0 of YF in the last weeks.

Actually, in the next few weeks I had planned to replace the vtiger installation in our company by YF 2.0 and have looked at the last changes.
However, I realized that you have changed, in my opinion, an important function of a B2B CRM system, to remove the contact of a company from the corresponding objects (opportunities, quotes, orders, etc.). Your decision to have multiple contacts is basically ok, but then you must marked one of these contacts as the main or default Contact and show it in the detail view.

Our customers have partially several thousands of employees in different departments which buy our products, how should our key account manager at a glance who is the relevant contact person.

I think you are doing a great job and also many things right with Yetiforce. Unfortunately you surprise the community with basic changes in the business logic, which at least makes me difficult long term put on YF. Such elementary changes should be optional (in the settings) and must be announced and should be discussed by the community.

I hope I could give you some suggestions, since I can not use or recommend the current YF so.

Greetings

**Comment by maikst** [comment]
+1

too many important changes, new, changed or deleted functions and so on...
in a short time.
For me it is impossible to use this product for customers under this
circumstances.

The reason why I would like to see a roadmap that can be discussed... I
wrote it before and can repeat this several times in the future :-)

cu
Maik



2015-06-19 23:22 GMT+02:00 Karsten <notifications@github.com>:

**Comment by waran70** [comment]
Just posted about that in mailing list... seems we all understand in the
same way. I hope yetifoce guys will understand too otherwise It will be sad
for me to leave here

**Comment by reeid** [comment]
In here, we have approx 650 customers and all of them are represented by human. It would be convenient to have those important modules possible to relate to Accounts or Contacts.
Actually thinking of migration, just this issue seems to be blocker.

**Comment by bpabiszczak** [comment]
waran70 wrote
As it was mentioned in mailing list, it seems to be enough reasons to be able to relate entity modules to organizations AND contacts. Without considering giant quantity of use cases which are based on Contacts as a primary customer this function was removed. It reflecting even in Portal operations. Looks like role of customer who got First and Last name has been here depreciated. This is very wrong operational logic which will not help YetiForce in expansion. 
I would like to ask (not only in my name) to return to previous model and keep entity modules running in line with vtiger, so migrations and other goodies can be applied without issues.. Additional functions and eventually logic in choosing model of use case could be enabled as a separate configuration.
