### ISSUE TITLE
[bug] User Default activity type become ready-only once edited

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#10646]
# 🐞 bug report

### ⁉️ Describe the bug

Once user default activity type had been set, the field became read-only and can't be edited anymore.

Steps to reproduce the behavior :
1. Login to Yetiforce Official demo and go to User Preferences
2. Change default activity type to something else
3. Save
4. Try to change it back --> unable, field is read-only now.

### 👎 Actual Behavior
Default activity type can't be edited more than once.

### 👍 Expected Behavior
Default activity type should be editable anytime.

**Comment by davide-alghi** [comment]
Hi apcloic,
you are right, it's a bug. Same behaviour for Default Event status.

Tomorrow I'll try to explain the bug: it's not easy and I'm so tired now. I'm going to sleep :)

**Comment by davide-alghi** [comment]
The problem step by step

1. in /layouts/basic/modules/Users/Edit/Field/Picklist.tpl:29, $FIELD_MODEL->isEditableReadOnly() is called and return false: so field is readonly. This because ...
2. isEditableReadOnly() function in /modules/Users/models/Field.php:157 call parent::isEditableReadOnly() function in /modules/Vtiger/models/Field.php:666
3. in /modules/Vtiger/models/Field.php:479 getPicklistValues() function set 'isEditableReadOnly' field attribute to true, because it cannot found all Picklist values and for protection reason picklist is locked

At this point, why are all picklist values not found?

User profile "Default activity type" field values should come from Calendar "Activity type" field and 
user profile "Default Event status" field values should come from Calendar "Status" field.

User profile "Default activity type" field system name is "defaultactivitytype", instead Calendar "Activity type" field system name is "activitytype" and
user profile "Default Event status" field system name is "defaulteventstatus", instead Calendar "Status" field system name is "activitystatus"

getPicklistValues() function, at 3. above, get picklist values from vtiger_<systemFieldName> table: so it is looking in wrong tables.
Respectively vtiger_defaultactivitytype and vtiger_defaulteventstatus tables, but correct tables are, respectively, vtiger_activitytype and vtiger_activitystatus

Now the question is "why does it work fine and sometime not?"
Because in database, vtiger_defaultactivitytype and vtiger_defaulteventstatus tables exist: I don't now why, but there are.


===== Solutions =====

First one
Each fields couple should point to a "shared picklist" (field with the same system name); "defaultactivitytype" becomes "activitytype" and "defaulteventstatus" becomes "activitystatus": but this require to change a lot of core code

Second one
In /modules/Users/models/Field.php:79 for getPicklistValues() function add "if" for "defaultactivitytype" and "defaulteventstatus" with relative "select from correct tables" and route self::isEditableReadOnly() to self::getPicklistValues() when "defaultactivitytype" or "defaulteventstatus" is encountered.


I stop here because the decision is delicate and it is up to the YF-team.
