### ISSUE TITLE
  How to  Add  Create event task for custom module

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10666]
### Description  

How to  Add  Create event task for custom module

![Add event](https://user-images.githubusercontent.com/47585969/59093115-7daa0d00-8956-11e9-833b-8a3c1b73f952.JPG)

![Event action](https://user-images.githubusercontent.com/47585969/59092994-358aea80-8956-11e9-9975-d2b6a598da08.gif)

**Comment by rskrzypczak** [comment]
Hello,
If you want to be able to create calendar records for custom modules then workflow actions require modification in the database, namely the  com_vtiger_workflow_tasktypes table, where you can specify for which modules this action is available. 
However, you won't be able to relate a newly created calendar record with any other record, eg. with the custom module record, because calendar relations work based on hierarchy.

**Comment by guide5232** [comment]
We tried to modify in the database but it showing the read only mode.

**Comment by vovpff** [comment]
What tool you use for database modification?

**Comment by guide5232** [comment]
DBeaver

**Comment by vovpff** [comment]
I'm not databases guru but I know what some tables in yetiforce looks like read only in phpmyadmin. This can be fixed by some modifications of phpmyadmin config file. I think DBeaver has the same situation.

**Comment by apcloic** [comment]
> However, you won't be able to relate a newly created calendar record with any other record, eg. with the custom module record, because calendar relations work based on hierarchy.

@bpabiszczak
In order to achieve this, adding the custom module to ModuleHierarchy do the trick, is there any particular issue with such a modification ?
 #7067
