### ISSUE TITLE
Which versions you are using    ?    

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#10661]
Dear YETIFORCE users!

So far, I have used the application mainly for the test and the last four published versions. Since you probably have similar problems with new versions and updates, please tell me which versions you are using or which you find most stable and useful.

Thanks

**Comment by vovpff** [comment]
5.1 works well

**Comment by SkavenKF** [comment]
Currently 4.0 productive. 
We wanted to update to 4.2 but had massive problems 4.1 => 4.2 at that time.

Since the Reporting Modul for our management is currently missing, an update is unfortunately not an option at the moment :-( 
Due to a lack of release planning, the associated planning security and short-term changes shortly before a release, my management is considering whether YetiforceCRM should continue to be used :-(

**Comment by ippeas1** [comment]
4.3.0 mainly and 5.1.0 in one system
