### ISSUE TITLE
[Feature]    Some ideas about reporting engine

### ISSUE THREAD

**Issue by umbz** [YetiForceCompany/YetiForceCRM#10707]
Yf is a great piece of software but lacks of a decent report engine.

 might be a good idea integrating yf with some other good pieces oft softwares like

metabase  [www.metabase.org](www.metabase.org)
reportjs [jsreport](https://jsreport.net)
or
redash [redash](https://redash.io)

?

regards

**Comment by bpabiszczak** [comment]
External reporting systems are used when you need to connect a number of independent systems and generate combined reports. It makes sense, as long as the permission layer is ignored [eg. when reporting from the perspective of all data]. Unfortunately, external systems will never understand YetiForce's permissions, because they are on the PHP layer, not SQL. From the practical side, you can use these tools, but they are unlikely to be ever supported by us [and they don’t have to be].

On the other hand, I believe our analytical / reporting tools are much more advanced than most of you think ... but this is a separate topic for a separate discussion.
