### ISSUE TITLE
error after installation 

### ISSUE THREAD

**Issue by timchinabuy** [YetiForceCompany/YetiForceCRM#10832]
I installed ampps and tried to use it in my office on local network environment. But after installation and certain set up, the follow errors come up. can you advise what i have to do?

! ) Fatal error: session_set_save_handler(): Session handler's function table is corrupt in C:\Program Files (x86)\Ampps\www\192.168.1.223\erp\app\Session.php on line 32
--

1 | 0.0030 | 360000 | {main}( ) | ...\index.php:0
2 | 0.1150 | 4184736 | Vtiger_WebUI->process( ) | ...\index.php:24
3 | 0.1600 | 5347296 | App\Session::init( ) | ...\WebUI.php:102
4 | 0.1610 | 5377944 | session_set_save_handler ( ) | ...\Session.php:32

**Comment by davide-alghi** [comment]
hi, what about your XAMPP version? it seems a problem related to XAMPP 7.1.30.
If your version is 7.1.30, please try XAMPP 7.2.19 (not with XAMPP 7.3.6: YF is now in testing for PHP 7.3)

**Comment by paula-w** [comment]
1. Unfortunately, we don’t provide support for servers, especially for environments we don’t recommend, like windows.
2. We can’t really help you because you didn’t attach a screenshot with your configuration
3. Have you installed your system using Softaculous? If you did, you should ask for help on their forum.
If you want we can install YetiForce in our cloud for a month for free for you, during this time you can test the system and fix the issues with your installation. If you’re interested, get in touch with us -https://yetiforce.com/en/company/contact – and we’ll let you know what information we need from you.
