### ISSUE TITLE
[Question]           Impact on performance with Advanced Permissions?

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#10934]
Hi, 

I noticed that my website became very slow after using advanced permissions. Cron kept turning for hours...
What is the impact of advanced permissions on website performance?

Also, what is the influence of the priority parameter?

Kind regards,

**Comment by paula-w** [comment]
It depends on your server and the number of users and data.
This option does however consume more resources than the default one and we only recommend using it on very fast servers.
For large databases with a lot of data and users we don’t recommend it at all because it might take hours to recalculate everything.
We would generally not recommend using this option.
