### ISSUE TITLE
[bug] Fontawesome index.js missing

### ISSUE THREAD

**Issue by Pietrox** [YetiForceCompany/YetiForceCRM#10979]
### ⁉️ Describe the bug

We are getting error 404 from ExceptionError.tpl on lines 72 and 74 requesting:

libraries/@fortawesome/fontawesome/index.js
libraries/@fortawesome/fontawesome-free-solid/index.js

It happened during git pull when trying to deploy a second staging instance.

I see those are missing files in our installation. Is there any way to recover them manually or do we need to do fresh install?

**Comment by rskrzypczak** [comment]
I don't know what version you're using but if you are using intermediate versions between stable releases you might stumble upon a number of problems, since library update (composer), or conversion of .js or .scss files might be required. However, the elements you mentioned were removed not too long ago. https://github.com/YetiForceCompany/YetiForceCRM/commit/8c8a2dc30019af4c1c0f093589749e66b6d1c417#diff-194b1d60066488698325607839c63157L72
