### ISSUE TITLE
Need help installing YetiForce on 000webhost hosted website

### ISSUE THREAD

**Issue by djhome50** [YetiForceCompany/YetiForceCRM#11182]
Hi, I was wondering if anyone could help me install the YetiForceCRM on my website. I’ve uploaded the YetiForce Complete 5.1.0 version but when I go to access the Install.php it just brings me to a blank page displaying a message at the top saying:
“Directory not found: vendor/rmccue/requests. For more information, visit https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/category/installation-updates”
Does anyone know what could be causing this issue & how to fix it?

**Comment by mrzewnicki** [comment]
Maybe cheeck does the dir exist? if it is, I would suggest check permission to directories.  Other way you also can instal 5.0.0 and update to 5.1. Update sepcially on fresh system and good server it's about 5-10 seconds. I didnt have any problem with install 5.0.0-complete version. 

I think this is not bad way to check because if there will be the same error on 5.0.0 that mean that's something wrong with your configuration. For now you must wait for verification. It's quicker way to check what is the problem i think.

**Comment by djhome50** [comment]
I just tried with version 5.0.0 complete and am still having the same error. I have the permissions set to 777 recursive which I believe is the highest. 
Is there anything else that it could possibly be?

**Comment by vovpff** [comment]
Chmod?

**Comment by mariuszkrzaczkowski** [comment]
did you check the logs?

**Comment by mrzewnicki** [comment]
If permissions are 777 check the owner. it should be user accessable from network, "www-data" for example. Check logs as Marisuz suggest. If you can not find logs it should be in /your_path/yetiforce/cache/logs. If there is nothing yo should check configurations of logs "/your_path/YetiForce/config/**Debug.php**" here you can turn on the logs
