### ISSUE TITLE
Customizing Product table, tax summary table and discount summary table

### ISSUE THREAD

**Issue by dfanaei** [YetiForceCompany/YetiForceCRM#11210]
Hi,
So far everything has been great in yetiforce except the pdf.
I'm having a hard time with the PDF maker especially when it comes to the Product table. 
I have a few questions:
1. Is there a possibility to separate the value of the tax summary from its' table? for example, I only want the total tax value and the total percentage.
2. Is the same possible with the discount summary?
3. How can I customize the product table? and tax summary/discount summary table? I am referring to the colors and fonts. is there a way I can do it directly through PDF module/ variable itself? ( Header background color, Table body font weight, etc.)
4. Will there be a module similar to Vtiger PDF maker in the future? That plugin was really helpful in vtiger, it made a big difference as proper report exporting is a really important feature to have in any CRM. 
Thanks in advance!

**Comment by KatarzynaUlichnowska** [comment]
We add functionalities that we need on a regular basis. None of our customers needed to color the table with products. The PDF module does everything we needed. We understand your business requirements, but all things that appear in the system are the result of a customer's order. Every month we add new functionalities in PDF [e.g. in the new version, you will be able to decide which fields should be visible in the product table before you print the document].
You can also ask the producers of PDFMaker to adapt the module to our system. Although as a company we prefer the community to contribute to the development of the built-in module because many users have a lot of requirements associated with it. Gather 50 people and everyone can contribute 89 EUR (the price for PDFMaker) and in total it will be nearly 4,500 EUR and we eagerly expand the module for you :]
