### ISSUE TITLE
mail list (YF database) 

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#113]
dont see pictures from foregin servers attached to mails in mails detail view (mail list module).

**Comment by KatarzynaUlichnowska** [comment]
Hello,
it has been blocked in order to increase security and to make it impossible to track a user who opens an email. We will probably add the possibility to download external pictures, but it has a low priority because roundube is used for receiving emails and the upload of external pictures is used only to load logs by marketing spammers and companies.
