### ISSUE TITLE
image lost issue comeback again

### ISSUE THREAD

**Issue by xinkyo** [YetiForceCompany/YetiForceCRM#11307]
the contact image and user image will lost after several days. my system is new install +service pack2 and service pack 3.
https://github.com/YetiForceCompany/YetiForceCRM/issues/10164
I check file is fixed as above.
but image still lost.
![f928c578c90e856604c674d3cfa13cb](https://user-images.githubusercontent.com/43132285/63333005-3505cb80-c36b-11e9-9ebc-0ea58ee5db3c.png)

**Comment by rskrzypczak** [comment]
If you lost images then they are gone for good because they were most likely removed from the server. 
You can verify it on the basis of the data in database for this file, there should be a path to this file. If you have a backup you can copy the missing files to the /storage directory. Otherwise you have to add these images again.
