### ISSUE TITLE
How to make workflow updating every 30 second          

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#11367]
I see post below and have question: I have workflow Update related record. How to set yetiforce to trigger it every 30 seconds?

**Comment by JohnMaverick** [comment]
Why Last Scan times are very different than set frequency?

![image](https://user-images.githubusercontent.com/29787568/63895412-44df7880-ca19-11e9-8e3d-d53b1695b415.png)

**Comment by z0lo13** [comment]
@JohnMaverick, first of all, it is recommended 15 minutes for workflow
2nd, why do you need it to run every 30 seconds? by looking without logs I can say your task never finished

**Comment by KatarzynaUlichnowska** [comment]
1. A workflow can be triggered even every 1 second, but only a developer should enable it as he understands the consequences of such action.
2. The "Last scan time" may be different from the set frequency, it is due to the fact that there are two mechanisms, one in CRM and the other on the OS layer. If the frequency in the operating system will be set for every 15 minutes, then regardless of what you set in the CRM system [e.g. 5 min] won't trigger CRON earlier than after 15 minutes.
