### ISSUE TITLE
📣 YetiForce 5.2 released!  🎉 

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#11421]
We have just released long-awaited **YetiForce CRM 5.2**! First of all, we would like to thank all community members for their patience and support. Thank you for the time that you spent for testing, sending pull requests, submitting issues, and translating YetiForce into so many languages. We would like you to know that we are aware of all your efforts and every single contribution and that motivates us to work even harder. 

The new version brings over 1000 new and significant changes but there are a few major things 🔥🔥🔥 that make this release different: 
- **Marketplace** - now you can purchase support packages and modules directly from the system. However, the prices of the products and services vary depending on the size of your company, which is determined by the number of users. It is also possible to become our Partner directly from the Marketplace.
- **YetiForce Chat** - it underwent a complete makeover, now it’s modern and even more functional
- **Knowledge Base** - created in VUE technology, completely new and powerful module that enables you to relate records to Documents, Tickets, and Projects. It also provides the possibility to prepare a multimedia presentation.
- **Advanced Ticket System** - now assigning and resolving Tickets will be more simple than ever because there is a new panel for creating custom SLA Policy rules.
- **Libraries Vulnerabilities** - now it’s a separate tab in the admin panel where you can monitor vulnerabilities in real-time, once again YetiForce takes care of your data’s security.

As usual, a detailed changelog will be posted on our official website in the [Developer Documentation](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation) - expect it on Monday.

💸**OPEN COLLECTIVE** 
We would like to remind you that some time ago, we joined [Open Collective](https://opencollective.com/yetiforcecrm) where you can donate to our project and help us develop new versions of the system. We also collect money towards 3 functionalities (Webforms, Reports, and PBX) that the community has been requesting for a while. We encourage you to visit our [collective](https://opencollective.com/yetiforcecrm) and chip in by donating even a small amount. If you want to find out more, take a look at the issue https://github.com/YetiForceCompany/YetiForceCRM/issues/10839

 🤝**PARTNERSHIP PROGRAMS**
We have also launched Partnership Programs, which you can find in the system as well as [here](https://yetiforce.com/en/yetiforce/partnership-programs)
There are three programs: YetiForce Reseller, YetiForce Module Producer, YetiForce Integrator.

🎯**LINKS** 
- GitHub - https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0
- SourceForge - https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/5.2.0/YetiForceCRM-5.2.0-complete.zip/download 
- Softaculous - It usually takes a few days for the new version to be released by Softaculous.

**UPDATE & REQUIREMENTS**
We would like to remind everyone that updates should first be executed on a test version, and only then on the production version [you should always have a backup copy of your environments].
- The list of current web server requirements necessary for version 5.2 to work properly can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)
- A detailed description of the installation process can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-update)

Enjoy and have a great weekend!

**Comment by vovpff** [comment]
Eeeeehhaaa

**Comment by LaurensCleyman** [comment]
This is the best day of my life.

**Comment by svdaru** [comment]
When will translations and lib_roundcube be available for new version?

**Comment by mariuszkrzaczkowski** [comment]
> When will translations and lib_roundcube be available for new version?

@svdaru Already published

**Comment by metrotyranno** [comment]
When will portal 2 release?

**Comment by zimart** [comment]
mam problem z app - własne moduły - czy jestem w stanie coś zrobic aby działały jak na 5.1 - czy musze budować od poczatku ?

**Comment by bpabiszczak** [comment]
@zimart nic szczególnego nie zmienialiśmy, może programista coś podpowie... ale odpowiedź jak zawsze jest w logach :] Pewnie jakaś pierdółka.

**Comment by liviubbo** [comment]
Class 'Config\Components\Branding' not found

**Comment by acsinsurancegroup** [comment]
No matter what I do, this is what I get when trying to install the latest 5.2 Complete version. I have NEVER had this happen before. All of my required settings are set correctly and I had no PHP issues or anything. 

I have a Plesk Server running on Centos 7 hosted with 1 & 1 Ionos. I have 5.1 installed on the same server with no issues whatsoever. 

Help please :)

![Unsuccesful](https://user-images.githubusercontent.com/42642523/64659692-b00a5100-d402-11e9-9127-4789f7d25237.png)

**Comment by waran70** [comment]
@acsinsurancegroup - chmod chown?

**Comment by mariuszkrzaczkowski** [comment]
@acsinsurancegroup 
logs?
was the database empty?

**Comment by acsinsurancegroup** [comment]
> @acsinsurancegroup - chmod chown?

Hi @waran70 Yes I even tried changing the permissions all to 0755 since originally the files were 0644 and directories where 0755 but still nothing. I had all permissions matching the other system that is running fine, no luck.

**Comment by acsinsurancegroup** [comment]
> @acsinsurancegroup
> logs?
> was the database empty?

Hi @mariuszkrzaczkowski thanks for responding, really appreciate the help.

Yes I deleted the database after every fail and tried again and still keeps failing. I tried installing from http and https with and without using the public_html directory and just fails repeatedly no matter what I do.

I have installed every version from the beginning and this one is the only one that has ever failed me. Here are screenshots of the entire process step by step since I really couldn't post the logs since it keeps failing.

![Yeti1](https://user-images.githubusercontent.com/42642523/64676673-aea94a80-d43b-11e9-86eb-92b0a8825cb1.png)

![Yeti2](https://user-images.githubusercontent.com/42642523/64676689-b79a1c00-d43b-11e9-927a-6434b668b311.png)

![Yeti3](https://user-images.githubusercontent.com/42642523/64676713-caacec00-d43b-11e9-9f28-51a6d5a8bd3c.png)

![Yeti4](https://user-images.githubusercontent.com/42642523/64676721-d0a2cd00-d43b-11e9-8070-2e4e536e2aa4.png)

![Yeti5](https://user-images.githubusercontent.com/42642523/64676744-ddbfbc00-d43b-11e9-9380-da535c066660.png)

![Yeti6](https://user-images.githubusercontent.com/42642523/64676749-e2847000-d43b-11e9-9a07-e3abdd0c0327.png)

![Yeti7](https://user-images.githubusercontent.com/42642523/64676760-e7e1ba80-d43b-11e9-9fe5-b0b405457295.png)

![Yeti8](https://user-images.githubusercontent.com/42642523/64676774-eca66e80-d43b-11e9-8f75-635041da94c9.png)

![Yeti9](https://user-images.githubusercontent.com/42642523/64676784-f29c4f80-d43b-11e9-989b-50433285d264.png)

![Yeti10](https://user-images.githubusercontent.com/42642523/64676823-02b42f00-d43c-11e9-9aea-6a5bd9be42f8.png)

![Yeti11](https://user-images.githubusercontent.com/42642523/64676851-0e9ff100-d43c-11e9-84ae-9ab9bf0d3e9e.png)

![Yeti12](https://user-images.githubusercontent.com/42642523/64676861-1495d200-d43c-11e9-9023-98378432bfe1.png)

![Yeti13](https://user-images.githubusercontent.com/42642523/64676870-1b244980-d43c-11e9-9847-a40125c0dc2b.png)

![Yeti14](https://user-images.githubusercontent.com/42642523/64676882-1fe8fd80-d43c-11e9-88e6-fee27311750a.png)

![Yeti15](https://user-images.githubusercontent.com/42642523/64676892-25464800-d43c-11e9-8ccf-83645489e1b2.png)

![Yeti16](https://user-images.githubusercontent.com/42642523/64676904-2aa39280-d43c-11e9-9bdb-902c7afc251f.png)

![Yeti17](https://user-images.githubusercontent.com/42642523/64676924-31320a00-d43c-11e9-9985-7812c0fafc3e.png)

![Yeti18](https://user-images.githubusercontent.com/42642523/64676934-35f6be00-d43c-11e9-86f2-de12ffdba1a1.png)

![Yeti19](https://user-images.githubusercontent.com/42642523/64676943-3bec9f00-d43c-11e9-873a-bbefc2f59cdf.png)

![Yeti20](https://user-images.githubusercontent.com/42642523/64676950-4018bc80-d43c-11e9-86d5-e9d60af94007.png)

![Yeti21](https://user-images.githubusercontent.com/42642523/64676962-45760700-d43c-11e9-83d2-105395c81d78.png)

![Yeti22](https://user-images.githubusercontent.com/42642523/64677074-81a96780-d43c-11e9-9ff0-babb4404af9b.png)

**Comment by mariuszkrzaczkowski** [comment]
You have two critical errors !!!
1. The system has no permission to save files, without it it cannot generate the necessary files
![image](https://user-images.githubusercontent.com/10198654/64678336-a1ab4c00-d479-11e9-9438-db896f85480f.png)

https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

> PRIVILEGES TO FOLDERS AND FILES 
> Privileges to folders and files are often the most common source of problems for people who install an application on VPS and dedicated servers. We prefer such a configuration of files [644] and folders [755] that allow full access from a browser to read and write uploaded files without changing privileges on these folders and files (so the browser has such privileges). It is necessary to remember that when the application is running, it also performs various operations such as read and write as well as creating and deleting files. If you do not know how to configure the privileges, ask your administrator to do it and send him a link to this article.

2. Your database version is not compatible with the requirements of
![image](https://user-images.githubusercontent.com/10198654/64678287-922c0300-d479-11e9-9d7e-eb1c7985a15e.png)

https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

> MariaDb 10 - the latest stable versions are recommended.
> MySQL 5.7, 8.0 -works also properly on earlier versions, i.e. 5.6 (the latest stable versions are recommended). You can also use alternative software as long as it is compatible.

**Comment by acsinsurancegroup** [comment]
Thank you @mariuszkrzaczkowski for looking into this. However on the first critical error you mentioned, all of the File and Directory permissions are set the same. The app_data and user_privileges directories have the exact same settings as the config, cache and storage directories as you can see in the screenshots below.

Most of all the file structure and permission settings as my server shows
![Screen0](https://user-images.githubusercontent.com/42642523/64737942-a1c83d80-d4b3-11e9-9b36-f9532201e1ba.png)

The file permissions for the Config directory
![Screen1](https://user-images.githubusercontent.com/42642523/64738044-db994400-d4b3-11e9-8482-cb514c2eec37.png)

The file permissions for the Cache directory
![Screen2](https://user-images.githubusercontent.com/42642523/64738156-2a46de00-d4b4-11e9-8a6b-14c78a91a3b6.png)

The file permissions for the App_Data
![Screen3](https://user-images.githubusercontent.com/42642523/64738277-6c701f80-d4b4-11e9-84f9-df9a0173e05b.png)
 directory

The file permissions for the Storage  directory
![Screen4](https://user-images.githubusercontent.com/42642523/64738345-945f8300-d4b4-11e9-9f33-277e416a4a58.png)

The file permissions for the User_Privileges  directory
![Screen5](https://user-images.githubusercontent.com/42642523/64738457-dc7ea580-d4b4-11e9-9604-5b67cb478410.png)

So I really don't think that the above is the issue at all unless the system is falsely reporting this somehow which has happened in the past. 

It could be the MariaDB Version not being 10.0 but I really can't update that right now because I have many client websites that need to remain on their current settings. I may have to test this in another server setup elsewhere for now but I think it should work as is since it always has before.

What are your thoughts now that you have seen the above screenshots? Is the DB situation really that critical that it will prevent from installing at all?

Thanks @mariuszkrzaczkowski I really appreciate your help.

**Comment by sbouillon** [comment]
@acsinsurancegroup Do yourself and your customers a huge favor and use Docker. You shouldn’t be handcuffed to mariadb version 5.5. It’s likely what’s causing these issues.

**Comment by sbouillon** [comment]
I should add that YetiForce runs perfectly inside of a docker container as well.

**Comment by mariuszkrzaczkowski** [comment]
@acsinsurancegroup These are critical errors, it won't work without it.

**Comment by acsinsurancegroup** [comment]
> I should add that YetiForce runs perfectly inside of a docker container as well.

Thanks for the reply and suggestion @sbouillon but I have absolutely no idea how to work with Docker although it is an available option in my Plesk panel. I just added a new server and upgraded MariaDB to 10.1 and it was working perfectly until I tried to add a new user.

**Comment by mariuszkrzaczkowski** [comment]
@tjaoc There is an example configuration 
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/tests/setup/Nginx
you just have to search

**Comment by tjaoc** [comment]
> @tjaoc There is an example configuration
> https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/tests/setup/Nginx
> you just have to search

Yes. Error 500

and error line 7 on yeti.conf

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski Hi Mariusz in the latest version 5.2 and even with the latest service pack v12 I still have issues with CalDav. 

Despite following this guide provided by @bpabiszczak a while back https://public.yetiforce.com/img/CalDav_and_DavDroid.gif

I still have errors in DAVx5 every single time I click on Synchronize I get the following error on my phone. 

"Received invalid event from server" then it says Ignoring one or more invalid resources

My Cron works fine except #8 which is CalDav integration and here are screenshots of that:

When running which never stops and shows a loop like in image
![cal_dav](https://user-images.githubusercontent.com/42642523/66104098-31c24a00-e57d-11e9-9698-3772e72aa900.png)

This next one shows it as Active but not completed
![cal_dav2](https://user-images.githubusercontent.com/42642523/66104141-4bfc2800-e57d-11e9-8d8a-a5d8a0427c5d.png)

All other Cron jobs run fine with absolutely no issues whatsoever. This has been a nightmare task for me on every Yeti system I've ever used. What do you recommend?

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski Hi Mariusz, anything regarding my last post above? Thank you!

**Comment by mariuszkrzaczkowski** [comment]
check it and delete accounts in dav and add again
![image](https://user-images.githubusercontent.com/10198654/66369523-084e5780-e99d-11e9-8f6a-e42bb3c61b5e.png)

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski Actually apparently that was it. Instead of having my settings on Owner, I had them both set on Owner + Share with + Group 

I also deleted the account like you said and then re-added it and boom now it works. Thanks so much Mariusz for all of your help. You're the man!

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski Hi Marius please see image below:

![cron](https://user-images.githubusercontent.com/42642523/66888403-f0319600-efa3-11e9-92f2-7ef73b578bc5.png)

Notice the CalDav integration CRON still has issues. Every other cron is running fine. Can you please give me an idea of what I need to check to fix this issue as it's still an ongoing problem? I thought it was resolved but obviously the Cron job itself is not working.

I have Version 5.2.0 with the latest service pack installed an in system under updates it says I have Service Pack version 15 installed although 14 is the latest one available in the Releases link. I did however install the latest service pack from the updater within the system.

I desperately need this working as I need my calendar events automatically syncing. I have a Plesk CentOS Server and absolutely no system warning issues are they are all Green. HELP PLEASE!

**Comment by mariuszkrzaczkowski** [comment]
create a new issue

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski That's such a tedious process though. Having to post all server settings and all that over again which I've done previously on several occasions. The issue is the same as above Marius is that not enough information to work with without having to go through all that other hassle? Thank you and respectfully :)

**Comment by mariuszkrzaczkowski** [comment]
you need to create a new one and fill in missing information, e.g. logs, configuration

**Comment by acsinsurancegroup** [comment]
Ok, I'll do it again thanks.

**Comment by P2remchand** [comment]
how to upgrade from 5.1 to 5.2 without loosing the customization and data of old version??
