### ISSUE TITLE
[Security] /config/db.php

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#11423]
/config/db.php - password stored in plain text. Any other way possible? :-)

**Comment by sbouillon** [comment]
I believe I read somewhere this might change in the far future but this is why managing your directory permissions and using the public folder is crucial to security.

**Comment by KatarzynaUlichnowska** [comment]
You can enable encryption and communicate via sockets. However, if someone has access to the configuration file (thereby access to the server), they can do anything and it won't matter how we change the authorization mechanism because they will always be able to log into the database.
Changing it to something else (e.g. encryption + sockets) would make it impossible to run on most hostings in the world. We want to change this in the future, but so far no customer (including corporations) perceived it as an important security issue that requires changing.
