### ISSUE TITLE
⚠YetiForce 5.2 - Service Pack ⚠

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#11502]
While updating our clients’ CRMs from 5.1 to 5.2 we found some issues that needed to be fixed, therefore we decided to release a service pack that not only fixes these problems, but also brings some improvements and new functionalities. 
Huge thanks to our community members @MacarenaReina  and @z0lo13 for their contribution, and to everyone who helped us by testing and reporting problems!  

**Download the Service Pack**: https://github.com/YetiForceCompany/YetiForceCRM/releases

**Bug fixes**:

- Added missing translations
- Added missing actions in filters
- Fixed saving issues in admin panel
- Fixed missing date in emails 
- Fixed an issue related to workflow (thanks to MacarenaReina’s contribution)
- Fixed missing query operators for conditions 
- Fixed a number of minor bugs reported on GitHub

**New & improved features**:

- Improved sorting elements on selection lists
- Improved comparing floating point numbers
- Added new time periods in quick filters (thanks z0lo13 for your contribution!)
- Added sending SMS to related records
- Expanded server config verification
- Improved sending emails from records
- Added an option to set default inventory description view (collapsed/expanded) and block height
- Added quick preview to related records in emails:
![related records preview](https://user-images.githubusercontent.com/13310141/64863532-55a50680-d635-11e9-8120-e882bc969e8c.png)

**Comment by LaurensCleyman** [comment]
Hi @paula-w , 

A dummy question... :-)

What is the correct way to install this service pack?

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/64944767-617c0d00-d86f-11e9-986b-c740bdadec79.png)
https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List

**Comment by ad1rie1** [comment]
![image](https://user-images.githubusercontent.com/1949622/64947644-bde22b00-d875-11e9-8aab-8519c07a4fd5.png)
:)

**Comment by elvissaba** [comment]
Should we install SP one by one, for example: SP 5.20v1, then v2...v3...vv6 or yust last one?

**Comment by mariuszkrzaczkowski** [comment]
only the latest one always installs, you have version 5.2.2 and the package is for 5.2.0.  change version in file

**Comment by acsinsurancegroup** [comment]
Hello @mariuszkrzaczkowski  since I added the last service pack, I cannot add any new users to the system no matter what I do. I did not try to add a new user after install until just now. Other than the main install, I've added the the first service pack and version 6 and that's all I've done. This screenshot shows the error I get when trying to add a new user:

![usererror](https://user-images.githubusercontent.com/42642523/65404192-2e6cd880-dd9d-11e9-91ed-7d792a1ce059.png)

I obviously have an Admin user or I wouldn't be able to even attempt to create a new user. After looking inside the Database, the admin user clearly has the User ID # 1 as it should. I then went in the system settings and users and just edited one basic setting in the admin account and now I can't even get back into the system at all. Here is a screenshot of that error:

![lockedout](https://user-images.githubusercontent.com/42642523/65404323-ab984d80-dd9d-11e9-985b-c7b1a684e460.png)

The only thing I could do then was hit Go back or Home page and I clicked on Home page and then got this error:

![lasterror](https://user-images.githubusercontent.com/42642523/65404418-00d45f00-dd9e-11e9-9660-740faafba038.png)
Any suggestions or ideas on this one? I had it installed and working perfectly up until I tried to add a new user. Every other setting I've set or changed I had no issues with. I had all green, no issues whatsoever and all clear in my logs nothing to report negatively until this. Please help!

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by acsinsurancegroup** [comment]
Hi @mariuszkrzaczkowski yes sir here you go. Luckily I just downloaded those shortly before I had all of this happen. 

![yetiforce_settings](https://user-images.githubusercontent.com/42642523/65446859-e381ae00-ddfa-11e9-89c9-680ec0f37e83.png)

**Comment by mariuszkrzaczkowski** [comment]
@acsinsurancegroup 
these are not logs,
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski Hey sorry I didn't have XDebug turned on but all other settings where good and no errors. Just earlier today I saw the latest service pack was v6 and then it was v9 and now its v10 so with all of the service packs being released at such a rapid rate, is it safe to say that Version 5.2.0 just wasn't ready for release?

Also, I downloaded the Service pack available currently v10 and extracted the files and uploaded them to the server overwriting the files that were currently there since I cannot get back into the live environment and that did not work at all either.

It's not my server I don't think. I'm gonna just try to reinstall the whole thing I guess and see what happens. When I reinstall, I'm assuming that whatever service pack is available then can simply be installed and there is no exact order to follow. In other words, I would install v10 today without needing 1-9 is that right?

**Comment by acsinsurancegroup** [comment]
Do the service packs need to be installed in order or if you install the latest you have 1- whatever?

**Comment by acsinsurancegroup** [comment]
Hi @mariuszkrzaczkowski I reinstalled everything and added the new service pack v12 now and I was able to create new users and everything is working fine so far. It was working fine before as well so hopefully this time it won't just suddenly quit working again. I will say that this is the first time EVER that I have absolutely all Green in the Summary area of settings meaning absolutely no issues whatsoever so hopefully this time I'm all set. Thanks for help.

**Comment by acsinsurancegroup** [comment]
Hello @mariuszkrzaczkowski Any new service packs? I noticed ever since I said something about how fast they were coming out, suddenly there hasn't been anymore since. Currently my system shows ver 5.2.19 while your demo version is showing 5.2.27 so I'm curious as to when the next service pack will be released. Thanks guys and by far this version is the best one ever.

**Comment by vovpff** [comment]
@acsinsurancegroup i think for stable woking SP12 is enough.

**Comment by acsinsurancegroup** [comment]
> @acsinsurancegroup i think for stable woking SP12 is enough.

Thanks @vovpff

**Comment by giuseppe4** [comment]
Hi,
I’ve updated to SP13 but I’m still seeing 5.2.0 version.
Is that normal? How can I update to the latest version?
Thanks

**Comment by acsinsurancegroup** [comment]
It sure would be awesome if every time we updated, it wouldn't automatically change all of the language files and completely overwrite all of the customization we worked so hard on setting up. UGH!

**Comment by waran70** [comment]
@acsinsurancegroup  core files are always at risk.... document changes well, so easier to get things fixed....

**Comment by acsinsurancegroup** [comment]
@waran70 Yes sir lucky I learned long ago and have a little cheat sheet to get it all back fairly quickly. Still takes a few hours though so it's just aggravating is all. The update code can be done where language files aren't overwritten they just don't do it that way is all.

**Comment by acsinsurancegroup** [comment]
What's new with the latest update Version 14? What does it fix? What does it break?
