### ISSUE TITLE
[Question]           How to hide updates of admin user / workflow in the history widget

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#11514]
Hi all, 

If I create a workflow that updates an age-field of a contact daily, then I have a new update every day in the history widget of the corresponding contact.

I don't want the other users to see the updates of these workflows. How can I hide the updates of the admin user / the workflows in the history widget?

Kind regards,

Laurens

**Comment by davide-alghi** [comment]
Hi Laurens,
you cannot.

You can only hide **all updates** for that profile
```Privileges to actions and views => Change history```

**Comment by LaurensCleyman** [comment]
Hi @davide-alghi , 

Thank you for the reply.

Alternatively, is there a table where this data is stored where i can remove the administrator's changes? Or this is not advisable.

**Comment by vovpff** [comment]
You can check table in database what contains all changes. You can periodically cleanup all rows where admin appears.
This is simple way for usual changes history but changes history of advanced modules is more harder story

**Comment by davide-alghi** [comment]
> Hi @davide-alghi ,
> 
> Thank you for the reply.
> 
> Alternatively, is there a table where this data is stored where i can remove the administrator's changes? Or this is not advisable.

removing admin tracks means deleting records on more than one table (modTracker tables) and, as you said, it's not advisable, and not easy too
alternatively, you can hide some tracked information through the tpl modification, core modification: but this is discouraged because will be overwritten (probably) by YF updates / upgrades packages

IMHO, the cleanest solution is to hide changes from users and assign the view only to specific user or admin

**Comment by bpabiszczak** [comment]
You can always update the record directly in the database ;)
