### ISSUE TITLE
[Feature] Yetiforce PDF Going to be discontinued? mPDF vs YETIFORCE PDF

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#11680]
Hello Everyone,

First things to start: Why you actually discontinued the mPDF library? It updated on an occasional basis and provide much much smaller output files. In advance to its great documentation.

The Subject is arising from the fact that no updates have been done for recent months.

**Yetipdf**
I have been monitoring YetiPDF library since its initial release, Unfortunately, no updates/Upgrades were made for a long time (I am not counting Performance fixes, as if the initial release would have proper testing, they would never occur). The library still does not support basic styles and output very large files, Even to put a font requires a library core modification as It does not work from the box.
**Design**
The tables layout is impossible to implement as the library sometimes outputs the wrong width. To create very simple one page pdfs yes absolutely not a problem to accomplish. Complicated 3+ pages report Impossible.  It is 2019 and I suppose designing in table layout is going too old school (Time Consuming).
mPDF Had the Feature of outputting directly in the browser, which was easier to check for issues with data, Now we need to download a file and open it somewhere else.
**Performance**
Of course, since the initial release performance rised in around 100%, however, I have a service contract which YetiPdf can generate only in around 25 Seconds, that's including that I have bare metal server setup. When mPdf for the same document having 2-3 seconds generation time. If it is 35 pages report It will just put PHP in the loop and you would have to restart the server, even if it accomplishes I can not even imagine the size of that file. mPdf - 4 seconds.

**If you monitor resource consumption during generate you will find out 100% CPU Utilization during the time of generating. Which puts the whole system at performance risk. If pdf sends server in a loop, Cron breaks as well, potentially errors arise**

Lastly, When something beeing generated the CRM session of a user who clicked generate freezes (Nothing could be done by the user except only when PDF Ready)

**If some image is too big or any error made in layout -> PHP Loop.
If the font is not supported -> PHP Loop.
A lot of text -> PHP Loop.
Too Complicated Table Layout -> Wrong Output.
Background-image -> No Image**

I am sure by reading all issues about YetiPdf I can add more points.

Due to the lack of features and support, we are thinking of going back to mPdf parser which provides much better performance and support.

Regards, 
z0lo13

**Comment by waran70** [comment]
PDF is the worst part of yetiforce. Was raised many times. Guys should just design great one and keep selling. Great means not worse than PDFMaker from vtiger.... and it means also NON programmatic skills should be required. PDFMaker needs to be allowed for not power users.... save a lot of time in many cases

**Comment by apcloic** [comment]
Indeed, I also noticed that YetiforcePDF is very very slow, a simple text document with 6 pages take around **35 seconds** to generate on my VPS.
When monitoring resource consumption during PDF generation, my **CPU utilization is 100%**

**Comment by hico11** [comment]
Problems with invoices and forms to PDF is definitely the weakest link of Yetiforce, a huge impediment to wider adoption.   Agree 100% that manually coding a functional form is time consuming and problemmatic for most users and for those who don't do code as a full time job.

**Comment by JohnMaverick** [comment]
Well... agree with above. Tried convince some guys to yetiforce, but pdf and reports was the main problem. One of them have beautifully designed PDF templates, so professional and complex that this is completely impossible in yetiforce PDF. Saying that everything can be done programmatically is just nonsense and should not be spoken out. Obviously as an out-of-the-box solution  current PDF is far better than dealing with native vtiger PDF solutions.... however, the problem is in resolving user needs and also earn money. As waran70 said, designing fully non-power-user friendly PDF maker can get yetiforce great cash on top. Also reports can be done as an extension. This two are super important if we want to deploy crm in environment where independent managers or users are allowed to generate various sets of data via PDF or reporting module.

**Comment by paula-w** [comment]
This is @bpabiszczak 's answer:

We’re not planning to go back to mPDF, it’s outdated, and what’s even worse, it’s licensed under GPL2+, which means it can’t be provided together with the software. 

We generate documents (such as quotes, orders, invoices) from the system using this library, just like dozens of our clients do.The fact that you generate custom documents is not a problem for this library. The difference between us and you is that when we need some modifications in the library we simply develop them, and you wait for someone else to do it for you. Performance optimization is a matter of 1 ~ 3 work days, so why don’t you do it or or pay to have it done? There is a place for donations after all - https://opencollective.com/yetiforcecrm where only one person pays $10 per month, what’s stopping you? The problem here is that you wait for someone to do something for you because you need it. 

Each change in the system is always the most “painful” to us, so if we introduce any changes you can be sure that we believe they’re absolutely necessary and we always keep the future of YetiForce in mind. These libraries are very complex (developing YFPDF took several months) and you have to understand that the power of open source isn’t based on one person doing everything while the others complain; it’s based on everyone contributing to the development of an even better tool. If all of you have several problems and pay for solving one or two of them, it might turn out that all of them will be fixed soon.

**Comment by waran70** [comment]
Paula, you missing the point. We want to buy fully functional extension. Suggestions about improving current state, or criticizing its performance is a pure brain-storm contribution to make YF better. Do you want it to be better? Sure you do. Again, why don't you develop extension and sell it out? It will pay bills surely... only existing base of your customers is a great potential isn't it? Guys like its4you, S.Warnat or vtextra doesn't work for free... do some calculations and rethink.... having great base of extensions to YF is itself great marketing thing. Cheers!

**Comment by paula-w** [comment]
**This is @bpabiszczak ‘s response:**

@waran70 does it mean that you want to buy a fully functional extension? Which ones of the currently existing and working ones have you purchased?If you’re using them and you find them alright, you could have donated towards the development of the project… If we wanted to live off plugins we could have still been developing Vtiger plugins (we had more than 60 of them in 2014). It’s a very bad direction, I don’t know why you want us to go this way. I could ask you why you aren’t using Vtiger with PDF Maker if it meets your requirements, why bother with YetiForce?

@z0lo13 1000% profit ;) You’re another person who wants us to create paid addons as a solution to all the problems. Are Vtiger users happy with the project despite having so many paid addons? mPDF is outdated, but it can support more HTML tags. If there are tags we aren’t supporting right now it means we didn’t need them (nor did our clients). If we need something that is missing we simply add it.
PS.: If the library didn’t support fonts the PDFs would be empty…

**Comment by z0lo13** [comment]
@paula-w 
I do not understand you already have paid add-ons, including geocoding which, I am not talking about completely paid pdf module, but at least features. Why I offered that because you said that you can not do it as it will not bring money. 

Alright money its only one small part of benefits which actually normal pdf module can bring to you, i will list them:
Opportunities:
The system will have more capacity to produce customized documents as well as act as a centralized documents managing system;
Possibility of creating Reports (So many people required that)
Possible to create bulk orders documents (Invoice with more than 400 products lets say would not proceed if it will include product pictures I do not even know what will happen.) 
Usual Managers would be able to create a PDF Template without hiring some IT person.
Beneftis:
More users of ERP -> Better brand recognition -> More potential investors covered 
More Features -> More Industries covered -> More ERP Installs
Easier PDF Creation -> More Users -> More Positive feedback -> Increased Brand Recognition
Better Compression -> Less file size -> When document sent through the email -> Less space needed.
Main tags support -> More User-Friendly -> More Users (I can imagine how much people turned away from yeti just because they do not know how to write in HTML) 

All of above -> More Customers you can sell your support or hosting -> more Profit

 If you still don't want again let us know how much you need, I personally will contribute to that, No Problem

Also maybe you misunderstood, but I am not saying you have to do it, its completely your business and the decision will be after you anyways, but as it is open source project, it is based on collective opinion. 

Regarding the tags I am personally your client, other people in this thread are your, clients, too, and it seems like all of us needed them here.

Regarding fonts yes of course one font supported (So much to choose from).
#11016

@bpabiszczak
Lastly, I do not understand what you are trying to say?
 Out of your quotes by paula i get only that you limiting the pdf features basing only on your company's personal needs, but as far as I know, Yetiforce ERP is a project to integrate into other companies with different structures and workflows, not everyone has and will never have same company structure and needs as yours.

To finish up if you actually want to have a great product you maybe need to create a product based on your target audience opinion which is us. 

Moreover, at first you saying pay us money and we will do it, then you say that you can do it but will not because you do not need it. And now you saying that you don't want to go to the direction of paid addons.

At the same time, Right now, the Usual user can not create a good customized nice looking pdf even invoice, without knowledge of coding.

Me personally I do not need your pdf at all, as I am enough skilled to create own solution, I just trying to contribute and make yeti much better, if all ideas will be thrown away with a flag " We haven't done it because we don't need it" then the whole idea of this project going open source does not make sense at all.

**Comment by waran70** [comment]
. I could ask you why you aren’t using Vtiger with PDF Maker if it meets your requirements, why bother with YetiForce?

I do use Vtiger mate. Only Vtiger. Just watching this project as it is interesting. Rest of yours answers are bunch of worthless non-productive, non-thought-through mix of nonsense. Stop watching mirror guys... we are trying to help you.

**Comment by z0lo13** [comment]
> 
> 
> . I could ask you why you aren’t using Vtiger with PDF Maker if it meets your requirements, why bother with YetiForce?
> 
> I do use Vtiger mate. Only Vtiger. Just watching this project as it is interesting. Rest of yours answers are bunch of worthless non-productive, non-thought-through mix of nonsense. Stop watching mirror guys... we are trying to help you.

i dont use vttiger on the reason that its a hosted erp and their 7.0 getting outdated and in a long term will be discontinued

**Comment by waran70** [comment]
Actually I can see progress here: https://code.vtiger.com/vtiger/vtigercrm/commits/master

**Comment by z0lo13** [comment]
> 
> 
> Actually I can see progress here: https://code.vtiger.com/vtiger/vtigercrm/commits/master

In terms of flexibility, Yeti is uncomparable to vtiger7 there is no API and most of the libraries are very old, moreover i have no idea how they get a track on php vulnerabilities, changing the erp system just beacuse of Pdf parser is not the smartest move out here. we have more than 10k records including very broad modifications and optimizations like custom modules and even Pdf parser

**Comment by waran70** [comment]
> In terms of flexibility, Yeti is uncomparable to vtiger7
are you sure? :-)
> there is no API
Please mate, do understand what you writing...it a little bit shame... 
> most of the libraries are very old
not very but definitely should be updated
> erp system 
what erp you mean? We didn't talk bout any here..
> we have more than 10k 
Make sure your machine have aircon :D

Summarizing, I don't encourage anyone to move to vtiger. I wish I could encourage to move to younger brother, and for this reason I press this damn button to wake up YF guys.

**Comment by mariuszkrzaczkowski** [comment]
@waran70 that's bad idea,

**Comment by waran70** [comment]
Waking up? Or what? :-)

**Comment by mariuszkrzaczkowski** [comment]
> Waking up

**Comment by z0lo13** [comment]
@waran70 
If you tried to be witty, Maybe you 've reached your point!:)
Vtiger and Yetiforce both ERP if you didn't know 😆.
Regarding anything else you show disrespect and unprofessionalism, that is not a joke forum

**Comment by waran70** [comment]
I guess you are not very power user? So than read below:

An ERP system covers the following common functional areas. In many ERP systems, these are called and grouped together as ERP modules:

    Financial accounting: general ledger, fixed assets, payables including vouchering, matching and payment, receivables and collections, cash management, financial consolidation
    Management accounting: budgeting, costing, cost management, activity based costing
    Human resources: recruiting, training, rostering, payroll, benefits, retirement and pension plans, diversity management, retirement, separation
    Manufacturing: engineering, bill of materials, work orders, scheduling, capacity, workflow management, quality control, manufacturing process, manufacturing projects, manufacturing flow, product life cycle management
    Order processing: order to cash, order entry, credit checking, pricing, available to promise, inventory, shipping, sales analysis and reporting, sales commissioning
    Supply chain management: supply chain planning, supplier scheduling, product configurator, order to cash, purchasing, inventory, claim processing, warehousing (receiving, putaway, picking and packing)
    Project management: project planning, resource planning, project costing, work breakdown structure, billing, time and expense, performance units, activity management
    Customer relationship management (CRM): sales and marketing, commissions, service, customer contact, call center support – CRM systems are not always considered part of ERP systems but rather business support systems (BSS)
    Data services : various "self–service" interfaces for customers, suppliers and/or employees

**Comment by TonyM15** [comment]
@z0lo13 kids like you should be kept away from this forum. You just throwing unnecessary issues, and showing lack of fundamental knowledge in programming, business logic and business applications. 
waran70 is right - yetiforce and vtiger are NOT ERP systems (yetiforce maybe on the way to, but this will be very long way) but CRM and yes.. you can do in both apps the same things. Saying that vtiger has no API flooring people here down and fact that you have 10k records makes you just a funny kid here. Your love to yetiforce is a bit excessive. 
---------
I start liking the way vtiger do - forum with all spam rubbish and unanswered questions, pseudo-developers list (pretty the same) and GIT where people like z0lo13 have very limited access.

**Comment by mariuszkrzaczkowski** [comment]
@waran70 
If you want to help, it's better to look for solutions to problems instead of creating new ones. You simply waste your and our time, while you could fix or improve something.

@all
A few tips for you if you want us to have more time for the development:
- Help in solving reported issues - it is common that the problem has already been solved or has been fixed in the DEV version, so it's enough to provide a link to the solution.

- Share solutions to the problems - don't close them without an explanation on what was the source of the problem and how you fixed it, you can help others who have the same problem.

- If you know how to code, you can show where the error may be and if you know how to fix it, you can send us a ready fix.

- if something is missing in the system, you can always add it and share it with the others.
Share your code and ideas.

- Don't complain - you waste your and our time and it doesn't bring any benefit to the project.

- Share ideas about what could be done better and what is missing - this helps us determine what the community needs and what can be combined with our plans.

- Help with languages - it's really a lot if you simply check or help with translating the system to your mother tongue.

**We invest a lot of our time in YetiForce. How much do you invest in it?**

_PS. Do you know how much I could do in the time when I wrote it? Think about how much time you simply waisted._

**Comment by z0lo13** [comment]
> 
> ## @z0lo13 kids like you should be kept away from this forum. You just throwing unnecessary issues, and showing lack of fundamental knowledge in programming, business logic and business applications.
> waran70 is right - yetiforce and vtiger are NOT ERP systems (yetiforce maybe on the way to, but this will be very long way) but CRM and yes.. you can do in both apps the same things. Saying that vtiger has no API flooring people here down and fact that you have 10k records makes you just a funny kid here. Your love to yetiforce is a bit excessive.
> 
> I start liking the way vtiger do - forum with all spam rubbish and unanswered questions, pseudo-developers list (pretty the same) and GIT where people like z0lo13 have very limited access.

I am actually amazed how disrespectful you are for the person you do not even know, it shows your education and moral level just. The issue was about pdf library and you and waran70 made a bazaar out of it.

**Comment by dfanaei** [comment]
@mariuszkrzaczkowski @paula-w @bpabiszczak 
Why don't you guys just drop your disgusting behaviour and actually see the positive side of people coming here and discussing with you all the problems they are facing with your system?
People are simply telling you what is wrong and what is needed hoping that you can fix it. not only to ensure they get a better CRM but also YOUR application becomes better and grows. 
I have simply seen this issue with the PDF not only for myself but almost for everybody that once got excited and installed Yetiforce thinking that it could fix the amateur problems that Vtiger was creating for them.
It is simple if you guys want to make money, then start what is better (Which YF is definitely better than Vtiger) and make it as great as possible (Fixing all issues like this), come up with a pricing plan that is much better that what vtiger is doing (perhaps learn from it's4you) and then monetize it. 
THE REASON WHY  PEOPLE DON'T REALLY BOTHER DONATING IS BECAUSE THEY CAN SIMPLY SEE IN HERE THAT YOU DON'T CARE ENOUGH AND INSTEAD OF RESPECTING YOUR USERS THAT ARE SPENDING TIME AND ENERGY TO COME HERE TO EITHER CONTRIBUTE (IF THEY CAN CODE) OR SIMPLY CONTRIBUTE TO DISCUSSIONS, YOU END UP DISRESPECTING THEM AND PRETTY MUCH TELLING THEM TO F OFF. EVERYTIME I DONATED TO A TEAM, I MADE SURE BEFORE THAT THEY WOULD CERTAINLY HELP ME TO GET MY PROBLEMS SOLVED. SIMPLE! 

There is a reason why in english they call it DONATING. they have the choice to do so and they gladly will if they see that the people they are donating to are much worth it. They don't need to be told to Donate!

**Comment by JohnMaverick** [comment]
In my opinion creating functional PDF extension and sell it to users will basically bring em nice cash injection. Not sure why this is so hard to understand. Maybe real base of installed app is not big enough? Yeti have all statistics, so maybe that's the reason. I would even discontinue current embarrassing PDF app and leaving only option to use existing templates force all guys to buy proper PDF extension if they wanna design new one. Yetiforce devs have enough skills to make it pretty the same of PDF maker for vtiger.

**Comment by s2b-git** [comment]
Anyone replaced yeti PDF with MPDF? Any tips?

**Comment by ArniSamano** [comment]
PDF and other reporting modules shall be designated for end-users who rather have limited clue about stuff behind curtain. PDF maker shall be moved to the same level and Email Templates, improved or recreated as a paid extension. 
If yetiforce is occupied too much, hiring developer and reselling extension in own marketplace would be a way
