### ISSUE TITLE
Themes not changing

### ISSUE THREAD

**Issue by JeRRimix** [YetiForceCompany/YetiForceCRM#1169]
I select other theme for example Orchid:

![image](https://cloud.githubusercontent.com/assets/13039836/8342518/113f3498-1ae6-11e5-8756-87571bbcec14.png)

In result it was changed just bottom not full:

![image](https://cloud.githubusercontent.com/assets/13039836/8342534/2f3229ba-1ae6-11e5-987f-a2478e4a027f.png)

How can I fix it?

**Comment by JeRRimix** [comment]
:(((((

**Comment by JeRRimix** [comment]
when version GA 2.2 is ready???

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, 2.1 will completely disable the possibility to change colors. In 2.2. there will be a completely new template in one color and 2.3 will add new colors of the same template.

**Comment by JeRRimix** [comment]
sad :(

**Comment by diderich** [comment]
Does that mean that the UI is expected to be stable again (no major changes planned) starting at 2.3?

**Comment by JeRRimix** [comment]
I just can not understand why on the official test site all shows right, but on other servers it crooked?

**Comment by reeid** [comment]
Do you have a mockup of new UI?
Does changes will affect in anyway current data related core functions?
By the way here is interesting what guys did for vtiger: http://demo.makeyourcloud.com/vtiger6.3/

**Comment by KatarzynaUlichnowska** [comment]
2.1 is going to be released in several days when we close all open issues with bugs. The look and feel of the system will be very similar to the one there is now [it won’t be worse, it will a bit different here and there]. 2.1 will be a stable version and if an error appears in this version, it will be fixed and available for downloading form GitHub. 2.2 will have a completely new look and it will also be a stable version. If any errors appear in this version, it will be because no one has noticed it so far [neither our community, our company nor our customers]. 2.3 will have new colors for the version published s 2.2, it will be stable too. 
YetiForce number system is explained here: https://yetiforce.com/en/administrator-documentation/instalation/138-yetiforce-number-system.html
