### ISSUE TITLE
[Question] corporate e-mails reply action

### ISSUE THREAD

**Issue by A3ANO** [YetiForceCompany/YetiForceCRM#11738]
Hello,

I'm having troubles with the action that is used when I want to reply/forward/... mails inside the corporate e-mails tab (Companies & contacts > contact/vendor/account/...). If I log in as the admin user, whenever I click on the forward/reply button in the corporate e-mails tab of a contact/vendor/account/... it opens a new window inside the RoundCube application. But for some reason if I log in as a non-admin user and use the same action, windows opens up the std. mail application. I would like the behavior to be the same as when I'm logged in as an admin user (open with Roundcube instead of windows mail/Outlook).
Is this something that I can change inside the settings? I have checked all the settings but I could not find anything relating to this.

Can somebody help me with this? I'm currently on the latest YetiForce version > 5.2.
Thanks in advance

**Comment by mrzewnicki** [comment]
Hello,

**About opening in Windows/Outlook:**
 it's because probably someone disabled the option internal mail composerin user settings:
![image](https://user-images.githubusercontent.com/21024857/66807150-16feb680-ef29-11e9-883a-5d83da4b6af0.png)

Check box in user settings must be marked if you wanna use roundcube 
Check box in user settings must be unmarked if you wanna use default windows mailbox 


![internal_mail_composer](https://user-images.githubusercontent.com/21024857/66807517-7d83d480-ef29-11e9-9bd9-449f1b7fa7f6.gif)


**About open new mail in new windows:**
You need to check roundcube client options
![image](https://user-images.githubusercontent.com/21024857/66807598-ac9a4600-ef29-11e9-9538-91152d4f28a4.png)

**Comment by A3ANO** [comment]
Hello mrzewnicki,

Your small guide helped me fix my issue.
Thanks you very much for your help.

kind regards
