### ISSUE TITLE
How to search by ticket number

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11815]
Hi all,

How do I search by a ticket number in YetiForce? 

I tried searching in the search box but it doesn't work.

**Comment by vovpff** [comment]
At first you need to change search labels parameters for tockets module trough admin user interface. After that you need some time for database update if you already have a lot tickets

**Comment by acoolov** [comment]
Thanks. 

How would i be able to accomplish that? 
Could you outline the steps by chance?

**Comment by vovpff** [comment]
@acoolov I can but in 4 hours or tomorrow...

**Comment by vovpff** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=13&fieldid=56

![image](https://user-images.githubusercontent.com/8545791/67517486-61133500-f6ab-11e9-9161-2979ed5db082.png)

In any case better way to use prefix for ticket number because in this case you can search by Hnumber in global search field.
