### ISSUE TITLE
Question about version 2.2. GA

### ISSUE THREAD

**Issue by JeRRimix** [YetiForceCompany/YetiForceCRM#1181]
Please tell me when the planned release of version 2.2 GA?

**Comment by diderich** [comment]
![ms](https://cloud.githubusercontent.com/assets/10230144/8374205/e2d6c7ec-1bf3-11e5-9673-307fb47de682.jpg)

**Comment by waw555** [comment]
What does the GA version of the end? And when planned stable version ???

**Comment by bpabiszczak** [comment]
If you find any errors, add them as issues because if no one reports it and we don’t notice it during internal testing, we are unable to guarantee that it will be deleted. The stability of the system depends on the amount of people testing it, even large companies such as Microsoft release systems with bugs or don’t fix errors reported a few years ago. The quality of a stable version dependent upon us, the community as well as upon you.


GA = General availability (stable)
