### ISSUE TITLE
Last version with changes from 25.06.2015

### ISSUE THREAD

**Issue by JeRRimix** [YetiForceCompany/YetiForceCRM#1182]
Yesterday I decided to completely reinstall YetiCRM and downloaded the last version from github. Last changes made at 25/06/2015. 

I use CentOS v.7, Nginx + PHP v. 5.6.9 in CGI mode

The first problem I encountered was when installer script checking parameters of PHP showed that display_errors = On although in the fact it's disabled. PHP info showed that it's also disabled and errors not showing. What does it mean?

The second problem, I still continue the installation and when it was completed I try to start CRM and showed a strange screen with symbols and nothing more! 

![image](https://cloud.githubusercontent.com/assets/13039836/8375650/c3e5bcf6-1c18-11e5-95f1-dfd8383e424b.png)

**Comment by JeRRimix** [comment]
Is it possible to do more stable version?

**Comment by JeRRimix** [comment]
Guys, what's about my problem? :((( What's version is more stable now?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/2.0.0

**Comment by JeRRimix** [comment]
This is part of server log file at the moment of installation end. It's display 504 error "timeout gateway".

[Sat Jun 27 23:06:07.267789 2015] [cgi:warn] [pid 8331] [client 62.133.162.20:55447] AH01220: Timeout waiting for output from CGI script /var/www/php-bin-isp-php56/user21114/php, referer: http://crm.shopavenue.ru/install/Install.php
[Sat Jun 27 23:06:07.268162 2015] [cgi:error] [pid 8331] [client 62.133.162.20:55447] Script timed out before returning headers: php, referer: http://crm.shopavenue.ru/install/Install.php
[Sat Jun 27 23:07:07.328684 2015] [cgi:warn] [pid 8331] [client 62.133.162.20:55447] AH01220: Timeout waiting for output from CGI script /var/www/php-bin-isp-php56/user21114/php, referer: http://crm.shopavenue.ru/install/Install.php

When I start CRM I see just two symbols "??"

Have ideas?

**Comment by KatarzynaUlichnowska** [comment]
The problem which you described is a server error [to be specific it’s proxy error that was triggered by the server error]. You need to have a look at server logs and see why there is a timeout or you can ask your administrator. On our server, the system is installed in less than 10s. It can take longer on slow servers with bad drives. 
If this problem is limit-related then you can install the system on your laptop [e.g. install WWW WAMP environment] and after the installation you need to copy files and database to the server and change paths in config/config.inc.php file.

**Comment by mariuszkrzaczkowski** [comment]
Check the latest version of the master or the error still occurs.

**Comment by JeRRimix** [comment]
As I understand it, the problem occurs when you install CRM system on HTTPD (Apache) with PHP interpreter as CGI or PHP-FPM via NGINX. 

The idea that installation script takes too long and does not return output to the browser, but the script will continue to execute on the server if you refresh page again and get blank page. In result CRM was installed. In manual you write that the timeout settings in php is necessary to put at least 600, but the problem occurs even at 3600. 

I increased absolutely all the parameters of timeouts in Apache, in proxy and PHP.ini but the problem can not be solved

**Comment by bpabiszczak** [comment]
Try:
1. Install on windows [WAMP]
2. Copy file on server
3. Copy database on serwer
4. Change path/database_access/root_directory/site_url inf config/config.inc.php

**Comment by JeRRimix** [comment]
What's WAMP if I have server on Linux??? What are you trying to say? If even VAMP is established, then what about those who have Linux?

**Comment by bpabiszczak** [comment]
In order to help you, you need to provide a step-by-step description of how we can reproduce the error. A good example of reproducing is using the same www environment, e.g. WAMP by you and us. Your example is [probably] related to server configuration. If the installation process is too long, you can install it on WAMP and then copy and install the system [you will skip limits in this way]. 

This kind of errors are always solved in our company by two people:

an administrator - analyzes a problem from server perspective
a developer - analyzes a problem from logs perspective
The information you provided are insufficient. We can't help you because we don't know how to reproduce the error, please describe it.
