### ISSUE TITLE
How to import from XLS 

### ISSUE THREAD

**Issue by ashelshark** [YetiForceCompany/YetiForceCRM#11919]
I am not a developer. I want to import by excel contacts into the the system. Can I do this without complicated coding?

**Comment by fbojan** [comment]
First you need to save the xls table as * .CVS separated by a comma. Because EXCEL does not save CSV in UTF-8 format, it is necessary to convert the * .csv file to UTF-8, preferably in any HTML editor. I do this in NOTEPAD +++, CODING in UTF-8. It is very important that you have the information in the right format, especially when it comes to dates and currencies. The table where you are importing data has some mandatory data, so you need to add 1-2 columns. Of course, you won't succeed right away in the first attempt, you'll just have to try it, but it works. Attached is a short film.
![imoprt1](https://user-images.githubusercontent.com/25682437/67974006-dafa6f80-fc11-11e9-8ab6-bcb19b6e1f88.gif)
![imoprt2](https://user-images.githubusercontent.com/25682437/67974978-a25b9580-fc13-11e9-9f6f-64c223d1fcbf.gif)

IMPORT CSV UTF-8
![imoprt3](https://user-images.githubusercontent.com/25682437/67975638-c5d31000-fc14-11e9-8e58-3f43074bcf7d.gif)

**Comment by ashelshark** [comment]
Thank you worked out
