### ISSUE TITLE
[Question] How to setup Yetiforce to assign tickets to contacts

### ISSUE THREAD

**Issue by A3ANO** [YetiForceCompany/YetiForceCRM#11947]
Hello,

I'm using Yetiforce for a few months now and it's a pretty good program. You guys and girls are doing a great job with the development of Yetiforce.
I have a small question concerning a problem. I cannot seem to assign a ticket to a contact, I only see the "vendor" or "account" option to assign my ticket to. I have read a few past tickets, but no real explanation is given on how to create a relation... Can somebody help me to show me how contacts can be added in this assign select field?

Thanks in advance.

Regards

**Comment by davide-alghi** [comment]
hi,
assignement is by "Assigned To". 
but ... if you mean to create a relation with a contact, you simply can add a "Related field (1:M)" custom field

https://gitstable.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=HelpDesk

**Comment by A3ANO** [comment]
Hi Davide, 

Indeed, i would like to create with the ticket to  a contact. So that i can see the tickets i created for a contact under that contact. I will try you solution.
Thanks for your answer.

Kind regards

**Comment by davide-alghi** [comment]
Hi,
I understand now that you wanna list related tickets from **Tickets tab** in contact details: but my previous suggestion doesn't do that.

take into account that YF provides many kind of relations and only a subset of those can be edited via YF GUI: the other ones can be added only programmatically.

that said, I just saw now that in contact details exist a **Tickets tab** for YF 5.2: that was not in YF 5.1, so it's a new feature. But this new feature doesn't provide, apparently, way to relate a ticket. I said apparently because there can be an automatism (into core code) to relate ticket to contact, but I've not investigated about that. Maybe an YF-team member will give to us a reply about this.

There is a way to add a new tab into contact details enabling **$CHANGE_RELATIONS** into /config/Developer.php, but it seems to create a wrong overriding.

@mariuszkrzaczkowski if, for contact module, you add a new relation for tickets (one already exist), the new one hide the existing and only the last one is visible in BE and FE. Whether just you delete the new relation, the old one reappears (after page reload).

**Comment by A3ANO** [comment]
Okay, gues i have to wait for one of the developers to see if it is possible.

**Comment by KatarzynaUlichnowska** [comment]
The relation in HelpDesk and Contacts modules is M:M, not 1:M, so after creating a Ticket, you can add a Contact. After adding, the Contact will be related to the Ticket. We do not recommend playing with relations unless you have a developer who will be able to solve problems.
