### ISSUE TITLE
[Question] Cron Job - Update coordinates/Get coordinates

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12328]
Please could you tell me what these cron jobs are supposed to do?  I set "update coordinates" to active but it never completes.

All my other cron jobs work fine.

**Comment by paula-w** [comment]
You didn’t provide us with any details about your system like the version or what info you see in the logs so unfortunately we are not really able to help you.
The system will connect by default to our map starting from version 5.3 (currently it connects to public maps that are severely limited). We assume the problem lies in the number of requests, if you send a lot of information that is not cached the server will reject it and CRON won’t work.
