### ISSUE TITLE
Confused In multiple licensing. 

### ISSUE THREAD

**Issue by uttamsharma** [YetiForceCompany/YetiForceCRM#12480]
Hello, first of all thanks for this nice CRM. Actually I'm confused in your licensing terms. Somewhere it's similar to MIT somewhere it's GPL or yetiforce licence. Actually I want to modify this Great CRM for my cloud application. I just want to ask is it allowed to do the following tasks. 
- Modify the source code (minor changes) and make available it on my cloud platform?

- yetiforce is a nice name, But can I give a different name to the modified my platform specific version of yetiforce (without removing the credit from footer)?

- Can I charge money for hosted solution and for provide support to users?

Thanks for this really great product. Expecting a reply soon. THANKS

**Comment by waistracloud** [comment]
Yes licensing is confusing, Cant understand what can do or don't. Installation wizard shows a License Similar to  MIT. But multiple licensing info on yetiforce website and MIT license on GitHub repository.

**Comment by waistracloud** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/5337 Read the following thread me be it can help you. I think you can change the name, Place your logo, Modify, Redistribute. Only two limitations Not remove the footer, Share the data of users with yetiforce.  @uttamsharma . It'll be great if a project contributor will explain your issue.

**Comment by uttamsharma** [comment]
This thread is helpful but still not clear about my doubts. Expecting a reply from project contributor.

**Comment by uttamsharma** [comment]
@bpabiszczak I'm waiting for you reply. Thanks

**Comment by uttamsharma** [comment]
@paula-w may you please on this issue?

**Comment by paula-w** [comment]
**This is @bpabiszczak’s response:**

@uttamsharma you want us to provide you with information that you should receive from your lawyer. What I’m going to say is not any kind of declaration or statement from us, the legal risk of creating a new system is something you have to assess on your own. Licensing is a very complicated subject, you have to take into consideration ALL the licenses in the system! Currently there are several different licenses in the system (YetiForce has its own license but it uses more than 140 libraries that are released under different licenses). Right now you can find such licenses as: 

- YetiForce Public License v3
- VPL 1.1
- SPL-1.1.2
- MPL-1.1+
- MIT
- LGPL-3.0
- LGPL-2.1
- ISC
- CC-BY-4.0
- BSD-3
- BSD-2
- Apache-2.0
- Apache-2.0 WITH LLVM-exception

You must understand all the licenses that are in the application, know their limits and what to pay attention to when using code under these licenses. If a license is not good for your project, then you have to use  a different one, sometimes it’s simple and sometimes complicated. From the list above, you should be particularly interested in LGPL licenses because copyleft sometimes applies to them. The system itself doesn’t have any GPL libraries (if this were the case, the entire application would have to be under GPL). That is why Roundcube is not distributed together with YetiForce (you can add it as a library) because it is under a copyleft license - in the nearest future roundcube will be completely removed from the library list. There is a huge difference between the GPL and LGPL licenses as well as between the different versions of these libraries, you should keep this in mind! If you install YetiForce, then in the configuration panel you have a list of all libraries and their licenses used in the application:
- Software configuration > About application > Licenses

Our license forbids you from removing the footer (it must remain as it is) and each version of the application must be registered with us with the real data of the company that will use the system. You can change the installer, login panel, configuration panel and add your new name there, but you can't delete our data and our name from the footer (so you can't really get rid of YetiForce). Our license is ideal for companies that want unlimited access to the source code and want to freely develop the application, however, it is not good for someone who wants to offer the product under their own name, due to these two points described above.

You would be better off picking Vtiger because their license doesn’t include the two conditions I mentioned (that’s why we forked it). We wouldn’t recommend forking SuiteCRM because it’s a licensing disaster (see: https://github.com/salesagility/SuiteCRM/issues/5374) 
 
We sometimes allow our corporate customers to change the YFPL license to a license without these two conditions (e.g. when a bank employing 10,000 employees wants to have their own footer instead of ours), then for an additional fee we allow them to do this (but these are really high costs, so we wouldn’t advise that to small and medium-sized companies). Small and medium-sized companies can take advantage of the option of disabling our branding and substitute it with their own. In this case only a few pieces of information about us remain in the footer, while links and buttons direct to the client's own pages - this solution is ok for 99% of the clients we work with.

**Comment by uttamsharma** [comment]
I loved the way you described the complete scenario. Thanks for your quick reply. 
Just a one more question. I know it's on the wrong forum. But if you can explain this it'll be a great help. 
I'm considering your suggestion for forking vtiger. As the both vtiger and suite is fork of suger CRM. 
What are the requirements for forking vtiger. Is the vtiger crm's licence allow the following things to do. Thanks for your response. @paula-w

**Comment by mariuszkrzaczkowski** [comment]
> Our license forbids you from removing the footer (it must remain as it is) and each version of the application must be registered with us with the real data of the company that will use the system. 

I will just add that the CRM has to be registered for the company that uses the system and also for the company that deployed it, and the company that integrates it with 3rd party services.

see the registration window, this is the field

![image](https://user-images.githubusercontent.com/10198654/73347516-04b24980-4288-11ea-8b41-66d274820954.png)

**Comment by paula-w** [comment]
Once again, @bpabiszczak's response:

We forked Vtiger, but you have to ask your lawyer about the licensing details, that’s the least risky solution for you. 

Vtiger forked Sugar in 2004, back then Sugar’s license was different, it used to be what Vtiger’s license is now. It was SPL 1.1.2, it’s the same license as Vtiger’s current license, LPL, and MPL - and they are all very good licenses, they let you fork the software and are business friendly. 

Later versions of Sugar introduced one of the worst licenses - AGPL - SuiteCRM inherited this license from them. Some companies forbid using any software released under AGPL.

**Comment by uttamsharma** [comment]
Thanks for your response @paula-w
