### ISSUE TITLE
Duplicate a module

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#12548]
Hi,
is it possible to duplicate a vitiger module? For example, I would like to copy the products module & rename it. The products module has features that I would like to use in a separate module but when I try to create my own it does not operate the same. I would like to load data from a module similar to the products module onto an invoice but this data needs to be private & needs to fall under a different category other than products. I am working on something that would be an awesome feature to implement in the next version of yetiforce. If this is possible I can move forward with the idea. Thanks

**Comment by davide-alghi** [comment]
Hi, @hobejeans,
yes, you can export a built-in module (like Products), setting vtiger_tab.customized=1

but, before re-import, you have to modify, by hand, many things.

- all php class names
- all php class filenames,
- all js class names
- all js filenames,
- all related table names
- and many other things into classes to reference to the new named stuffs

after all this, it's not assured that the new so created module will work exactly as original Products: other new functions and changes must be made programmatically.

### anyway, don't try to re-import a so exported module without adequate changes because the risk is to damage your installation

My suggestion is to start with a new fresh empty module e build your custom module by hand, including database actions.

**Comment by hobejeans** [comment]
Hi Davide, Thanks for responding...  Can you explain a little further on the step to exporting a module. Thanks

**Comment by davide-alghi** [comment]
Of course: in table vtiger_tab, search for name='Products'; then change customized field to 1. After this, go to back-end: Standard modules > Modules – Installation: here you'll see export button for Products module. Click on it and save the zip file.
