### ISSUE TITLE
[Feature] Allow to store all data in a designated folder

### ISSUE THREAD

**Issue by ayufan** [YetiForceCompany/YetiForceCRM#12598]
## 🚀 feature request

I'm trying hard to deploy YetiForceCRM via Docker / Kubernetes. It is super hard, as YetiForceCRM writes files "all over the place".

- Can we somehow abstract where the files are stored?
- Can we make the application code to be immutable / and be allowed as read-only?

The above makes it significantly easier to deploy / update and manage data of YetiForceCRM, as:

- all data are stored in designated space
- only this folder requires write permission
- root filesystem with the application code can be mounted as read-only (eq. to making that all application code cannot re-write itself)
- makes upgrade simpler, as given that application is immutable (does not self-change) does not require any special "persistence settings", or overwrite of existing files.

### Describe the solution you'd like

I would like to pass an environment variable:
- `YETIFORCECRM_DATA_PATH=/data`

This environment variable would instruct YetiForceCRM from where to load/store all files, instead of defaults.

### Is your feature request related to a problem? Please describe.
Yes, it is impossible to run YetiForceCRM via Docker in a way that allows this container to be "somehow" easy to update"

### Describe alternatives you've considered
There's no really. I tried to alias path and link them to another places, but this is messy solution. 
Take a look at a list of "all files": https://yetiforce.com/en/component/zoo/item/web-server-requirements.

This is very long list of overrides.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
this is @bpabiszczak's answer:
For over 300 implementations I have carried out, only one customer had such requirements and it was a bank. The system can be easily run via docker, but running it in read-only mode requires programming.

- How should the system behave when we create new modules? Currently, it creates the appropriate files and directories, so should this possibility be blocked or moved to the database layer?

- How should the system behave when a user adds files? It should locate them in the database or in a directory [and we are talking here about at least two cache places, anti-virus, and a target directory]

- How should the system behave when we modify configurations? Currently, the configuration is in files with the option of modifying it from the configuration panel.

- How should the system behave when a user wants to download and install a new module from the store?

This can be changed, but I don't see any benefits at the moment. The situation when 1 in 100 companies has special requirements means that this company should have the software adjusted or the cost must be included in the implementation. In order to make such modifications, someone has to pay for them, and this is a considerable cost, probably around 10,000 - 15,000 EUR.

We don't plan such changes in the near future unless a bank with which we are negotiating decides to implement the system.
