### ISSUE TITLE
[Feature] Feature for sale and marketing

### ISSUE THREAD

**Issue by mdtuyen** [YetiForceCompany/YetiForceCRM#12591]
Hi @Team
Thanks for good system

In order to serve sales and marketing, I find the following function very important:
- Check in the position of sale (position at the assigned position of the day)
- Send messages / emails simultaneously, automatically or by schedule
- Managing social networks
Does your system have these modules yet? If so, in what position? If not, do you plan to integrate in the future?

**Comment by KatarzynaUlichnowska** [comment]
- I don't know what you mean by "position of sale".

- Such reports can be prepared by using the Workflow tool. YetiForce in version 5.3 will have some reports encoded, but they will be disabled by default because they should be adjusted to each client individually [maybe soon we will add the configuration in the panel]. We currently run reports for clients, but we always verify them before launching in production:
daily sales report
weekly sales report
monthly sales report
shortages report

- YetiForce offers integration with Twitter

Due to the fact that we don't sell licenses, we earn our living from services, so what appears in the new version of YetiForce depends on what customers order. So far, no customer needed integration with FB or LI, so there is no such integration and it will be added only when a customer orders and pays for such functionality or when we think consider it as necessary.

**Comment by mdtuyen** [comment]
Hi, 
"position of sale": I mean for example I have a sales team, I give them some customers who need to take care of / offer. I want to know where they went, whether or not they actually went to those positions.
As you said, there are some modules that are not shown on the demo, or not yet implemented. Do I need to pay for your implementation or integration? So is there any way or document that introduces these modules so I can refer to them first?

**Comment by KatarzynaUlichnowska** [comment]
Hello!
Unfortunately, I still don't know what you mean. If you carry out sales and it has stages, in the Opportunities you can see everything - its stage, who takes care of it and what should be the next step.
If something in YetiForce isn't enabled by default, it means that this functionality hasn't been finished yet.
