### ISSUE TITLE
[Question] ROUNDCUBE CONFIGURATION

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12592]
Hello ,

gitdeveloper config

[https://gitdeveloper.yetiforce.com/index.php?module=OSSMail&parent=Settings&view=Index&block=8&fieldid=94](url)

![image](https://user-images.githubusercontent.com/60758367/74822355-4a04ec80-5305-11ea-8239-369fc8ef8f7a.png)

Does it means that if credential are 

for smtp google :  login :  userA@gmail.com    password : userA_pass
                                          userB@gmail.com    password : userB_pass

User on the crm should be set as : 

user name : userA    password : UserA_pass 
                   userB     password : UserB_pass

so when UserA is connected to the crm,   system will map userA credential for smtp connection ?

REGARDS

**Comment by KatarzynaUlichnowska** [comment]
CRM login details and mailbox [Roundcube] login details are not the same things. When logging in to your mailbox, use the same data that is used to log in to Outlook/Thunderbird. Roundcube is an independent application [installed additionally] and that's why it also works independently [not using CRM login datails]. After logging in to the mailbox in the panel it is possible to relate the CRM user to the mailbox user here:
Software configuration> Mail tools> Mail - Auto Login

When you configure it, the system will automatically log you in and you won't have to enter your login and password each time.

If you purchased our SLA support for the system, we can help you configure your mailbox.

**Comment by fanthome75** [comment]
For sure , to support also the project
thanks
