### ISSUE TITLE
Implementing Yetoforce on Windows Server 

### ISSUE THREAD

**Issue by harshdoshihd** [YetiForceCompany/YetiForceCRM#12593]
Hello Team,

I have been trying to search how do implement Yetiforce on windows server but, haven't found any reference. Can anyone please help?

Things I did:
Updated php 7.4 on server
Enabled PHP support for the domain
unziped the package and uploaded on httpdocs folder on windows server. 

Errors I got in server logs:
2020-02-19 11:57:17 XXX.XXX.XXX.XXX GET / - 443 - 171.XXX.231.XXX HTTP/2.0 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/77.0.3865.90+Safari/537.36 - www.domain.com 500 0 2 1430 514 109
2020-02-19 11:57:17 XXX.XXX.XXX.XXX GET /favicon.ico - 443 - 171.XXX.231.XXX HTTP/2.0 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/77.0.3865.90+Safari/537.36 https://www.domain.com/ www.domain.com 200 0 0 5730 459 109

Thanks in Advance.

Best!

**Comment by davide-alghi** [comment]
500 is an Internal Error: probably YF requirements are not met on your server.

Maybe you have something like XAMPP installed and surely you have checked corrected working of Apache, PHP, MySql and PhpMyAdmin.
If all these are running correctly you have simply to check requirements and instructions. Take a look to YouTube video. **Requirements satisfaction is very important**.

https://yetiforce.com/pl/component/zoo/item/web-server-requirements
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/crm-installation
https://www.youtube.com/watch?v=MXmx73fQgRA

**Comment by paula-w** [comment]
This is @bpabiszczak’s response:

We discourage you from using Windows Server, it’s not a good environment for projects that require PHP and Apache/Nginx. I performed 2 installations  for clients on MS Server and each time I ran into a number of issues. Windows Server’s biggest problem are paths that you have to change in main php/mysql/apache config files in order for the system to work properly. If you have no other choice and must use Windows but have no experience with apache/mysql/apache then I’d suggest using something ready-made like XAMPP, however, these solutions have default configurations (which means they aren’t very safe).

You need someone who knows what they are doing in order to do this well. Our team unfortunately can’t help because we don’t have any experience with this and like I said before, we discourage everyone from using Windows server. 

Also, we don’t recommend PHP 7.4, for the latest stable version we suggest using 7.2.
