### ISSUE TITLE
[Question]  List view how to  mask button "add record" with removing create in profile

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12631]
Hi team ,

I would like my team record " customer sales order "  only from account view , this way 

![image](https://user-images.githubusercontent.com/60758367/75383289-63490280-58dc-11ea-9809-95f19f68b5ac.png)

But i want also to give access to all the record as list view but i want to delete action " add new record"

![image](https://user-images.githubusercontent.com/60758367/75383557-dbafc380-58dc-11ea-88b7-6f39cffad97f.png)

Why !  may be a setting issue because i would like to save " customer sales order "  without  quote 

and if i try to  add a record from list view , this is not working  but from account panel this is 
working

![image](https://user-images.githubusercontent.com/60758367/75384037-be2f2980-58dd-11ea-8446-e4702327021c.png)

Would be happy to find a way to solve this

thanks

**Comment by rskrzypczak** [comment]
> and if i try to add a record from list view , this is not working

It was blocked in order to ensure data consistency, so that the users don't add different Accounts than the ones that are supposed to be listed on an Opportunity or a Quote for example. 

> i want to delete action " add new record"

There is no way of removing the button without also removing the functionality to create records.
What you are trying to do requires programming work.
