### ISSUE TITLE
[Question] Cache issues

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#12650]
Hello Friends, just a little question related to cache

Using 5.3

When Accesing to calendar from account tab:

![image](https://user-images.githubusercontent.com/40429279/75665102-87556c80-5c6b-11ea-9ba2-a17b9bec1c32.png)

I cannot share the entry with other users when I do this process the second time. The field does not respond. I have to delete de browser cache and refresh everytime I have to do second appointment to the same account

![image](https://user-images.githubusercontent.com/40429279/75665234-c4b9fa00-5c6b-11ea-809a-0dc305f923b5.png)

I have marked in browser NO CACHE tag, but the behavior is the same.

![image](https://user-images.githubusercontent.com/40429279/75665337-e9ae6d00-5c6b-11ea-832e-a6e4790658ad.png)

thank you!

**Comment by rskrzypczak** [comment]
I highly doubt you're using version 5.3 because it hasn't even been released yet :)
However, browser cache should have nothing to do with it. 
Most likely there's something wrong with your files.
Enable [debugging](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Debug.php), maybe you'll find something in the console ([event](https://github.com/YetiForceCompany/YetiForceCRM/blob/ccc2b60e5861f5f8feb94c7355ee8d28e69b8536/public_html/layouts/basic/modules/Vtiger/resources/Detail.js#L1381)).
Check the cohesion between files and a clean version you have.
Apart from that, the error doesn't exist in either stable or dev versions so I'm closing the issue.

**Comment by santyabreu** [comment]
Sorry I meant 5.2

The browser goes fine when refreshing or deleting cache.
