### ISSUE TITLE
How to install on Synology

### ISSUE THREAD

**Issue by Ethratian** [YetiForceCompany/YetiForceCRM#12677]
Hello!

I tried to install YetiForce on my Synology NAS. The webserver is activated and I copied the core-version via FileZilla to "/volume1/web/YetiForce."

When i enter "myipadress/YetiForfce" in the browser I am redirected to "myipadress/YetiForce/install/Install.php" and I just receive the notification "This page isn't working"

Any suggestions?

Thanks!

**Comment by davide-alghi** [comment]
Hi @Ethratian,
that is an HTTP ERROR 500: internar server error. the problem is your server.
- did you download complete zip from here (**YetiForceCRM-5.2.0-complete.zip**)? https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/5.2.0/
- are all YF requirements satisfied? https://yetiforce.com/pl/component/zoo/item/web-server-requirements

In case the problem persists, please
- detail your server
- attach web-server error log (only piece between installation start time and installation crash time)
- attach database-server log (only piece between installation start time and installation crash time)


PS: after successful installation, remember to install last service package too: (**5.2.0_ServicePack_v19.zip**) https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/Update%20packages/

**Comment by Ethratian** [comment]
Hello @davide-alghi,

thanks for your suggestions.

I have downloaded the complete .zip-file.

Regarding the requirements: I do believe that the core software is installed.

Mint, CentOS, Debian, Ubuntu --> it is a Synology NAS.

Apache 2.4 , MariaDB10 and PHP 7.2 are installed.

Nginx is automatically installed as part of the webserver as far as i know.
The same goes for MySQL.

I will have to check whetere the requirements for the data base engine (MySQL) are met, since I never had to change anything in that area. Is this something that has to be done within phpMyAdmin?

I am not sure how to change the php.ini and .htaccess files regarding YF requirements. When I tried to change those files regarding other software the files were updated by Synology automatically sonn after and all my changes were overwritten.

**Comment by mariuszkrzaczkowski** [comment]
check the logs and carefully read the requirements and configuration is the key to success

**Comment by davide-alghi** [comment]
Hi, please follow our suggestions


> Regarding the requirements: I do believe that the core software is installed.
> 
it's not sufficient

> Apache 2.4 , MariaDB10 and PHP 7.2 are installed.
> 
ok

> I will have to check whetere the requirements for the data base engine (MySQL) are met, since I never had to change anything in that area. Is this something that has to be done within phpMyAdmin?
> 
maybe your problem is not db-server: anyway check requirements via phpmyadmin and/or mysql cmd line

> I am not sure how to change the php.ini and .htaccess files regarding YF requirements. 
>
they don't need to be changed

____________________________________________________________________
**HINT**

to quick and friendly check of YF requirements satisfaction, create a file named info.php and paste this
```PHP
<?php
  phpInfo();
?>
```
upload info.php file into web-server root folder and call it via browser: ```http://<ipaddress>/info.php```
__________ OR __________
if you prefer, you can enable phpInfo() into PhpMyAdmin, adding
```php
$cfg['ShowPhpInfo'] = true;
```
into 
```
/etc/phpmyadmin/config.inc.php
```
you'll find link **Show PHP information** on PhpMyAdmin dashboard

**Comment by apcloic** [comment]
@Ethratian Regarding Synology, maybe another option is to install and use Docker instead.

**Comment by bpabiszczak** [comment]
You must ask for administrator help or use hosting [~ 10$/$20 per month].
