### ISSUE TITLE
[bug] Invoicing does not work when "Products" are disabled

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12708]
# 🐞 bug report

### ⁉️ Describe the bug

As a consulting firm I only offer services, so I disabled the "Products" module.

When trying to produce an invoice, I cannot add a service
![inv](https://user-images.githubusercontent.com/10230144/76685831-04db8e00-6617-11ea-9410-46e2b56e4f4d.png)

The functionality works correctly when the "Products" module is enabled, but then I have to delete the first row suggested as it relates to a product.

### 🔥 How to trigger the error

1. Disable "Products" module
2. Create a new "Sales Invoice"
3. Try to add a new service 

### 👎 Actual Behavior

Service cannot be added

### 👍 Expected Behavior

It should be able to add a service

### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.3.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by davide-alghi** [comment]
Hi @diderich,
that is not a bug; you don't have to disable the product module: here the correct procedure ...

![invnoprods](https://user-images.githubusercontent.com/48508691/76687976-01510280-6629-11ea-8d6f-f7533c6bb9c2.gif)

**Comment by diderich** [comment]
Question: Are the other modules that need to be enabled for YetiForce to work correctly? If so, wouldn't it be sound to disable the possibility to disable them?

**Comment by davide-alghi** [comment]
Good morning Claude,
I agree with you. Some modules are mandatory, Accounts, Products and Services. it would be useful to introduce the concept of **system module**: system modules should be without enable/disable feature in back-end. another useful concept is **dependency between modules**. but this is not a priority, perhaps in the future.

about your first question: it depends, in primis, on what you are going to disable. for example: sales process has this flow

![sales-process](https://user-images.githubusercontent.com/48508691/76728762-e7620d80-6757-11ea-9c22-d8dfea3c746c.png)

before disable Opportunities module, you should modify relations in Sales enquiry, requirements, Calculations, Quotes and Sales Order.
Furthermore it depends on your customization: if you have related a lineitem with **specific module**, that **specific module** cannot be disabled

Maybe, sometimes, it's better to rework the main menù with needed modules only rather than disable unnecessary modules.
