### ISSUE TITLE
[bug] Workflows Error when task was executed during record creation

### ISSUE THREAD

**Issue by allyh12** [YetiForceCompany/YetiForceCRM#12782]
🐞 bug report

⁉️ Describe the bug
A workflow scheduled with 'Creating a Record' and 'Update Fields' was created.
Error message pops up when record was created.
However, workflow get executed and fields have been updated.

🔥 How to trigger the error
1. Create Workfows/Creating Record/Update Field
2. Create record in relevant module
3. Save the record
Error pops up
![image](https://user-images.githubusercontent.com/59724920/77726060-043cf180-7032-11ea-986d-199c2bd9b7da.png)

everytime when new record is created

👎 Actual Behavior
Error Message

![yetiforce2](https://user-images.githubusercontent.com/59724920/77725745-339f2e80-7031-11ea-85a3-46a2ea8f71b4.gif)

👍 Expected Behavior
No error message

👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [v ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

📷 Screenshot of configuration

📝 PHP/Apache/Nginx/Browser/CRM Logs

🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.3.0 SP1
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

❓ Additional context

❗️ Inform the community if you solve the problem

**Comment by mariuszkrzaczkowski** [comment]
logs ?

**Comment by allyh12** [comment]
Hi Mariusz,

Thanks for your prompt response.

I'm very sorry for asking some help as I'm new to Yetiforce.
Appreciate if you could provide some guidance on getting the logs ready for you.

https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/debugging

I refered to the above link and changed log-errors and display_errors to On in user.ini. Then, I tried to create the record to generate the error again but I still couldn't see those log files.

Thanks.

Regards,
Ally


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by allyh12** [comment]
Hi Mariusz,

I managed to get the system log!
Please check if this is sufficient.

Thanks,
Ally


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by z0lo13** [comment]
@MacarenaReina @allyh12 @mariuszkrzaczkowski 
its same issue as https://github.com/YetiForceCompany/YetiForceCRM/issues/12768

 the issue is with only VTUpdateFieldsTask with recordModel->save() 

particularly with 

```
public function getEventHandler(): App\EventHandler
	{
		if (!$this->handler) {
			$this->handler = (new \App\EventHandler())->setRecordModel($this)->setModuleName($this->getModuleName());
		}
		return $this->handler;
	}
```

if you replace 

`$eventHandler = $this->getEventHandler();`

with 

```
$eventHandler = new App\EventHandler();
        $eventHandler->setRecordModel($this);
        $eventHandler->setModuleName($moduleName);
```

everything the record saves just fine but it may break the additional validation implemented in 
https://github.com/YetiForceCompany/YetiForceCRM/commit/028601e97fd9c537e49890af4c97ec99f0448ac9#diff-b7da741f3a161a40feb12e45abc510eb

**Comment by zazy** [comment]
This happens in gitstable too, just tested. It appears that YetiForce tries to save the same record two times getting a duplicate key error from the database engine. If I disable the workflow that bind to "On create" all works fine. Also the _Every time a record is created_ bind causes the same error.

I noticed that this happens if the workflow tries to **modify the just created record**. If I use the same worflow but I change the field to modify from the same module to a related module all works fine

P.S.: **For anyone** looking for a solution and want to test a patch, I posted one to the issue #12768
