### ISSUE TITLE
[Question] How to update calendar from custom module

### ISSUE THREAD

**Issue by martin-crockett** [YetiForceCompany/YetiForceCRM#12935]
so i created a custom module, employes call customer and make appointement, after they put the date in the custom module. generate a calendar record. at this point everyhing works. but if the we need to change the date in custom module, and then try to update the date in the calandar with workflows it does not update in calandar.

how can i make it work ?

Here is me trying to do it with a manual execution of the workflow
![updatecalendar](https://user-images.githubusercontent.com/45770116/79916357-94cedd80-83f6-11ea-94a6-60dcaa5c6ecd.gif)

and here is my workflow
![workflow updatecalendar](https://user-images.githubusercontent.com/45770116/79916531-ec6d4900-83f6-11ea-9d5c-146c5e866e13.gif)

**Comment by apcloic** [comment]
@martin-crockett 
Maybe simpler is better ?
I don't know if I understand correctly but I think you don't need the "rendez-vous" block in customer module because it will be limited to a single entry while I suppose a customer may have multiple rendez-vous.
If you need to change the date of an event, your employees could go to calendar related tab and edit the rendez-vous directly here, no need for a workflow.
To avoid having to click on calendar related tab, you may configure and use a widget related to calendar.
https://gitstable.yetiforce.com/index.php?module=Widgets&parent=Settings&view=Index&block=2&fieldid=58

**Comment by martin-crockett** [comment]
they will work primarly in the custom module to book appointement. and the appointement needs to go in the calendar of an other specific person who goes at the house of the customer.

right now the first time that they book the appointement the generate de calendar record but after if they change it in the custom module, they have to delete the old calendar record et re-generate a new.

 i would like it to update the calendar record automatically when the record of the custom module changes...

and i want employees in the call center do less manipulations

**Comment by apcloic** [comment]
You could always write a custom workflow that will do exactly what you want.
I still don't see why you don't want to simply **edit** the related calendar event directly.
If you configure a calendar widget in your custom module, changing a date in the calendar event or in your custom module will take the same time.
