### ISSUE TITLE
[Feature] Email campaign tracking

### ISSUE THREAD

**Issue by blloyd78** [YetiForceCompany/YetiForceCRM#13009]
## 🚀 feature request

Would love to see an email marketing module. Essentially this would need:
- The ability to create a target list of email addresses
- A tracking pixel to detect when the email is opened
- Bounce detection to identify email delivery failures
- An unsubscribe mechanism that would 'disable' the recipient's email in there Yetiforce system

### Is your feature request related to a problem? Please describe.
This functionality is already in alternative systems like SuiteCRM

### Describe alternatives you've considered

I am waiting for Yetiforce to add this functionality so that I can move away from SuiteCRM

### Additional context

None

**Comment by bpabiszczak** [comment]
1. You can create any lists you want, both in campaigns and on record lists in other modules.
2. Tracking users is against GDPR (I haven’t met a company who legally obtained consent to do that before sending an email). We recommend using links that will be analyzed once they are clicked in the email and the user will go to the website. 
3. Bounce detection can be automated (it requires a programmer because we don’t have this functionality) although good databases will just require a little manual processing (especially if we are in touch with that person over the phone).
4. As far as unsubscribing is concerned, we have a mechanism like this in YetiForce and the API, but there is no mechanism that would let you unsubscribe at the email client level (eg. Outlook) but we’ll most likely add it soon. 

We only develop functionalities that are ordered by our clients, so everything you described will have to wait until we have a client who pays for it.

When it comes to Suite CRM, it's one of the worst possible systems due to its licensing - AGPL, which is the worst license for business and additionally Suite breaches SugarCRM’s license. These licensing issues should be what makes you change this system to anything else under a better license.

**Comment by waran70** [comment]
Below will not apply if user get consent to send emails. Email tracking is very important in marketing related applications.
On top of it admins can build near-artificial intelligency workflow system automating a lot. Tracking statistic should be a part of all contemporary CRM systems
> Tracking users is against GDPR (I haven’t met a company who legally obtained consent to do that before sending an email). We recommend using links that will be analyzed once they are clicked in the email and the user will go to the website.
