### ISSUE TITLE
[Question] Prestashop integration ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13140]
Hi,

Back in 2016, there was an announce regarding the integration of Yetiforce and Prestashop :
[https://www.facebook.com/YetiForceCRM/posts/the-integration-of-two-open-source-platforms-yetiforce-prestashop-is-available-i/372703616233709/](url)
I understand that this module is not available anymore because it is not compatible with YF current version.
Does YF team plan to release a new version ?
We will be glad to buy it.
Regards,

**Comment by bpabiszczak** [comment]
Nobody was interested in this integration. Version 5.4 has integration with Magento. Version 5.4 is "almost" ready.

**Comment by apcloic** [comment]
@bpabiszczak 
Thanks for your reply but how do you know that nobody is interested without asking Yetiforce or Prestashop community ?

**Comment by bpabiszczak** [comment]
GitHub is maybe 10% of the community, 90% contact us by email. We don't have to ask if no one asks us, that means there is no interest.

**Comment by apcloic** [comment]
@bpabiszczak 
Ok, I understand.
Do you mind sharing the PrestaSync module "as is", I know it's no longer compatible with YF current version but I will be very interested in study its code.
My email is apcloic@gmail.com
Thanks again.
Regards

**Comment by dandumit** [comment]
Good Morning,
I am interested as well in this integration. 
Could you please offer that code ? I will try upgrade it to this version.
thank you,
Daniel

**Comment by theGera** [comment]
some time ago I installed yetiforce and it was precisely because of that integration with prestashop.

Leave yetiforce, because we focus on having the perfect prestashop to integrate with yetiforce.

this year it was the idea of using yetiforce and prestashop .. and I find that it no longer exists :-(

It is correct and they have said that no one was interested. if it was only for a while and they didn't let them continue ...

This was my case, we saw that there was a way and now there is no 👎 

I would love for you to return, it is a good product yetiforce it does not have integration with perhaps one of the best oscommerce.

thanks.. 🥇
