### ISSUE TITLE
How do I assign Contact to a lead instead of Accounts

### ISSUE THREAD

**Issue by harshdoshihd** [YetiForceCompany/YetiForceCRM#13280]
Hi Team,

I see the last paragraph about the logic mentions:
Disabling Accounts for benefits of Contacts is possible, but not recommended. 

https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/how-to-enter-new-leads

But I do not see any knowledge base to help me do it.

I need to assign contact to - Opportunities & Projects instead of Accounts. 

Can you please help me with the same.

Best Regards,
Harsh

**Comment by KatarzynaUlichnowska** [comment]
The system treats the Accounts module as the primary module, where all companies/individuals can be found. Having one module [instead of two] allows for better reporting and sales analysis. That is why an Opportunity should always be assigned to an Account [it might be for Contact but this is optional], so even if you sell to private individuals, they must also be Accounts.

In the new version [5.4] it has been improved. When you create an Account, you select whether it is a private individual or a company. If it's a private individual, then the fields for name and surname appear instead of the company name. Please see the screenshots below. 

![Zrzut ekranu 2020-07-09 o 11 44 25](https://user-images.githubusercontent.com/10218164/87024866-f161bd80-c1d9-11ea-9eb3-50ab3b8b7075.png)

![Zrzut ekranu 2020-07-09 o 11 44 38](https://user-images.githubusercontent.com/10218164/87024874-f58ddb00-c1d9-11ea-8e80-5204bad5faa9.png)

**Comment by harshdoshihd** [comment]
Hi Katarzyna,

Thanks for your revert.

In my case, we work with organizations, where individual contact in an
organization are separate opportunities for us, hence we need to map
contact as well as accounts. If not accounts, contact is very much required.



Best Regards,
Harsh Doshi

**Comment by deepti4666** [comment]
I have the same issue, trying to connect an existing contact to a lead or opportunity
