### ISSUE TITLE
[Question] Minimum setup

### ISSUE THREAD

**Issue by krijnsent** [YetiForceCompany/YetiForceCRM#13314]
### Description
I just installed Yetiforce 0.5.3 through Softaculous and feel quite overwhelmed by all the modules that are installed & activated. I'm trying to find some documentation on which modules I need for the bare minimum of what we are looking for.

Let me paint you the picture, hopefully you can point me to the right documentation/posts:

- I'd like a minimal CRM, switch off anything we don't use
- our business is basically a monthly subscription to our software (Saas)
- we call people to plan demonstrations of our tool, those can convert into offers and those into contracts. I'd like to log that all (that's why I need a CRM).
- the subscription has a couple of options (basically 3 sub-products can be combined in any combination).
- we'd like to invoice our customers on a monthly/quarterly/etc basis.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
the [documentation](https://yetiforce.com/en/knowledge-base/documentation) for YetiForce can be found at our official website. 
The system allows for multidimensional management in a company therefore it is so complex. However, the unnecessary modules can be disabled in the admin panel [here](https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List). 
The sales process has been described in detail in our documentation. However, you can also check out our [mapping](https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List) feature which will allow you to create relations between any modules and convert documents. 
In order to generate recurring invoices, you have to first set up recurring orders, and then create a workflow.
Hope it helps. If you have any additional questions, I encourage you to check out our YetiForce Help package which includes e-mail support for admins and users. You will find it in our Marketplace as well as on our official website.
