### ISSUE TITLE
[Question] how to deal with page-break on multi-page invoice ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13459]
Hi all,

I'm using ProductsTableShortVersion on my PDF template, depending on the table size produced, I get different results.
For single page, I have no issue, it works great.
For multi-page, the first page contains only header and footer and the second page contains body + footer.
If I do another test with more products, then I get :
- first page with header + a body with the first part of the product table (which is great) + footer
- second page contains the second part of the product table...but it overlaps with the summary tax block + footer.
I would like to avoid empty 1st page as this is an invoice ;)
Also, I don't know why the product table overlap the SummaryTax table.
If someone have some tips in order to get nice and smart page-break on invoice PDF, let me know.
Regards

**Comment by vdpawel** [comment]
Maybe try to put everything in a table with invisible lines, I haven't tested this solution, but maybe thanks to this the elements will not overlap.

**Comment by apcloic** [comment]
@vdpawel thanks for your help, I did put everything in a table as recommended, unfortunately it still overlaps.

**Comment by KatarzynaUlichnowska** [comment]
The PDF library is still under development. If a customer orders printouts then we add mechanisms to the library that are not available but are required. Therefore, until the customer with higher printing needs appears, we won't modify anything in the library because we have no time for it. Your problem requires analysis (you haven't even sent the printout templates) and the analysis requires a developer.
