### ISSUE TITLE
Security issues 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#13559]
Hi Yetiforce Team

Unknown users tried to login into CRM with a different username. They tried 500 times within a single minute and same IP address but they could not log into CRM. Could this be a problem for our CRM or not.

**Comment by mariuszkrzaczkowski** [comment]
do you have an active bruteforce?

**Comment by bpabiszczak** [comment]
I suppose your CRM's web address is public!

**Comment by guide5232** [comment]
> do you have an active bruteforce?: 


Yes we have active bruteforce.


![Brute force](https://user-images.githubusercontent.com/47585969/94518172-0f721380-0247-11eb-997d-3eefcdabdf98.PNG)
![Login history](https://user-images.githubusercontent.com/47585969/94518174-113bd700-0247-11eb-8713-479f1c5d5fd9.PNG)

**Comment by bpabiszczak** [comment]
Write your CRM web address [if you don't want to enter it here, write me an e-mail: github@yetiforce.com]

**Comment by guide5232** [comment]
Ok i will send it

**Comment by guide5232** [comment]
> Write your CRM web address [if you don't want to enter it here, write me an e-mail: [github@yetiforce.com](mailto:github@yetiforce.com)]

CRM web address:  http://crm.xxxxxxxx.com.xx/index.php

**Comment by paula-w** [comment]
This is @bpabiszczak's answer:

Someone is trying to attack your CRM. Most likely the domain is public (eg. assigned directly to the IP, and once the IP is called the CRM is visible, which means you don’t need to know the domain name in order to access the website) or someone found out your CRM address and decided to attack you. The screenshots show that these are automatic mechanisms, they are not directed at YetiForce, they just blindly search for bugs. 

The best solution would be to hide your CRM behind a VPN, eg. if you have our hosting we can enable access only via VPN.
