### ISSUE TITLE
[Question] time control and time end

### ISSUE THREAD

**Issue by DarioGui** [YetiForceCompany/YetiForceCRM#13614]
Hello everybody,
when a ticket is closed, the time control opens.
the time control start date and time coincide with the ticket closing date and time.
Is there a way to ensure that the ticket closing date and time is taken at the time control closing date and time and not at the start?
for example:
if I close a ticket at 11:34 this time should be put in the ticket closing time in the time control

**Comment by Patriciawa** [comment]
Hi @DarioGui,
You could probably achieve this with Workflows

**Comment by DarioGui** [comment]
before answering I tried to see but I didn't understand the way.
With the workflow I can call the function to update the processing times but it is this that should be changed and it is out of my knowledge.
I add to the things I have to get done

Thanks a lot!

**Comment by KatarzynaUlichnowska** [comment]
You didn't provide the system version. In newer versions of the system, the Time Control doesn't appear after closing the ticket. In line with the business logic, you must first add working time and then close the ticket. If you want it to work differently [or more automatically] then you have to write or run the appropriate workflow. You may need a developer to do it because you want to set up some fields in Time Control.

**Comment by DarioGui** [comment]
Hello and thanks for the reply.
I have your Yetiforce Hosting and crm is updated to 5.3 with bugfix.
I have seen how the timesheet mechanics work but my timing logic is that when I close a ticket, the moment of closure must be entered in the timesheet's closure and not in the timesheet's opening.
I put in the list of things I will make you do :)
