### ISSUE TITLE
[Question] 5.4 gone from milestones

### ISSUE THREAD

**Issue by TonyM15** [YetiForceCompany/YetiForceCRM#13691]
5.4 gone from milestones and 6.0 already out of the deadline. Any chance to have clear and trustworthy 
project management here?

**Comment by bpabiszczak** [comment]
Appreciate what you have.

**Comment by JohnMaverick** [comment]
Blazej, your answer is ridiculous. You should rather keep silent than throwing such things (not the first time). Tony is totally right. You make this project your own barn forgetting that you are committed to the opensource honesty, openness, and expected professionalism. Being rude and shallow, won't help you now and in the future.
Shame man!

**Comment by bpabiszczak** [comment]
@JohnMaverick

The less a person contributes to the project in terms of money and time, the more they demand (I don’t know what it results from).

You’re confusing being honest for being rude. What @TonyM15 said added nothing to the project, it only had one purpose - to attack. For the past 6 years since the project was created there have been about 15 people, who kept attacking the YetiForce project to a greater or lesser degree. Anything is reason enough to attack, be it a removed functionality, a delay in release, or an error someone dislikes. 

Look at the profiles of people who joined the project and keep consistently contributing significantly more than they expect from others (@davide-alghi is a great example). They have more rights than @TonyM15 to demand and complain, yet they don’t - why? Because they know that nobody has created anything by complaining about it. 

My manner of tackling the issue depends on the other person. If @TonyM15 genuinely wanted to know why there is a delay, why v5.4 has been replaced by v6.0 he could’ve asked politely, but he hasn’t. That’s why he got this kind of answer. 

What’s gonna happen if @TonyM15 or you leave the project? Nothing. 20 others will come in your place. Especially that @TonyM15 as well as @JohnMaverick have taken more from the project than contributed to it (is this too brutal, or just very honest?).

What’s gonna happen if @TonyM15 or you, instead of complaining, start developing the system together with us? YetiForce will be even better. 

If some of the community members want to complain or take offense - there are better places on GitHub to do so. We simply don’t have time to deal with that.

**Comment by TonyM15** [comment]
"What @TonyM15 said added nothing to the project, it only had one purpose - to attack"  - Blazej, did you read carefully my post? Where is the word I attacked you? 

"What’s gonna happen if @TonyM15 or you, instead of complaining, start developing the system together with us" - How can we help you developing yetiforce if you don't bother with managing project in a professional manner? 

Every post which is not in line with your overgrown ego is bullied immediately. For that you have time, but to respect the community you don't ha? Do you know what respect should mean here? No, you don't.  Be professional, or stop posting at all.

**Comment by JohnMaverick** [comment]
Regarding: @JohnMaverick have taken more from the project than contributed to it
Believe or not Mr Blazej, but I don't use yetiforce for any production purposes. I am watching this because I like watching it.
