### ISSUE TITLE
niotifcations bug

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13910]
ok i made a test on gitstable so i hope now u can help me. now

creating a "project task" from demo yetiforce and assigning to to "sales yetiforce" users gives notifcation in worng way..

YetiForce Demo $(translate : ModTracker|LBL_CREATED)$ $(record : RecordLabel)$
it shoudl display task name and details...

![image](https://user-images.githubusercontent.com/54880467/101878774-27a2cf00-3bb6-11eb-8483-93fe966bda91.png)

_Originally posted by @rioshaz in https://github.com/YetiForceCompany/YetiForceCRM/issues/13909#issuecomment-743042941_

also notification list shows this  
![image](https://user-images.githubusercontent.com/54880467/101896964-d1428a00-3bcf-11eb-9b12-949eb515fb01.png)

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski @KatarzynaUlichnowska @davide-alghi

**Comment by rioshaz** [comment]
hello

**Comment by davide-alghi** [comment]
Hi @rioshaz,
I see that this problem was already issue and fixed(?).
But this fix fixed the problem? Sure?
https://github.com/YetiForceCompany/YetiForceCRM/pull/13433/files
if yes, pls check if the fix is there in your instance.

I don't understand how you can see "sales yetiforce" user notifications on gitstable? pls can you create a mp4 with all steps on gitstable?

**Comment by rioshaz** [comment]
@davide-alghi  its demo yetiforce... nit sales

thanks a lot problem solved
