### ISSUE TITLE
Encoding Asian currency symbol error

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#14]
PDF Output don't show Asian (particularly Thai) currencies. This is important issue significantly limiting usage of application. Encoding needs urgent review.

See the link for the attachment:
http://sourceforge.net/p/yetiforce/tickets/127/

**Comment by bpabiszczak** [comment]
At the moment, this problem is quite complex. It isn’t enough to add a currency sign to solve all the problems.

We don’t know what kind of problems may appear and what to watch out for. In this case, we have two ways out:

the community will solve the problem itself
someone from the community will describe in detail where and what should be added (in terms of translations, currencies, pdf printouts, configurations, coding, etc.)
Only in case of

a complete proposal of how to solve the problem
and a long-term interest
we can undertake the development of the PDF module
