### ISSUE TITLE
[REQUEST] Option to remove modules

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1482]
It's now easy to add/create  custom modules but there seems no simple way to remove them.
Would be nice to include a system for removing a module with files and tables completely.

**Comment by waw555** [comment]
Keep this topic

It is necessary to add the ability to delete and export modules

**Comment by reeid** [comment]
you can use: vtlib/tools.console.php
But not sure if this is working with YF..

**Comment by zebrahosting** [comment]
Well this is clearly not something needed short term. I would wait until the core dev is done because so much is changing at the moment. Another reason to wait is that there are no/hardly third party modules at the moment. Also less need for it since all requests where I needed modules for @vtiger are now already implemented in the core (and better). So yes I thing it is good practice when you have an installer, to also have an uninstaller but certainly should not be on top of the list.

**Comment by nikdejan** [comment]
+1

**Comment by ojundi** [comment]
+1

**Comment by bpabiszczak** [comment]
At the moment it's been given low priority, I'd gladly remove from the system the possibility of adding new modules... Such complicated things should be done by developers, not administrators. It's even worse with deleting, because only a programmer knows what should be deleted so that the system deletes everything. Additionally, a problem of relations appears, which can't be predicted automatically. The whole problem is so complicated and of so low priority, that I'd prefer to close the issue :]

**Comment by bpabiszczak** [comment]
First version: https://github.com/YetiForceCompany/YetiForceCRM/commit/c4f2db110e76f877a8c65ffbf52efda9d347cf07

**Comment by reeid** [comment]
After pressing Delete button, should popup warning dialog or even two, such as"
1. You are about to delete module. Are you sure?
2. This is last warning. Clicking OK will remove module from the system permanently.

**Comment by bpabiszczak** [comment]
Good idea, but please open new issue.
