### ISSUE TITLE
[bug] IMAP configuration for saving emails > ignored in Gmail

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#14925]
I have set AWS SES as a SMTP and pointed sent emails to be saved in certain folder (label) in Gmail.
Whatever label I enter in the field "Folder" the emails will be set anyway in Inbox

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/124806247-c466f880-df5c-11eb-94d1-9fe153798cd6.jpg)

**Comment by s2b-git** [comment]
Not sure how to write this issue in line with provided template. I cannot test it on installations provided for testing and I will expose my passwords.
 Here is the way (one of) I trying to set sent emails in sent folder

**Comment by s2b-git** [comment]
Tried various config, and nothing is working. Cannot save sent emails 
![image](https://user-images.githubusercontent.com/84110093/124866120-1011b480-dfe6-11eb-9df6-f6474bd4b82a.png)

**Comment by apcloic** [comment]
@s2b-git I remember I also had some issue with saving sent mails to Gmail while using Postfix as MTA.
Afaik it may depend on which language is used on Gmail side, this problem is not related to YF.
Give a try with something like this as Folder : [Gmail]/Sent
For example, in french I had to use : [Gmail]/Messages envoyés
Where "Messages envoyés" is the french translation for "Sent".
Regards,

**Comment by s2b-git** [comment]
[Gmail]/Sent Mail - this works.

Thanks!

**Comment by TonyM15** [comment]
However, it is enigmatic to save sent emails in Dovecot IMAP. What would be the folder name in this case?
