### ISSUE TITLE
[bug] payment status is not reset to default value when duplicating an invoice

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#15212]
Hi,

Not a big deal but I've noticed that when duplicating an invoice, payment status is not reset to default value.

![payment_status_not_updated](https://user-images.githubusercontent.com/2930560/134324581-6cd2152b-8f01-4b61-8809-48887695910e.gif)

Ok, found a simple solution by creating a workflow for sales invoice that will reset "payment status" to default value when creating a new record.

Regards,

**Comment by vovpff** [comment]
@apcloic Your solution is good but I think this option should be flexible for users/admins. In case of duplicating for example IGDN/IGRN with `Accepted` status there is two problems:
1. Products quantity calculated when saved every time (IStorages handler)
2. If user don't have permissions to set `Accepted` status he can't change status to `Draft` or any other because status field is grey (not editable)

**Comment by vovpff** [comment]
What is difference between displaytype 10 and 2?

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/be762076179912f3e65abbbb38667da8866cbcb5/languages/en-US/Settings/LayoutEditor.json#L77-L83

**Comment by vovpff** [comment]
@rskrzypczak how to be with duplicating IGDN/IGRN modules records?
