### ISSUE TITLE
Not able to create a REST API user on DEMO

### ISSUE THREAD

**Issue by bmankowski** [YetiForceCompany/YetiForceCRM#15307]
When trying to add a rest api user:
https://gitstable.yetiforce.com/index.php?module=WebserviceUsers&view=List&parent=Settings
I'm not able to close a form and add the new user.

**Comment by rskrzypczak** [comment]
Yes, since the stable version requires support for Argon2id hashing algorithm.
This has already been fixed here: https://github.com/YetiForceCompany/YetiForceCRM/commit/0940e785ed8dd866b70859475066287836963fa4#diff-11f0abb3f07603a1ab93c353847cca7663759866bddd15327aa90dbe6155cea9R301

We will improve the demo stable environment soon. Thanks.
