### ISSUE TITLE
[bug] Fresh 6.2 install, multiple issues

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#15310]
Hello friends from Yeti! 

Just wanted to list some of the issues I've experienced with a brand new 6.2 installation. 

Just installed Yetiforce 6.2 on top of Plesk web server with PHP 7.4 and Apache run on Plesk. All went pretty smooth with no issues. Copied Yetiforce files into the Plesk file manager and ran the Yeti install wizard. 

These are the issues that I've got so far. I don't know if they are related. 

1. When trying to create a new calendar To Do record, the calendar loads and "Loading Please Wait" message keeps spinning preventing from being able to do anything else. Have to refresh the page to get out of the calendar. 
2. When I create a new Filter in Settings > Labels Filters, it gets saved, but then when I try to add sorted by, the sorting option does not get saved. It just goes back to the empty default value.
3. When I try disable Visit Purpose message through the web gui and go to Settings > Admin Access it loads a blank page and gives a message saying "Error, please inform the administrator". Both Admin Access and Visit Purpose tabs are blank.

I don't know if these issues are related at all, or if they are related to installing Yetiforce in Plesk. But installing Yeti in Plesk seems to be a simpler process and you don't have to install everything manually like PHP, Apache, MySQL etc. Plesk takes care of all that. 

Are there any certain best practices when installing Yeti in Plesk?

**Comment by vovpff** [comment]
I think you need to tune your  web server config at first.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/137202705-248aab13-11f6-48ac-97fd-b5363a94d19c.jpg)

**Comment by acoolov** [comment]
What are the other requirements to tweak with the web server apart from the php flags and such? @vovpff

**Comment by rskrzypczak** [comment]
The first thing you should do is install the latest service pack which contains fixes for some of the bugs you mentioned. The remaining bugs have already been fixed in the development version and will disappear after the update to 6.3, which is due to be released soon.
I am closing the issue because I do not see any errors that need to be fixed.
Before creating the issue, check if the bugs are present in the demo version(https://gitdeveloper.yetiforce.com/), and for other issues please create a discussion.

@acoolov https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements
