### ISSUE TITLE
[Improved PDF templates] Separation of products and services

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1556]
Please add the PDF templates, the ability to embed a separate table with products and services.

**Comment by bpabiszczak** [comment]
Currently you can control the order and set the position according to the order. I don't really understand the point of that division, because both elements [products/services] must be arranged in a way that allows adding them up.
In the new version of the product module it will be possible. We won't change it n the old version. I'm closing this issue, when we release the new module you can open a new issue if you think it's missing something.
