### ISSUE TITLE
some question about ftp setting at backup

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1563]
I check the YetiForce 2.0.346,use the Firefox web,When I enter the IP and port, click save button and the status icon is green,but after I refresh the web,the status icon is red.when generate backup,the ftp folder has no files for backup.At the backup folder  the files have existed.
![snip20150721_2](https://cloud.githubusercontent.com/assets/12697896/8790279/a4f058a0-2f7e-11e5-9eb5-54450cc5c6f5.png)
When I set the setting at YetiForce 2.0.0 RC,When I refresh the web,the status always is green.

**Comment by bpabiszczak** [comment]
Please test on developer version:
https://gitdeveloper.yetiforce.com/
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer

**Comment by bpabiszczak** [comment]
The backup module doesn't work correctly for 2.0.0 version. It was redesigned and fixed in the new version [2.1 version will be released next week], currently you can test the new solution in here:https://gitdeveloper.yetiforce.com/ , or you can download the latest version from: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer and check if the new version works correctly.
