### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1564]
ver. 2.0.484:

Opening the CRM on an iPad slides the body part up, hiding the filter section in most modules like contacts. It does not give a mobile option.
![crm_ipad](https://cloud.githubusercontent.com/assets/10379403/8793449/37a83274-2f77-11e5-8dc1-5a6c67234d23.png)

Opening on an iphone (6+) Does give the mobile option on the login screen but after selecting it, it blanks the screen. The URL shows xxx/modules/Mobile/

**Comment by eptapsyxos** [comment]
The theme is even worst at iPad mini.you can not handle it at all...

**Comment by florek41** [comment]
And here is right place for question: what about using CRM on smartphones / tablets ?
Any plans about Yeti App (ios/android) ?

**Comment by bpabiszczak** [comment]
At the moment we have no plans concerning mobile versions. When it comes to responsiveness, we will work on it in 2.2 version

**Comment by bpabiszczak** [comment]
In YetiForce the mobile version, that has always been available in /modules/Mobile, was disabled by default [there were some security errors that we haven't dealt with yet]. You can enable it here [at your own risk] :  https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/api.php.

A responsive version on the system is in preparation, and will be released either in v2.3 or v2.4. We are not planning to publish a mobile app for Android or iOS, it will appear in the future, but I don't know when exactly. I'm closing the issue, because like I said – we are working on the changes related to responsiveness; you can report errors once we publish them.
