### ISSUE TITLE
Default sorting order

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1572]
is there any way to define default sorting (colum and order) in
- filters
- normal list view
- widgets
?

It would be very useful specially in filters.

**Comment by bpabiszczak** [comment]
Currently sorting is controlled by the main file of the module, for which we review the data [regardless whether we do it from the record list in this module or as a related module] In order to change sorting it's necessary to change for example 
https://github.com/YetiForceCompany/YetiForceCRM/blob/master/modules/Accounts/Accounts.php

//Added these variables which are used as default order by and sortorder in ListView
var $default_order_by = 'accountname';
var $default_sort_order = 'ASC';

In the future we will add the option to configure sorting from the panel.
