### ISSUE TITLE
[enhancement] Inline editing in listview - UX improvement

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1612]
Fast editing record form listview (ex. status) will be very big user experience improvement and speed up work with CRM.

Something like editing in Summary view, but on list with all other records.

Did you think about that ?

**Comment by nikdejan** [comment]
+1 
And also editing related modules from Summary View Widgets would be a great improvement to user experience.

**Comment by bpabiszczak** [comment]
We thought about a functionality like this. From the technical point of view it would definitely cause many problems, that would keep appearing for weeks, though it's not a problem [yet in SuiteCRM they still have issues with this change]. Some clients who use the system think that the current chance of an “accidental” change of something is too high. They often need to add the option to confirm the change in case of quick edition, because leaving the field is frequently accidental.

On the other hand, we change our attitude to some fields, for example to the status field, which in our opinion should not be editable in any module! The system should have the full control over the status, because processes, filters, widgets and many more elements are dependent on it. Check what accepting an event from the widget in Account looks like to see where we are going with this [some statuses are controlled by cron, some by the user – we define the user's permissions to actions in the profile]

At the moment we are not planning to implement a change that would allow to edit any field from the list view.
