### ISSUE TITLE
[bug] Calendar: Status - Picklist Field values cannot be edited / roles assigned

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#16402]
# 🐞 bug report

### ⁉️ Describe the bug

The `Calendar` module contains a field picklist called `status`:
![field](https://user-images.githubusercontent.com/10230144/187061636-142b5b5c-eb35-4924-a9ae-2eee173901af.jpg)

Neither the values, not the assignment to specific roles of those values can be edited:
![calendar](https://user-images.githubusercontent.com/10230144/187061653-5bb4abb3-18fc-4733-8358-59ba15ab3c1d.jpg)

One consequence is that it is impossible to define a calendar list that filters on the entry status.

### 🔥 How to trigger the error

1. Go to 'Software Configuration / Standard Modules / Fields - Picklist'
2. Select 'Calendar' module
3. Look for picklist in calendar
4. Picklist status cannot be found

### 👍 Expected Behavior

Status picklist is displayed and can be edited / assigned to roles.

Status picklist is not available for editing

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

Not relevant, as problem occurs on https://gitstable.yetiforce.com and https://gitdeveloper.yetiforce.com.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Not relevant.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4.0 / 6.4.16
| PHP                                 |   8.0.22             |

**Comment by rskrzypczak** [comment]
I see no error here.
Calendar status is determined automatically.
No user should be able to manually change the status except with a small exception as shown below.
![image](https://user-images.githubusercontent.com/10221999/187069644-a38f22e7-1d56-4d0c-adcf-bb0fc9783ad0.png)
These actions, however, depend on separate configurable actions on the profile.
![image](https://user-images.githubusercontent.com/10221999/187069688-55bb44bb-f05d-44aa-b3bf-6ac54bbd59ed.png)


For now, I am closing the issue, because as I mentioned, I do not see the error here.
If you have any comments, feel free to mention them.

**Comment by diderich** [comment]
I want to create a calendar list that filters on `status`. But in my installation, I don't see any options. It is my understanding that I do not have access to that picklist's elements, so I wanted to add the access, but, as shown in the picture 2 in the original post, this is not possible:
![error](https://user-images.githubusercontent.com/10230144/187070292-53f9c877-bab2-4d9c-b4ac-97563eb50a9e.jpg)

**Comment by rskrzypczak** [comment]
The issue does not occur in YetiForce version 7
