### ISSUE TITLE
Upgrade ERROR[bug] 

### ISSUE THREAD

**Issue by Xtrato01** [YetiForceCompany/YetiForceCRM#16541]
Hi , so im getting the following ERRRO while upgrading ,not sure what the issue might be ,but any help is appreciated :

Current Versions: Y6.3.0
To Version: 6.4.0
Package name: YetiForce CRM 6.4.0 v3

`['tableName'=>'vtiger_project','columns'=>['targetbudget'=>NULL],'conditions'=>['targetbudget'=>'']]` PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DECIMAL value: '' in /YETIPATH/crm/vendor/yetiforce/yii2/db/Command.php:1302 Stack trace: #0 /YETIPATH/crm/vendor/yetiforce/yii2/db/Command.php(1302): PDOStatement->execute() #1 /YETIPATH/crm/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE `vtiger_...') #2 /YETIPATH/crm/app/Db/Updater.php(120): yii\db\Command->execute() #3 /YETIPATH/crm/cache/updates/updates/init.php(674): App\Db\Updater::batchUpdate(Array) #4 /YETIPATH/crm/cache/updates/updates/init.php(139): YetiForceUpdate->updateData() #5 /YETIPATH/crm/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /YETIPATH/crm/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /YETIPATH/crm/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import('cache/542747ff8...') #8 /YETIPATH/crm/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3(Object(App\Request)) #9 /YETIPATH/crm/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModul...', Object(App\Request)) #10 /YETIPATH/crm/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process(Object(App\Request)) #11 /YETIPATH/crm/index.php(26): Vtiger_WebUI->process(Object(App\Request)) #12 {main} Next yii\db\Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DECIMAL value: '' The SQL being executed was: UPDATE `vtiger_project` SET `targetbudget`=NULL WHERE `targetbudget`='' in /YETIPATH/crm/vendor/yetiforce/yii2/db/Schema.php:678 Stack trace: #0 /YETIPATH/crm/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `vtiger_...') #1 /YETIPATH/crm/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE `vtiger_...') #2 /YETIPATH/crm/app/Db/Updater.php(120): yii\db\Command->execute() #3 /YETIPATH/crm/cache/updates/updates/init.php(674): App\Db\Updater::batchUpdate(Array) #4 /YETIPATH/crm/cache/updates/updates/init.php(139): YetiForceUpdate->updateData() #5 /YETIPATH/crm/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /YETIPATH/crm/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /YETIPATH/crm/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import('cache/542747ff8...') #8 /YETIPATH/crm/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3(Object(App\Request)) #9 /YETIPATH/crm/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModul...', Object(App\Request)) #10 /YETIPATH/crm/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process(Object(App\Request)) #11 /YETIPATH/crm/index.php(26): Vtiger_WebUI->process(Object(App\Request)) #12 {main} Additional Information: Array ( [0] => 22007 [1] => 1292 [2] => Truncated incorrect DECIMAL value: '' ) ``

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/193415923-4fa26af3-afc9-47fe-81c6-01a6a4879552.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Send the log file to github@yetiforce.com

**Comment by zazy** [comment]
Got the same error upgrading from 6.3.0 v8 to 6.4.0 v3. 

Apache 2.4.41
PHP 7.4.3
MySql 8.0.30

My error is a little bit different. I have an incorrect INTEGER instead of an incorrect DECIMAL on the same column of the same table:
['tableName'=>'vtiger_project','columns'=>['targetbudget'=>NULL],'conditions'=>['targetbudget'=>'']] PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' in /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php:1302 Stack trace: #0 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1302): PDOStatement->execute() #1 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute() #2 /var/www/yetiforce/app/Db/Updater.php(120): yii\db\Command->execute() #3 /var/www/yetiforce/cache/updates/updates/init.php(674): App\Db\Updater::batchUpdate() #4 /var/www/yetiforce/cache/updates/updates/init.php(139): YetiForceUpdate->updateData() #5 /var/www/yetiforce/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /var/www/yetiforce/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /var/www/yetiforce/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import() #8 /var/www/yetiforce/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3() #9 /var/www/yetiforce/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod() #10 /var/www/yetiforce/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process() #11 /var/www/yetiforce/index.php(26): Vtiger_WebUI->process() #12 /var/www/yetiforce/public_html/index.php(13): require('/var/www/yetifo...') #13 {main} Next yii\db\Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' The SQL being executed was: UPDATE `vtiger_project` SET `targetbudget`=NULL WHERE `targetbudget`='' in /var/www/yetiforce/vendor/yetiforce/yii2/db/Schema.php:678 Stack trace: #0 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException() #1 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute() #2 /var/www/yetiforce/app/Db/Updater.php(120): yii\db\Command->execute() #3 /var/www/yetiforce/cache/updates/updates/init.php(674): App\Db\Updater::batchUpdate() #4 /var/www/yetiforce/cache/updates/updates/init.php(139): YetiForceUpdate->updateData() #5 /var/www/yetiforce/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /var/www/yetiforce/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /var/www/yetiforce/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import() #8 /var/www/yetiforce/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3() #9 /var/www/yetiforce/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod() #10 /var/www/yetiforce/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process() #11 /var/www/yetiforce/index.php(26): Vtiger_WebUI->process() #12 /var/www/yetiforce/public_html/index.php(13): require('/var/www/yetifo...') #13 {main} Additional Information: Array ( [0] => 22007 [1] => 1292 [2] => Truncated incorrect INTEGER value: '' )

**Comment by Coonelli** [comment]
I'm also having this issue.

# 🐞 bug report

### ⁉️ Describe the bug

When attempting to upgrade, an error will appear indicating the database update failed. This occurs while attempting to upgrade to 6.3 securityfix 8 AND 6.4.0 v3.

### 🔥 How to trigger the error

1- Go to software configuration > logs > updates
2- Click Download package for 6.3.0 securityFix v8 or 6.4.0 v3
3- Click Install package
4- accept disclaimer
5- get error

### 👎 Actual Behavior

System is not updated.

### 👍 Expected Behavior

The system updates.

### 👷 Testing



- [ Not Applicable ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ Not Applicable ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment



| Environment                         | Version / Name |

| YetiForce                                               | 6.3.0 v3
| Web server (name and version)       |  2.4.41
| PHP                                                        | 7.4.33 (8.1.14 also available)
| Browser (name and version)             |  Firefox 108.0.1
| Operating System (name and version) | Ubuntu 20.04
| Database (name and version)         | MySQL 8.0.31
| Service Pack version                         | 

### ❓ Additional context

Add any other context about the problem here.

**Comment by Coonelli** [comment]
Log files sent to [github@yetiforce.com](mailto:github@yetiforce.com)
