### ISSUE TITLE
[bug ] bug in picklist dependency

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16632]
### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/16631

I can only make picklist dependence working with two picklist fields
I trying to design in cascade mode three picklists. Second working well with first, third ignoring second and first values.
This scenario is tested in both 6.3 and 6.4 installations. Currently cannot access dev so I cannot confirm, but it seems that it will show the same (as I tested on two apps).

Scenario has been recreated on git stable in Services in block TEST BLOCK
Fields P1, P2, P3
Conditions are set in picklists dependency panel 
If you check carefully you will realize that dependencies are ignored

Best

**Comment by s2b-git** [comment]
I found this: https://github.com/YetiForceCompany/YetiForceCRM/pull/16149/commits/1ded2215ff85f4ce9993681ff00311a1ea9ee57d

But replacing files in the latest version (including latest update) returning error. Seems like some dependencies got missed in PR?

**Comment by rskrzypczak** [comment]
The commit indicated by you does not apply. 
The mechanism has been completely rebuilt and operates on a different basis.
There is no longer any limit to the number of picklist dependencies. You are currently setting conditions for each picklist value independently.
**I don't see any error here.**
If you can, post a short video of the problem because the test environments are restarted.

**Comment by s2b-git** [comment]
No I can check on gitdev and indeed it works. Seems like upgrade to 6.4 doesnt went well (however no single error showed up). Will be checking
