### ISSUE TITLE
[bug]Project Tasks import does not work

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1689]
when I import the data from v2.0.0 RC to v2.0.683,it give such error:
![qq 20150803170825](https://cloud.githubusercontent.com/assets/12697896/9034439/4248f52a-3a02-11e5-81ac-016c56295b89.png)

**Comment by MaciejStencel** [comment]
It is not an error Per se. Project task has few reference fields mainly to related project and related project milestone. It has another reference field which is referencing another project task. In english translation fields referencing parent project and another project task were the same.

Mandatory one was referencing project, not mandatory one was referencing project task. It has been changed so that the second one is now translated as 'Related task', so it won't be confusing more.

Regarding your problem, i can see from screen shot that you have mapped field Related to to Project::::Building. Thsi field is not amndatory, it is referencing another project task. The mandatory one, referencing parent project is not mapped on the screen, hence when submitting you have error about mandatory field not mapped.

If you'll check closely on the dropdown You have two fields Related to, one with star.

This field has been translated now to project task, and You can check it on gitdeveloper.yetiforce.com.

I have checked import of project task and it went smooth after correctly mapping of fields.
