### ISSUE TITLE
[Enhancement] Required fields

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1717]
Currently the system has a number of fields marked required. Looking at them, some of these fields are required for the system to work (because they are referenced somewhere else) and some fields are required because of an assumed business logic.

There should be a possibility (for example in the settings module) to see which fields are required by the system and which are required by the configuration / assumed business logic. This is important when configuring the system to match a perticular business model's needs without breaking the system.

For example in the lead module, "Lead status" is a field required by the system to work (the possibilty to convert a lead to an opportunity depends on it). On the other hand a field like "VAT" is required in a give business logic but could be made inactive or even deleted if the system is only used for B2C.

**Comment by bpabiszczak** [comment]
Currently this is how the system works. There are some system fields that can't be disabled or modified, because they're system fields, and there are some other fields that someone marked as “mandatory”, but this can be changed in the settings. 
For some time it was possible to manage all fields from the panel [we thought it was a good functionality because we needed it ourselves], unfortunately most of the users disabled all the fields, which was their loss, therefore in the current version some field managing options are only available in the developer mode [https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/developer.php].
