### ISSUE TITLE
[bug] Cannot change language

### ISSUE THREAD

**Issue by diealon** [YetiForceCompany/YetiForceCRM#17292]
Hello. I just started using the Yetiforce system. I did a lot of research on the problem I was experiencing, but I couldn't find any results. After integrating the system into my website, I want to change the language settings, but no matter what I do, the language cannot be changed. It always remains in English. Thank you very much in advance if you can help.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/102286811/61cfb50e-abb3-4fb8-9d6a-64d7633bd10d)

Even though I click on the update button and the default button, there is no change.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/f5c2d8ea-6381-4be7-9f2f-462d7414ae50)

**Comment by rskrzypczak** [comment]
In your screenshot, you can see that you have **Turkish set as your default language**.
so you don't have to change anything, because everything is already OK.
I would like to point out that Turkish is only translated in 28%, so don't be surprised that most of it is in English ;)
https://crowdin.com/project/yetiforcecrm
