### ISSUE TITLE
Custom Module new record redirect to empty page

### ISSUE THREAD

**Issue by ojundi** [YetiForceCompany/YetiForceCRM#1731]
Symptoms

After adding a record to any custom module the system redirects to an empty page index.php page.

**Comment by konadrian** [comment]
Can you occur this error on https://gitdeveloper.yetiforce.com

**Comment by ojundi** [comment]
nope and checked master as well.. no issue there

**Comment by SkavenKF** [comment]
I have the same problem with a new 2.1 installation ...

**Comment by SkavenKF** [comment]
with test.yetifforce.com i became the following error 
"Fatal error: Call to a member function rowCount() on boolean in /home/yetiforce1/domains/test.yetiforce.com/public_html/include/database/PearDatabase.php on line 283"
when i add a record to a custom module (see. Kontaktliste under "Companies and Contacts)

I hope it gave a patch for the "unstable" 2.1 release, that make the relase useable.

**Comment by bpabiszczak** [comment]
In order to fix your error we have to be able to trigger it. Unfortunately, the description you provided us with is not enough, which makes it impossible for us to help you. You can try using these fixes:

https://github.com/YetiForceCompany/YetiForceCRM/commit/bcd14e91a51c93508dd8601d91562d2762ceaa28 

https://github.com/YetiForceCompany/YetiForceCRM/commit/9743193eaf867cea1d4fbe73f78e1f7a9f3504de 

but I don't know if it's related to the same situation you're experiencing.
Unfortunately, you have to find a way to trigger this error on master/developer version or run the test version of your system somewhere, so that we can trigger this error and access the logs.

**Comment by SkavenKF** [comment]
to became the error, do the following:

1. https://test.yetiforce.com/
2. go to ModuleManager
3. Create Module
4. Fill the following fields and Save
	*Module name	= "testmodul"
	*Module label	= "TestModul"
	*Entity field name	= "test"
	*Entity field label	= "Test"
5.	Got to Fields and Layout Editor and add the following custom field to the block "Custom Information":
	Select Field Type	= "Text Area"
	* Label Name	= "description"
	* Field name	= "Beschreibung"
	* Table	= "Additional (eg. vtiger_accountcf)"
6.	Add the new Modul to a menü
7. 	got to the Modul "TestModul"
8. 	Add an entry and save.
	Field Test = "Test"
9.  => Fatal error: Call to a member function rowCount() on boolean in /home/yetiforce1/domains/test.yetiforce.com/public_html/include/database/PearDatabase.php on line 283

the two fixes don't work for me :-(
