### ISSUE TITLE
[BUG] Login page for small devices v 2.1

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1732]
Design bug Login page for small devices.  Example: Samsung Galaxy S3

![screenshot_2015-08-06-23-40-08](https://cloud.githubusercontent.com/assets/1402355/9120392/6e25fb94-3c95-11e5-956c-307ba3d3a712.png)

**Comment by bpabiszczak** [comment]
In the first stage we updated the libraries [v2.1] ignoring the responsiveness. In the second stage we will concentrate on the responsiveness and fix the appearance [v2.2/2.3]. The third stage will be designing a new better template [v2.4/2.5].
I don't classify it as an error, because it was our initial intention.
