### ISSUE TITLE
[BUG] creating records

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1739]
Found a few places where I am unable to create new records:

From with a project, trying to create a Project task
From within an Account trying to add a contact.

Doing this directly from the menu, it works fine.

**Comment by kpaulaha** [comment]
Same with organizations, contacts etc. Can not create new opportunities, activities, projects, etc from them

**Comment by SkavenKF** [comment]
Same with Select.

Without this function, the 2.1 Release is not very useable. I hope it gave a official patch for 2.1.

**Comment by rskrzypczak** [comment]
I can't see that the 'Select' button works incorrectly. Please check it here https://gitdeveloper.yetiforce.com, if the error still occurs provide me with more details.

**Comment by zebrahosting** [comment]
You are correct, it is working on versions > 2.1.0
We did updates from 2.0 to 2.1.0 and had this problem. I have just copied over most of the files from the dev branch to our CRM and now it also works. 
Still leaves the problem for 2.1.0 people that did an early update.
Yeti demo is also already on 2.1.2 but there has not been a patch for 2.1.0 ->2.1.2
Hoping that no DB changes have been made in between it could be a matter of copying the right files over but still, these are the little things where patches should work and the distributing program should be  adjusted for.

**Comment by SkavenKF** [comment]
I have tested with the "stable" 2.1 https://test.yetiforce.com, not with the developer version. 
I think, the 2.1 should be the productive version for customers.

With the post from Błażej yesterday, he clarify the update strategie from yetiforce. I hope the first patch for the stable is faster as every few weeks ... :-)

**Comment by SkavenKF** [comment]
zebrahosting +1

**Comment by bpabiszczak** [comment]
You should never overwrite the gitdeveloper files, we introduce tons of changes there [at the moment we got the 2.1.39 version], doing this might solve one or two problems and generate several new ones, which you won't be able to handle.

A test upgrade package for the current version you can download here [test version]: 
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.1.0_to_2.2.0/zip

**Comment by zebrahosting** [comment]
Nice to see a patch version but aren’t you a bit over enthusiastic with the versioning?

We are currently at stable 2.1.xx.
I am at 2.1.0 and your demo site is at 2.1.2 so I would expect a patch file 2.1.0 to 2.1.2

If this is already a test first version for 2.2 I still have the trouble with my stable sites that I manually need to fix the bugs. Without it is not usable.
Guess I am not the only one.

But very glad most of the main issues are fixed in a short time span, now we just need a proper way to upgrade stable CRM’s in between.

Bastiaan Houtkooper
Zebra Hosting


From: Błażej Pabiszczak
Reply-To: YetiForceCompany/YetiForceCRM
Date: maandag 10 augustus 2015 12:59
To: YetiForceCompany/YetiForceCRM
Cc: Zebra Hosting
Subject: Re: [YetiForceCRM] [BUG] creating records (#1739)


You should never overwrite the gitdeveloper files, we introduce tons of changes there [at the moment we got the 2.1.39 version], doing this might solve one or two problems and generate several new ones, which you won't be able to handle.

A test upgrade package for the current version you can download here [test version]:
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.1.0_to_2.2.0/zip

**Comment by bpabiszczak** [comment]
I don't know why there's a different version than 2.1.0 in the test version, I'll find it out tomorrow because I don't remember ordering the update for the test version to anyone. 
The link to the update package you received is the developer version and it's used to update the system from v2.1.0 to v2.1.x if someone needs that [for example you need an update to v2.2.0 because some functionality is not working for you]. The update package you have the access to is the test developer version [we don't officially post it anywhere, because the official version will be available in September]. This package is made on an incremental basis, which mean that every couple of days the programmer receives the changes that were accepted and they appeared in the Master version. It received the 2.2 version because v2.1 was closed! We won't add any changes to it; even if it included a modification of a single line of the code it would also be marked as v2.2 [we could at most call it alpha or beta instead of RC, maybe then the name wouldn't bother you] 

I don't know what errors you're talking about, the only errors known to us can be found here:  https://github.com/YetiForceCompany/YetiForceCRM/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22YetiForce+2.2+GA%22+label%3Abug  and none of them are critical for the system's functioning. 

Unfortunately I don't know what your issue with updates between the stable versions is, but it seems like it's caused by misinterpreting the update package, to which you received the link from us, you treated it as a stable final version but it is just a test version prepared for you, among others.

**Comment by zebrahosting** [comment]
OK understand that you don't want to follow international standards that minor updates keep the same major number. I'll live with that.

I will keep testing your 2.2 dev updater on my dev versions. Thanks for the explanation.

I don't overwrite gitdev versions, my testing is always with a clean install once in a while and double checked with Yeti github versions.

The main issue remains for me: how to deal with all the bugfixes right after the stable version has been publicized. And yes it is unusable for us when there are still a few crucial bugs. Of course that happens and will be different for everybody, but we use the filters , mailtemplates etc extensively and it is breaking our workflow. I am confident and see that most of it is fixed in no time but still there need to be a better way of 'fixing' /  updating a stable version. 
Now I add the fixes manually one by one. Sometimes in code, sometimes replacing the file. Don't think you can expect that from every client. At the same time it is good if users get small incremental updates ones in a while. In this case I would say two weeks after the stable release there could be a patch file with the fixes up to that date.
If you use the move to 2.2. version number the next update will not work.
So still wondering how you will solve this.

**Comment by SkavenKF** [comment]
Sorry Błażej, i found this bug "[BUG] creating records #1739" is a CRITICAL BUG for a "stable" version!!!!

You cannot SELECT or ADD an entry from a related tab! You can test this at https://test.yetiforce.com.

In my opinion (with over 15 years experience in Softwaredevelopment and as a CRM-Consultant), normally a version that named "stable" should be stable and must be fixed to a stable version. This cannot wait to the next stable release (with new features and new bugs) .
