### ISSUE TITLE
History Widget not visible

### ISSUE THREAD

**Issue by agilisgmbh** [YetiForceCompany/YetiForceCRM#1750]
I´ve found no Option to add History Widget on my Dashboard.
Bug?!

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by nextgennitin** [comment]
We are also facing same problem.

**Comment by agilisgmbh** [comment]
I dont know, why they just closed the tiopic, did not find out what I made wrong with my post...
Still no solution - till now...

**Comment by bpabiszczak** [comment]
Read this: https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by agilisgmbh** [comment]
bpabiszczak, whats the problem to give a HINT whats wrong with the kind of reporting this bug?

**Comment by nextgennitin** [comment]
Sir we already installed the latest version.But history widget is not showing

**Comment by bpabiszczak** [comment]
Reporting issues:
First of all - please follow the instructions for reporting issues. I can't see:

-What version of the system is installed [we need the exact number; it's not enough if someone says it's the latest version]
-What steps have to be followed in order to recreate the error in the test versions [e.g. Stable, gitmaster, gitdeveloper]
-The perfect solution would be to record a short clip like this:  https://github.com/YetiForceCompany/YetiForceCRM/issues/1894  in which you explain and show the issues.

Problem:
I think your problem results from your lack of knowledge how widgets in YetiForce work [it's different than in vtiger]. The widget managing panel [enabling and disabling widgets] can be found here: https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67 

Unfortunately, I don't know if this is what you mean, because this issue is not described well enough.

**Comment by agilisgmbh** [comment]
Thank you bpabiszczak for that helpful reply.
Ill post a bug in future in this way.

About your "Solution". Thank you. Didn´t know, that this must be manually added. Thought it´s a bug on my installation. This Topic could be closed again for me, as the "History-Widget" know is visible on my Dashboard! Thank you!

**Comment by bpabiszczak** [comment]
We are always willing to help, but the issue has to be well described [this way we minimize the amount of time needed to solve the problem]. We care a lot about the well described issues, because an issue that is not clearly explained takes more time to fix, which means less time for us to develop the system :]
Thank you for being a part of the community.

**Comment by agilisgmbh** [comment]
You´re welcome. Thanks again.
