### ISSUE TITLE
[BUG] filter with 'contains' and combobox not working 2

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1757]
I open this again in a new ticket, can't reopen: #1737

The current fix is not working. Now we don't have the 'contains' filter option in the options for a combobox.
Don't think that is the proper way to handle bugs by removing the option :-)

Please have a look at it again.

**Comment by SkavenKF** [comment]
I agree with zebrahosting. When i choode the "contains" option, it should be display the options!

**Comment by florek41** [comment]
Maybe it's about that you can enter ex. "est" and every option (test 1, test 2, test 3) meet conditions isn't it ?

~~But it will be good to have possibility select more than one option.~~

Now you can do it by set few conditions in "Any condition" section, something like this:
![any](https://cloud.githubusercontent.com/assets/4824588/9210288/ab50c35c-407b-11e5-88eb-ac016c64ccb0.JPG)

Additionaly - is something change in gitdeveloper version and "contains" option disappeared ?
![mising_contains](https://cloud.githubusercontent.com/assets/4824588/9210344/0a3b5fda-407c-11e5-97e4-17680b948056.JPG)

**Comment by zebrahosting** [comment]
Well that might work for simple lists but we have comboboxes with 5-6 items in it. They can have all different combinations selected and it is far easier to check the existence (contain)  of one item than put all possible combinations in there.(equals). Yes with one selected it can be done like you show, but not really with multi selects.

It was al working fine in 2.0 so I don't understand why it is removed as 'solution'.

**Comment by florek41** [comment]
Now it's clear - you have right and it should works like you described - especially with multiselect !

**Comment by rskrzypczak** [comment]
Hello,
I agree that some of the filter options for multi select fields were unnecessarily removed. The person who removed them must have not thought that through :) . 
Thanks.
Apart from that, ...
![picklist2](https://cloud.githubusercontent.com/assets/10221999/9217533/f94af3fa-40c8-11e5-8584-5ab542c2a8d0.jpg)

**Comment by zebrahosting** [comment]
Don't understand why this issue is closed without making a ticket. Don't see a fix so it must remains on the list.

**Comment by bpabiszczak** [comment]
What do you need 'contains' for picklist type fields for? I've never had to set the 'contains' type in the filter for a field like that. Even if you find some business explanation for that, you have to remember that it's a translated field, so entering any sequence of characters there would require setting various factors, including the language the word is related to. Additionally, some expressions can't be translated into any other language. In my opinion the programmer did the right thing, disabled something that wasn't and should not be serviced by the system.

**Comment by zebrahosting** [comment]
I have two good reasons why I can not just be scrapped from the version:

1. we have a stable version running with about 20 filters using the 'does not contain' . The update renders them useless in one go on a production system. That should not happen in my opinion.

2. We use 'does not contain' extensively in listings where there are a lot of possible options, if I keep it simple for an example: if you have 4 entries in the combobox, it means 16 different ways of selecting them. If I want to see them all excluding one I use 'does not contain' otherwise I have to add the 15 possible options.
I found 'equal too' or 'not equal too' not sufficient and not doing the simple filtering we use now.

**Comment by bpabiszczak** [comment]
Changing 20 filters is not too laborious, I assume it takes around 40 – 60 minutes, which is less than both of us spend discussing that. Remember we also have many clients, who use various filters, and we'll upload that change to their systems as well, and for us it's not a problem to introduce good solutions to YetiForce.

The functionality you used to use, that is “contain”, doesn't function properly – it only works for the English language [if the same value we used to search was in the database; in case someone changed the value in the translation file it didn't work properly]. It means that this functionality can't really be a part of the system, since it doesn't work as it should. We would fix it if there was any simple way to do that, but unfortunately there isn't.

If you think that something can't be set because of some imposed limits, then please provide us with an example, and we'll try to consider the problem and offer a solution.

In my opinion what we did brought more benefits than disadvantages. If you want us to change it you must convince us with arguments.

Your arguments aren't sufficient for me, remember that you can always hire someone to develop the “contain” functionality for you [we're open to any assistance] but don't expect us to keep functionalities that don't work properly.

**Comment by zebrahosting** [comment]
The competition (OROCRM):
<img width="714" alt="screen shot 2015-08-13 at 20 42 50" src="https://cloud.githubusercontent.com/assets/10379403/9260484/35f23f12-4208-11e5-88bf-d863e115c143.png">

**Comment by mariuszkrzaczkowski** [comment]
Nie prawda to była lista wyboru  problemu z wyszukiwaniem nie było.  Ja bym 
to osobiście przywrócił było to dobre. Problem był tylko z select2 bo nie 
było listy a po za tym to działało poprawnie

Wiadomość została wysłana przy pomocy AquaMail dla systemu Android
http://www.aqua-mail.com


Dnia 13 sierpnia 2015 19:10:14 Błażej Pabiszczak <notifications@github.com> 
napisał(a):

**Comment by nikdejan** [comment]
I'm with zebrahosting here.

**Comment by bpabiszczak** [comment]
"The functionality you used to use, that is “contain”, doesn't function properly – it only works for the English language [if the same value we used to search was in the database; in case someone changed the value in the translation file it didn't work properly]"

**Comment by zebrahosting** [comment]
Did you actually try this (for example in contacts and create some custom fields)? When you use a combobox it shows you the actual values from the list to select. Seems not depending on language. So it is not a plain search string but an already existing field content.
Never had any issue with it when using  / switching language. But in 99% I assume people keep using the same language as they create their filters in....

**Comment by zebrahosting** [comment]
An example how we use it:
Contact pay for trainingweekends, 1-4 or all in one go.
This gets registered in a combox where there can be multi selects:

Then I want to filter the people that did not pay weekend 3:

<img width="399" alt="screen shot 2015-08-14 at 14 00 12" src="https://cloud.githubusercontent.com/assets/10379403/9273456/267b53c2-428d-11e5-8839-52e408255ac8.png">


<img width="1431" alt="screen shot 2015-08-14 at 14 02 05" src="https://cloud.githubusercontent.com/assets/10379403/9273457/2de29f62-428d-11e5-9c84-d3e5eda09781.png">

With the 'does not contain' it was easy but now almost impossible...

**Comment by bpabiszczak** [comment]
end?

**Comment by zebrahosting** [comment]
how would you filter out everyone that has not weekend3 and/or weekend all in its records.

**Comment by bpabiszczak** [comment]
There are two types of fields in the system:

Picklist

Multi-picklist

In both of these types we can choose various mechanisms:

Picklist

equals

not equal to

is empty

is not empty

Multi-Picklist

equals

not equal to

is empty

is not empty

starts with

ends with

contains

does not contain

In both of these types you should use the preset condition values [you can't enter your own values], which is logical because we know the list of all available values, and these values were translated to different languages, so it's impossible to use just parts of words for searching, because it won't work properly.

Currently "contains & does not contain" are available in the system only for multi-picklist, which allows you to do exactly what you need to, which is to exclude some elements according to the example you provided. In case of a simple picklist field, the "contains & does not contain" values have no reason to to exist, therefore they were removed.

So I think you have all the necessary tools to create the filters you need. However, if I'm wrong, please record a clip to show me what can't be set.

**Comment by zebrahosting** [comment]
This was how it was before the bug came, and yes this is exactly right and the way it should work.
Thanks for fixing. Already using it the moment it was updated and it works fine again.

**Comment by bpabiszczak** [comment]
Good :]

**Comment by nikdejan** [comment]
Great

**Comment by florek41** [comment]
Awsome ! ;)
