### ISSUE TITLE
Changed the name 'Organizations' to  'Accounts'

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1765]

**Comment by diderich** [comment]
Does that mean that there is (will be) no more concept of an Organization, i.e. a legal entity?
How do you expect to handle if a contact belongs to more than one Account?
Do you expect to add fields for specific roles in an Account, like an Account owner, Finance contact, Administrative contact?

**Comment by bpabiszczak** [comment]
1. We only change the name of the module back to the original one, because it complies with the actual role of this module [there aren't only organizations and companies there] 
2. The users don't have to agree with this change, currently everyone can have their own language files, it's enough to follow this article:  https://yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html 
3. I don't understand what a change of the name has to do with the number of contacts under the Account?
4. I don't understand what a change of the name has to do with the legal form?
5. I don't understand what a change of the name has to do with the type of a contact?

I think points 3,4,5 are completely different issues according to the rule: 1 problem/question = 1 issue.
