### ISSUE TITLE
[BUG] Marketing processes and Leads Assigned To Group

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1778]
![animation 118](https://cloud.githubusercontent.com/assets/1402355/9253296/8cec4432-41f6-11e5-8c46-49987b91ecd7.gif)

**Comment by bpabiszczak** [comment]
This is not what these groups are for. You can't see groups in leads because you didn't enable it in groups. To make them available in this module check this:  https://gitdeveloper.yetiforce.com/index.php?module=Groups&parent=Settings&view=Edit&record=2.

The groups you're showing in the clip are groups that together with the checkbox button allow for an automatic change of the record owner. When you select group A and after that someone edits a record that belongs to this group he will automatically become the owner of that record.
