### ISSUE TITLE
[Help wanted] Roundcube: SMTP cannot connect to my Exchange server

### ISSUE THREAD

**Issue by Dieter01** [YetiForceCompany/YetiForceCRM#1799]
Hi,

first of all, great thanks to YetiForce team!! I have evaluated vtiger a lot, and shortly before rollout tested YetiForce as well. As it is much better, I decided to rollout YF. However, now we hit a big problem:

We run an on premises Exchange server. This works fine an can be accessed via active sync, POP and IMAP. Using a mail client, I can recieve and send mails via IMAP/SMTP.
I run the latest stable version, tried master as well. 1and1 Hosting in Germany. PHP5.5, SSL.

Trying since days and reading a lot, still I could not manage to get the YetiForce mail to send mails. As there are 2 settings, here are my situations:

1. Settings -> Mail -> Outgoing Mailserver = newly installed YF does not work:
Settings are:
- Server Name: tls:\\mydomain.tld:587
- User Name: validuser@mydomain.tld
- Password: valid password
- From Email: empty
- Requires Authentication: yes
=> Test Mail Status :  Mail could not be sent to the admin user. Please check the admin emailid/Server settings
FIX: I found following fix in the vtiger forum: 
- modify: modules/Emails/class.phpmailer.php
- replace function IsSMTP() {$this->Mailer = “smtp”;} with following function IsSMTP() {$this->IsSendmail();}
=>> Result: works find, sending mails wokrs now!

Could not fix problem with Roundcube
2. Settings -> Mail -> Mail Client: Roundcube configuration
- Name: valid mail account on Exchange server
- Validate certificate: yes
- Add type and protocol to address: yes
- Name of IMAP server: ssl://mydomain.tld
- Port used to connect to IMAP: 993
- Name of SMTP server: tls://mydomain.tld
- Login to SMTP server ( "%u" - login of logged in user): validuser@mydomain.tld
- Password to SMTP server ( "%p" - password of logged in user): valid password
- SMTP port (default 25; 465 for SSL; 587): 587
=> An error occurred! SMTP Error (-1): Connection to server failed.

I have tried all kind of setting, however, could not sen mails. However, I can receive mails.

Any ideas, what I can do. I cannot use a CRM without the ability to send mails.

Best regards
Dieter

**Comment by bpabiszczak** [comment]
This, and every similar case, requires an analysis of the problem by someone with sufficient knowledge [as far as YetiForce and the server are concerned]. Logs are the most important, both – the ones from the CRM, and the ones from the mail server; only on this basis can we find the issue and solve it.
The problem is that we don't provide these services free of charge [only in exceptional circumstances].

**Comment by mariuszkrzaczkowski** [comment]
Send me the acces to some example email account if you can, so I will check why it's not possible to send emails.
try the configuration below:

Name of SMTP server: ssl://mydomain.tld
Login to SMTP server ( "%u" - login of logged in user): %u
Password to SMTP server ( "%p" - password of logged in user): %p
SMTP port (default 25; 465 for SSL; 587): 465

**Comment by mariuszkrzaczkowski** [comment]
Send the access info to email

**Comment by Dieter01** [comment]
Thanks for your support! I have tested some more options and opened a trouble ticket with 1and1. They have told me, that their Hosting does not allow to send mails per SMTP. So it is not possible for all of their customers, to access external servers to send mail. IMAP is no problem.
They recommend:
1. sendmail
2. PHPmailer
3. use their SMTP-Server for sending mrv.kundenserver.de IMPORTANT: set timeout to 20 or 30

Setup of Outgoing Server:
In YetiForce "Outgoing Server" -> "Mail Server Settings (SMTP)" -> "Server Name" I use "mrvnet.kundenserver.de"
In class.phpmailer.php (/modules/Email/) I have changed the value of timeout from 10 to 30. Testmail works fine. Just wondering, if this is reset with future updates. Maybe it is possible ot set timeout in settings menu.

Setup of Mail Client:
In the moment, we can only put user login and password for SMTP (which is also used for IMAP). 

For 1and1 we would  need the possibility, to use login credentials for IMAP only and have "no auth" for SMTP "mrvnet.kundenserver.de"

It would be great, if you could extend possible settings to cover this. In Germany, many people use 1and1 (1und1 or 1&1).

If you need access to a YetiForce installation on a 1and1 server, I can install a separate version for you. So you can test new settings.

**Comment by bpabiszczak** [comment]
[...] This, and every similar case, requires an analysis of the problem by someone with sufficient knowledge [as far as YetiForce and the server are concerned]. Logs are the most important, both – the ones from the CRM, and the ones from the mail server; only on this basis can we find the issue and solve it.
The problem is that we don't provide these services free of charge [only in exceptional circumstances]. [...]

**Comment by robygladio** [comment]
hello bpabiszczak ,
congratulations! Yeti is very powerful. I agree that have support for free and products for free is not useful to grow both business. 
By the way the map api key (both google and open) doesn't work out of the box, SMTP doesn't work out of the box etc.. So if it's not possible get the functionality without pay for them better you sell it and we all save time. Be sure on a CRM system the customer soon or late need support. 
If I have all the function work properly (with some setting but not reprogramming!) I'll happy to improve the solution. If the beginning is too hard I'll go to another easier solution. 
This is my opinion and because I'm nobody it's just a point of view. 

Best regards,
Roberto
