### ISSUE TITLE
[Bug] Comments in Contact Overview sent to contact

### ISSUE THREAD

**Issue by Dieter01** [YetiForceCompany/YetiForceCRM#1800]
Hi,
I just fill YetiForce with data. Creatiing organizations and assigning contacts to them. Once this is done, I want to add some comments about this contact. Usually, the account manager assigned to this contact should see/read them. But now I realized, that these comments are sent to the contact !!!!, so he can read internal comments. This must be a bug. 

The contact gets a mails: 
New comment added to ticket
Dear User,
A new comment has been added to the ticket.

However, the contact is not a user of our system and should not get this!!!

![screenshot contact overview](https://cloud.githubusercontent.com/assets/11521275/9293861/fe3ee8e2-443a-11e5-8793-595dac81ccf1.jpg)

Best regards
Dieter

**Comment by bpabiszczak** [comment]
In my opinion, the system doesn't send anything on its own. In order for the system to be able to send anything, that function has to be enabled. Please read this article:  https://yetiforce.com/en/user-documentation/support-process/140-automation-of-notifications-in-tickets.html.
However, if the system does send anything on its own, then please describe step by step how to trigger this action in a clean version of the system.

**Comment by Dieter01** [comment]
Thanks for your answer. The mail sent, makes sense if this is a (support) ticket. The field I used to write a commet is in the upper right of the screen shot = Kommentare in German, means "comments". So, either it is a Comment, then it should not trigger a ticket workflow, or it is a ticket, then label is wrong.
Generally, on this position it should be a Comment. Workflow should be, to inform Owner, not customer.

**Comment by bpabiszczak** [comment]
Unfortunately I don't really understand the entire process, that's why it requires some more specifying. The easiest solution is to describe step by step how to trigger this error, for example in the test version or the gitdeveloper version [remember these versions are reset everyday]. If you describe how to trigger the error [or even better – if you record it just like waw555 does] then we will be sure what you're reporting and whether or not it's an error. 
At the moment I don't know your system configuration, who and how added the comment [and where he added it], who received the email and whether or not that person really received it. We have to be 100% sure if we understand the problem, otherwise we won't take care of it.
