### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1829]
I'll put this in a separate issue.

Importing:

Contacts - ability to import Associated Companies (as in vTiger) and immediately, not scheduled.
Campaigns - How can I import all of our existing Campaigns (with associated Products and Contacts)?
Price Books - Imported PriceBooks do not show up in Price Books and how do I import all the associated Products?
Products - Didn't import associated Tree (Category) data (what is the table so I can manually import the relation?)
SalesOrders - Can I import S.O.s, or will there be a similar problem?

How can I Import (Migrate) all of my vTiger tables so when they come in, they don't loose their previous relationships due to new id numbering?  What is the table that holds the next Seq Number for Products so I can change it to match vTiger so when I import I don't loose all my relations to (Pricebook etc)?

**Comment by mykljohn** [comment]
Any help available on this?

**Comment by bpabiszczak** [comment]
Too many questions in a single issue...

At the moment import/export only supports 1:M relation [so for example, in case of Campaign you have a different M:M relation that the system won't be able to handle by default – it has to be imported using a script]
If the categories can't be imported - please describe step by step how to recreate that error in the gitdeveloper version and we will check that.

Regarding the Sales Orders – you won't know until you check it :) as far as I know, it should work in the latest version [there were some problems with it in the 2.0 version]

Vtiger data should be migrated using a built in tool in YetiForce, instead of being imported/exported.

Generally it's a very chaotic issue, I recommend reading this document:  https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
