### ISSUE TITLE
Ticket comments don't trigger workflow

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1858]
Standard setting has an option to send an email on ticket creation and ticket modification.
The last one does not seem to work if people add a comment to a ticket in the portal (1) . (or the admin does)

Meaning that if the ticket is created and some feedback is send, usually the customer might have additional reaction and add it in the comments section. 
Only if the admin changes status or one of the settings the 'modified' workflow seems to trigger.

Not sure if this is by design but at least does not work for us. Most of the times it is not as simple as answering a ticket in one go but there is some back and forth mailing before there is a final answer.

**Comment by bpabiszczak** [comment]
Various mechanisms you described work in the comments module [I just don't know which ones you mean because tiggers, workflows, and handlers are completely different things] 

I think you misunderstood the concept of what you are trying to do. If you want the system to do something, for example while adding a comment to a ticket, then workflow shouldn't be set on the ticket, but rather on the comment [and in it you should verify whether or not it is linked to the ticket module] 

Check what I wrote about comments:  https://github.com/YetiForceCompany/YetiForceCRM/issues/1853#issuecomment-136688784
