### ISSUE TITLE
To add quick create next to UI Type 10 in popup

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1898]
To add quick create next to UI Type 10 in popup. It will create another popup overlaying previous pop-up window (suppose to be modal). It will speed up creating dependent records in tied modules. Ex. Quotes > Requirement card > Opportunity

**Comment by bpabiszczak** [comment]
I don't consider it currently important, because the situation you described should not take place [we should first create the Opportunity, then the Requirements Card, and only then the Quote]. Also, while quick creating, we can always go to the full form where we can once again enable the modal window. At the moment we are not planning to add this mechanism.
