### ISSUE TITLE
Remove need for Account Record

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1906]
Many of our clients (students) are individuals, but the Opportunity Screen requires an Account.  I can work around this by creating a dummy Account/Company, but that seems kludgy.  Is there any way to get around the required fields?

**Comment by bpabiszczak** [comment]
First of all – you didn't provide us with enough information, because I don't really know where you put the students [probably as Contacts] and that raises a bunch of other questions. Regardless of these questions, I think the solution to your problem is entering each student as an Account [what are your comments on this?]

**Comment by mykljohn** [comment]
Sorry, we enter out students as Contacts and if it's a corporate account, the company the work for goes in Accounts.  in vt, I renamed Organizations to Companies to use for our corporate accts.  

I modified Campaigns to act as Course Groups (each scheduled class session).

And some of our Groups are all for one Company (Account)

**Comment by bpabiszczak** [comment]
So how can we help you, if you applied your own logic that's incompatible with the logic offered by the system?
