### ISSUE TITLE
Multiple Contacts Related to Events

### ISSUE THREAD

**Issue by pmaxx** [YetiForceCompany/YetiForceCRM#1913]
Greetings:

First, YetiForce is great! Thank you for this powerful software!

We need to assign multiple contacts to events. In a project meeting, there are usually several people. Sometimes from different companies. We need to record all contacts who attended the meeting.

Thanks again!

**Comment by waran70** [comment]
+1

**Comment by bpabiszczak** [comment]
We are not planning to introduce such functionality at the moment. This is due to many factors, first of all changing the relation requires rebuilding the entire system, it also creates a problem while maintaining the continuity of history, and separating the history between accounts. We will not change that for the time being.

**Comment by vtechnik** [comment]
Hi, 

First, thanks for your good job.

In many jobs, there are usually many people, sometimes from different companies who are present in the meeting. If you are not planning to introduce such functionality at the moment. Could it be possible to make a icon to duplicate the meeting with the subjet and the description, so we can link it easely to another contact (and process)...
