### ISSUE TITLE
Campaigns

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1914]
I modified the Campaign Module in vTiger to handle Class Registration (the Sales Order is used for Enrollment).  I have 5000 records in the Campaign table that I need to import into YF.  I tried to do the import just in MySQL, (into campaigns, campaign_contrel, and crmentity.)  But I had problems afterwards.  Is there a webservice or php script I can use to import these records?

**Comment by bpabiszczak** [comment]
Unfortunately your description is not detailed enough. 
First of the problems I noticed is the logic. Campaigns are used for mailing and finding interested people. When one of them starts talking to us, he should be linked to the Opportunity, when we close the registration and begin sales, all these people should be placed in Project. And considering what you said it seems that you want to have everything in Campaign, but it was not designed for that.

Another problem is that I don't really know what “import to YF” means. If you have Vtiger then you should migrate it to Yetiforce, then all relations and configurations are saved. Although, if you don't want to migrate [which isn't right] and you only want to transfer the records manually from system A to system B then I wouldn't recommend doing that, because exporting in vtiger doesn't work properly, and we are fixing that in Yeti right now. Moreover, import/export doesn't work with M:M relations currently, and contacts in campaign are an M:M relation.

These imports are made manually, using scripts, you load the required YetiForce libraries into the script and create a dedicated solution
