### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by nextgennitin** [YetiForceCompany/YetiForceCRM#1916]
We found Yetiforce is really powerful CRM and learnt so much, but I still have some problems.

The biggest gain is Invoice and Inventory relationship. I planned to to sell product bundles A, which includes 1 parent product B and 2 parent product C. so it means if I sell one A, the inventory of B and C should reduce 1 and 2. but I didnot get the luck to be successful, they always reduce the same quantity of how many I sell bundle A. I tried to change the qty/unit, still not work. 

Please solve if possible.

**Comment by vovpff** [comment]
The same situation was in all version of original vtiger. I think problem in core of vtiger.

**Comment by nextgennitin** [comment]
Right now we are using Vtiger 5.4 and thinking to start yetiforce CRM.We solved the same bug in Vtiger 5.4 but trying to solve the same in yetiforce.And update.

**Comment by nextgennitin** [comment]
Right now we are using Vtiger 5.4 and thinking to start yetiforce CRM.We solved the same bug in Vtiger 5.4 but trying to solve the same in yetiforce.And update.

**Comment by bpabiszczak** [comment]
It won't be fixed in the YetiForce system because a new mechanism used in the modules with products has been added. We will soon add storage modules, then add creating products using “recipes”, and we will offer “product bundles”. Once these solutions are implemented, new advanced mechanisms used for accounting for the inventory stock will be added. Currently YF doesn't have the inventory, it will be added in v2.4/2.5.
