### ISSUE TITLE
[ISSUE]The sales process

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1917]
The sales process:

I do not quite understand the processes in the system

1. Please Client -> Create Message
2. Identify needs -> Create Transaction and Counterparty
3. From the transaction creates proposal, but the proposal can not be created without the application form (to stop the process)

Let's go the other way:

1. Please Client -> Create RFQ again required transaction and counterparty, well established and Transaction Counterparty.
2. Create Card Applications
3. Create Calculation
4. Create Offer
5. Next, you can create invoices or orders, but the account can not be created without orders
7. Create Order
8. Create Account

What's next?

**Comment by paula-w** [comment]
A few questions:

By “Please Client”  - do you mean “Create a new client”?
By “application form” - do you mean “ticket”?
By “Card Applications” - do you mean “Requirements Card”? 

Can you switch your system's language to English for a moment and check if these are the names? We need to be sure exactly what you mean in order to be able to help you.  

Can you clarify what you mean by “Create RFQ again required transaction and counterparty, well established and Transaction Counterparty.” ?

**Comment by waw555** [comment]
Ok, now on another paraphrase

**Comment by waw555** [comment]
I come back to my question

Not really, I understand the logic of the sales system.

1. It begins with the client request to the company by phone or through the website it does not matter, in any case, we have to create Leads.

![animation 171](https://cloud.githubusercontent.com/assets/1402355/11771411/991e4a84-a231-11e5-9ed3-c4cdea2e662a.gif)

2. Further, to make contact with a customer, we have to transform client Account. When converting, created by default Opportunity, which does not bear any information content, if it is not full. This option should be made optional in the system settings, or always open.

![animation 172](https://cloud.githubusercontent.com/assets/1402355/11771449/24f2dfde-a232-11e5-82b2-54dae263ebdd.gif)

3. Add Account contacts. This position 1 in the menu, and it is logical to be fast access to view the contacts

![animation 173](https://cloud.githubusercontent.com/assets/1402355/11771467/8f83f6bc-a232-11e5-8293-9276ce1a9ce0.gif)

4. Opportunities are created automatically, but now we need to fix it. And if the company created a day for 100 Opportunities, who would rule. When editing, I just have a problem, understand that a sales manager will not run as administrator. I'll describe about the system out of the box without changing any settings. What are the system administrator also lead to confusion.

![animation 174](https://cloud.githubusercontent.com/assets/1402355/11771558/c2132296-a233-11e5-9378-b070897d0120.gif)

5. Return to the Account. 
And here comes the very moment that prompted me to write this - what to do?

![animation 175](https://cloud.githubusercontent.com/assets/1402355/11771622/b9868c3e-a234-11e5-95cc-bf8deefa3acf.gif)

5.1.  In my mind, I have to make an account offer. And then once there is a problem that requires Requirement Cards, which you want to create Quotes enquires, which is required to create a switch to full the edit form, which will lead to the fact that creating a commercial offer would have to

![animation 176](https://cloud.githubusercontent.com/assets/1402355/11771715/fa387ce6-a235-11e5-9664-1e669bfed43d.gif)

5.2. Let's try to go the other way, as the Opportunities is an integral part of the sales process in the system, go through the Opportunities. The top line, we see that we can create invoice and offer. The offer we create are not going to try to create an invoice.

![animation 177](https://cloud.githubusercontent.com/assets/1402355/11771793/048eb4f2-a237-11e5-83f7-24b0184e9675.gif)

5.3. We returned to form Opportunities. And visually, I do not see anywhere that there was an invoice. Only in detailed form I can see the sum of all invoices for payment. That is, nor any indication that I just, do something, and suddenly a bill does not create?

![animation 178](https://cloud.githubusercontent.com/assets/1402355/11771835/8932734c-a237-11e5-9e73-694cc5253cd3.gif)

6. Now let's see what's on the menu Sales. And there we see that sales begin with Campaign, then comes Opportunities (that got me stumped), followed Quotes enquires. Let's try to create Quotes enquires and see what will happen next.

![animation 179](https://cloud.githubusercontent.com/assets/1402355/11771964/1e8a936a-a239-11e5-9d30-8cf2d10dc2e2.gif)

Created Quotes enquiries, but no further action, there is no button to continue the sales process. And it should be a button to create a Requirement Cards

7. Let's try to create a Requirement Cards.

![animation 180](https://cloud.githubusercontent.com/assets/1402355/11772027/c0fe118a-a239-11e5-8fce-27963c2f246f.gif)

Created Requirement Cards, but no further action, there is no button to continue the sales process. And it should be a button to create a Calculations.

8. Let's try to create a Calculations.

![animation 181](https://cloud.githubusercontent.com/assets/1402355/11772102/d0e26884-a23a-11e5-8ed8-891376637943.gif)


Created Calculation, thank you to substitute part of the data automatically. But again the question of what to do next, because logically, we must create Quotes, but again there is no button again to go to the menu.

This is all. Later continue.

Each organization its postrebnosti, but the sales process should be set in the system for each organization, and I'm for that developers have taken this into account and make the necessary buttons, or the ability to create and customize these buttons. This is not necessary calculation and someone to do without quotes enquires, you must

P.S. Reopen Please

**Comment by nikdejan** [comment]
This is a very long post and the language is not very precise, but I will try to explain what I understand, although I'm also new to CRM world.
First, when someone contacts you over the phone, you do not create Lead. Lead is for "zombies", not for real people. Lead is for people whose visit cards you have, or for the emails you harvested from websites, or for people who liked you facebook page. Lead is for people who might be your customers in the future, but at the moment they do not know it yet. At the moment they do not call you, they do not send you emails or ask for quote.
Instead of creating lead, when someone contacts you over the phone and starts a conversation about your products and services, you should create Account AND Opportunity. (At the same moment, depending of how far your first conversation goes, you might create Quote Enquiry and Requirement Card).
Opportunity is particular business potential, a conversation that could bring you some money. You use Opportunity to connect different activities which occur during sales process. This activities include: 
1. Quote Enquiry (Customer - Account asks you for your offer (quote). He expresses his first general intention, what he GENERALLY wants from you) 
2. Requirement Card (You start a conversation with a customer and get additional information from him and fill in the Requirement Card. In Requirement Card you have more detailed and precise information, not only general information.) 
3. Calculation (Calculation is something like quote preparation. You are checking your purchase orders, purchase pricing, you are calculating your margin etc. Calculation is inside process. Customer knows nothing about it.) 
4. Quote (Based on calculation, you send an offer (a quote) to your customer. This is essential part.)
5. Sales Order (If customer accepts your offer, you create Sales Order. SO is a statement of the customer that he accepts your offer).
6. Invoice (You create invoice and expect payment from the customer).
YetiForce has some additional modules that I do not quite understand (costs, payments in, out) so I will not talk about them.

Flexibility is not always good and when you give all the possibilities to the people, they tend to make a mess out of it. And I agree that CRM should not be "tabula rasa", but instead should lead you in the right direction. But "lead" doesn't mean constraint. CRM should lead you but should also leave you freedom to change the process, if you know what are you doing. 
I, personally, do not need Quote Enquiries and Calculations. I only need Requirement Cards, Quotes and Sales Orders.

**Comment by bpabiszczak** [comment]
1. Everything depends on what logic we are talking about. Do you mean the vtiger logic? The old YetiForce logic? Or maybe you mean the new logic, that we're just building and that will evolve over the next months.

2. For me the marketing process and the sales process are two different things. If someone decides that he wants to convert a lead to an account, then he only does that to start the sales process. If not, then what for? What's the business scenario for not creating an opportunity while converting from lead?

3. Your problem is that you are trying to adjust the functionality and the processes to your needs, not really knowing what they are used for... it causes chaos in what you write. Secondly, you start the process from the end, not the beginning - @nikdejan described it well. Remember, you don't have to use all modules, you can disable the modules and fields that you don't need.

And the biggest mistake you make is trying to use a process that hasn't been finished, a process that we're still improving, which will be ready together with v2.4

PS. Unfortunately you added so many videos that this post can't be viewed. I'm closing it, if something is still unclear to you then make a new issue. We'll try to describe the sales process in detail when we release v2.4
