### ISSUE TITLE
Error in Modles Installation

### ISSUE THREAD

**Issue by nextgennitin** [YetiForceCompany/YetiForceCRM#1919]
Unable to Install New External modules of vtiger like Colorizer
Error is coming

Call to a member function rowCount() on a non-object in /home/nextgenmailers/public_html/yetiforce/include/database/PearDatabase.php on line 283

**Comment by bpabiszczak** [comment]
The vtiger modules won't work, the producer has to change several minor things for it to work in our system, because we changed the paths to some files for example. Though our system has its own coloring feature, similar to the module you want to install, so the question is if you really need it.

**Comment by vovpff** [comment]
This colorising function can be very useful for me too.

**Comment by nextgennitin** [comment]
iT MEANS WE CANNIT INSTALL VTIGER MODULES WHICH WE ALREADY PURCHASED?

**Comment by nextgennitin** [comment]
IT MEANS WE CANNOT INSTALL VTIGER MODULES WHICH WE ALREADY PURCHASED?

**Comment by vovpff** [comment]
I think yes because you purchase modules for vtiger, not for yetiforce. I have the same situation with PDFmaker module. Now problem with license activation.

**Comment by vovpff** [comment]
to bpabiszczak
What information neede to made vtiger modules applicable to yetiforce?

**Comment by reeid** [comment]
What I noted is different menu and different structure of language files.... but surely here is more

**Comment by bpabiszczak** [comment]
Some of the vtiger modules will work, some won't [we don't know which ones work because we don't use the vtiger modules you can buy]

If a module doesn't work - contact its producer, ask them to introduce all the necessary fixes, so that it works in our system [shouldn't take long]

We follow a rule that good modules that you have to pay for in Vtiger we create for free in YetiForce [when we have time for that]. The module you are trying to install works partially in YetiForce too [it has a similar built-in functionality], so I'd check if our soulution is sufficient for you.

**Comment by bpabiszczak** [comment]
We don't have the list of files, changes that are necessary. They are different for each module, because each module does something else. An easier solution is enabling your logs and trying to install the module, then the producer should solve these problems easily and quickly [e.g. the path to the file, a different way of adding to menu, etc].

The PDF module is currently being rebuilt from scratch [in 2 – 3 weeks it'll be ready for testing], so it might turn out that soon you won't need PDF Maker at all.

**Comment by vovpff** [comment]
to bpabiszczak
This is very good news! Nice to hear this. PDF exporting needed for me too much.

**Comment by reeid** [comment]
Nested related blocks and unlimited fields are welcome (like in PDF Maker). 
Also advanced special functions and easy manipulation with php function will be very helpful.
How about templates compatibility between current and new version?

**Comment by bpabiszczak** [comment]
Templates will not be compatible.
