### ISSUE TITLE
[BUG] Invoice import

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1930]
My situation. I has exported invoice  CSV from vtiger 6.2.0 prepared for importing to Yetiforce.
I made field mapping and import all record without faults but products quantity changed randomly after importing. UpdateInventory worklow for invoices diactivated before import. Any ideas?

**Comment by paula-w** [comment]
One problem per issue please.
We don't recommend using import/export of documents with documents via CSV files, because it doesn't work properly in Vtiger 6.2 [we are fixing this in YetiForce at the moment].
UpdateInventory doesn't work because it has been removed from the system; new mechanisms, that we'll soon add to the system, will be responsible for accounting for the inventory stock.

**Comment by vovpff** [comment]
@paula-w UpdateInventory works correct witout any problems. Nice to hear about new mechanisms! I will wait it.
About import problem. After some action at import process qty of products was changed but there is no workflows activated what must change qty. Looks like something going wront in yeti core.

**Comment by bpabiszczak** [comment]
Maybe this help you: https://github.com/YetiForceCompany/YetiForceCRM/commit/14ce0d8bedf9bc5d0f4598f2369b8ae265965c93
