### ISSUE TITLE
[BUG] Permissions to edit works incorrect

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1941]
I has a Sales profile with next settings for Invoices:
![image](https://cloud.githubusercontent.com/assets/8545791/9844650/952f3c54-5acd-11e5-89bd-fb3d59c2878c.png)
If I logged in by user what assigned to Sales profile I have possibility to edit Invoice fields in what setted as read-only for this profile:
![image](https://cloud.githubusercontent.com/assets/8545791/9844699/21043eaa-5ace-11e5-93eb-1822c24b656b.png)
Looks like something works wrong with sharing and editing rules.
Another one question: is it possible to disallow editing of some fields or all (for different modules) regarding some field (for example if status of invoice is Written off then nobody can not edit this Invoice record except for admin)

**Comment by bpabiszczak** [comment]
1.Where exactly did you set it to be read only?

2.Please describe in detail how to trigger this error in our test version, permissions are very complicated and they have to be well described in order to help you.

3.You can block saving in some fields that are not system fields [changing the parameter is impossible in the system fields- it concerns profiles]
