### ISSUE TITLE
[Request] Comments from related modules in Accounts page

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1944]
For exaple there is 3 important for me modules:
- Accounts
- Contacts
- Assets
*(list of modules must be adjustable because a lot of Yetiforce users works with Tickets module and etc.

At Account summary page I can post some comments:
![image](https://cloud.githubusercontent.com/assets/8545791/9872196/50519fea-5ba0-11e5-98d0-19c5ab1ffeab.png)
Separately I can post some comments for related for this account contact:
![image](https://cloud.githubusercontent.com/assets/8545791/9872236/9f2b46f2-5ba0-11e5-9702-d543e72cb2ac.png)
This is very usefull to assing head module (for example Accounts) what comments section can collect comments from submodules (Contacts, Assets, Tickets and etc...) and view it at summary page  and/or comments related tab.
My imagination of this:
![image](https://cloud.githubusercontent.com/assets/8545791/9872491/5a1dcbc8-5ba2-11e5-9293-6ccb090833c9.png)

**Comment by nikdejan** [comment]
+1 This would be VERY, VERY useful. I desperately need this! My plan was to achieve something similar with Emails. I had an idea to put multiple prefixes in email subject in order to attach them to more than one record in different modules. Like "SS123 - CC13 Some subject". Thus Email could be listed under certain Account AND under related opportunity. But what  @vovpff suggested with comments is even better.

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
