### ISSUE TITLE
[Question] Mailscanner - Only import mails where to/from email address is in yetiforce

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#1951]
when 'Create email message' task is configured in the Mail Scanner for an account, all emails are imported to yetiforce.
Is it possible to import only emails if the email address from the to/from/cc/bcc fields is found in the lead/account/conatct module.?
One client CEO complained that confidential emails from e.g. Laywers or board members are imported to yetifore and are visible to unauthorized persons.

**Comment by bpabiszczak** [comment]
This problem doesn't concern the functionality of the system, but the misconfiguration of the permissions. If the module is configured as private, then even if it downloads the mail, no unauthorized user will be able to view it; so I don't see any connection with not importing the mails for records that are not in the database. Your suggestion doesn't solve anything, because if there's an Account in the company and he sends an email full of confidential info to the CEO then the mail will be visible anyway
