### ISSUE TITLE
occupied hours from other event tasks on calendar

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1968]
lets think a realistic scenario. how many jobs can be done at the same time; i personal believe maximum two...
and if we are talking about visits or appoitments its only one. 
so i believe on calendar when we schedule a task or event there is must be something to prevenet or to warn us that something else is scheduled for the same time.

maybe a pop up warning.

your thoughts please....

**Comment by bpabiszczak** [comment]
In my opinion the current solution isn't bad. We often schedule something for a given date [phone/task] then we schedule something more important for the same date, for example a meeting. 
Of course the system might not allow [because why not] to make it impossible to enter it in this way, but it's not that obvious. Especially if you add some all day activities [then you wouldn't be able to add anything else for that day].. All calendars known to me allow for adding overlapping events. I can find some business ideology to that but I don't think that's necessary.

At the moment we are not planning to block that, you should remember though, that blocking this takes 1 – 2 h, so it's possible to adjust the calendar for the client while deploying the system. The calendar is based on the fullcalendar library, which has great possibilities, maybe that option can be already configured there.

We will block upcoming events during the work time for sure.
