### ISSUE TITLE
Type::Question about Asterisk integration

### ISSUE THREAD

**Issue by ssstorm** [YetiForceCompany/YetiForceCRM#1969]
Hello
I can use the original Vtiger Asterisk Connector  1.4, right?
Which Asterisk version supported? (I have 11.18.0)
Thank you

P.S. I found YetiForcePushCall, is it necessary to use this connector for Asterisk? But I did not find any manual how to install and configure, could you help?

**Comment by bpabiszczak** [comment]
Asterisk integration should be the same as it is in vtiger, we didn't change it, but it might not work properly. We are planning to remove it completely in order to substitute it with a different integration [better].

YetiForcePushCall – it works with a mobile android app. We don't have instructions for this yet

**Comment by ssstorm** [comment]
Thank you for the answer
