### ISSUE TITLE
An important statement needed

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1981]
Blazej, if I decide to move hundreds of thousands records to yetiforce where will be many of invoices, sales orders, service contracts, tickets, comments etc. If I develop some modules by adding custom fields, workflows, handlers, relations, pdf templates..... if I do that, can you guarantee that on some point in the future internal changes in yetiforce will not affect developed functionality, relations, workflows, templates, reports? How serious is risk that my work will be damaged by changing internal logic and functionality? Asking as even you call versions 2.1, 2.2, 2.3 stable, they are really not. They need still some attention and fixings as well as from I can see new functions will be introduced too.
 For this reason If I move now, I would expect following upgrade without major troubles. Thanks for deep analyse and answer.

**Comment by bpabiszczak** [comment]
You are using open source software, where the manufacturer does not give you any warranty on anything. You can purchase a warranty like that as an additional option, but if you don't have the SLA service, then you are to rely on yourself and only you take the responsibility for the deployment, migration and upgrades.

However, if you pay any company for the implementation [no matter what company], then you can expect everything from them, and therefore that no update will "change the system"; you will have to pay someone in order to be completely sure of everything.

If you see any errors in v2.2 that should be fixed, then you can only blame yourself for the fact that these errors have not been fixed, because I can only see 1 error here: https://github.com/YetiForceCompany/YetiForceCRM/issues. If you're one of the users who notice errors but don't report them, then why do you blame the developer for the software's lack of stability?

The software's stability doesn't only depend on the developer, but it also depends on the community / users who use it. A good example of that is the coreBOS system, it is based on an old version Vtiger 5.4 [which was considered stable] to this day they keep introducing fixes [they don't add any significant functionalities] and they might as well continue to do so forever. Every software has bugs [eg. Windows XP, after 12 years, still has some bugs reported years ago]. The developer must balance the desire to achieve perfection and the development, and if nobody reports errors, then we concentrate on the development.

We develop the product very rapidly [I suppose we develop our system faster than coreBOS, SuiteCRM, EPESI, and Vtiger together], some changes require a radical approach [workflow improvement, the new PDF module, new modules with products], which makes data migration not fully automatic [for example you have to export and import data among functionalities, or transfer a PDF template and fix it, or build a new workflow]. Such changes in the system won't be a bad thing, you see it in large projects, ie. Joomla, Windows, Android. However, these are minor changes and shouldn't take much time for the implementation company, but if someone tries to implement the system on his own and doesn't have sufficient knowledge, then such and update can be laborious for him.

Think why you want to move to YetiForce? Why not move to CoreBOS for example? In CoreBOS they have a very cautious approach to changes, the product gets fixes but doesn't change in a significant way. I suppose you were attracted to YetiForce because of all the possibilities , but these possibilities have to steam from something - the current YetiForce has 4 thousand changes compared to Vtiger 6.3 …

What YetiForce looks like tomorrow, next month or next year depends also on you. Testing the whole system carefully, reporting all bugs and describing them properly, ensures you that all errors will be removed.
