### ISSUE TITLE
[Question] Visit report of seals person

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#1982]
Dear,
I looking into way of creation report after customer visit perform by sales person. It has to be link to contact and have some dedicated structure (form some mandatory fields filled in )...
Ho can make it? Can you be so kind and advice?
Thanks

**Comment by paula-w** [comment]
Could you please provide us with some more details about the report?

**Comment by witer30** [comment]
well, I would like to have module (or something like that) link with contact (available also from contact page) who is visiting by my salesman. And I would like to have possibility for such salesman to enter such report with defined few section - general info, project, competition, etc... So after each visit such report should be possible to prepare…   How i can make such module? Or maybe it already exist...?Dnia 8 października 2015 10:14 Paula W napisał(a):
 Could you please provide us with some more details about the report?—

**Comment by witer30** [comment]
I would like to have some module to report info gather after visit of salesman. 
So below I create some example and min what I would like to have...
In contact page:
![2015-10-08 14_00_20-contacts](https://cloud.githubusercontent.com/assets/11491482/10366051/07e3115a-6dc8-11e5-8f6a-b31d28d13104.png)

When i open Visit report then should have list of reports and possibility to create new one like below:
![report](https://cloud.githubusercontent.com/assets/11491482/10366085/2dbbccf0-6dc8-11e5-9a03-e215df99b4bb.png)

Simple thing to gather more infos after meeting with customers...

**Comment by bpabiszczak** [comment]
In my subjective assessment, you don't enter the data correctly into the system. Everything you enter into that "report" should be in Opportunity. Hence:

1. Whatever the customer is interested in should appear in Products & Services

2. Offer should be in the offer linked to Opportunity, the comment about the high offer should be in offer in the comments section and/or in the Opportunity.

3. New project, I don't understand that point, but we talk with the client about things that for us could be more or less important. If the customer tells us about something he wants to do in the future, we should, on this basis, either add a task for the future or a new opportunity.

4. Info about competition, depending on what it is about, should also be entered in the right place.

5. Info about the customer's growth is important, but what's more important is what we plan to do with this info. If the customer will have greater needs, then we have to work harder, eg. create an additional opportunity.

Of course, we can theorize, but the most important task of the system is to gather information, but not in the form of notes like you're trying to do. The system should allow entering the data in a way that enables the system to generate these reports on its own. We see another meeting in the report not because someone wrote about it in the comments, but because they added a new appointment to the calendar. Info about the high price doesn't appear because someone wrote a note, but because they closed the deal as rejected, and as the reason for rejection they entered the price. This is how the system should work.

**Comment by witer30** [comment]
Dear Blazej,
Regarding task of CRM system I completely agree with you... CRM is grate tool for executing planed tasks, todoes, meetings, offers, etc. Completely agree with you...
But like you have requirements card for calculation I propose visit report (this is beginning for all things enter to the CRM) as place to entered comments which are reference for all other records in CRM. During reading this visit report immediately other person can see and will know reasons of some, for example, records in calendar, opportunities etc... 
This was my intention to  for such visit report. Additionally other info like competition intelligence presented at the customer - where to put it in Yeti to be available for others. Products which customer will be interesting in the future... So this report could be extra tool for such additional infos...
