### ISSUE TITLE
Question: How does the PBX manager work?

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2059]
How does the PBX Manager work? 

Configure Asterisk Server Details after Installing YetiForce Asterisk Connector in your Asterisk Server

Where is the YetiForce Asterisk Connector? IS that the vtiger pbx connector?

**Comment by bpabiszczak** [comment]
We do not support this module. Soon it will be removed and replaced with a new module.

**Comment by easaw** [comment]
Soon? it's now 2017 - still no replacement for the PBX feature, which still isn't removed.

**Comment by SeeMirra** [comment]
I'd also like to see this. You can use the vt module asterisk side, and modify csrf-magic so that running Vtiger_PBXManager_Js.registerPBXOutboundCall(numberToDial,UserIDToShow) issues call/bridge events to your local asterisk server, but there are lots of things missing/broken on the yetiforce side. Not complaining, yfteam has been pretty clear that it's not supported yet.

**Comment by bpabiszczak** [comment]
@easaw 
You can order integration with Asterisk [only 2.500 EUR].

**Comment by SeeMirra** [comment]
Ever think about crowdfunding feature requests? A /issues/ thread really isn't the place to discuss this, but FYI, I'd chip in a few bucks via kickstarter even though I don't really have a need for the code anymore.

I couldn't use yetiforce base for my last CRM because my project is very pbx integrated, though I definitely considered it as yf's search feature is hands-down the best in their segment.

**Comment by paula-w** [comment]
Thank you for the suggestion. 
We don’t plan to start any Kickstarter campaigns right now, but the community can do that. Donations can also be sent through PayPal (there’s a button on our website), you can specify the purpose of your donation. We think this is enough for now.

**Comment by projakethomas** [comment]
Still, no changes made 4.0.0 still have PBX Manager feature, still not removed and a new one added?

@bpabiszczak 
> We do not support this module. Soon it will be removed and replaced with a new module.
