### ISSUE TITLE
[improvement] Payments Out Module

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2089]
We would like to modify the Payments Out module to track when they are due.

So I added 2 new fields to the module: Due Date and Amount Due.

But then I thought, what if only Partial Payment is made, and I noticed the Parent Payment Out field.  How does this tie in, and How can I show the Balance Due?

**Comment by mykljohn** [comment]
After I added these 2 fields, I get the following error:

Database ERROR: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION globo_yeti.len does not exist
Query: insert into vtiger_crmentity (crmid,smcreatorid,smownerid,setype,description,attention,modifiedby,createdtime,modifiedtime,inheritsharing) values(?,?,?,?,?,?,?,?,?,?)
Params: 11174,1,1,PaymentsOut,,,1,2015-10-18 22:50:23,2015-10-18 22:50:23,
#0  PearDatabase->checkError() called at [/home1/globo/public_html/yeti/include/database/PearDatabase.php:354]
#1  PearDatabase->pquery() called at [/home1/globo/public_html/yeti/include/CRMEntity.php:306]
#2  CRMEntity->insertIntoCrmEntity() called at [/home1/globo/public_html/yeti/include/CRMEntity.php:96]
#3  CRMEntity->saveentity() called at [/home1/globo/public_html/yeti/include/CRMEntity.php:832]
#4  CRMEntity->save() called at [/home1/globo/public_html/yeti/modules/Vtiger/models/Module.php:169]
#5  Vtiger_Module_Model->saveRecord() called at [/home1/globo/public_html/yeti/modules/Vtiger/models/Record.php:260]
#6  Vtiger_Record_Model->save() called at [/home1/globo/public_html/yeti/modules/Vtiger/actions/Save.php:49]
#7  Vtiger_Save_Action->saveRecord() called at [/home1/globo/public_html/yeti/modules/Vtiger/actions/Save.php:26]
#8  Vtiger_Save_Action->process() called at [/home1/globo/public_html/yeti/include/main/WebUI.php:220]
#9  Vtiger_WebUI->process() called at [/home1/globo/public_html/yeti/index.php:25]

**Comment by bpabiszczak** [comment]
The trick is not to add something to your own system, but to complement the existing processes in the system and add them to the main engine. So you should think about how to do it universally and in a way that would allow to add the mechanism to Yetiforce. If you add it all only to yourself, it means that it will not be considered in statements, notifications, reports, which we will create for the system. To answer your questions:

1.The deadline for payment should be on the document the payment relates to. It has nothing to do with payments in and payments out.

2. Customer balance should be in Account [and as far as I remember it is there] and should be dynamically calculated based on all charges and payments ... so that we have the actual amount of the balance at a given time.

**Comment by mykljohn** [comment]
That's makes sense...(doing it to the main system).  You really need a Purchasing Module which would be similar to the existing Purchase Order Module, except for things being bought, not sold.  I've mentioned this in a different post in which I want to modify the Purchase Order to be used for Purchases (we don't use POs for sales).   Then you can relate the Payments Out to the Purchase Order and Vendor (Purchases) or Employee (Payroll and Expenses).

I'm not sure what you're referring to with Documents, by I will look at them.  cheers
