### ISSUE TITLE
Language barriers

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2111]
I noticed that many threads/issues are in Polish language. I am not sure if running two languages on the same international platform is wise enough. It limiting significantly resolving, understanding and tracking issues/conversations. It would be of an advantage to run only English here. This is also important from professional point of view on Yetiforce team and its global targets.

Zdrowka! Cheers!

**Comment by reeid** [comment]
Another thing is trolling. Some guys here should not post their basic questions (often non-matured or just silly from the developer point of view) unrelated to code development. Such trolling should be limited by some general rules written by main developer, such as: "How to use Git issues"
Troll should be threaten with link to this code of posting or/and set of links including online manual (if any). I am not a programmer, but also tired of reading useless statements or just whining..

**Comment by witer30** [comment]
Dear reeid,
I do not agree with you that some question are silly...
to know how system is working sometimes you have to ask questions which for some users can be very silly but for others are very important... Not everybody has the same knowledge and experience with CRM systems...
Accordingly language ok, international system let focus on English... 
If Yeti team agree lest's move question to other place as manual will be develop in next year as Blazej mentioned...
Dnia 19 października 2015 17:37 reeid &lt;notifications@github.com&gt; napisał(a):
Another thing is trolling. Some guys here should not post their basic questions (often non-matured or just silly from the developer point of view) unrelated to code development. Such trolling should be limited by some general rules written by main developer, such as: "How to use Git issues"
Troll should be threaten with link to this code of posting or/and set of links including online manual (if any). I am not a programmer, but also tired of reading useless statements or just whining..—

**Comment by bpabiszczak** [comment]
Just like @witer30 said – there are no silly questions. If someone asks the question in a wrong way, we will ask him to read the manual on how to create issues. At the moment it works well.

We removed a part of tickets in Polish, and we won't add them in the future [''we'' is the keyword], though it has more advantages than disadvantages.

However, I think nothing terrible happens when someone asks a question in Polish every now and then. Not everyone speaks English, and even if they do, some questions are hard to specify even in the native language, let alone in a foreign language.

Nothing will happen either, if someone observes GitHub and doesn't understand every single issue because it's not in English. We got around 200 internal tickets waiting for realization, they' re not on GitHub because we don't want to waste our time translating them. Nobody knows about them so they don't bother anyone...
