### ISSUE TITLE
Error updating to 2.4

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2139]
When I updated to 2.4 I got the following error:

Database ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'globo_yeti_tst.s_yf_multireference' doesn't exist

**Comment by bpabiszczak** [comment]
2.4? What was your version before updating, and what you've downloaded the file to update?

**Comment by mykljohn** [comment]
from 2.3 to 2.349 from this link you sent me https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

![image](https://cloud.githubusercontent.com/assets/11919990/10699684/4a77d8f4-797e-11e5-9a08-6d79cd6048d9.png)

**Comment by mykljohn** [comment]
Today I tried this one https://github.com/YetiForceCompany/UpdatePackages/commit/5b4bd94d9534f4e6242da374bfea6df70f20c63c

but it does the import, when I check the agreement and click import, it just goes to a blankish screen and kind of freezes.  
![image](https://cloud.githubusercontent.com/assets/11919990/10700248/03ddd08e-7982-11e5-9cb4-468bf91ff68c.png)
If I click home and go back to the updates, it just shows the previous update

**Comment by bpabiszczak** [comment]
Last time I saw this error it was caused because I picked the wrong update package [for v2.2 i tried to install 2.3.x package, instead of 2.3.0] and I assume you did the same thing. If I'm wrong, then install clean v2.3 and update it to 2.3.x and record a clip so i can see how and where this error is generated.
