### ISSUE TITLE
What happen that 2.3 shows that many errors?

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2145]
Was here some major changes in the core? It is impossible to put it on production in this state, so throwing it to public might not be good from marketing point of view?

**Comment by reeid** [comment]
Bugs are squashed in the speed vtiger can only dream about what is cool, just concerned what could actually cause that

**Comment by bpabiszczak** [comment]
1. We uploaded v2.2.0 instead of v2.3.49 to SourceForge by mistake :/  We just fixed that 
2. Most of the reported issues concerned the same thing, in addition, the system has a lot more users ... we have just improved the error that occurred on PHP version 5.4 and the remaining versions worked properly. For you it may seem like a lot, because you saw like 5-10 errors ... this is because users are testing the system only after the official package is published. Most of the issues could've been avoided if they tested the package before its release. We can't test everything on our own, and we internally fix about 200 /300 errors that result from the new changes.
3. We want to reduce the number of issues to minimum, but you have to consider how much is happening right now, how many changes. Vtiger has published only a few fixes, and they contain a lot of errors ... Check on SuiteCRM: https://github.com/salesagility/SuiteCRM/issues?q=is%3Aopen+is%3Aissue+label%3Abug They got 100 errors that haven't been fixed.. some are critical. Check our GitHub, we got ~60 issues, and just a few of them are errors.

What is important, is that reported errors are fixed quickly :]
