### ISSUE TITLE
[Question] Related field to User Module

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2154]
I'm working on the integration for Yeti to Moodle via related tabs.   I've created my new modlue and it works connecting to the Contact Module, but i need to do the same with the User Module, which doesn't show up in the Related Module List.  Basically I want a filed similar to the Assigned To field.  

FYI, I already have the Moodle Integration working via MySQL Triggers, but that's outside of Yeti.  I want to create the Module so it's within Yeti.

**Comment by bpabiszczak** [comment]
You cannot touch DB :/

**Comment by mykljohn** [comment]
I want to connect to the user module.  like the Assigned To field.

**Comment by bpabiszczak** [comment]
Check how this work https://github.com/YetiForceCompany/YetiForcePortal2/tree/developer [in code]

**Comment by mykljohn** [comment]
Here's my Module 
![image](https://cloud.githubusercontent.com/assets/11919990/10705040/a25c9790-79a0-11e5-87b6-d30d3f21a0d0.png)

I tried connecting to the Employee Module, bu there's an error there which I told you about previously.  But I'd rather connect it to the User module

**Comment by bpabiszczak** [comment]
This is entity module? This should be setting module.

**Comment by mykljohn** [comment]
I'm not sure.  Let me explain the function.  When A student or User is created, a record is added into this module (moodle_integration table) which will be picked up by Moodle and processed.  The event handler will write the email, name, ect to this module.

**Comment by mykljohn** [comment]
On the plus side for YetiForce, there are a lot of Moodle users looking for CRM packages that integrate well :)

**Comment by mykljohn** [comment]
What is a settings module?

**Comment by bpabiszczak** [comment]
Type of module. Accounts is entity module, Roles is settings module.

**Comment by mykljohn** [comment]
Ok, so this would really be neither.  It's for integration purposes.  It would be filled automatically when a User (or Employee) is created or a Contact is created.

**Comment by mykljohn** [comment]
Trying to import that module for customer portal, I get error with language

![image](https://cloud.githubusercontent.com/assets/11919990/10706556/5748a82c-79ad-11e5-884f-5397406d029e.png)

**Comment by bpabiszczak** [comment]
this is only example of code, this not work :]

**Comment by mykljohn** [comment]
ok

**Comment by bpabiszczak** [comment]
1. No module or function should connect to the database, the objects are there to use them.
2. The users module will ultimately be unavailable from the user's level. To generate a list of users, you should use the field with an appropriate uitype, for example the “record owner” field works.
3. If an error occurs you should enable the logs, find out the reason, and fix where it's required. You can read more about logs here: https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

Unfortunately, your descriptions are inconsistent, they lack some information, descriptions, and specifications of what and how you want to do things. This is not a programming course, you have to ask one specific question, rather than many small questions. Creating synchronization between two systems is complicated because it requires extensive knowledge of both systems. I'm closing this issue, if you have one specific question, please open another issue.

**Comment by mykljohn** [comment]
I actually did ask just one question.  And you answered it I think...I need to use the UI Type for the Assigned To field.  cheers
