### ISSUE TITLE
[Question/Improvement] Purchasing Module

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2157]
We want to setup the Purchase Order module to work from the buying side, not the selling side.  Can you send me docs on the Outsourced Products and Services Modules?  I want to modify them to connect to separate Products and Services sold from Products and Services Purchased.   This will make YF more of an ERP system :)  And I'l give you the modules when I finish.  Is there anyway way I can export them?

**Comment by bpabiszczak** [comment]
We're currently rebuilding the engine in order to make this system an ERP system. Within the next few weeks [ 4 – 6 ] we'll publish huge changes related to new modules, and they'll concern following processes:

Sales
Storage
Financial

We're planning to launch around 20 modules that are supposed to replace the old ones and bring new possibilities. If you have to create your own modules do it, but if I were you I'd wait... You could also ask us to create your modules, then we'd take your needs into account.

**Comment by mykljohn** [comment]
Sounds awesome.  for the Purchasing side of things, a separate Consumables Products module is needed, separate from Sales Products.  Or at least a field in the Products table to identify the item as a Consumable and not a For Sale item.   Then the Purchase Order would be able to maintain Consumables Inventory as well as For Sale Product Inventory.
