### ISSUE TITLE
server error 500

### ISSUE THREAD

**Issue by Ade-sd** [YetiForceCompany/YetiForceCRM#2185]
hi , i'm trying to install last version off YetiForce "2.3.49" on TurnKey lamp and i'll give 777 permission to YetiForce directory, but when i enter the file name in browser address bar for install it , it gives me server error 500 :
![server error](https://cloud.githubusercontent.com/assets/15356259/10780999/664c7a20-7d58-11e5-9880-dc04a06312ff.png)
thanks to all yeti guys good job.

**Comment by florek41** [comment]
First of all you should turn debugging on. Currently there is no possibility to see what's happening.

Secondly - there was problem with installation before - try current developer version https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

Last but not least - permissions 777 is very bad idea because of security - especially with application on public server.
First of all you should turn debugging on. Currently there is no possibility to see what's happening.

Secondly - there was problem with installation before - try current developer version https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

Last but not least - permissions 777 is very bad idea because of security - especially with application on public server.

**Comment by Ade-sd** [comment]
Thanks @florek41 for your answer ,The problem is solved . it was about my Turn Key  version , i use Turn Key 13 but when i get  Turn Key 14 it was solved.

**Comment by bpabiszczak** [comment]
Thank you @florek41

**Comment by labaiktours** [comment]
i am facing same problem setup wizard doesn't appear and i get 500 internal server error. i tried everything. I also tested it on xampp on windows server and on that it works but on centos keep failing. 

I also tried to contact support for paid installation but got not reply so far.

**Comment by bpabiszczak** [comment]
debug debug debug debug [apache first]
