### ISSUE TITLE
Tickets being created twice from mail scanner

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2246]
Tickets are being created twice from mail scanner.

An email comes in
A ticket is created twice with different ticket numbers.

version 2.3.49

I am thinking it's a setting but I'm not sure what. I tried to create a workflow to attach documents to tickets when they tickets are created via email. However, I have deleted the workflow.

**Comment by nuno-robosavvy** [comment]
I've experienced the same situation, still need to investigate a bit more if was my mistake on configurations

**Comment by nikdejan** [comment]
Same here. Version 2.3.88.

**Comment by nikdejan** [comment]
Possible reason for this could be in Mail Scanner->Folder Configuration. If you are using Gmail, the same mail will appear in more than one folder. So if you configure Scanner to scan Inbox AND All (and the same mail appears in both) you will probably end up scanning every mail twice, i.e. creating double Tickets. This is my guess, because at the moment I'm not able to test on my server.

**Comment by amicheals** [comment]
That's a good explanation. I will try to check. Do you have any suggestion to fix this.

Maybe a check if the mall has men scanned already

**Comment by nikdejan** [comment]
Try this configuration in Mail Scanner->Folder Configuration. This is how Mail Scanner is configured on test.yetiforce.com. If this doesn't solve the problem, then the problem is elsewhere.
![scanner](https://cloud.githubusercontent.com/assets/13381850/11363029/9157a70e-9297-11e5-93e9-ca52185dc4ca.PNG)

**Comment by mariuszkrzaczkowski** [comment]
Actions mail scanner has been restructured and optimized error should no longer occur.
https://github.com/YetiForceCompany/YetiForceCRM/commit/6602e6333453068ecc2305e714f124b3920528c9
