### ISSUE TITLE
PDF Module - Functions

### ISSUE THREAD

**Issue by agilisgmbh** [YetiForceCompany/YetiForceCRM#2260]
Hi Guys,
is there any Option / Possibility to use functions in PDF Module?
In PDFMaker Module from ITS4You (vTiger) you can use functions like:

[CUSTOMFUNCTION|its4you_if|condition|=|condition1|outputtrue|outputfalse|CUSTOMFUNCTION]

So you can say e.g.:
If Paymentstatus = payed then output "Invoice paid" else output "Invoice not paid".

Is this possible? Also I need this feature for some language dependent textphrases... and much more..

regards

**Comment by bpabiszczak** [comment]
1. You can't directly call a system function in the template, because it's a breach of security, and the module should not allow for that.

2. You can call so called 'special functions' in the templates, and you can do whatever you want in the special function [the programmer decides what and how it takes from the system, and in what form it's presented], but this option requires at least basic programming knowledge.

3. Our module can be tested here: https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35

**Comment by agilisgmbh** [comment]
Thanks Blazej for that information.
So, it´s not possible for a "non.dev" to add easy functions like in my example, correct?
Second: When will your new PFMaker be published? I tried to make small test, but i cant use it in "invoices". I can relate it to invoices,yet, but not use it in demo, correct?

**Comment by bpabiszczak** [comment]
New questions, new issues.
