### ISSUE TITLE
[Problem] Upgrade - Labels Disappeared - Revisited

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2311]
Ok, I started with a clean install using YetiForceCRM22.zip (no problems)

Stepped through the upgrades...The labels disappeared 2.2 > 2.3, but I kept going hoping that the would return.  
![screenshot_6](https://cloud.githubusercontent.com/assets/11919990/11321114/b8f96f58-9077-11e5-9013-5240bbeb9c11.png)

No such luck.

**Comment by mykljohn** [comment]
This is strange...If I go into YF through MS Edge, all the labels are there...if I use Firefox or Chrome, no Labels...Any Ideas how to resolve this?  We don't use Edge as our browser.

**Comment by mykljohn** [comment]
This seems to be a problem with php5.5.  I migrated to a new host with php5.6 and the labels are visible.

**Comment by bpabiszczak** [comment]
We plan to abandon support for PHP version 5.4 / 5.5.

**Comment by raphinology** [comment]
I just wanted to add some insight on this issue. It appears to have something to do with the way chrome is caching the menu array along with its relation to your session. You'll end up seeing the following message in your {root_install_dir}/cache/logs/phpError.log:

array_key_exists() expects parameter 2 to be array, null given in {root_install_dir}/modules/Vtiger/models/Menu.php on line 41

As it mentions, its looking for an array, but the returned array was null, therefore, you're not seeing any menu labels. 

A quick fix is to clear your cache "From the beginning of time". To get your labels back. Unforunately, this hasn't reappeared, so I wasn't able to spend much time figuring out what the issue was. I suspect that it was session/cookie related, but I'm not 100% certain.

Hope that helps : )
