### ISSUE TITLE
[Question / Improvement] Quote

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2322]
When we display a send a Quote, we would like to display the other prices from Price book related to the Product.  or example, if the client wants a Quote for xyx, we want to display that price (with the Price Book Description) as requested along with the other available pricing (and descriptions) applicable for xyx from the related prices books.

xyx   English Basic I                  - Group Class          $x,xxx

         other available pricing      - Semi-Grupal          $x,xxx
                                                  - Particular               $x,xxx
                                                  - Intensive                $x,xxx

**Comment by nikdejan** [comment]
If I understood you correctly, you want to be able to offer more than one alternative to the customer, in the single quote? For that, maybe it's better to use separate quotes for each offer, because that is what each quote record is. And if you have in a single quote prices for:  Requested Product, Alternative Product A and Alternative Product B, how do you think to calculate totals? 
What you want to send to a customer is actually not a quote but a Price list.
Just in case you missed it. Similar topics have been discussed here: #2299 and here: #1656

**Comment by mykljohn** [comment]
Yes, basically show the other prices offered for that Product.  Since those are Closed, I'll continue my idea here.  We don't sell Products, we sell Courses.  A Prospect may request a Group Course, but we want to show the Price for a Private Course as well.  I thought I could just attach the Price List for the Course, but I can't figure out how to do a Price List.

**Comment by nikdejan** [comment]
Solution that comes to my mind is to use Quote as a Price list. 
In normal Quote you have list of products which together form a complete Quote.
In normal quote:
1. First product (part of a package)       $120
2. Second product (part of a package)  $30
3. Third product (part of a package)      $45
    Total (whole package, sum of 1,2,3)  $195
Now if you remove Total, you will have a list of product each of which could be treated as whole package. So in your case, in a modified quote you would have something like this
1. First product                                     $120
2. Second product                                $30
3. Third product                                    $45
No total, because this are alternatives. Nobody will buy all three.
You also need to adapt language of quotes.
You are going to have a small problem when you convert Quote (offer) to Sales Order. In Sales order you would have all three Products. And then you will have to delete two and leave the one which a customer has chosen. 
This is possible from the technical point of view, but I am not sure this is a good solution. Because when you use a CRM you need to follow the logic of CRM and the logic of business. So not every modification that is possible technically is good modification, and I don't have enough experience with CRM to tell if this is good direction. 
What you are asking for is, I suppose, not so uncommon, so there must be a ready solution for your situation.

**Comment by mykljohn** [comment]
@nikdejan Thanks for the input.  I tried that already and it's not practical.  First, as you said, the problem in converting to a Sales Order.  It's a pain to delete each added item (slow).  2nd, The description of the Price Book isn't added, so The clerk will have to type that in each time (not really convenient).

That would also be a nice addition, to be able to add the Price Book Description to the Product Item 

Description.  I'll have to wait on this.

**Comment by nikdejan** [comment]
"Price Book Description"? Do you mean Product Description?
I'm in a similar situation so I'm just thinking out loud.
Another option would be to add Products to Opportunity. Then you would need an email template based on Opportunity module, which would list all products related with given opportunity. What do you think?

**Comment by mykljohn** [comment]
That has possibilities, let me look at that.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2461
