### ISSUE TITLE
[Question] ¨Workflow create Entity

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2341]
I want to create an entity from Sales Orders (automatically create the Invoice) but Invoice isn't in the available Entities.  It has the relation both ways, but not in the list of Available Entities.  Could this be because I added a Translation for the Sales Orders Module to Enrollments?

**Comment by bpabiszczak** [comment]
1. Which version are we talking about?

2. There is a new mechanism in the dev version which allows you to generate a record from module A to module B: https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95. I don't remember if there's a ready function in the workflow to automatically call what we configured in mapping, but if it doesn't exist then you can easily create it yourself, because this module has been designed for automatic generation.

**Comment by nikdejan** [comment]
Current developer version doesn't have invoices at all.
