### ISSUE TITLE
System universal compatibility

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2344]
Just get some clue about various operating systems and hardware environment scenarios.
Maybe it will be of an advantage to optimize YF for let say AWS stack and chosen Linux version? 
By the way... anyone installed it in there?

**Comment by bpabiszczak** [comment]
The OS doesn't matter for us because our application is a web application and works on practically everything. We are a partner at Suse https://www.partnernetprogram.com/partnerfinder/partner.html?id=49ACC05E and we're preparing tests in this web environment and our programmers will participate in many training courses.
