### ISSUE TITLE
Question / Which is the porpouse / logic behind shownerid

### ISSUE THREAD

**Issue by playmono** [YetiForceCompany/YetiForceCRM#2366]
Hi,

I can see you added in vtiger_crmentity a core field called "shownerid". Can I understand which is the porpouse / logic / workflow behind this field? A regular record saving should value empty?

Thanks.

**Comment by nikdejan** [comment]
https://yetiforce.com/en/user-documentation/sales-process/118-opportunities.html
"Users sharing - a list of users who can access this specific opportunity. Inheritance works regardless of company organizational structure."
It makes sense to me. Sometimes, for whatever reason, you might want to share particular record with certain user, while you don't want to let him see all the records of particular module.

**Comment by bpabiszczak** [comment]
The field is used for the same purpose as the record owner field, however, you can select more values.

In the old version of the system [eg. the last stable version] we're still using this field. Although in the new version [developer version] we use a new mechanism and this field won't be used [but it will still be in the system, because the field in vtiger_field must be linked to some field]. The new version of this mechanism will use relation tables [it's caused by the need for quick narrowing down of relationships, and in case of the old method we had to deserialize data].
