### ISSUE TITLE
Crucial changes in the system

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#2387]
1. We removed the Dutch language (nl_nl) from the system because it hasn't been actively translated, and included only 20% translations compared to English.

2. We removed the "old layout" from the system and we kept the new one - we did it primarily because supporting two layouts takes too much time, and we want at least one template to be well developed. If someone prefers the old template then he can download it from GitHub. The system supports a variety of templates, so anyone can add a new one anytime, and it will not interfere with the system.

**Comment by nikdejan** [comment]
1. I am not personally interested in Dutch language, but if it's only 20% translated, then removing it sounds reasonable. Personally I stick with English, although it's not my native language. It takes less effort for employees to learn few technical terms (like Account, Opportunity, Lead...) than it takes for admin to translate each and every occurrence of this terms, and than to keep all this updated. And using clumsy other people community translations is probably even worst, because it's rarely consistent and can easily lead to confusion. I hope that abandoning support for unused languages will lead toward more complete English version.
2. Since you created Responsive layout, I stopped using Vlayout. All my layout modifications are in Responsive. Vlayout has some advantages if you are an admin and you are setting up yetiforce. You have two menus, left sidebar and top. It makes navigation during setup process a bit easier. But in regular usage Responsive is far superior. And having one good layout is much better than having two bad layouts.

**Comment by eptapsyxos** [comment]
Ok. Good choices Both.
