### ISSUE TITLE
[Questions ]The Future Of Yeti

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2448]
First of all i want to say a huge thanks to developers of yetiforce for they efforts.

Second(the question)

As i saw on SETTINGS we have the ability to create Module and not to install from file.
What is the Strategy of  your company for the future?
And to be more specific.
With the release of responsive template i understand that the modules from vtiger will not be compatible.Am i right?

If yes ..we have a new reality.

That means that you will create new modules-extensions or a freelancer developer or an outsourced company will create for clients.

Have you decided how to share this new creations?
Via Marketplace (paid or free versions) ?
paid or free through software updates?

If no....we keep going as usual.

Do you plan to release any kind of roadmap for 2016?

My intention is to know how you will move to give us a clear vision of strategy to implement this to our bussiness.What to expect and what not.

Because we are making too plans for 2016 and i believe all the clients want to know how will move(because i believe all we want to keep using yeti,because it will make our life easier up to a point).

All we understand that you are not a charity business and you are running under huge pressure and costs have you decided how to finance Yeti?
For example.
Are you open to Donations?

It's important i believe to paid for your effort we if all of us want to see this project to grow up.Passion will fade away when real needs  knock the door.
(we saw that on vtiger and sugarcm but they did it with very wrong movements...they became famous from community members and developers and suddenly they changed their strategy..)

This is some of my thoughts with my best of my intentions.
I am not a developer i am a simple user and i am trying from my position to help as much i can.

and one more time...Thank you very much.

**Comment by witer30** [comment]
+1

**Comment by bpabiszczak** [comment]
FAQ: 
Why I cannot install a module on a testing version?
This restriction applies only to our testing version at https://test.yetiforce.com. It increases the security and stability of a testing version. Versions downloaded from GitHub have all functionalities enabled by default.

**Comment by witer30** [comment]
Think that the YF project is greate and is going into good direction... 
For me are very interesting infos which have been asked by eptapsyxos...

But crusial is complete implementation of new modules (sales process, qoutes, calculation, etc.) as old are not longer  supported and contains still some bugs, and new ones are not intergrated with the system and still have some bugs as well...
Think that this should be priority as without salse process a system is not a real CRM... Of course this is my opinion.

**Comment by nikdejan** [comment]
I like new modules because they offer a lot of possibilities and many things are obviously better. I tried to customize them in order to use them for production. Unfortunately, while testing this new modules I understood that they are still too far from being usable. 
That is why I decided to stick with old modules. And then I understand that old modules are not supported any more. 
So what should you choose? Old or new? Old is not supported and still has some bugs, new is not ready to be used because it it is not integrated into CRM and has even more bugs than old! It's hard to be YF user this days.
And there is one more problem. If I use old, will I be able to convert old to new in the future? YF team doesn't promise that.  
YetiForce doesn't promise anything! YetiForce doesn't recommend anything! (#2303) Use it on your own risk!
There is one question with a clear answer: "Does YetiForce CRM have more features that vTiger". Definitely Yes!
But there is another question which each one of us will eventually ask at certain point: "Is YetiForce overall better than vTiger?, i.e. can you recommend it over vTiger?" Well, I'm not sure anymore.

**Comment by bpabiszczak** [comment]
@eptapsyxos 

Regarding YetiForce:

1.The new template version has nothing to do with backward compatibility with Vtiger. At most, the module might have a "not matching" appearance after installation , but it shouldn't affect its operation. However, Vtiger and YetiForce are two different systems, and they'll differ more and more every day. A module for Vtiger is not a module for Yetiforce [and vice versa] because we are changing the permissions logic, file loading logic, configuration logic ... Each Vtiger module needs to be adapted to this to work with YetiForce and it will stay this way. It's not because we are mean, but because maintaining backward compatibility with a system that doesn't develop would slow us down too much.

2. There is a possibility to install and create modules! This option is disabled in the test / gitdeveloper / gitmaster versions. In the near future we will open a store, but it will differ from Vtiger's store, there will only be extensions, instead of entire modules that should be part of the system, like in case of Vtiger. For example, you will be able to buy different versions of pdf invoice in our store, but in the the system itself there will be a panel to manually create pdf templates, and one template will be available for free.

3. There will also be some revolutions in the system, concerning “process replacement” and they are bound to start many “heated discussions”. Unfortunately, it's necessary due to the engine modifications for modules with products and to expand the system with new processes [eg. multi storage capability, accounting]

Regarding the future:

1. Our goal is to create the best open system for companies in the world. We know we need a few, or several more months for that. The system will always be open and there will always be only 1 version of it [just like it is now]

2. The development direction [what and when is added to the system] is directed by our customers. We add functionalities that are not in the system but the customers need them. We don't know what functionalities will be requested in 2016 by our clients, so a plan like that for 2016 is probably never going to be released. Of course we have a general overview of the system and we control its development direction, but our priorities come from our customers.

Financial support:

1. We already launched a donation website-  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JJWUUTQD79GCL , the button will be available by default in the configuration tab in the system, as well as on our website. The financial support from the donations will allow us to create a professional documentation for the users, provide better and faster user support on github, and it will speed up granting the "whims" of our users.

**Comment by nikdejan** [comment]
The most important "functionality" that anybody needs is stability. We do not have it, and we never had it. We can hope that in the future it will bi different.

**Comment by eptapsyxos** [comment]
@bpabiszczak  thank you very much for your clear words.we have the need to hear it from official mouth.
Personally i am staying sticked to yeti.
It will be a long way trip with ups and downs but worth the pantient.

**Comment by bpabiszczak** [comment]
1. Currently, the stable version is 2.3.49 and can be downloaded here: https://github.com/YetiForceCompany/YetiForceCRM/releases.

2. The new process exists only in versions higher than 2.3.49 [developer version] and the new process will be fully operational when we release the next stable version 2.4.

3. You decided to use the developer version without the right support from developers and without knowledge of what the dev version contains. In this case, I can only tell you that this is your own fault. When we install any version for a customer [even if it's the developer version] we know its limitations and errors, if an error occurs in the client's version, we fix it on the same day. You unfortunately don't have the developer's support, and you're trying to live with these errors ...

4. All reported critical bugs to the stable version 2.3.0 were fixed and the 2.3.49 was released. You have to wait for further improvements because they will be released together with version 2.4, how stable that version is going to be largely depends on the number of people testing it.

**Comment by nikdejan** [comment]
@bpabiszczak not entirely my fault #2303. You said that you plan to keep old modules and Opportunities, but to disable them, and I based some of my decisions on that. Now you completely remove them. Can you, please, at least leave Opportunities until the last moment, when you create Opportunities->Sales Processes migration tool?
I really believe that you are going to succeed with your main goal, i.e. to create the best open CRM, in a few months. And I am happy for that. I still think that you are going too fast. If you want to have more bug reports you must have more testers, and the best testers are real life users. And real life users need stability and long term support. And stable 2.349 still has a lot of problems, and for many questions the answer is "this will be completely different in the future".
Good luck!
