### ISSUE TITLE
PDF again

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2452]
Got impression that PDF module has been abandon. Promised functions (similar to PDFMaker from Vtiger) are not rolling out. Can you guys confirm you working on it or current state is final?
As I dont see any developer who willing to write professional and rich in functionality PDF module it seems to be reasonable to figure out development of it. 
Another thing is use of custom functions. It is crucial to allow some set of ready made functions similar to PDFMaker (vtiger)  especially  allowing PHP function directly in PDF template. Saying that it is not safe is not solicited here as Administrator is a one who got highest level of authority. If admin crush his system by silly action it is his own problem. Similar risk is by using mass edit (even much more risky) so I dont see any reason to defend non existence of PHP in templates.
Related blocks are another factor which is super useful.... worth to think of it....
More advanced PDFMaker can be released as a paid extension - I dont mind to pay even 100usd

Cheers

**Comment by eptapsyxos** [comment]
+1 For erstes blocks
Plus
Dynamic Blocks  For all Fields. Not only  picklists

**Comment by eptapsyxos** [comment]
you Can Check here  http://www.its4you.sk/en/vtiger-extensions/dynamic-fields 
Dynamic  Blocks  For all Fields

**Comment by bpabiszczak** [comment]
Most of your post focuses on criticizing, if you want to discuss something I propose switching to a substantial level. First of all I'd like to ask you for a list of functionalities, that - according to you - don't exist in the module, but should exist there by default.

Destroying the system with poor management is most likely not your problem, but it always is our problem, because it's us who must try to help the end user, and it's us who get blamed that the system is unstable. In particular, because most people believe that they shouldn't be able to “destroy” the system from the administrator's level.

**Comment by florek41** [comment]
If we are talking about functionalities that missing in the PDF module
- For me important is possibility to print **reports** - for single/selected records (ex. i want to print project tasks for selected projects or invoices for selected client)

**Comment by reeid** [comment]
"Most of your post focuses on criticizing" -- I am not sure Blazej... is that was to me? If so, where is my criticizing part of my post?! 
I am giving you guys advice as a power user and professional who using such systems more than 20 years. Even you will find form anyone here criticism,  you should be able to transform it into positive factors.... are you?

**Comment by bpabiszczak** [comment]
"First of all I'd like to ask you for a list of functionalities, that - according to you - don't exist in the module, but should exist there by default."

**Comment by reeid** [comment]
Blazej, reproducing most of the PDFMaker functions will be a perfect. As I said, it could be paid extension. Anyway somebody should start writing paid extensions to encourage community to be involved more. 
Major issue is a lack of related blocks and math/txt/logical functions plus use of some basic php operands. Again - mentioned safety issue from Admin level should not be a problem of Yetiforce.
Especially that you providing paid support.
Such a model functioning in vtiger (and PDMaker) for a years, and I never heard any complaining about messing things. Maybe you need PDFMaker license? I believe we all can donate some coins so you can have reference for development. 
I would love to hear others opinion too.
.

**Comment by bpabiszczak** [comment]
I asked for a list of missing functionalities that should be added. Instead of that I got a suggestion to close the system and start adding paid stuff an answer to check the functionalities myself

You wanna donate for the PDFMaker license? I spent several thousand Euro on creating our module, and I'd have to collect money for the competition's solution? I've seen PDFMaker for each and every Vtiger version, I know how it works, I know its advantages and disadvantages, I know its license as well... and I assume I know more about it, than the majority of its users... If you want to help develop YetiForce, you can do it by:

1. Becoming a client of ours 
2. Expanding the system together with us, by adding functionalities 
3. Supporting us financially, using donations

Our module has got a great potential, however, due to the lack of documentation, part of the functionalities is unknown for many users. If something is missing – it can be easily added using a special function. And it's going to remain like this for now, until one of out clients orders a new functionality to be added to the module.

We get tons of ideas for new elements from our users weekly. I come up with hundreds of these ideas daily. However, the question is – who is going to do that? We only add these functionalities that were either ordered by our clients, or ones we consider reasonable and relevant for the system.
