### ISSUE TITLE
RFE: Extensions Of LineItem

### ISSUE THREAD

**Issue by ChristopheLux** [YetiForceCompany/YetiForceCRM#2465]
Hello Yeti Team,

You are progressing so fast. Maybe I was not able to catch it but I would like to have the possibility to
1.Attach a record type (Account/Contact...) of my choice to Line item (configurable)
2.Show X fields of my choice of the record chosen onto the Line Item (Optionally to have a workflow/rule to select or to impact the price/pricebook) 
3.Configuration above apply throughout the life of the Line Item (Quote/PO/Invoice...)

Thanks in advance for considering my request...or at least give some guidance./indications to start building this

Happy Greetings Season

**Comment by nikdejan** [comment]
In order to answer your question I went to https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SCalculations
and found this bug: https://github.com/YetiForceCompany/YetiForceCRM/issues/2473
So, at the moment, I am not able to check and give you exact answer.
But, as far as I remember,
1. 99% sure it is possible
2. Not sure
3. 80% sure it is possible, with Field Mapping.

**Comment by ChristopheLux** [comment]
Hello

What info/details you require?

Kind Regards

**Comment by nikdejan** [comment]
Now that bug is fixed, here is how the things are:
1. Definitely Yes. You can go to: https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SCalculations and switch to Managing an advanced block tab. Basic Verse > Add Custom Field and then Select field type: Reference. You can choose one or more modules.
2. As from what I see, this is not possible without code modifications. It shouldn't be too difficult if you are a developer.
3. Looks like it is possible. You go here https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95, and then choose modules for which you want to map fields. Reference field is available for mapping as any other field.

**Comment by ChristopheLux** [comment]
Hello Nikdejan

For 1 it is working perfecty

![calculationref](https://cloud.githubusercontent.com/assets/11833461/11956542/509830dc-a8bb-11e5-9f57-0dee1c17e0d0.png)
 and see the result
![calculationref2](https://cloud.githubusercontent.com/assets/11833461/11956548/5e156536-a8bb-11e5-8560-ba8c0923fb3c.png)

When trying to make 3 see what i have when i choose the select module as Calculations and Related Module as Contacts...I am not able to choose any field from Contacts

![mapfieldcalculationcontact2](https://cloud.githubusercontent.com/assets/11833461/11956573/8d5d2ea0-a8bb-11e5-8cb7-3471b9ceecd2.png)

Thanks in advance

**Comment by nikdejan** [comment]
No, no. It works differently. You can reference Contact from a Calculation and you can map Calculations to Quotes and reference to contact will be passed from Calculation to Quote. Calculation is advanced module and Calculation's reference to a contact can not be mapped to a contact, but only to some other Advanced module (Quote, SO, Invoice...).
Sounds confusing, but when mapping you need to map calculation to a quote and you need to have analogous reference fields in both.

**Comment by ChristopheLux** [comment]
Hello nikdejan

Thanks a lot for all the help so far

So what I have to do is to create in Calculations/Quotes/SO/Invoice....a reference field link to contact for example and then map calculations with each of the module above?...
I trust you it works but to me it is a bit circumlocutory
Happy Holydays!

**Comment by ChristopheLux** [comment]
I want to do the same thing as https://github.com/YetiForceCompany/YetiForceCRM/commit/6280e5db2aa416c386614bfb5787e8f21eec0d68 but for LineItem (eventually activate or not the realtionship) and be able to choose what fields I show from Contact on the LineItem...

**Comment by paula-w** [comment]
@ChristopheLux could you just sum up what is still unclear for you, so we could help you? And what do you mean you want to do the same thing as  6280e5d? Could you give us some more details? 
Thanks a lot :)

**Comment by ChristopheLux** [comment]
Hello Paula

The explanation which was given was a bit confusing
I can not make screenshots as of now as gitdeveloper.yetiforce is throwing an error

As of the same thins as  6280e5d : I want to be able to create a relationship between LineItem and Contact and I want to be able to choose the fields from contacts that does appear on lineitem block on calculations quotes, invoices SO etc...

Thanks for following up

**Comment by ChristopheLux** [comment]
Hello

Here
![lineitem_relation](https://cloud.githubusercontent.com/assets/11833461/12509503/3aaf51f0-c103-11e5-8db9-75e835d91d50.png)

I want to be able to select LineItem or your equivalent

**Comment by paula-w** [comment]
The new gitdeveloper version allows you to add uitype10 field to each line of the product block. 
At the moment we're not planning to expand this mechanism any further.

**Comment by ChristopheLux** [comment]
Thanks @paula-w 

Would you mind making a small example or very quick step by step guide

And if we add the field in product block will this impact Quotes/Invoices etc...

Thanks
