### ISSUE TITLE
leads error after upgrade to 2.3.49

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#2474]
After upgrade to yeti 2.3.49 custom fields from previous versions gives error on creating new leads:

Error!!!

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'kundetype' in 'field list'

"kundetype" is a custom field on leads.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by lalord** [comment]
Please let me know how to give you more instructions on this?

Error is related to some custom fields created in previous versions of yetiforce.

see this video capture: http://www.screencast.com/t/ImUzidft3IL

No errors in any of the yeti log files.

**Comment by bpabiszczak** [comment]
Please check test version https://test.yetiforce.com/
PHP version?

**Comment by lalord** [comment]
PHP Version 5.5.30
I cant really test this issue on test.yetiforce.com since it accoured after upgrade to newest version.
Problem is that custom fields is not handled correct in new version.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
the bug is quite simple, the is no column in the data base and the system is trying to find it. Either this fields needs to be removed from the system, or the column needs to be added where it's missing. To confirm what is the cause of this problem, it would be necessary to analyze this case in details and it should be done by a person who implemented the system.
