### ISSUE TITLE
Basic navigation improvement N2

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2509]
Describing a common procedure.

I am opening a contact
I am selecting the tab Activities
I am selecting add Event
I am creating the event
The system links me to Event summary View.

WHY?i have just created and I know the details and I was working on setuping my contact.
Now I have to re open the responsive menu
To find in list view my contact
To continue my work on contact.

The system must get back us to Contacts.

This  logical sequence must  be applied to all modules.

**Comment by eptapsyxos** [comment]
I ve photoshoped an idea HAVE A LOOK
![dropdown](https://cloud.githubusercontent.com/assets/6897502/11929624/75094068-a7e5-11e5-87a4-33358b0d0d53.jpg)

**Comment by nikdejan** [comment]
+1

**Comment by florek41** [comment]
So mabye all buttons in related tabs should display quick add modal ?
Or better - User can configure this button to show quickcreate or fulll form.

**Comment by eptapsyxos** [comment]
@florek41 i believe that if full form drop down we have to make.more movements to scroll down.its not bad idea.to be configurable. 
Yes i agree this pattern to be applied in all tabs.

**Comment by bpabiszczak** [comment]
1. In YF system, the user doesn't get to configure anything, he doesn't get to decide what's best for him ;P it's the system administrator's job.

2. I don't see how it would make things easier, mainly because most of the events should be created from the process or mail levels...

3. We will improve tabs in the future, but it's of too low priority to do it now.
