### ISSUE TITLE
Future Request Calendar right panel Drag and Drop Events

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2510]
Something like that
![image](https://cloud.githubusercontent.com/assets/6897502/11914151/7890e292-a680-11e5-9844-bc42a51857ee.jpeg)

**Comment by florek41** [comment]
I can not understand for what this functionality is, can you describe it? How it works?

**Comment by eptapsyxos** [comment]
Wait a minute to show you

**Comment by eptapsyxos** [comment]
http://responsiweb.com/themes/preview/ace/1.3.5/calendar.html Try it here.drag and drop event from the right list inside the calendar.

**Comment by florek41** [comment]
I understood how it should works but I don't understand what do you want to achieve with this tool ?
You can drop a task but you need to specify much more things like related process (account, ticket, project etc.) or additional description.

Shout it be something like "Generate form template" ?

**Comment by eptapsyxos** [comment]
I saw a version when you dropped the event into the calendar pop uped a window similar to ours quick create.there you had the ability to fill additional details. In our case that you can achieve is to write multiple times the same topic of event or to do.

**Comment by nikdejan** [comment]
I like the general idea to avoid entering the same data again and again. I think that the biggest problem with activities is that you need to enter too much data every time. Most of the companies most of the time use a finite number of activity types. That's why I was thinking about some kind of templates for the activities where you could have preset field values for certain types of activities. It's the same logic as the logic behind using Canned Responses in email client. 
If you add an activity from a activity widget in particular opportunity then this widget would be automatically attached to given opportunity and to opportunity's parent account. Then, you should be able to choose some kind of Preset, or predefined template, which would automatically populate Activity subject, Dates and Times and possibly Assigned to, because you might organize your company in a way that certain tasks are always done by particular employee or a group of employees. 
That would certainly speed up the process of creating new activities and this module would finally be usable. Now it is not usable. How do I know that it is not usable? Well, ask your employee to choose between: 1) creating activity and assigning it to a coworker and 2) contacting coworker over some kind of chat and telling him what to do. Most employees will choose chat, which means that creating activities is not fast and simple enough.
It's another question of Drag&Drop is the best interface to realize general idea of Preset activities. It's mostly a matter of taste. I personally like Drag&Drop, but I would also like, maybe even more, to be able to chose a template from a picklist. Another benefit could be overall simplification of Activities. Now you have to choose between To Do and Event, and if you choose Event you additionally have to choose event type (Meeting, Call). If you add templates to all this it is going to be total mess. I think we need only one picklist called Event Type where we could choose preset Activities, which would be user configurable like: Urgent Call, Meeting Next Day, Do till the end of a shift, During next month... Off course, employee should be able to manually change all field values. In most companies 90% of activities are typical activities and we could save a lot of time on them. For the other 10% we can always set them manually.

**Comment by eptapsyxos** [comment]
Maybe a solution for not to fill again and again the same data.

![sameevent](https://cloud.githubusercontent.com/assets/6897502/11930059/e87b1370-a7e8-11e5-8e7c-3be76d9088e5.jpg)
@nikdejan @florek41 @TomaszQr @mariuszkrzaczkowski @bpabiszczak

**Comment by bpabiszczak** [comment]
![autowork](https://cloud.githubusercontent.com/assets/10197525/12012757/e0281798-ad03-11e5-8569-583c3450c5d4.gif)

**Comment by nikdejan** [comment]
@bpabiszczak 
Manual workflows are great, but we do not have them in Opportunities, and this is where they are most needed.

**Comment by bpabiszczak** [comment]
Workflows work everywhere

**Comment by nikdejan** [comment]
Sorry. It is OK with old opportunities, but new opportunities (SSales Processes) don't have Create ToDo option in workflows. They are not connected to Calendar at all, but I guess this will be done in few days :-)
