### ISSUE TITLE
Improvements. See also #2513 

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2521]
Is there any progress, action, or anyone tried to use Yetiforce with Asterisks?
Obviously if this part is not working, CRM can not be deployed  on large scale projects.
I am asking as I might need to step into integration and possibly will be looking for some help here..

**Comment by bpabiszczak** [comment]
I don't see any connection with #2513. At the moment in YetiForce there's no functionality integrating with telephone exchange [whatever is there is Vtiger leftovers]. When we have a client who wants to pay for such integration, then we'll most likely add it to YetiForce as well. I'm closing the issue, because we're not planning to implement it anytime soon.
