### ISSUE TITLE
[Improvement] Parent Summary widget

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2548]
Opportunity is a heart of sales process. All activities connected to particular sale should be related to particular opportunity. In opportunity's summary view we can see the most important of those related records. 
So far so good. But what is missing? We don't have the MOST IMPORTANT RELATED RECORD, and that is Account record. 
Why do we need more account details? Well we might need to see account's working hour, or it's legal form, or phone number, or some comment/attention or many, many other things, depending on particular business. 
Now we only have a clickable account name, but if we need more info about account we need to go to account page.
So I suggest to create Parent Summary widget which would contain summary Account information (maybe the same that we have on account summary page).

**Comment by eptapsyxos** [comment]
Agree

**Comment by bpabiszczak** [comment]
In my opinion the problem is that we have too much information in one place. To add something new, you should delete something else first, or else it won't be transparent. In 2016 we will improve the UX, but the widget with information about an Account doesn't really do anything. Maybe we'll add an icon with the customer's mail, phone, address next to his name ... but currently it has a very low priority. Additionally, you should think about how it should be designed for each system, and what's important at the given moment.

So the new widget is a “No” for me ... but you can always create it and send to YetiForce on GitHub.

**Comment by nikdejan** [comment]
Somebody said something like "If you don't need a widget, you can disable it :-]" ;-)
Nobody will use all the widgets. If it was so we would already have too many widgets to fit a single page.
I think I provided enough argument that this widget might be used by lot of people and that's why it needs to be a part of the best open crm.  
( @bpabiszczak, we are using this "best crm" against you so often that you are probably sorry you ever said that ;-) Anyway, keep going!)

**Comment by reeid** [comment]
@bpabiszczak > Listening community is more important than listening own customers - if we talking about "healthy" open source project. 
As your aim is to build something exceptional on the CRM market, there is no other way but:
1. build as large as possible community
2. start analyzing voices and implement wise advises

Otherwise you might disappoint great programmers what will end up  with very limited code contribution/extension design. Without those who are involved in adding values to system small number of end users (especially large corporations) will be using yetiforce. 

Vtiger have thousands implementations as community has been built through many years (including inheritance from SugarCRM). The way to popularity in this field is to convince developers. Each serious developer have base of own customers, so it means faster multiplication of end users.

Above on the conditions of building open source application in line with adhered standards. Obviously your plan might be a bit different, so it would be good to issue clear statement such as: "you can fork me but dont mess with me"

Remember one thing: if you want to do your own way with hope to glue end users as your own customers, you might need more programmers on board. Here again coming back crucial message: do convince programmers to work with you :-)

Anyway, whatever plan is, you are doing good job in the meaning of programming

**Comment by eptapsyxos** [comment]
i believe that yeti cannot handle the high hopes that created to the community users.

**Comment by bpabiszczak** [comment]
@nikdejan

The difference is that it's us who do all the work, so if you want something we don't want, you can create it an add it to the system. However, if you don't want something that we want – just hide it. We definitely won't add things we don't want and then hide them for ourselves. As you see, your arguments weren't convincing to us, and even if they were, it doesn't mean we'd have the resources to add this functionality. Let's be clear – I got 100 new ideas to expand the system daily, but it doesn't mean they'll be added, even though I think they should.

For the most of you it doesn't matter that we add a number of things daily. The tragedy happens when we don't add one thing that you care about. The difference is that we look at the system from YetiForce's development perspective, and particular people on GitHub look at what they need the most at the moment. This isn't fair.

@reeid 
There are no other programmers in YetiForce, apart from our own. So as far as programmers are concerned – we won't scare anybody away, because there isn't anybody :]. The community doesn't look at it from YetiForce's development perspective, most of the time those are the needs of individual users, that are important for them here and now. When we don't make their wishes come true they're disappointed, and it doesn't matter that on the same exact day we added a bunch of new functionalities – the biggest problem is that we didn't add what that one particular person wanted. Especially that it's open source, and the person can add it on his own, and develop the system this way.

Interestingly enough, this creates a kind of absurd sometimes, where our competitive companies, instead of developing the system they use and send the fixes to us [because they got the knowledge and the programmers], they simply generate an issue hoping we would fix it for them. We're not here to satisfy everyone's whims – we're here to expand YetiForce, give it the right direction, and support everyone who wants to help us as much as we can at the given moment.

I'm not going to convince anybody to my opinions, I don't think that I'm always right either, but at the moment we develop the system in 99%, as long as these proportions remain you can't expect us to do things we don't consider beneficial, or are of low priority. We provide an alternative for those who don't like Vtiger, coreBOS, SuiteCRM,SugarCRM, EPESI, etc, but it doesn't mean that they'll find what they're looking for in our system. I hope we can achieve that one day, but we can't force anything.

@eptapsyxos
Just like I said, we're not here to satisfy everybody's whims. We have a specified goal, and if we don't agree with something, or we don't consider it our priority, we won't implement it. What I don't understand is why the unhappy ones don't invest any resources to add to the system what they're missing.

**Comment by JEEVAN28** [comment]
Hi,

Is this added in Yetiforce 5.30 ?

Thanks in Advance

Regards
Jeevan Pendhari
