### ISSUE TITLE
[Feature request] Documents module and related records

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#257]
It would be great help to be able to see all modules/records related to document. It could be in form of related list. Advantages are obvious. Similar solution was proposed and requested in vtiger many times but so far only CoreBOS implemented it as a standard solution.

**Comment by bpabiszczak** [comment]
I don’t think it is a good idea. Such solutions have more disadvantages than advantages if we look at it from a business perspective. The ability to relate documents to modules or records should be possible in locations where there is a business explanation for it. If you think that such relation should be added to a certain module, write to us about it, because we won’t join the documents with everything in the system.
