### ISSUE TITLE
problem with system acess over https

### ISSUE THREAD

**Issue by myexmyoki** [YetiForceCompany/YetiForceCRM#2580]
Need help.I created a self signed SSL certificate  for testing my yetiforce crn server.however after running the crm system over https,login and other components work fine but can't log out as logout prompts to open a php script(index.php) and logout action is not executed.vtiger crm is working fine with the same.kindly help

**Comment by myexmyoki** [comment]
I'm using Ubuntu

**Comment by bpabiszczak** [comment]
SSL has nothing to do with YetiForce operating properly. Keep in mind that if you install the system at http, and then change it to https, you must also change the system configuration [eg. in config / config.inc.php].

If you get index.php file then it's an error in apache configuration, and you should consult it with the admin [it might happen due to some application error, but the administrator should tell you what's wrong].

I don't know if you noticed, but our systems are always configured at https. For example: https://gitdeveloper.yetiforce.com/.
