### ISSUE TITLE
Ideas For 2016

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2585]
Another Quick Photoshop for yeti and how it should be in 2016 ! :-)
happy new year!

![yetiv5](https://cloud.githubusercontent.com/assets/6897502/12147849/ccf1ab6a-b4a3-11e5-8b38-fd3a513703c4.jpg)

**Comment by reeid** [comment]
Said before: related tabs should not have icons. It looks messy. Try without guys...

**Comment by eptapsyxos** [comment]
Clock In Clock Out for User for all the working day or
The same could be usefull on contacts vendors projects etc...
(idea from bitrix24)
![clockin-clockout](https://cloud.githubusercontent.com/assets/6897502/12148136/8448886e-b4a5-11e5-9648-c3b716256d25.jpg)

**Comment by eptapsyxos** [comment]
Notification Budge for new Records on menu and + (plus/add symbol) on the right for new record creation.

![menuimprove](https://cloud.githubusercontent.com/assets/6897502/12149144/bc5cb98c-b4aa-11e5-9c1d-853d8dfa10cd.jpg)

**Comment by florek41** [comment]
@eptapsyxos - for me most of those screenshots are overdesigned. I don't mean that is wrong idea but I think we need describe that idea instead of making designs. Actually I have no idea for what is "Clock In Clock Out", how works "Task Timer", seriously you need time/date display in CRM? etc. But I agree there is a lot of things which can be developed into YF :)

@reeid 
try add 
```css
.relatedNav .iconModule {
    display:none;
}
```
at the end of css file
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/layouts/basic/skins/twilight/style.css

**Comment by eptapsyxos** [comment]
@florek41 clock in clock out make a free account on bitrix24 and check it out :-)
you are right i had to describe the ideas to be more specific.

**Comment by bpabiszczak** [comment]
It's great that you want to improve the system's appearance. The appearance will definitely keep evolving and changing. The current one is more of a initial project, so all the following changes will be thought through and we will consider the UX. Your idea is mostly just adding things because they look good... but in reality it isn't that simple, because you have to look at it from the perspective of 60 modules. Changes are global – so we have to think globally.

When we create something we don't want it to just “be”. We have to think whether whatever we want to add:
1. is really necessary?
2. can it be done in a simpler way?
3. can we do better?
4. is this really the right place to present the information?
5. where do we get the data for the info we want to present? 
6. are the data we get stored in a way that allows for searching from pdf, filters and reports levels?
7. etc

I don't want to discourage you, but I want to show you that if you want to present too many changes in one place, and these changes aren't properly described and justified, then it might turn out that none of them will be introduced, even though they might be necessary from the business point of view.

I'm closing the issue, got nothing more to add in here...
