### ISSUE TITLE
[Improvement] Facebook integration

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2607]
A module called Facebook conversations would be nice. Conversations should be from fb page. Modules position inside crm should be simillar to Email's. 
From fb module we could relate conversations with contacts an opportunities. 
FB module would be a real giant step forward.

**Comment by eptapsyxos** [comment]
Zapier would be better.

**Comment by nikdejan** [comment]
Unfortunately, Zapier doesn't have too much integration options with Facebook. As Trigger App you can choose only Facebook page, and there only trigger action - when someone posts something on your page.
Nothing about fan page messages and conversations in Zapier.
On the other hand, there is very nice Facebook api for handling fan page messages: https://developers.facebook.com/docs/graph-api/reference/v2.5/conversation/messages

**Comment by bpabiszczak** [comment]
We want the system to be integrated with various social networks. Currently it's not our priority though, because it's more important for us to build a good marketing module. That's why I want you to know that this integration will take place, but what it will look like, or when exactly it's gonna be created, and what networks will be connected - it's still too early for these discussions.

Might turn out that this integration will be built in a year, so it makes no sense for this issue to stay opened for a year. If there's a customer who wants to pay for this integration, then it will obviously appear earlier [just like all the other hundreds of functionalities].

**Comment by nikdejan** [comment]
Fair enough
