### ISSUE TITLE
Menu improvement

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2623]
Current menu/submenu sliding right function is not aesthetic nether functional.
I suggest to organize menu in the way as MYC did it. Moving screen right/hiding AND covering working area just disturbing too much. Also fact that submenu is activated on hover is a bit uncomfortable. Click and keep submenu open is much better solution.
See here if you don't get my suggestion:
http://demo.makeyourcloud.com/vtiger6.4/index.php?module=Potentials&view=List

**Comment by waran70** [comment]
Right. Also too much gfx elements.

**Comment by bpabiszczak** [comment]
I just logged on the MYC website and their menu works in a quite similar way to ours - hovering on the icon expands the whole menu. Another thing is that the appearance is a matter of personal preference. There are people who think this is better, and some others who think this is worse. I don't see the point in changing that, because it's OK in my opinion. But this is open source, you can create your own menu, enable switching between menus in the panel, send it to us to add to the engine, together with the declaration that you will keep developing this version of the menu every time we change our version [so it doesn't turn out that we will have to support two different menus].

Your point of view didn't convince us... so I'm closing the issue. If you want too add something new to the discussion I can reopen it.
