### ISSUE TITLE
Creating YetiForce software was possible thanks to the open source project called Vtiger CRM and other programs that have open source codes.

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2644]
This statement can be removed. Eating space and to be honest, it nothing good to inform people of source of YF - like vtiger erased pretty all info of sugarcrm.
Here also coming issue with naming tables and other ...

**Comment by limor1** [comment]
Being a derivative of vtiger sounds much better than yet another opensource CRM. There are some 100 opensource CRMs. We have evaluated around 15 CRM systems and chose Yeti because it has Vtiger features in addition to having some active development in Github. Vtiger is a recognized brand. Vtiger CE is still in development and Yeti can benefit from expanding on Vtiger for the foreseeable future. If anything I would change the statement to imply that YetiForce has taken over where Vtiger CE stopped (like suiteCRM [states](https://en.wikipedia.org/wiki/SuiteCRM) with regards to sugarCRM and ERPNext states with regards to Oodo/OpenERP).

**Comment by zebrahosting** [comment]
YetiForce software was possible thanks to the open source projects like Vtiger CRM ?

**Comment by waran70** [comment]
True, English is also a bit invalid here.
It like thanks to particular cow for the milk included in yogurt... if
there is no legal implications, such statement can be hidden in the code
only

**Comment by bpabiszczak** [comment]
Before I answer your question, I need to ask you something. Did people, who take part in this thread, read and understood the licenses which we inherited, e.g. VPL, SPL or YFPL? If so, I can continue the discussion. If not, there is nothing to talk about.
