### ISSUE TITLE
Mass mail

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2653]
Is it true that mass mails with a template are still not working in the newer versions?
Tried dev version on yetiforce (error)
Tried on an upgraded 2.3 version 1008 (blank screen)
Tried on fresh install of v1008 (blank screen)
Now I read that the main implementation will be in v2.5?
Hope that at least this minimum mass email system will start working in v2.4
Couldn't use the CRM for months now because of this.
I see a lot of nice work and improvements and understand that priorities need to be set but bookkeeping before email marketing in a CRM?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1478

**Comment by zebrahosting** [comment]
I think it is important to understand that in the link you added , you mentioned it would work in v2.2, than it became 2.3, 2,4 and now I see it in 2.5 (may be?)
As said I understand priorities and how things go when the actual coding is done.

I have started to advise clients to use Yetiforce, installed it for some. Now I have to tell them that the functionality they need is broken and will not be fixed for another while. The whole UI starts to look great, what is made new is working well it seems. But please take a short time to at least fix things like the not working email template with the email system. Errors look bad to clients.
This issue is from July 2015!

As said I understand that from a coders point of view, you look into the code and think, we can do better, lets make it from scratch. You are right about that and proofed it. But since all this re-coding takes more time than anticipated we are stuck with this not working email system. 

Please see if it is not possible to look into this and make the bare minimum working in v2.4.
Use an email template (with the variables) to send emails out.
If not possible I have to disable the modules and deal with all the helpdesk request why it is not working.
Since YetiforceCRM is out of beta and companies start using it, I think it is not a good idea to degrade functions before the new alternative is active.

Just my 2cts.

**Comment by reeid** [comment]
I would love to believe that once code of YF will stabilize and no more giant changes will be introduced than some of developers will start writing commercial extensions (such a robust email marketing) This is actually reflecting popularity of open source. Is there anyone here who planning it?

**Comment by zebrahosting** [comment]
@reeid: absolutely true but that point is not there yet. Guess when YetiforceCRM is finished it hardly needs anything else :-)
I am also convinced that Blazej  and team will create a very good mailing module somewhere later this year. No doubt about that.
It's just that at the moment there is a module causing errors and malfunction in a production app and in my opinion this should be avoided in this stage. It has also been on the bug list time and time again.

**Comment by bpabiszczak** [comment]
@zebrahosting 

1. An important business rule is not to promise things we cann't control. So please, don't promise your customers any changes that aren't there and might never be. Because we can change our mind at any time [just like what happened with WebDAV] and there's nothing we can do about it. Only our customers, who have received the order, and for whom we work, can accuse us of failing to meet the deadlines, if they don't comply with the schedule.

2. Unfortunately, I don't know what functionality you're talking about [what doesn't work for you], give me the issue number if you can. The entire mass mailing functionality is planned, but the exact date of its arrival will ultimately depend on our customers, at the moment it isn't a priority either for them or for us. If it becomes a priority for any of the customers, it will be a priority for us as well.

3. For the past few days we've been improving the whole mail mechanism [this has nothing to do with mass mailing] - the previous mechanism worked properly, but after the changes in the new version it required rebuilding, which we did. If you have any objections to the mail module, please report them on github. At the moment I don't see any errors, besides the language change in roundcube.

**Comment by reeid** [comment]
Ad 1  "Because we can change our mind at any time [just like what happened with WebDAV] and there's nothing we can do about it. Only our customers, who have received the order, and for whom we work, can accuse us of failing to meet the deadlines, if they don't comply with the schedule."

So I ask than - is it open source? How you can call that if you without any consultation with community, without even considering them - changing core functionalities?  Once you declared it "open source" you should respect some basic rules. Some guys may work here hard, contributing to yetifirce code, and they should be afraid that you dismiss their time spent without mercy?

I do appreciate work you did so far, but such statement is not wise enough to be threaten seriously by developers. Your customers can not determine direction of open source app but agreed with community approach should be on top. 
Keep good standards and if you want changes for own customers set separate repositories for them. Somebody call you here to strength core functions. So far you adding more and more modules what should not belong to the base....  leave space for developers (and yourself too) so they will create modules and extensions... this is where you got money from yes?
Now answer yourself what CRM should be equipped with to allow professional interaction with customers. Here is base and here is what MOST of devs and end users requires.  

Your position is not convincing many guys to carry on with yetiforce. Me too, but once you start understanding I will start contributing, not earlier as I dont wanna waste my precious time. 

Regards

**Comment by waran70** [comment]
So errors reporting is not a contribution....?
---------

**Comment by zebrahosting** [comment]
Dear Blazej, please don't treat me like a child. I am CEO of several companies and work in this business for more than 35 years. I know how to talk to my clients.
If they ask me what CRM to uses I have choices based on my experience, tests etc. At some point I have to advice them that Yeti might be a solution but that it is unfinished and therefor a risk. At the same time I think it is promising enough and it was also functioning well enough to start using it. 
Many have asked for a roadmap for that reason.You have tried to outline the plans and adjusted them. That is fair enough since you do all the dev work. At the moment het is impossible for others to really help in this setup because of this but we patiently wait for an end of the big changes.

If every error reported or question asked is treated as a personal insult it is hard to give proper feedback. Those might be part of the cultural differences and characters but please be  a bit gentle and open to others that try to help, even if that is a little outside how you train your own people. We all want a good CRM and many here do so by reporting problems and suggest improvements.
We all have followed you from the mailinglist to the GIT system that also changed a few times. We are still there.

To go back on topic:

Go to Databases -Email templates and create a new email template.
Lets say it starts with Dear #xxxxxxx# (first name variable)
Save and go to a contact. Send an email and notice that the variable does nothing else than showing itself.
This happens in just sending a single email from template and it happens in selecting people in a contact list and sending them all an email with template.

For now I can work without a full working mass email system, (we just export most and import it to Acymailing) But getting the template system back in working order is crucial for us. It used to work and I tested this in your demo setup and in several of my own. Hope this is a simple fix.

**Comment by zebrahosting** [comment]
I have been digging a bit more: when I create a workflow with the same email template and let it be send to a contact the variables work fine. So it seems (note: careful wording) that using the mass email function does not trigger the right userid of what ever links it to that contact name. This is also visible that the selected contact name does not show up in the generated email in roundcube.
The base variable system is working, it is just not with the direct mass email option in the contacts itself.

**Comment by bpabiszczak** [comment]
@reeid

What does Open Source have to do with the community? Open Source means only that all we offer [in this case – YetiForce] is open. It certainly does not determine what the community around the project should look like! To make it clear, because many people, including you, seem to have some problems understanding the community: YetiForce Ltd [company] is not here to satisfy people's whims; our priority is the prosperity of the project, and we choose the direction of its development. You, as the community, can develop, use, implement, and do whatever you want with it, as long as it's permitted by the license, but you have no right to expect us to do something that you don't feel like doing.

We're not your development team, if we don't consider some of your requests beneficial for the project, or we see them as low priority, then any open source project gives you the chance to add it on your own. And if you don't like where we're going, then you can create your own version of the system, and develop it the way you want!!! This is the power of open source... contrary to the belief of some people, that open source means a company that fulfills your company's objectives for free.

Our project isn't the only one on the market. You can choose from coreBOS, Vtiger, SuiteCRM, SugarCRM, etc. You can also pick a commercial system for your company.. but please, don't tell us what to do, and how to do it, because ultimately, it's not you who pays the people who create this system. Be thankful for what you got, and in case you don't like it – you can find a better project, and we definitely won't resent you for doing so. We'll keep developing a great system that will always remain open source.

@waran70

Of course it is contribution!!! and a very important one, but programming is still more important. From the perspective of the entire project, I'd estimate the community's contribution to be around 3 – 5 %, so it's not huge enough to let the community decide and demand things from us. If someone comes around, reports 30 issues, then despite his contribution, he won't tell me what to do! Once the community starts contributing as much as we do, then we can think of voting for projects. And even if this doesn't work out – nobody is going to stop you from adding new functionalities. The community can have its own roadmap, can develop the functionalities they consider relevant, we won't dictate the direction of development, we'll only verify the validity as far as logic [of the entire project] and code quality are concerned.

@zebrahosting

Just like someone once said, I'm not a marketing person, and you will only ever get the truth from me. It has its advantages and disadvantages, and it will remain this way. Note that a lot of people don't discuss deadlines, functionalities, or the means of communication with us. What they do is help to develop the system, @florek41 for example. He's got his opinion on many issues, and I'm certain we don't agree on many more, but we have different goals, different priorities, and we have to respect that. I don't force anybody what, when, and how to do things. Unfortunately, part of the community believes that we will realize their internal objectives, and that's not going to happen.

If you expect something that is important to you, and we don't want to do that, or we simply don't have enough time, then why don't you hire a company, or developers, to create that for you, and why don't you just add it to the system? Why do you expect more from us, than from yourselves?

I do appreciate everything each and everyone of you does for the system, but don't expect us to realize your internal goals and your internal priorities in return. We do all we can to release a stable and fully functional system as soon as possible, but some changes and features require more time and energy. You look at the project from the perspective of a few days or weeks... we look at it from the perspective of months and years.

Regarding your error – create a separate issue, and mark it as important. I'll take a look at it and decide what to do next. This issue is no good for that.

--------------------------------------------------------------------------------------------------------------------
Ps. Mail module has been rebuilt, in 2.4 we will only fix found errors, so I'm closing this issue. If you have ideas for more cool functionalities related to this -  open new issues, however, we're not going to realize them sooner than in a few months from now.
