### ISSUE TITLE
Login to CRM Issue

### ISSUE THREAD

**Issue by Seitrafficonline** [YetiForceCompany/YetiForceCRM#2663]
Hi
by trying to login to the system crm10.elittebinary.com im getting the following message Invalid username or password. all configuration has been done correctly with latest stable version.
Can you please tell me what is the issue
Thanks

**Comment by waw555** [comment]
Test use

admin
admin

**Comment by waw555** [comment]
It's work ))))

**Comment by Seitrafficonline** [comment]
lovely. why it didnt work with my credentials? i can change username and password?

**Comment by Seitrafficonline** [comment]
working well.
thanks

**Comment by waw555** [comment]
yes, in user settings

**Comment by kjradv** [comment]
hello, perhaps there was an error during installation  #2651

**Comment by kjradv** [comment]
hello, perhaps there was an error during installation  #2651

**Comment by waw555** [comment]
This bias, it always happens, starting with release 2.3

**Comment by kjradv** [comment]
возможно ты прав, просто несколько раз ставил на различные конфигурации веб-сервера, была одна и таже ошибка в связи с чем настройки пользователя проливались по дефолту

**Comment by waw555** [comment]
In the native language, please write in a personal, then in English only (На родном языке, просьба писать в личку, тут только на Английском)

**Comment by kjradv** [comment]
no problem:
maybe you are right, just put a few times on various web server configuration, it has been one and the same error in the connection settings by spilled by default

**Comment by bpabiszczak** [comment]
We checked it multiple times and the password setting during the installation works correctly. There is one case why you cannot login to the system with your own password but you can with the admin password – it is when the installation has not been completed correctly because the last thing that the system does is changing the password. If your password didn’t change, it is necessary to check in logs whether this error occurred during the installation.
