### ISSUE TITLE
QuickCreate duplicated functions

### ISSUE THREAD

**Issue by playmono** [YetiForceCompany/YetiForceCRM#2704]
Hi Yetiforce,

I need to code a function working in a custom module EditView. I need this behaviour in EditView and QuickCreate from other modules, since for me, it's the same if I create a new Record from EditView or I create a record from QuickCreate.
![comissions editview](https://cloud.githubusercontent.com/assets/1773174/12780939/6d1b8470-ca71-11e5-924b-ebf55609521b.png)
![comissions quickcreate](https://cloud.githubusercontent.com/assets/1773174/12781000/dd273b7e-ca71-11e5-9b5f-0404abfd97d5.png)

To achieve this, I studied how works the field "all day" in Calendar Module since it does what I want. A behaviour in EditView and QuickCreateView. My surprise is, to achieve this, function is duplicated.

For EditView, function is:
https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/layouts/vlayout/modules/Calendar/resources/Edit.js#L270

And for QuickCreate function is:
https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/layouts/vlayout/modules/Vtiger/resources/Header.js#L344

As you can see, function almost do the same: this cant happen. In addition, every time you open a QuickCreate, vtiger is running the function "toggleTimesInputs" which makes no sense.

Finally, I tried to resolve this but I think it's a very core problem (Trying to avoid Header.js) and I think YF team should bring official solution.

Thanks.

**Comment by mariuszkrzaczkowski** [comment]
I removed redundant code. 
In order to achieve a similar effect to toggleTimesInputs, you have to add your own function to registerBasicEvents
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/layouts/basic/modules/Calendar/resources/Edit.js#L300

Create Edit.js file and add your code in registerBasicEvents.
Then the function will be triggered in full edition and in quick create.
You don't have to add the code to Header.js, and if there's something you can't do this way then we'll add some new mechanism.
