### ISSUE TITLE
Beste way to keep up to date with producton CRMs

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2706]
Just noticed that Milestone 2.4 moved again one month to March. This brings me back to the issue we discussed before:
How to keep up to date with production CRM's?
We discussed having patches in between Milestones but that happened only a few times.
SInce there are no patches it is tempting to just run the updater files now and then, fooling the versions number back to 2.3.0 to be able to run them.

Not sure how and if this will keep working for a final version. I assume the updater checks on existing tables and modifies when needed?

Why not wait?
V 2.3 has been out for a long time and some of the issues fixed / added are really important to us. We also have issues that are solved on github but can't wait for months to get implemented. 2.4 was originally scheduled in December.

Would be great to know if the 'in between' updates are more or less safe to apply in a production environment. I have been testing this and it all seems fine on our dev systems.

Blazej can you chime in and help with your thoughts? "Officially " you want us to use the milestone versions, but is there a road in between?

**Comment by bpabiszczak** [comment]
1. Currently [from the very beginning of YetiForce] we introduce fundamental changes in the system and it slowly starts to look like we're at the end of that road... it's just gonna get easier after that. Unfortunately, it's impossible to achieve that using small steps, too many things had to be removed, added, replaced, which is why these systems differ so much, and why monthly updates tend to complicate a lot.
2. Note that Vtiger releases updates once every 6-8 months and they don't really introduce too many changes. It's been less than 4 months since our last stable release, and the delay results from the amount of key changes in the system [more than 1100 revisions].
3. We use the DEV version in production environments, but when an error occurs we can simply fix it. We know what works and what doesn't in DEV. Users who are unaware of what the DEV version includes shouldn't install it. When a problem occurs we repair it, are you also able to fix it? As a developer, we recommend using only the STABLE version.
4. Updates are made to work for each version in the branch, and they're ''resistant'' to using the Z version - for example, you can install the same update several times and it shouldn't affect the system. However, according to this article: https://yetiforce.com/en/implementer/installation-updates/138-yetiforce-number-system.html we only recommend using stable releases and the Z version updates aren't supported by us.

In my opinion: 2.4 introduces a ton of changes. It requires around 2 – 3 more weeks of hard work. Then all the following changes will only improve the existing functionalities and slowly develop new ones. I think only companies that employ PHP programmers with vast CRM knowledge can use the DEV version, otherwise you can easily get discouraged by an unfinished version. This week we'll finish two key mechanisms: 
1. Finances [around 7 modules]
2. Storage [around 6 modules]
Once we finish them, we will test them, check for bugs, and move forward to the stable version.

**Comment by mykljohn** [comment]
Hi, what is the status of the stable 2.4 version?  We're patiently waiting.
