### ISSUE TITLE
[bug] - qoute

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2729]
![image](https://cloud.githubusercontent.com/assets/11491482/13002568/b7b08936-d16f-11e5-8423-487b8e743647.png)

**Comment by rskrzypczak** [comment]
The mentioned issue was most likely fixed in this commit https://github.com/YetiForceCompany/YetiForceCRM/commit/8d80a94ea6e6ed91a5cf3af1f896c0522d88a1db .
The width of columns in this block is configurable
![widthcolumn](https://cloud.githubusercontent.com/assets/10221999/13042964/230fac32-d3c5-11e5-876f-be86524b12c0.jpg)
