### ISSUE TITLE
[bug] - credit limit cause issue with saving qoute

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2777]
If there is not or is adjusted credit limit it cause issue with saving qoute...
Current developer version - demo...

![image](https://cloud.githubusercontent.com/assets/11491482/13872839/8103b162-eced-11e5-8e8f-8df564853fff.png)
![image](https://cloud.githubusercontent.com/assets/11491482/13872872/b8dd73c0-eced-11e5-8d42-163393a69f0c.png)
![image](https://cloud.githubusercontent.com/assets/11491482/13872821/6c75733e-eced-11e5-985d-19383ef5e973.png)

**Comment by rskrzypczak** [comment]
EN:
If the related account's credit limit is higher or equal to the sum of products in the quote,  then the record will save. Otherwise the message will appear and it won't save. 
If you don't want the related account's credit limit to be checked, then  you can disable that field in account.
The credit limit is limited to 4294967295
PL:
Jeżeli powiązany kontrahent posiad limit kredytowy o wartości wyższej lub równej niż suma produktów na ofercie, to rekord się zapisze, w przeciwnym razie wyskoczy komunikat i rekord się nie zapisze. 
Jeżeli nie chcesz by był sprawdzany limit kredytowy powiązanego kontrahenta, to możesz po prostu wyłączyć to pole w kontrahencie.
Limit kredytowy jest ograniczony do wartości 4294967295.

![creditlimits](https://cloud.githubusercontent.com/assets/10221999/14910804/04538776-0df1-11e6-9d38-528d6ab5196b.jpg)

**Comment by galciu** [comment]
Ja mam podobny problem, tylko na fv proforma,
nawet jak wybiorę "gotówka" to i tak mam komunikat że przekroczono limit.
Przecież do proformy nie powinien być brany limit kredytowy, gdyż to jest FV proforma, a tym bardziej gdy wybierzemy opcję gotówka (Przy zwykłej fv chyba też tak jest że wybierając gotówka sprawdza limit kredytowy).
