### ISSUE TITLE
[bug] - sending quote via email - missing attachment

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2794]
current vestion of dev demo 2.3.1598

during sending qoute via email there is not attached file... 
![image](https://cloud.githubusercontent.com/assets/11491482/14029260/5b4b0a42-f201-11e5-9c6b-34fa96ff14d4.png)

PDF and email templates created and exist...

**Comment by rskrzypczak** [comment]
It's working now, most likely due to these 2 commits: https://github.com/YetiForceCompany/YetiForceCRM/commit/a44cfc175bd0b83e1f1c2bdbc3f0a6740f336b9b https://github.com/YetiForceCompany/YetiForceCRM/commit/c2e760501ae0e8552b0b9c16b43dabdd44bbddd7

![send_via](https://cloud.githubusercontent.com/assets/10221999/15214508/c114f104-184d-11e6-8d02-ef9a712c9774.gif)
