### ISSUE TITLE
Working Hours ISSUE

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#2802]
Hi All,
I have a issue when create Ticket in "Service Contract" and add hours to "Time Control"; "working time summary" in "Service Contract" dont display any Total Time and the same in "used unit" label.

 I did the test in Chrome and Firefox and safari, latest version both of them

![image](https://cloud.githubusercontent.com/assets/3030997/14114585/d9714350-f5ad-11e5-80d7-8e469a60d835.png)

![image](https://cloud.githubusercontent.com/assets/3030997/14114611/e85bce9e-f5ad-11e5-99d0-f3e7ab8f1b8c.png)

![image](https://cloud.githubusercontent.com/assets/3030997/14114622/f5d472b0-f5ad-11e5-9973-d796f179867a.png)

Thanks 4 all!

**Comment by skramanzia** [comment]
After add crontab vtigercron.sh only update "Total Time (Service Contract)". I have create one ticket.

![image](https://cloud.githubusercontent.com/assets/3030997/14120269/66ee588e-f5c8-11e5-8c44-4cef85211f55.png)

**Comment by rskrzypczak** [comment]
Hello,
The "work time summary" block has been removed in this revision (https://github.com/YetiForceCompany/YetiForceCRM/commit/5ca76479896f9d1d37f73bac830f2e44db56d271), because the time fields included in it are not supported by the working time calculating mechanism. Only one field, "Total time [h]" remains, which is related only to the working time in this particular module.

As far as "Used units" is concerned, the value for this field is calculated once some conditions are met. The conditions are, for example:
- proper value in "Tracking unit" field,
- "Closed" status in the related ticket record
-etc.

**Comment by skramanzia** [comment]
Thanks you rskrzypczak!
