### ISSUE TITLE
Q: Zyxel NAS OS is lacking php5-imap.so. Alternatives?

### ISSUE THREAD

**Issue by casati-dolibarr** [YetiForceCompany/YetiForceCRM#2812]
The Roundcube interface of Yeti requires IMAP support. Otherwise only sending of Emails from within Yeti works.

As an example all curent Zyxel NAS lack a complete PHP5 implementation. Before delving into PHP5 recompile with Entware-ng, I kindly ask for other ideas eg. using another Lib instead of php5-imap.so

Best regards

**Comment by paula-w** [comment]
In our opinion it's not a question to us, because it doesn't concern the YetiForce application itself, but rather the proper server configuration, and we don't provide support for these issues in here. We have an admin who configures linux servers and has RHEL certificates, but we charge for this kind of support. Your problem is generally related to configuration, so you can ask in here:  http://www.roundcubeforum.net/ or here: http://stackoverflow.com/, but the best solution would be talking to a good webserver admin.

Another thing is that NAS is not a good server for the CRM, because our CRM requires quite a lot of cpu resources, and NAS's cpu is usually weak, and 50% of of it is often used by NAS itself, in case of regular load. Use a hosting, VPS, or a dedicated server – we recommend the latter.
