### ISSUE TITLE
AcyMailing & Joomla User integration

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2815]
Hi,

Firstly, would you know if there are any extensions that can integrate Joomla users with yetiforce?
I did used to use Joomtiger with Vtiger, which basically sent new Joomla user registrations into the Vtiger leads table. I have tried to use their latest version with Yetiforce but it no longer works. I think maybe because some file differences between Yetiforce and Joomla. I have successfully got their versions for Jomsocial (a community component for Joomla) to work with Jetiforce - that more or less worked straight away. 

Secondly, we use Acymailing to send out newsletters (this is also a Joomla component), and again I was wondering if there were any integrations that could synchronise newsletter subscribers with yetiforce contacts (basically just to keep the user's mailing preferences in sync i.e. if subscriber unsubscribes in Acymailing, then Yetiforce contact is shown as unsubscribed to a list.

On another note, where do I find the latest developer version, as have checked out your new demo site and would love to try it. Can I ask, can the menu bars be moved to other positions in the new version i.e. to the top, or are they now fixed?

My apologies if I should have made these 3 separate posts.

Regards

Percy

**Comment by KatarzynaUlichnowska** [comment]
Hello!
1. We don't know anything about any extensions for YetiForce, it's probably because we still haven't advertised the system, so not many people know that this system exists. 
2. The mechanisms hard-wired in Vtiger [webforms] aren't very safe, it would be best to handle such forms through, e.g. email parsing or direct access to an indirect table in which all data would be saved. In Vtiger, the file is enabled in CRM by default but the system shouldn't be accessible from the outside... not  even its single file. 
3. https://github.com/YetiForceCompany/YetiForceCRM
4. The menu might be changed with HTML/CSS/TPL. The engine is based on Bootstrap, so it's possible to change the look and feel of it to anything you desire.
