### ISSUE TITLE
[bug] Edit Field integer field

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#2850]
H
my ver 2.3.49
i create 3 field with type integer
after save record is ok and show my data at detail view:
![001](https://cloud.githubusercontent.com/assets/11961062/14526097/4d35d814-0256-11e6-8991-bc9eca4c7b71.jpg)

but not show at edit view and after save make zero value for  all integer new fields.
![002](https://cloud.githubusercontent.com/assets/11961062/14526114/6ec29404-0256-11e6-830d-1f919eed33e8.jpg)

**Comment by TomaszQr** [comment]
The error doesn't exist in the current version

**Comment by rskrzypczak** [comment]
Hi,
The error occurred because the database recorded redundant characters in quotation marks (").
There should be no "" values in vtiger_field in fieldparams column, once you delete them, the field values should appear in edition.
The error was fixed in: https://github.com/YetiForceCompany/YetiForceCRM/commit/42956bf2ad645f348e3b6b4f957a5d78c8c059d1
