### ISSUE TITLE
Missing Sales and Realization Process functions

### ISSUE THREAD

**Issue by elmarbransch** [YetiForceCompany/YetiForceCRM#2858]
Hi there,

I am testing locally against "git master" and online demo "git developer".
On both versions I am unable to do
* create an invoice from sales order (no matter what state the order is in)
* take over elements from sales order into projects (as stated in the docu)
* create an invoice based on an contract

In "git stable" I am able to generate a PDF from orders, quotations, but I am unable to send them by email directly from order or quotation management.
In "git developer" I am missing the PDF options completely

My main issue is to identify if I, maybe, understand the process incorrectly and need to search elsewhere for the functions. In the end they are not in the place where I would expect them or they are not available (at the moment - of course they have been there some time before according to the 2015 documentation)

thanks
-Elmar

**Comment by echemik** [comment]
+1 for create an invoice from sales order

**Comment by paula-w** [comment]
Hi,
1. Read this article : https://yetiforce.com/en/github/issues/126-issues.html
2. We strongly believe in our "one issue = one problem" rule, and we would like to ask all our users to follow that rule. 
3. Gitdeveloper yesterday and gitdeveloper today are two completely different systems, therefore it's always a good idea to let us know exactly what version you were testing.

The documentation will be updated, we think that most of the issues you reported were already fixed, but unfortunately we can't really do anything because the description is insufficient, check out the article I mentioned at the very beginning.
