### ISSUE TITLE
How i can install Customer Portal for version 3.0.0

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#2898]
Hello.
Please someomne tell me how to install customer portal. i don't know how to do this. Thanks !

**Comment by iaiox** [comment]
Same than others versions...

Check documentation in website

**Comment by noclav** [comment]
Here is what i did. I have my own Debian box so it may be different on your end. 
First i created a new Virtual Host name portal.domain.com
then i uploaded the portal files to the webserver. 
I reset permissions on files to 644 and folders to 775 and changed ownership to www-data. 
Then i setup Cron Jobs so that the vtigercron.sh runs every 5 min. then i modified the config and api files as per instructions. Next i activated the Triggers Generate Customer Login Details and send customer login details. Finally i setup the SMTP Server. 

Here is the website for the instructions. https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html
