### ISSUE TITLE
Yetiforce 3.0 installation not working

### ISSUE THREAD

**Issue by preexo** [YetiForceCompany/YetiForceCRM#2903]
I wget the package, untar, chown to apache user then call yetiforce. server error 500. apache log says:

```
[Mon Apr 25 15:47:46 2016] [error] [client 192.168.10.83] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: root_directory in /var/lib/shared/websites/custom/www/YetiForceCRM-3.0.0/include/ConfigUtils.php on line 140
[Mon Apr 25 15:47:46 2016] [error] [client 192.168.10.83] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Fatal error:  require_once(): Cannot redeclare class appconfig in /var/lib/shared/websites/custom/www/YetiForceCRM-3.0.0/include/main/WebUI.php on line 14
```

**Comment by preexo** [comment]
Huh... it magically worked when opening it in an incognito windows (seems like the vtiger session problems have not been resolved in yetiforce either).

Installation went through, then I get this:
```
Fatal error: Can't use method return value in write context in /var/lib/shared/websites/custom/www/YetiForceCRM-3.0.0/modules/Users/models/Privileges.php on line 438
```

If you are coming to the vtiger forums and advertising Yetiforce in every possible thread in the most rude way possible, at least make sure your own solution doesn't break at first try out.

Looking forward to a suggestion to solve this since I would be keen on trying out yetiforce in comparison to vtiger.

**Comment by KatarzynaUlichnowska** [comment]
Hello!
1. I love it when someone suggest a bug in the applications but wasn't even bothered to verify if it is true and it is a bug. 

2. If I remember correctly, the bug that you reported was about the wrong version of PHP [it should be 5.5 minimum and it's best if it is 5.6]. In our opinion, your server has not been configured properly. You can find a solution here: https://github.com/YetiForceCompany/YetiForceCRM/search?q=Can%27t+use+method+return+value+in+write+context&type=Issues&utf8=%E2%9C%93

3. We like discussions if they are substantive. It seems you don't know much about advertising because if we wanted to advertise something, we would do it on the official Vtiger discussions page as well as on LinkedIn and in hundreds of blogs/portals. The developer list doesn't have any marketing value to us. 

If you can't manage the installation of the system, then:
1. Use test versions:
- https://gitdeveloper.yetiforce.com/ - it resets every 12h.
2. Have the system installed by professionals.

**Comment by preexo** [comment]
I understand, thanks for the explanation. 
I suggest adding the minimum php requirement to the installation check, I should have not been able to install. 
I still wonder what caused the first error, but not too important I suppose. 

Our different view on you way of interacting with the vtiger developer list can be discussed via mail I guess ;) 

Will spin up yeti force on php 5.6 and check it out then, thanks for getting back to this.
