### ISSUE TITLE
[How to] Line item qty in relation tab

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2908]
In previous versions of YetiForce (2.0-2.1) was great feature what gives possibility to see how much pieces of product contains invoice/SO/PO without opening invoice/SO/PO by related tabs. Now only possible to check only usual fields not line items for relater columns in relaterd tab. Anybody can help with this?

**Comment by vovpff** [comment]
This is my explanation on ver 2.1.0
![rel_qty](https://cloud.githubusercontent.com/assets/8545791/14916275/4e7c00e6-0e21-11e6-88c4-c70206cd5131.gif)

**Comment by paula-w** [comment]
The new version of the system brought new modules, by default there's no quantity counting in these modules. 
It's due to the fact that the companies that use them never expressed their need for this feature when we designed the modules for them. This field might prove not to be very useful, because different products have different measurements [not only units], so summing them might not make much sense. The only thing you could sum is the number of items, not unit quantity. 
At the moment we are not planning to add this feature.
