### ISSUE TITLE
Recurrence in completed events

### ISSUE THREAD

**Issue by averied** [YetiForceCompany/YetiForceCRM#2916]
If create an event and mark it as complete, the event goes to historical calendar view. However, I can edit the event and setup a recurrence for this event, say every first monday of the mont till year ends.

Events are created in the calendar, but all are marked as complete. Does not make much sense. It should be created as new events, or at least I must be able to mark the event as in process again.

**Comment by paula-w** [comment]
Hi.
We need some more details.
What version are you using?
Does this error also occur in gitdeveloper?
It would be great if you could take a look at [our manual](https://yetiforce.com/en/developer-documentation/bugs/126-issues.html) for reporting issues, so that we can have all the necessary info right away when an issue is created

**Comment by averied** [comment]
Sorry.. I'm using developer ver. 3.0.17 for testing purposes.

Let me know if you need more details
