### ISSUE TITLE
Where to place feature requests?

### ISSUE THREAD

**Issue by sol2014** [YetiForceCompany/YetiForceCRM#2928]
Hello Everyone!

I'm new to Yetiforce and am not sure I'm in the right location but this is a feature request I have in mind. The Workflow doesn't allow us to create various entities such as Invoice. I wanted to create a workflow where an invoice is automatically created once a ticket is set to a specific status/state.
E.g. Closed/Resolved = Create an invoice to bill the customer.

Can Yetiforce do this already and I'm just not able to see it?

**Comment by paula-w** [comment]
Hi.
Thanks for your suggestion! 
We got tons of ideas daily how to improve the system as well... but not enough people to do that. 

As far as your question is concerned – You can create an invoice from a ticket, in order to do that you should: 
Create mapping here:  https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95  
add suitable workflow Workflow →  Create entity →  Get mapping from panel.

Unfortunately, using this tool won't let you create line items on the invoice, because this mechanism is used to generate records from similar modules (eg. Orders → Invoice). It can be developed so that it can generate a complete invoice, but right now we're not planning to do that. Unless there's a client who's gonna pay for this.

**Comment by playmono** [comment]
/offtopic
Sad to hear you dont have enough people. I suposse you dont have open positions, but in other case, maybe you can add a section in your website for this :)

**Comment by paula-w** [comment]
The case is slightly different - we do have enough people to work, we just don't hire people to fulfill every whim/wish/suggestion we receive. The things that we add to the system are either things we consider essential, or functionalities that someone ordered.
