### ISSUE TITLE
Unable to apply 2.3.49 to 2.3.1072 upgrade patch

### ISSUE THREAD

**Issue by nuno-robosavvy** [YetiForceCompany/YetiForceCRM#2942]
I'm currently running 2.3.49 and want to migrate to the latest 3.0.0

Starting with the first patch from 2.3.49 to 2.3.1072 I have the following error

Error!!!
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '225590-12' for key 'mix'​

**Comment by paula-w** [comment]
This error might be caused by several factors. When we migrate a system we check mysql and application logs in order to check what the script is trying to add [eg. you have the same user added twice to a field, and the settings in this field don't allow for that] and we solve the problem. We can't help you without accessing the system, and we unfortunately don't do that for free. You can use our paid support, or ask the vendor who installed your system to help you with the problem. 

Your problem is not common, if more people had it, it would be easier to fix it.
