### ISSUE TITLE
Is it possible to switch themes?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2950]
Hi,

in vtiger there used to be a theme switcher, is there one in yetiforce? I only want to change the lighter blue shade i.e. behind where the small logo appears above the menu to a green, everything else I like as is. I see there is a colour changer but this doesn't seem to affect that base colour - unless i am doing something wrong?

Percy

**Comment by paula-w** [comment]
Hi,
in order to change the menu colors you have to modify the style.css file. 

To change the background color, where the company logo is:
.userDetailsContainer {
 background-color: #4979aa;
}

To change the main menu color:
.baseContainer .leftPanel:after{
 background: #4a5364;
}

To change the submenu background color:
.leftPanel .nav .subMenu:after{
 background: #f0f1f1;
}

To change the header background color
.bodyHeader{
 background-color: #4a5364;
}

To change the footer background color:
.vtFooter p{
 background: #404952;
}

**Comment by PercyP** [comment]
Hi Paula, 

thank you so much, that was exactly what I needed.

Kind regards

Percy
