### ISSUE TITLE
vtiger 6.4 migration to yetiforce 3.0

### ISSUE THREAD

**Issue by preexo** [YetiForceCompany/YetiForceCRM#2966]
According to #1758 it was planned to be available sometime now, I would love to give this a try. Any news on this?

**Comment by vovpff** [comment]
@preexo If you want to migrate now it is more quicker to export data from vt and import to yeti. My data from vt 6.4 takes 3-4 days with preperation. New XML import looks like more comfortable and stable than CS import

**Comment by preexo** [comment]
@vovpff - thanks for feedback!

This means there is no official migration path, nothing during an installation of yetiforce anymore? I read Yetiforce staff writing there would be something on here before, but maybe they have dropped those plans then?

**Comment by KatarzynaUlichnowska** [comment]
Response from @bpabiszczak:
We planned to add it to 3.0 and we are still planning to do that... the problem is that such a migration script requires the minimum of 40 hours of work... and we don't have time for that, so we've been waiting for someone to pay for it :p We don't know either how many people would use it. Soon, a new 6.5 version is going to be released and it will require another migration pack. To be honest, migration packs are a nightmare from the programming perspective... and most migrations that we perform are from previous versions of Vtiger and in YetiForce 2.x there is a built-in migration pack for that.
If there are more people interested in it, you can buy this package together: https://shop.yetiforce.com/en/support/10-platinum-package.html and it will become our priority. If not, it will still have to wait.

**Comment by preexo** [comment]
I understand, fair enough. Thanks for the info.

From my point of view: It's hard to say how many people would be interested in moving on from vtiger > 6.4, but as long as there is no smooth migration path, I don't think it's going to happen at all.

**Comment by paula-w** [comment]
Thanks for your feedback.
You can migrate clients from Vtiger in YetiForce, but only up to version 6.2, and so far this has been enough for us, since all the clients who ordered migration used to have versions older than 6.3. Nobody ordered a paid migration from 6.3/6.4 so for us it's of a quite low priority. 
There were about 2 or 3 questions about it on Github, and that's not enough for us to devote so much work for that, especially that we don't have enough time.

**Comment by preexo** [comment]
@paula-w - fair enough. I was curious to try out yetiforce with our vtiger database, but we haven't decided on a migration. Once we did, we might even pay the extra dime :) if request is very low, then it doesn't make sense to implement this.

Vtiger users of 6.3 and 6.4 still have the exporting data and importing data again, I suppose.
