### ISSUE TITLE
Multiple quote module

### ISSUE THREAD

**Issue by natpicone** [YetiForceCompany/YetiForceCRM#3007]
Hi,
I need to have a second quote module with different detail item fields.
Is there a way to duplicate the quote module ?

Thanks a lot

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
I wouldn't recommend it to anyone because it requires broad expertise in programming. Such a module should be related to other modules... Creating a duplicate isn't a problem because the module can be exported, you can change names in files and that's it. However, it will be just the beginning of problems that you may encounter when creating such a module.
