### ISSUE TITLE
vtiger plugin compatibilty and php7

### ISSUE THREAD

**Issue by micker** [YetiForceCompany/YetiForceCRM#3015]
Hello i have a question before yetiforce migration :
does vtiger plugin work with yetiforce : PDF maker, EmailTemplates, ListView Colors 4 You
and did you optimize yetiforce for php7 ?
regards

**Comment by vovpff** [comment]
@micker PDF maker don't work with yeti without module deleloper optimisation for yeti.
Yeti has wery stong email templates module
ListView Colors 4 You - particullary implemented in yeti for this time.

Are you paurchased PDF maker Pro from Its4you? sorry for offtopic

**Comment by micker** [comment]
ok for pdf maker yes i buy it
ok for teplate module
listview is already inside ??

**Comment by vovpff** [comment]
@micker listwiew works for one condition per color without priority of conditions. #2987 #2988 #2989 my issues for this feature

**Comment by vovpff** [comment]
@micker give me your email or skype (some idea about PDFmaker)

**Comment by KatarzynaUlichnowska** [comment]
Hello!
1. Please add one question per issue. 
2. Vtiger plugins need some adjustment in order to work with YetiForce [in most cases it is enough to fix  the inclusion of files because we transfer files/folders within the system].
3. You don't need Colors4You in YetiForce because we have a similar functionality.
4. The same with EmailTemplates, there is a similar functionality.
5. You also don't need PDFMaker as YetiForce has a similar functionality. I doubt that the producer of PDFMaker will ever adjust it to YetiForce because our module is free and very complex. The situation was different in Vtiger because there wasn't anything in it and PDFMaker was the only solution. 
6. The new version of the system [3.2 or 3.3] should be compatible with PHP7.
