### ISSUE TITLE
Feedback update 3.0->3.1

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#3027]
Did some updates on several instances:
Brand new 3.0 install went fine
Very recent 2.4 install, already updated to 3.0 last month with not too much records and users, went smooth to 3.1 too

My own (test) CRM that started with the first versions and already did a troublesome update to 3.0 (missing key somewhere but fixed it in the DB) and now with 3.1 again issues.

Error:

#0 /var/www/vhosts/taoxxxx.xx/crm2.taoxxxx.xx/include/utils/CommonUtils.php(394): Vtiger_Deprecated::checkFileAccessForDeletion('cache/vtlib/use...')
#1 /var/www/vhosts/taoxxxx.xx/crm2.taoxxxx.xx/modules/Settings/ModuleManager/views/ModuleImport.php(146): checkFileAccessForDeletion('cache/vtlib/use...')
#2 [internal function]: Settings_ModuleManager_ModuleImport_View->importUserModuleStep3(Object(Vtiger_Request))
#3 /var/www/vhosts/taoxxxx.xx/crm2.taoxxxx.xx/include/runtime/Controller.php(89): call_user_func_array(Array, Array)
#4 /var/www/vhosts/taoxxxx.xx/crm2.taoxxxx.xx/modules/Settings/ModuleManager/views/ModuleImport.php(32): Vtiger_Controller->invokeExposedMethod('importUserModul...', Object(Vtiger_Request))
#5 /var/www/vhosts/taoxxxx.xx/crm2.taoxxxx.xx/include/main/WebUI.php(220): Settings_ModuleManager_ModuleImport_View->process(Object(Vtiger_Request))
#6 /var/www/vhosts/taoxxxx.xx/crm2.taoxxxx.xx/index.php(24): Vtiger_WebUI->process(Object(Vtiger_Request))
#7 {main}

Any clue what could cause this?

**Comment by rskrzypczak** [comment]
Update packages validate to some extent all changes introduced to the database, but they are not error-proof, as far as the errors that already exist in the database (or files) are concerned. The update script, no matter how meticulously written,  can't predict all database errors, whose cause is not always the CRM itself.  
I really don't know what could be the cause of your errors, but from what I can see your problem lies in the very beginning of the process, before the actual CRM update :)
Try cleaning your cache (especially the cache/updates file if it exists). 
Maybe its an error related to permissions.
It's hard to tell for sure where the problem is with so little information. 
YetiForce team can try to help you solve the problem directly, but it's a paid service.

**Comment by zebrahosting** [comment]
Just for others having issues: we debugged it back to the address book being corrupt.
It seems a good idea to clean all cache items before the upgrade.
