### ISSUE TITLE
POS demo

### ISSUE THREAD

**Issue by gokkstudio** [YetiForceCompany/YetiForceCRM#3040]
Where can I find POS module demo and more information about it?
Thanks

**Comment by paula-w** [comment]
POS is a mobile app for Android devices. The app works offline and synchronizes data with YetiForce. By default the app supports multiple storages, each user or catering premise can have different products. The app shows products with descriptions, pictures, and other crucial info divided into categories.
It's perfect for catering premises, restaurants, or train catering, which basically means - everywhere where orders are needed. It can also be used by sales representatives who visit their clients and place orders in real time.

In order to launch the app you first have to configure it and adapt to the client's needs [that's why the price includes our support]. Since it's quite expensive we want to make sure our users configure and use it properly. 

More details and screenshots can be found in our store -  https://shop.yetiforce.com/en/products/18-pos.html. Unfortunately we don't have a demo version of this app online, but we can make a short presentation over Skype or some other program if you want to see the app in action. 

If you have any additional questions I think it's best to to contact us via the store email - shop@yetiforce.com
