### ISSUE TITLE
Outgoing server gmail issue

### ISSUE THREAD

**Issue by mnevens** [YetiForceCompany/YetiForceCRM#3052]
I have installed (on a shared host) the latest release of Yetiforce CRM. I have following message when configuring smtp outgoing server for gmail: "Test Mail Status : Mail could not be sent to the admin user. Please check the admin emailid/Server settings"

Servername: ssl://smtp.gmail.com:465
Username + Password
checked requieres authentification

I can't find a solution in order to solve this issue.

**Comment by PercyP** [comment]
Hi mnevens,

I used the same settings as you on shared hosting (heartinternet) and they connect file. Are you using the full email address as the username?

Percy

**Comment by mnevens** [comment]
Hello Percy,

I use full emailadress as username

**Comment by PercyP** [comment]
@mnevens 

I am not sure, but do you need to enable imap in your gmail account? Mine just connects straight away with the above settings. The only other thing I did differently was to enable secure server in my shared hosting as this was needed to get the portal working - but not sure if it effects gmail access. I posted my solution here for the portal issue:
https://github.com/YetiForceCompany/YetiForceCRM/issues/2921

Have you tested your signin details on gmail and they definitely work?

**Comment by galciu** [comment]
Also try to configure individual smtp in roundcube settings (not global but on user mail)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
did you read the [article](https://yetiforce.com/en/github/issues/126-issues.html])?
We aren't able to help if we don't see logs, please enable them and see what's wrong.
Have you verified your data on our gitdeveloper server? You can create a fake gmail account for testing purposes. If it turns out that it works properly on our server, then consult it with your administrator and ask whether firewall doesn't block something.
