### ISSUE TITLE
Bug - Quotes

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3083]
Cannot search in Opportunity

![image](https://cloud.githubusercontent.com/assets/3030997/15720298/232cc2a6-280a-11e6-990c-59004d155bc9.png)

layout is not see great
![image](https://cloud.githubusercontent.com/assets/3030997/15720345/543d6698-280a-11e6-9dff-7f27122c0f29.png)

Not work Copy address From:

![image](https://cloud.githubusercontent.com/assets/3030997/15720385/8cf70d7c-280a-11e6-8bb4-2fe598a3275f.png)

![image](https://cloud.githubusercontent.com/assets/3030997/15720411/a9fadd04-280a-11e6-9f1b-de6b4d93a109.png)

Thanks

**Comment by paula-w** [comment]
Hi
Have you checked it on the [demo version](https://gitdeveloper.yetiforce.com) ? It seems to be working just fine there.

**Comment by rskrzypczak** [comment]
You most likely have some errors in the database, most likely :)
Enable logs, displaying errors and check what's wrong ([link](https://yetiforce.com/en/developer-documentation/engine/115-debugging.html)).

**Comment by skramanzia** [comment]
these errors occurred after update to 3.0 to the latest, update pack.

**Comment by rskrzypczak** [comment]
There's a possibility that something unexpected happened while updating, and part of the code wasn't executed, and since you most likely had error suppressing enabled then the update was provisionally successful. 
These are only my assumptions. Right now we don't actually know anything for sure. The error you described might be caused by various factors.
