### ISSUE TITLE
vTiger 6.20 migration to Yeti 3.1.0

### ISSUE THREAD

**Issue by IndysITDept** [YetiForceCompany/YetiForceCRM#3090]
I have written asking for direction to a 'How-To' on migrating from vTiger to Yeti and was directed to here.

Could someone please point me in the correct direction on how to move away from vTiger community version which seems to be dead in the support/dev arena.

Thanks

**Comment by vovpff** [comment]
@IndysITDept for this time you can only export your data from vtiger and import to actual yeti version.

**Comment by paula-w** [comment]
Migration from Vtiger to YetiForce is quite complicated. Theoretically speaking it's enough to download YetiForce, which has a built in Vtiger 6.2 migration [that's YetiForce 2.0 as far as I remember], and then you download all updates required to update YF to the latest version, namely:
- 2.0 → 2.1 → 2.2 → 2.3
- 2.3 → 3.0 → 3.1 → 3.1.247 

Considering the fact that both of these systems are highly configurable and are often modified, it might turn out that migration errors have to be analyzed. It takes several hours [about 4 ~8] when we migrate the system, but sometimes we stumble upon some more serious problems [eg. incorrect migration from 5.4 to 6.0, or from 6.0 to 6.1] and we have to devote more time to migration in this case. 
We can't simply describe it all in documentation, because each case has to be analyzed individually by a programmer, and it requires vast knowledge of Vtiger and YetiForce. 

All required files are free and available for example here: https://github.com/YetiForceCompany/UpdatePackages  
We also have a paid migration service in our store: https://shop.yetiforce.com/en/migration/14-migration-v23-v30.html.
