### ISSUE TITLE
Resource Module for projects

### ISSUE THREAD

**Issue by mojtabajml** [YetiForceCompany/YetiForceCRM#3095]
One of the important part of project management softwares is Resources. In this module we can define all resources and cost per units of them and use them for each task.
for example in ms project we define all of resource in a separate part with this fields:
- Resource Name
- Type
- Material Label
- Initials
- Group
- Max. Units
- Std. Rate
- Ovt. Rate
- Cost/Use
- Accrue At
- Base Calendar
- Code  
Then we can assign resources  for each task.So the cost of tasks can be calculated by task module and lots of useful reports can be generated for project managers.

**Comment by vahid-jml** [comment]
i think creating this module for project management of yf isn't a hard working. and this module is necessary for project management .

i have developed some module for vtiger and i think is not so difrent to  yf.i check the yf modules and If I could i create this module .

**Comment by paula-w** [comment]
We wrote a short article about ideas for new features : https://yetiforce.com/en/github/issues/206-system-development-ideas.html 
We think that what you described in the issue is already in the system, but works in a little different way. All the info (related to work, equipment, or resources) can be found in calculations, if we add employee's working time and the cost, then we have what was planned [quoted] and what was realized, and we don't need anything else. What's important, we have information and events continuity. The only thing that's missing is adequate relations, they will be added when we develop processes.
