### ISSUE TITLE
Arabic Language need to add

### ISSUE THREAD

**Issue by johntonji** [YetiForceCompany/YetiForceCRM#3153]
Can anyone help me add Arabic Language. Can I just import Arabic from vtiger

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, you cannot import Arabic from Vtiger, many language files have been changed and in fact the entire system differs from Vtiger. You would have to translate it from scratch by downloading the English language pack from YetiForce.
We will also require signing CLA. It defines the terms under which intellectual property has been contributed to our open source project. 
When you translate all language files, sign CLA and send all of it to us, we verify it and add to the system if everything is all right. 
Additionally, I hope you are aware of the fact that it is a very time-consuming process because the translations need to be developed all the time.

**Comment by johntonji** [comment]
Thanks for the info
