### ISSUE TITLE
Roundcube - email template variables get not replaced with values

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#316]
Clean installation of version 1.3.
When I click on an email address in Leads the roundcube compose window opens. If I then insert an email template that contains module variables e.g. shortname (#a#41#aEnd#). These variables are not replaced with the actual field value when send.
Recipient still sees the variable #a#41#aEnd# in his email

**Comment by amicheals** [comment]
Same issue here

**Comment by witer30** [comment]
I have the same issue, when trying to use email template there are some variables insted of requested names... when sent there are only #a#34343#aEnd#

**Comment by Jibe9191** [comment]
I have the same issue

**Comment by bpabiszczak** [comment]
Veriables work only when you click send email in a mail block in a record view [e.g. Opportunity]. Otherwise, the system doesn't know which data it should mark! In the latest version of the templates module we added a possibility to choose for which views a template will be available. It is a lot more intuitive.
