### ISSUE TITLE
How to user can change only password

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3166]
how to user which not admin can change only password but cant change information.

**Comment by vovpff** [comment]
#2915

**Comment by konadrian** [comment]
Just like in the example shown by @vovpff, you should change the variable found in  config\security.php to 'SHOW_MY_PREFERENCES' => true,

**Comment by vovpff** [comment]
@konadrian this is not so correct answer for @ezbank question

> can change only password but cant change information

**Comment by rskrzypczak** [comment]
There's a possibility to change user's password in menu, but for some time now it hasn't been working as it should. 
It was fixed in this commit: https://github.com/YetiForceCompany/YetiForceCRM/commit/115bde2b6c90185442a7dd1f86e61c2fa2d09ee4

You first have to set CHANGE_LOGIN_PASSWORD parameter to "true" in config/security.php file , but I think it's set like this by default. 
Now it's enough to add a profile to menu and that's it.
![profilemenu](https://cloud.githubusercontent.com/assets/10221999/16521928/98b3bd84-3f9a-11e6-87a8-8ffd6a4c3655.gif)
