### ISSUE TITLE
[Question] Calendar related list

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3172]
Guys tell me where to edit the related calendar list - "Company/Contact"

![screen shot](https://cloud.githubusercontent.com/assets/17310158/16456082/4e91cd6c-3e1f-11e6-9b8e-41266c5bab4f.png)

I want to add here a custom module.

**Comment by KatarzynaUlichnowska** [comment]
You don't want to do it ;) It is a very problematic change, which influences many mechanisms, including CalDAV synchronization. Additionally, many elements depend on this field, including integration bar in mail and many other systems. If you don't know how it works, it's better not to touch it. Unfortunately, we won't describe you how to change it because it requires a lot of modifications in various locations and even more testing. 

The question is: why do you want to develop it?
