### ISSUE TITLE
[Bug] Updates - no possibility to mark as read

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3179]
There is no "mark as read" button at records view and updates tab and qty of updates not appears at list view and summary for original Demo user, but visible another users:
![updates bit](https://cloud.githubusercontent.com/assets/8545791/16518406/3cfac67c-3f8b-11e6-98a2-198851fea808.gif)

**Comment by vovpff** [comment]
After update to dev  [ver. 3.1.441] firts time "mark as read" button appears only once. After clicking this button disappeared permanently. From another user this button does not appear at all

**Comment by rskrzypczak** [comment]
In my opinion it's okay. 
However, it was indeed  slightly modified  lately.
the history of changes is displayed in the way another user would see it.
You can't however "impersonate" the user you switched to, and that's why you cant review the changes on his behalf.
The author of all changes made on the user you switched to is the base user, that's why when you switch back to your own account you don't see any unreviewed changes in the "changes history".
