### ISSUE TITLE
OSSMail slows down yetiforce

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#318]
When I enable mailbox and sign in, after that, the CRM starts running really slowly. It seems when it tries to check for email, the entire system crawls.

Is there someone I can look to fix this. It's almost unusable.

**Comment by amicheals** [comment]
My page load times went from .27 seconds to

Copyright 2014 YetiForce.com All rights reserved. [ver. 1.3.96 RC] [Page loading time: 15.561s.]
Creating YetiForce software was possible thanks to the open source project called Vtiger CRM and other programs that have open source codes.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/optimization/107-connection-to-the-mail-server.html

**Comment by waw555** [comment]
And in Russian will do the instructions?

**Comment by bpabiszczak** [comment]
We don’t have anyone who speaks or writes in Russian in our company. It’s not enough to translate something once a week, because we are planning to add articles every 2-3 days, it’s a part-time job for a translator. Until we have a Russian translator, texts will be published only in Polish and English.

**Comment by amicheals** [comment]
thank you

**Comment by amicheals** [comment]
I figured it out.
Under mail scanner once you configure a mailbox, if you assign yourself as the user the system slows down. If you assign the mailbox to a grou . It works fine
