### ISSUE TITLE
proposal: send notification from comment

### ISSUE THREAD

**Issue by simonetravaglini** [YetiForceCompany/YetiForceCRM#3214]
Hi, why not insert possiblity to tag in comment a user and automatically this create a notification?

**Comment by KatarzynaUlichnowska** [comment]
- There is an automatic mechanism for notifications in the system and you can receive notifications about comments.
- There is a mechanism that allows to monitor records in accordance with their importance, so you receive notifications with all actions performed on records. 
- There is a mechanism that shows the number of changes on records list since you last login.

We can obviously add many more mechanisms but I suggest to start using the existing ones. We aren't currently planning to add this functionality because, in our opinion, users have a lot of other tools that show the same thing.
