### ISSUE TITLE
Google Calendar Integration

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3226]
Hello,

How can i send the notification from calendar to google calendar?

Something like this https://wiki.vtiger.com/vtiger6/index.php/Google_Integration

**Comment by paula-w** [comment]
Hello :)

YetiForce has a built-in integration with CalDAV [http://sabre.io/], every device [eg. Android, iPhone] or software [eg. Thunderbird, Outlook] can connect to YetiForce as long as they support this format. We don't know what it works like with Google, because we don't use Google. Most likely there are some ready made solutions available on the Internet. The biggest problem is that both, YetiForce and Google, are CalDAV servers, so if you are using YetiForce then what's the purpose of using Google as well?
