### ISSUE TITLE
email in leads and contact

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3236]
hi 
i set email smtp , mail scanner and cron settings and it work properly . so i can send and received email from a contact but in summery tap in email widget there is no email .

i test it in ver 3.1.564

**Comment by bpabiszczak** [comment]
1. Probably because the scanner wasn't enabled
2. Probably because nobody set what folders to scan after enabling the scanner
3. Probably because after enabling the scanner, and setting the folders, nobody selected suitable actions for scanned mailboxes
4. Were any mailfields selected, for the scanner to search relations by? 
I don't see any logs, no gif how to trigger it on gitdeveloper, etc.
