### ISSUE TITLE
One suggestion - Images in Lists & Filters

### ISSUE THREAD

**Issue by StaggerLeee** [YetiForceCompany/YetiForceCRM#3241]
Make it better than it was on Vtiger. They did not have option to set Contact/Account/etc images in different Lists.

I think personally it helps a lot when you get so called "bird´s view" over all your things, be it Profile Photo, logo, any image possible. With time lists tend to be just a collection of dull and boring letters and numbers, and one small image in list(s) makes huge difference to see quickly what is going on and not to lose much time.

I know one of the reasons it doesnt exist is List(s) load and pageload.
Make it hidden, optional. So anyone wishing to use it can activate it byself. Thanks.

**Comment by ezbank** [comment]
so hard

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html

**Comment by StaggerLeee** [comment]
Few sentences what developer thinks why it is not necessary would be fine. Dont answer like robots. No difference how those Indians behind Vtiger treated Users.

**Comment by bpabiszczak** [comment]
Don't take it so personally. My English is quite poor, and writing full sentences requires translations, that's why we close some issues this way – by giving the author a link to a relevant article that answers his question. And it's exactly what happened here. It doesn't matter how amazing peoples' ideas are, what matters is who pays for making them happen. Right now we are not planning to add this feature. It doesn't matter whether we like it or not, we realize tasks ordered by our clients as our priority, then we realize tasks that we believe are essential, and at the end we take care of user's ideas, that YetiForce can “live” without.

To save the time I don't see the need to make pretty sentences. GitHub is not a marketing/sales platform – it's working space. We got people who write and speak fluently in English, but I still don't see the need to write meticulous descriptions in each issue. The link I gave you provides you with the adequate answer. If you wanna talk or conduct a discussion I have no problem with that, let me know, I'll label the issue as Category::Discussion...

**Comment by StaggerLeee** [comment]
OK, it is better thanks.

Would like to see better way for us to make custom fields. That way we could take lot of work on ourself and make even Google Maps field. This one with image would not be difficult to make if I knew how to make it without messing with many core files.

All that is needed somehow is own custom field where we self can add "a" wrapper and possibly some PHP code inside wrapper, for "href" or classes.

For Google Maps for instance we could make self wrapper for Gmap URL, add own API KEY, etc.

And share it here for other Users, so you can continue to develop more essentiall things. (I know this with Image in lists is not essential).

**Comment by paula-w** [comment]
Thanks for the suggestions.
It would be best if you could create new issues for the ideas unrelated to your main question if you want to talk about them, especially the one about maps, and the one about a new feature. Otherwise it'll get pretty confusing when we start discussing several ideas in one issue.
