### ISSUE TITLE
Understanding Gantt Charts

### ISSUE THREAD

**Issue by rickscherle** [YetiForceCompany/YetiForceCRM#3329]
Hi! Thanks for all your hard work on this project.

I just installed it and am trying to understand how it works. I'm having a lot of difficulty with the Gantt charts. They appear somewhat backwards of other Gantt implementations I have used. (For example, the milestone arrows point to the END of the tasks?) These are the types of charts I am used to seeing: https://en.wikipedia.org/wiki/Gantt_chart

Also, some of the functionality seems to be missing. For example, extending a subordinate tasks actual ending date does not seem to push the milestone.

And I can't really see a visualization of the slack time, or the critical path, and I can't see how to set up multiple dependencies.

Perhaps I just don't know how to use it. I checked all of the documentation I could find on "Realization" and I didn't find anything. Is there something written?

Or perhaps this module is not just complete? Or maybe you just have a different idea of what Gantt charts are all about.

Anyway, I would appreciate hearing from you on this topic. I have some clients who might be interested in this software.

Thanks again and very best regards.

**Comment by rickscherle** [comment]
![yetiforce-index-php-1470121831958](https://cloud.githubusercontent.com/assets/20788847/17320229/513a02e0-5847-11e6-974b-5953d2526463.png)

**Comment by serbiaserbia** [comment]
I am also intersted in "how to use gantt diagram" in projects,  task and milestone.
Any documentation or answers?
Best regards :-)

**Comment by KatarzynaUlichnowska** [comment]
1. We will verify the direction of arrows but it is currently not of hight priority. 
2. All actions in the chart require more coding, it means that if someone needs them and pays for them, we will add them. 
3. The process has not been optimized, so it may have some faults. We will surely optimize it soon, so we will verify critical paths and multiple dependencies. Then, a special documentation will be also created because, at the moment, there isn't any. 
4. The entire module will be certainly improved. Unfortunately, we don't know when, as it may be in a month time or even later.
