### ISSUE TITLE
Difference between table type choose - when creating new field?

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3344]
Can someone explain difference between:
1. Basic (eg.  vtiger_account)
2. Additional (eg.  vtiger_accountcf)
 when creating new field? 

What is difference in explatation  when selecting one of these?

**Comment by lamontef** [comment]
I spent a great deal of time searching for a solid answer to this question over the last two weeks and finally gave up having not found anything that clearly answered it. I settled on option '2. Additional', so that I wasn't having to come up with dbase field names and I wanted my custom fields in a separate table in the dbase. Hopefully someone has some insight on this one...

**Comment by KatarzynaUlichnowska** [comment]
In Vtiger, in some locations, fields are only taken from the main table (probably main search engine) and we tried to fix it everywhere. We don't see any point in dividing it into two tables (we always add to the main one) but such separation is important for larger bases where tables contain more data.
