### ISSUE TITLE
Convert Lead to Contact

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3355]
in /modules/Leads/models/Record.php from line 259 to 264

`/*
$contactFields = $this->getContactFieldsForLeadConvert();
if(!empty($contactFields)) {
$convertFields['Contacts'] = $contactFields;
}
*/`

I don't understand why these lines were commented.
do not allow the display of the conversion button from leads to contacts if the module accounts is disable or user not have the editview privileges on accounts module.

**Comment by rskrzypczak** [comment]
The piece of code you mentioned was commented, because for a very long time conversion from lead to contact has been blocked. As far as I  know this option will never be available.
If you want to create a contact based on lead you can use the mapping panel ([link](https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95))

**Comment by nic86** [comment]
Thank you for the explanation.
