### ISSUE TITLE
Error after testing latest update package - from 3.1.0 to 3.1.898

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3357]
I have just tried to test the upgrade from 3.1.0 to 3.1.898 and after installation receive the following error:

Fatal error: Class 'Vtiger_Link' not found in /home/mysite/public_html/crm/cache/updates/init.php on line 1508

**Comment by PercyP** [comment]
I forgot to mention, I had already updated to RC5 version yesterday, and I changed the version number back to 3.1.0 prior to running the update. After uploading and running the update the error appeared and it didn't update.

**Comment by rskrzypczak** [comment]
System update in a non-stable version (3.1.xx) is possible using an update package for YetiForce v3.1.247 or earlier. Significant changes in the source code were introduced later, therefore the script included in the update package is not valid. That's why you are getting errors when you're trying to update the crm from later versions.
