### ISSUE TITLE
Invoice Template

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3370]
Can you help me with an invoice template that looks like the attachment ?

https://www.google.ro/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjxkpGTiMbOAhWJvhQKHZFtA_4QjRwIBw&url=https%3A%2F%2Fwww.invoiceberry.com%2Ffree-invoice-templates&psig=AFQjCNFpmcDF5lbUf7TTkKuSLQ84yX4REA&ust=1471441289696047

**Comment by dextras** [comment]
Hi!
I do not have time to explain everything now but I can just tell you that you have to start with your own list of fields you would need to place on the invoice. Everything except the product list is quite straightforward to accomplish with the wizard included in yeticrm. Try to do the structure first (tables, position of different elements, etc) with dummy data, test it and then replace the dummy data with the actual variables. 

In order to have the list of products to look as in the invoice example you provided you would have to modify(or better - copy and make your own) special pdf function in (yourcrmfolder)/modules/vtiger/pdf/special_functions/ProductsTable.php.

Are you familiar with css/html and basics of php? If yes you should not have much problems. If not maybe you should consider asking vtiger team to help ? (you would have to pay them some $).

When I find some time I would like to prepare some tutorial on how to modify the products list to match people's needs. I do not know when it happens though ;)
