### ISSUE TITLE
[Question] Suggestion for the next version

### ISSUE THREAD

**Issue by michelmarques1** [YetiForceCompany/YetiForceCRM#3407]
Hello Colleagues Community.

I believe this is the right place to suggest new features for the next version of CRM.

First, I believe the YetiForce is one of the solutions more complete and functional CRM open source that exist.

Here are three suggestions that I think are interesting:

1) Change the name of "Custom Block"

Once created, we can not change the Editor the name of the Custom Block. It would be interesting that possibility.

![image](https://cloud.githubusercontent.com/assets/18095104/17912250/d5a80a04-6968-11e6-94c5-ccc0ab010ac5.png)

The next two suggestions are inspired by the mySAP CRM SAP.

2) Group customized blocks within a custom block.

Allow to insert a group of custom blocks, within another group, so that they are side by side.

![image](https://cloud.githubusercontent.com/assets/18095104/17912322/3c65454a-6969-11e6-91ce-8862abc4fa7b.png)

3) Grouped text fields.

I really like the way the SAP developed mySAP CRM and groups a set of text fields.

In the SAP solution, text fields are within a single custom block, we need to click a "New" button, select the text field you intend to fill and insert.

Once inserted, if we want to change, you have to click on the text entered and there will be a button written Add. The add button actually keeps the history of what has already been inserted, and adds more information to the field.

Ex:

![image](https://cloud.githubusercontent.com/assets/18095104/17912377/84c8938c-6969-11e6-8f50-a6565bc051a6.png)

![image](https://cloud.githubusercontent.com/assets/18095104/17912393/99ecfcf8-6969-11e6-899b-c3f4fd111e32.png)

![image](https://cloud.githubusercontent.com/assets/18095104/17912422/d0c63cf8-6969-11e6-90ab-3b265307fbd6.png)

**Comment by vovpff** [comment]
@michelmarques1 
1st - can be achived by Language Editor. Custom block name you transtate to any another name
2nd - this idea need a lot of time for modifacation of CRM GUI and vTiger core. This takes a lot of time.
3rd - solution is comments module (widget for summary view and tab for detail view)

**Comment by paula-w** [comment]
1. We can change the block in the panel, just like @vovpff said, or, what's more important, you can use composer [or loader, but loader will be removed at some point], then you can overwrite any file /translation at your own file level. Some more info available at https://yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html  and  https://getcomposer.org/doc/01-basic-usage.md. If you want to introduce changes from the panel, then they will be overwritten upon system update, when you use loader/composer they won't be overwritten. 
2. Redundant gimmick, none of our clients has asked us about it so far... The question is whether or not you're using the mechanisms that already exist in YetiForce, such as mechanisms that allow you to hide entire blocks according to set conditions [eg. The block will only show when you sill in the field]. The best answer to your question can be found here: https://yetiforce.com/en/github/issues/206-system-development-ideas.html 
3. I unfortunately don't understand the business logic in this one, why you need that, and why the solutions YetiForce offers aren't enough... The point is that we don't create tools and features because they look nice, but because they result from actual needs of our clients and community, and they are relevant as far as YetiForce's development is concerned.
