### ISSUE TITLE
Auto fill - field in Payment in

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3497]
#### Issue

I have added mapping in MappedField option,
Mapping is as follows
Module : Accounts
RelatedModule: Payment in
Field Mapped - 
Assigned_to (of Accounts) to Assigned_to (of Payment in)

#### Expected Behavior

I wish to autofill to do following activity
- field Assigned_to in (Payment_in) module same as that of related field value of Assigned_to in Accounts module. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by dextras** [comment]
Hi!
You have to give us more info. How does the system behave right now? (Actual behavior), How should it behave according to your needs (Expected behavior)? From what I understand you want it like that:

When you create PaymentIn from Account then the Assigned_to field in PaymentIn should be automatically filled with value from Assigned_to field in Account?
