### ISSUE TITLE
[BUG] Caldav iOS sync - No 'Authorization: Digest' header found

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3510]
version: 3.2.127

tested in gitdeveloper.yetiforce.com not permit to add caldav in IOS system

Address: http://gitdeveloper.yetiforce.com/api/dav.php/principals/demo/ 
User: demo
Pass: demo

in local installation in cache/logs/davException.php

```
============ 2016-09-08 12:58:19 ====== Error exception ======
exception: Sabre\DAV\Exception\NotAuthenticated
message: No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured
file: /var/www/yetiroot/libraries/SabreDAV/DAV/Auth/Plugin.php
line: 188
code: 0
stacktrace: 
#0 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /var/www/yetiroot/libraries/SabreDAV/Event/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#2 /var/www/yetiroot/libraries/SabreDAV/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#3 /var/www/yetiroot/libraries/SabreDAV/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /var/www/yetiroot/api/dav.php(82): Sabre\DAV\Server->exec()
#5 {main}
```

in htacces there are lines:
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

**Comment by mariuszkrzaczkowski** [comment]
"No 'Authorization: Digest' header found" it's not an error. IOS wants to first connect without authorization data, and only after that it logs with the authorization data, that's why the message appears.
I tested it on gitdeveloper, it works properly.

**Comment by nic86** [comment]
Thanks , I'll try

**Comment by nic86** [comment]
> IOS wants to first connect without authorization data

I do not understand how it could be done, when I add a CalDAV account in IOS the username and the password fields are required. how can I do ?

thank you

**Comment by ldgbc** [comment]
@nic86 Do you have any luck with the CalDav? I got similar error with yours. I don't want to use Demo because it might accidentally sync my phone contact.

**Comment by ldgbc** [comment]
Here some of the error.

Here the log:   davDebug.log 
[caldav-error-log.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/784857/caldav-error-log.txt)


``` other errors below:
`exception: Sabre\DAV\Exception\NotAuthenticated
message: No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured
file: /home4/(myusername)/public_html/websitename.com/libraries/SabreDAV/DAV/Auth/Plugin.php
line: 188
code: 0
stacktrace: 

```
#0 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /home4/(myusername)/public_html/websitename.com/libraries/SabreDAV/Event/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#2 /home4/(myusername)/public_html/websitename.com/libraries/SabreDAV/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#3 /home4/(myusername)/public_html/websitename.com/libraries/SabreDAV/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /home4/(myusername)/public_html/websitename.com/api/dav.php(80): Sabre\DAV\Server->exec()
#5 {main}`

**Comment by ldgbc** [comment]
So the initial issue showed that DavDroid did not work for me. I recently discovered that when I create a new contact the option is weird and different. The Backup option on my phone also show "DavDroid". So it seem like it did work.

I add a copy of contact. went onto my /api/dav.php and notice that information is populated. It did "sync" onto the server in some way. The menu let me download those vCard type but it not very useful since what I'm after is syncing contact of my CRM/Yeti with my phone so I don't have to add them twice(s) (1 on CRM and 1 on phone, another 1 on email client, etc).

I went into admin > integration > dav 
and notice that there a "numbers" on Contact. So Yeti is recognizing it. I checked my CRON and see that the Dav CRON is "running", it took quite long but didn't finish so I assume it refrozen and will need to investigate it.

Next I try searching on my CRM/Yeti to see some of these "Test" contact I been adding on phone appear on it. Couldn't find any.

From my experience I seem only able to do 1 direction sync (phone to CRM). I have yet to discover on how to make it CRM > phone.

Hopefully it doesn't delete my existing contact, I haven't made backup of phone in a while.

**Comment by ldgbc** [comment]
Hope that v4.0 Caldav work, I tried to copy related CalDAV/CardDav file from  v4.0 to me 3.4 version. 

It didn't work as planned, maybe I'm missing something or the code change is to great to cheat the system like that.

I looked at the CRON again and it still frozen at Running and doesn't changed.

#3778 @ahmido I wonder if you figure out on your system since we both using v3.4.21.

**Comment by nic86** [comment]
try this change in version 3.4.21 #3919
