### ISSUE TITLE
Search returns 0 results

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3524]
#### Issue
When I try the search box at top of page it always returns 0 results. I have tried this on 2 different servers and neither produces a result - even though the records are in the system.

#### Actual Behavior
Enter a search term, click search, returns 0 results.

#### Expected Behavior
Brings up records that match search term.

#### How to trigger the error
Search for a record you know exists in the system

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: chrome, firefox (latest updated versions today)
* Environment name and version: 
* Operating System and version:

**Comment by Raggazzoo** [comment]
Did you configure the cron task?

**Comment by PercyP** [comment]
@Raggazzoo 

Perfect! I needed to run the cron. I am not sure if this is the correct way to do it but I basically entered the full path to my browser and ran:

http://www.mysite.com/yetiforce/cron/vtigercron.php

I am not sure if this now runs regularly or if I have to create a cron in my cpanel section? I read [how to setup cron](https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html)

But I am not sure what string I put in the run code box. Yetiforce looks like this:

*/5 * * * * sh /var/www/crm/cron/vtigercron.sh &>/var/www/crm/cache/logs/cron.log

But that does not work in my schedule cron on shared hosting account. What does the path look like in your cron?

**Comment by Raggazzoo** [comment]
I have had this line in crontab with /etc/crontab -e 
*/5 * * * * sh /var/www/yetiforcecrm/cron/vtigercron.sh &>/var/www/yetiforcecrm/cache/logs/cron.log

Beware at the path of your installation.

**Comment by drfixit** [comment]
I'm not program saavy. But is there step by step instructions to fix this?
The reason I'm asking is that the instructions referenced earlier seem to assume that I already know how to program.

**Comment by ldgbc** [comment]
@drfixit have you had any luck getting it to work?
Here is a reference for those you are stuck in same position as we are.

1. I'm using CPanel provided by my host.
2. My path to my Yetiforce is like so:
/home4/(myusername)/public_html/(crm.websitename.com)/cron/vtigercron.sh
3. I tried adding it using Cron Jobs option in CPanel.
4. I set my time to be every 3 minutes, while I do the test. Hoping to find the correct "Command" to use. With each try I fresh on Yetiforce 
/index.php?module=CronTasks&parent=Settings&view=List&block=15&fieldid=26
To see if Last scan started show any numbers like @Raggazzoo image show.
5. I also edit the /cron/vtigercron.sh to PHP: export USE_PHP=/usr/local/php56/bin/php
By removing the # in front it. The issue is I could not find where is "/usr/local/php56/bin/php" to confirm that PHP is correct path though.

Here is the following Command I tried, all which failed.

1 - /home4/(myusername)/public_html/(crm.websitename.com)/cron/vtigercron.php
2 - /etc/crontab -e */5 * * * * sh /home4/(myusername)/public_html/(crm.websitename.com)/cron/vtigercron.sh &>(myusername)/public_html/(crm.websitename.com)/cache/logs/cron.log
None of which worked. 
3 - /home4/(myusername)/public_html/(crm.websitename.com)/cron/vtigercron.sh
4 - /home4/(myusername)/public_html/(crm.websitename.com)/cron/vtigercron.php

If any can shed some light it would be great. Thank you.

**Comment by ldgbc** [comment]
Hi all,

I manage to get the CRON to run. I will update tomorrow or some other days when I figure out which command is actually working.
