### ISSUE TITLE
Pulling data from Wordpress database

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3580]
Hi Guys,

I want to pull vacancies down and import into a module called "leads" How easy would it be todo this? 

Basically We create a Vacancy/lead on the website then just pull it straight into Yetiforce under the leads section.

**Comment by kabelo38** [comment]
You have to do API integration.

I did this few months ago firstly go to root directory of your WordPress site and create a file called 
YetiForce.php and copy the contents of the file below.

[YetiForce.php.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/493208/YetiForce.php.pdf)


With WordPress its not related to this forum but anyway i will share my work.
[Callback function wordpress.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/493212/Callback.function.wordpress.pdf)


In my case the site has multiple forms i think we used Form 7 or something and we used a callback function to connect to the CRM after any form submission to save the lead , but this really depends on your requirements note i placed my callback functions inside a file called /wp-content/themes/theme-name/functions.php, because we will never change the theme but if the theme is frequently changed then i suggest you write a WordPress plugin

**Comment by alextovey** [comment]
Okay, I'm using Hirebee tried this and not sure how to setup fully. anyone else has an idea? @PercyP

**Comment by bpabiszczak** [comment]
Use mail scanner  [lead from form send via e-mail].
