### ISSUE TITLE
[question] Same version, different code

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3587]
Just out of curiosity, why on page 'gitstable.yetiforce.com' with ver.3.2.0 is different from the stable ver.3.2.0 in github?
without AJAXChat, mPHP, Roundcube, PHPExcel, among others

**Comment by paula-w** [comment]
Some libraries can't be part of YetiForce due to licensing, it mostly applies to Roundcube and mPDF. From the new version on, these libraries should be manually downloaded after system installation [there will be a simple tool in the system that will allow to do it with just 1 click].  
The AjaxChat and PHPExcel libraries will be most likely removed in a while, and substituted by new libraries, because they're either outdated or include too many programming errors.

**Comment by WalterLuis** [comment]
Ok, thank you for answering.
