### ISSUE TITLE
How to edit existing field name and type

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#362]
Hi,
How do I edit existing field name (field label) once it's been created. I also would like to change field type.

In FAQ module, I want the "Answer" Field to be A WYSIWYG field instead of a text field.

**Comment by bpabiszczak** [comment]
In order to change an existing field name, it is necessary to use a language editor. We don’t have any plans that would include label modifications in the database, because it would cause too many problems.

If you need to change a field type, it needs to be preformed by a programmer, because it also causes many problems. It’s not enough to change it in the application, but it also needs to be changed in the database, sometimes a conversion has to be done or indexes changed. We don’t plan it for the nearest time; it might be easily implemented from a programmer’s point.
