### ISSUE TITLE
[Feature request] DMS - document management system 

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#366]
include seeddms AS embedded DMS Yeti? 

see http://www.seeddms.org/index.php?id=2

**Comment by maikst** [comment]
Integration of a DMS makes sense, but it has to be discussed which one will fit best.

**Comment by SergeyDjam** [comment]
Ok

**Comment by waran70** [comment]
There is an alternative - Alfresco. Proper documents management will kick yetiforce on next level. It shouldn't be called CRM anymore, rather sort of Business Operating System.

**Comment by SergeyDjam** [comment]
Alfresco system is too heavy. Here it is unnecessary. But the level of paperwork required SeedDMS in CRM

**Comment by bpabiszczak** [comment]
I checked this DMS and to be honest - it’s terrible. My first impression is that it cannot be used properly and we won’t use it for sure.

It is necessary to realize that in fact DMS shouldn’t exist as an independent tool. A document management system, which you mentioned, should be an integral part of the CRM system. If a document is waiting to be approved, it should be a part of this process, and not an external tool. In fact, what is offered by this DMS exists already in the system, but needs to be properly organized.

Meta data can be set.
Workflow for documents can be set [there is not graphic form, but it’s possible].
Documents can be assigned to folders.
Privileges can be configured.
At the moment we are working on WebDav integration that, in my opinion, offers great opportunities [e.g. ownCloud is based on it] and after this integration we are going to develop other functionalities so the solutions included in DMS will become a part of our system. I’m going to close this issue for now, because:

we are currently implementing WebDav,
a deployment of full DMS means weeks of analyses and optimizations of the system, we will proceed it according to our internal strategy [WebDav first and then we will think what’s next :p].

**Comment by maikst** [comment]
Dms is an essential tool for a company in most cases.
i would never choose dms within a crm as the main dms in my company...

Check out agorum dms.
A dms which is easily to integrate in an organisation and I think also
usable with Yeti out of the box.

Maik

Am Dienstag, 17. März 2015 schrieb Błażej Pabiszczak :
