### ISSUE TITLE
[Feature request] WebRTC-phone

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#367]
How see for it?

See it https://code.google.com/p/webrtc-phone/

**Comment by maikst** [comment]
No, makes no sense to me.
Not many customers use WebRTC

Better is a good interface to an Asterisk PBX like MobyDick 
https://www.pascom.net/en/mobydick-voip/overview/
or FreePBX

Maik

**Comment by SergeyDjam** [comment]
Hmm, сщддсутеук a Yeti on the interface asterisk very bad idea

**Comment by maikst** [comment]
A PBX interface is a very important feature for a CRM.
The interface on Vtger and Yeti is just very basic and not perfect.
But this can be changed.

**Comment by bpabiszczak** [comment]
At the moment we don’t plan any universal integration with any call center. We have enabled an internal version of Asterisk 13, but we lack deployment resources to take care of it. Every company uses a different solution in a different version with different API and that makes an integration is even more difficult. Every company has different expectations what complicates it and that’s why creating a universal solution is hard. Solutions that existed in Vtiger 5.4 cannot be even called basic; they were useless from a business point of view.

A good integration requires time, resources and 2-3 professionals so the costs of it are high so at the moment we perform only individual call center deployments for customers [each of them expects something different and has a different environment]. If we decide to build something like that, it will be a complex solution and such solution needs to become mature before we start its realization process. I’m going to close the issue, if we decide to do it, it will be because a customer is willing to pay for a complex solutions with a centralized call center or because we designate deployment resources. It will be probably dictated by a business need and not a feature request on github :]

I consider WebTC-phone solution as insufficient [we prefer full API with Asterisk 13]. Secondly, this library is already dead and we don’t even touch such libraries.
