### ISSUE TITLE
Integration with mautic

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3672]
Hello,

Can anyone help me integrating Yetiforce with Mautic 2.2.2?
I want to update the accounts from yetiforce to a selfhosted Mautic platform.

**Comment by kpaulaha** [comment]
We have the same on schedule. Beginning with it asap.

**Comment by serbiaserbia** [comment]
this would be awesome if someone had experience with this integration and could share it!

@immhub  did you try with MailChimp?
Any results with Mautic?

**Comment by immhub** [comment]
I didn't try MailChimp. 
I just installed Mautic and i'm trying to find a solution to integrate it with yetifroce.

**Comment by paula-w** [comment]
@bpabiszczak  suggests that instead of integrating with other systems, you consider adding a feature like this to YetiForce. Mautic has almost 70% of redundant features, because they already exist in YetiForce. Integrations already available (with Vtiger for example) are very limited, and not that much from Mautic goes into the CRM. The only way to get a decent marketing system is to make it 100% integrated with CRM, and costs of an integration like this would exceed the costs of adding the marketing mechanism to YetiForce.

**Comment by waran70** [comment]
YF with marketing robust module will knock down all other SalesForce's etc.
Knock down well...

**Comment by kpaulaha** [comment]
With all respect, @bpabiszczak  I do not quite agree with you. We have been using Mautic for couple years, from the beginning, and I do not see much similarity with it and YetiForce (or other crm). Okey, you can collect contacts with both using forms and there are campaigns in both, but they are totally on different level. The rest of functions in Mautic are the ones that make the value eg. campaing builder, contact tracking, landing pages, social media marketing, a/b testing, integrations with most popular cms-systems, focusing, dynamic content, etc. We and our customers have used Mautic for dozens of marketing campaigns and will not give up working with it, if nothing better comes up of course. On the other hand I do not know if it is worth to find the wheel again with building similar functions to YF instead of integration between, but of course it is your decision. As a crm, I think YF is among the very best, we have tested a lot during 11 years and joined lot of communities and are more than happy to work with YF now.

**Comment by bpabiszczak** [comment]
It doesn’t matter what features Mautic includes, the question is which of these features have to be in YetiForce. Eventually, in most of the cases, it turns out that all info from Mautic should be available in YetiForce, which means that these mechanisms must be added to YetiForce. In my opinion marketing in YetiForce has to be 100% related to current mechanisms in the system, and this can be achieved either by creating a solution from scratch, or adapting and integrating a solution like we did with Roundcube.

At the moment it’s not a problem, because in order to add something to the system it has to be written, for it to be written it has to be ordered, and for it to be ordered it has to be described in detail how it’s supposed to work from the business perspective. Until now nobody has described it properly, so we are talking about distant future.
