### ISSUE TITLE
individual mailbox for each user

### ISSUE THREAD

**Issue by cosmibota** [YetiForceCompany/YetiForceCRM#3717]
Is it possible to have individual mail box for each user? In system settings i can define only one email account. Is it possible to create individual email account (inbox) for each user? How?

**Comment by kpaulaha** [comment]
Don't quite understand your question. In setup you configure the corporate mail server and every user logs in to his/her own mail account.

**Comment by PercyP** [comment]
@cosmibota 

I believe you set up the smpt outgoing server once and this is used by everyone. Then the ser needs to have a yetiforce account and as long as their email account is the either the same as the smpt url i.e. @mybiz.com they simply log in tom their email account via yetiforce. 
to set up individual user email accounts you first create the user profile (add new user to yetiforce). 
I noticed this also works using different domains as long as they are on the same server. For example I have a VPS server with about 5 separate domains. i.e. mybiz.com, mysite.co.uk, thisbiz.net, thatbit.com

So as long as the email account uses one of those domains, a user can log in to their email account. I think it might be because it uses localhost but don't know enough about it yet.

Percy
