### ISSUE TITLE
Multiple Outgoing SMTP Servers

### ISSUE THREAD

**Issue by proyectosit** [YetiForceCompany/YetiForceCRM#3731]
#### Issue
Is there a chance to set up multiple outgoing SMTP servers?
I' ve found that RoundCube allows multiple identities, configured one but get an error... is that the way to proceed?
![smtp_settings](https://cloud.githubusercontent.com/assets/16767924/19944372/68d90204-a11a-11e6-956c-da4439ded5f4.png)

#### Your Environment
* YetiForce Version used: 3.2.0

Thanks in advance,
GP

**Comment by serbiaserbia** [comment]
It would be great feature to have multiple smtp server.
For example> in my business we have different emails in use (email@xxxx.com and email@zzzz.com) because we have complete different online stores, and consumers should receive emails from website they visited.
I have a doubts on how to handle this.

**Comment by PercyP** [comment]
This was a downside with Vtiger in that there can only be one outgoing server. I don't know if it would be possible to achieve i.e. to set individual smpt details for every yetiforce user) - as guessing that is what would be needed? That might create lots more nightmares?
 
I think it is currently set up for a corporate structure whereby everyone who uses the system works within the organisation and uses the corporate email account i.e. dave@mybiz.com, sally@mybiz.com etc. 

However, smaller companies might have contractors or employees who do not sit inside the organisation, but use the system as part of the company team, but use their own email account or even gmail. Or a consultant working for a large corporate (quite often in my experience) keeps his own consultancy email address as they work with multiple organisations at once and so for sanity sake need/prefer to keep their existing email account for all communications, and they also need to use/have access to all the system tools like other regular employees. 

So currently (I believe - please correct me if I am wrong), if you set up yetiforce smpt to mybiz.com those with gmail accounts or other external mail can't use it to view their mail accounts. Likewise, if you set the smpt sever up for gmail account, then it can only be accessed using a gmail acconbt email address - that goes for all employees who use the system.

@proyectosit I am not totally sure, but I thought the different identities where for different email addresses for the same org i.e. dave@mybiz.com is your direct email then there might be marketing@mybiz.com that you might also need access to along with others in the marketing team. 

So unless the email address ends with mybiz.com it can't be added as an identity. Is that wrong?

Percy

**Comment by waran70** [comment]
Yetiforce guys...  you should at least release paid version of such solution. It often seek option in vtiger. 
They got paid modules for that

**Comment by PercyP** [comment]
@waran70 @waran70 

I have just contacted https://www.vgsglobal.com/extensions/one-smtp-per-user-vtiger-add-on/

to see if their extension would be compatible with yetiforce as it seems the perfect solution. It's only $79.

I hope yetiforce can start providing paid for extensions like this but guess they have enough to do with the main component

**Comment by bpabiszczak** [comment]
In YetiForce you can send and receive emails from different email accounts in different domains.
In YetiForce every user can have multiple accounts at Roundcube level to send emails.
There’s a mechanism in the system that allows you to set a different account in modules by default; for example, in the tickets module, if we click reply in the mail widget in a ticket, then instead of our default mailbox (eg. b.pabiszczak@yetiforce.com) it can automatically set a different email (eg. sla@yetiforce.com).
The only drawback is that the system notifications are always sent from one SMTP, we will deal with this when we develop the marketing module further.
The documentation has to be created, but this is a task for 2017, when we have some time to do that.
The problem is that you try to figure out how to do something for free, and without much effort. The more energy you invest in YetiForce the more benefits you’ll get. Start building the system with us, not separately.

**Comment by waran70** [comment]
>The only drawback is that the system notifications are always sent from one SMTP, we will deal with this 

Indeed it is drawback, as if you test email with some spam score check it will show low degree of deliverability - pain in xxx of digital marketing guys

**Comment by bpabiszczak** [comment]
We have added a new functionality:  Multiple Outgoing SMTP Servers 
https://gitdeveloper.yetiforce.com/index.php?module=MailSmtp&parent=Settings&view=List&block=8&fieldid=105

**Comment by PercyP** [comment]
This looks brilliant - exactly what was needed. 

How do we install it?

**Comment by bpabiszczak** [comment]
You have to wait for the new version.

**Comment by PercyP** [comment]
Ah ok :)

Will that be in 3.5 or 4?

**Comment by bpabiszczak** [comment]
next version

**Comment by proyectosit** [comment]
Great news!

 

De: Błażej Pabiszczak [mailto:notifications@github.com] 
Enviado el: domingo, 15 de enero de 2017 10:39 a.m.
Para: YetiForceCompany/YetiForceCRM
CC: proyectosit; Mention
Asunto: Re: [YetiForceCompany/YetiForceCRM] Multiple Outgoing SMTP Servers (#3731)

 

We have added a new functionality: Multiple Outgoing SMTP Servers
https://gitdeveloper.yetiforce.com/index.php?module=MailSmtp <https://gitdeveloper.yetiforce.com/index.php?module=MailSmtp&parent=Settings&view=List&block=8&fieldid=105> &parent=Settings&view=List&block=8&fieldid=105
