### ISSUE TITLE
Hosting & Installation - Basan Equity 

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3780]
Hosting & installation  . .

#### Issue

I would like to host web server and get it installed with by merging with my existing database (of yetiforce). 
I would also like to purchase 8 hours of man support - Service to customize as per my need. 

I liked Yetiforce very much and much suitable for my office use. Please give me call on 
+919701852000 (India) for further discussion. 

I have tried installations at my end, but because of lack of knowledge on language- i'm unable to resolve issues. 

I have been posting on http://shop.yetiforce.com and also mailed on sla@yetiforce.com, but not getting response from there.  Sorry to use this platform, but i had no other option to communicate. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by alextovey** [comment]
They are very busy, I'm sure they will speak to you when ready.

**Comment by paula-w** [comment]
We actually did try to speak to them, I mailed them personally twice, first time after they sent the access data requested by Błażej in https://github.com/YetiForceCompany/YetiForceCRM/issues/3767, because the data they sent did not work. I mailed them on the same day they sent the access data. I didn’t receive any answer. 
Than I sent another email after this issue was opened, and attached the first mail. Once again no reply.
