### ISSUE TITLE
Records Permission - not set properly

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3782]
#### Issue

Permissions are not set properly

#### Actual Behavior

Other users are able to see records of all users - irrespective of hierarchy, however - when there are clicking on record - it is showing Permission Denied. At same time, user is not able to access his own records also. 

For example (as in GIF), user name - bhanuprakash has only one record - which is assigned to him. 
And also, in hierarchy, he is last - so he should be able to see only one record in Accounts module (Client module, as per gif) - but when bhanuprakash is logging in - he is able to see all the available records.

However, access permission is denied - when he is trying to get information of that record. Also, he is not able to view or edit his own records also. 

1. No special permission is granted to any user. 
2. All CRONs are active
3. 
Please find GIF below

#### Expected Behavior

1. Access of records should be as per "Assigned To" or "Share with User" only. 

2. Records to be visible as per Hierarchy is allowed. 

3. Other users records should not be even listed in view also., in user's 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4.21
* Browser name and version: Google Chrome
* Environment name and version: Stable - 
![permissions - error](https://cloud.githubusercontent.com/assets/21319919/20562888/103775c0-b1ac-11e6-8470-ba3bc3e96584.gif)

 * Operating System and version: Linux

**Comment by vovpff** [comment]
@basanthagarwal let's try to made relogin. Users switching sometimes be a cuse of domentation bugs

**Comment by paula-w** [comment]
1. Switching users has never caused any errors for us, and we’re sure it’s also not the case in here.
2. The error you describe is caused by the permissions not being calculated. In order for permissions to work properly your CRON has to be configured. However, this error only exists in one situation - we see a record on the list, but when we want to access it we don’t have the permissions. Permissions on the list are calculated in CRON, but record permissions are verified in real time, which means that record permissions are missing.
3. The problem is that we can’t see your system and we don’t know what you modified, whether or not it generates errors. This is why cases like this should be triggered in the GitDeveloper and GitStable versions, and only then we can check what’s wrong, of course if the error also exists in our versions. If it doesn’t exist in our versions we recommend individual support.

**Comment by basanthagarwal** [comment]
Ok .. 

I'm sending login details to sla@yetiforce.com, please do the needful. 

My email id is basanth.agarwal@gmail.com for further communication. 
Man-Support charges - please let me know, i'm ready to pay as per requirement. 

Also, ready to migrate to your server for hosting, and take private repository - GitDeveloper also. 
Please let me know procedure, i will follow the same.

**Comment by basanthagarwal** [comment]
Problem is resolved.  I have reinstalled with version 3.2 -> 3.3 -> 3.4 -> hotfix .. It is working fine. 


Previously, i installed 3.4 directly .. there was problem. 


Thank you

**Comment by basanthagarwal** [comment]
Problem still Prevails ... 

Till version 3.2 -> it was working fine. 

After updating to version 3.3-> and 3.4 ... same problem continues/.. 

Please look into matter. .. However, i'm shifting to version 3.2 for temporary basis.
