### ISSUE TITLE
Time Control Usage

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#3815]
#### Issue

Hi all, this is not a bug but just a request of hel to understand the logic of the time control module.

#### Actual Behavior

Actually, when employees insert their activities, all the people can see the timesheets of anyone else in the company. This is for sure by default.

#### Expected Behavior

I'd like to know if there is a way in the system settings that can let me respect the employees hierarchy. 

I mean, the employee whitout persons that report to him, can only see his timesheet. 
A manager can see (and approve) the timesheets of the persons that is heading. 
The idea is that a person can see and approve only the timesheets of the people 1 level below his position, and not all the timesheets inserted in the system.

Any hints, please?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
You have to check out what permissions in the system can do, because they give you great possibilities for configuration, and you can manage them the way you described. Unfortunately right now we don’t have any step by step documentation to present how to manage permissions. I do hope that in the nearest future we’ll publish some new materials. 

In your case I’d start from setting the module to private, because all modules are public by default, and this is why everyone can see everything:  https://gitdeveloper.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5.
