### ISSUE TITLE
Enable Accounts by Quotes

### ISSUE THREAD

**Issue by KarenNL** [YetiForceCompany/YetiForceCRM#3823]
Hi, How can I enable Accounts by Quotes? 
<img width="1204" alt="schermafbeelding 2016-12-18 om 15 48 35" src="https://cloud.githubusercontent.com/assets/24546765/21294286/aec9d14c-c539-11e6-9875-4040c7f63b65.png">

**Comment by vovpff** [comment]
@KarenNL let's select oportunity first

**Comment by KarenNL** [comment]
And when I don't use Oportunity? I disable that module.

**Comment by KatarzynaUlichnowska** [comment]
We do not recommend disabling an Opportunity field because Opportunities are considered as one of the primary modules in the system. Obviously, a condition might be written in such a way that when you disable the filed, an Account field will be unblocked. However, it requires some programming. We can write it for you, but you would need to buy this package: https://shop.yetiforce.com/en/support/20-sla-1-man-hour.html
