### ISSUE TITLE
[Bug] CalDav Activity Type

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3828]
if you add new activity type in module events from
software configuration> Standard modules> Fields - picklists

The query select in YetiForceCRM/modules/API/models/CalDAV.php at line 38 not sync the event with the new activity type value:

```
$query = 'SELECT vtiger_activity.*, vtiger_crmentity.crmid, vtiger_crmentity.smownerid, vtiger_crmentity.deleted, vtiger_crmentity.createdtime, vtiger_crmentity.modifiedtime, vtiger_crmentity.description '
			. 'FROM vtiger_activity '
			. 'INNER JOIN vtiger_crmentity ON vtiger_activity.activityid = vtiger_crmentity.crmid '
			. "WHERE vtiger_crmentity.deleted=0 AND vtiger_activity.activitytype IN ('Task','Meeting') AND vtiger_activity.dav_status = 1;";

```

**vtiger_activity.activitytype IN ('Task','Meeting')**

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/API/models/CalDAV.php#L30

**Comment by mariuszkrzaczkowski** [comment]
But removing these parameters doesn't entirely solve the problem, because there are some places  where the conditions are hard coded for event types.
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/API/models/CalDAV.php#L308
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/API/models/CalDAV.php#L79
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/API/models/CalDAV.php#L165
