### ISSUE TITLE
Arrow navigation bug ?

### ISSUE THREAD

**Issue by Benny7b** [YetiForceCompany/YetiForceCRM#3879]
#### Issue

In Yeti 2.X when on a lead it was possible to navigate from one document to another with next and previous arrows (cf. attached file)
 in Yeti 3.X (french version )it doesn't appear..
 Is it a bug or something to configurate ?

#### Actual Behavior

In Yeti 3.02 and 3.04 the arrows are not appearing
#### Expected Behavior

Arrows appear in each lead and you can navigate from one lead to another without using backspace and returning everytime in the main menu

#### How to trigger the error

1.
2.
3.
![yeti](https://cloud.githubusercontent.com/assets/24945476/21698289/e925396c-d39e-11e6-88e2-68fd36ee5603.jpg)

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
We disabled that feature some time ago because it wasn't very efficient. We don't really miss it, our clients don't ask about it. We can add it again and make it optimal, but it requires an order.

**Comment by waran70** [comment]
"because it wasn't very efficient" ??  a bit surprising statement
especially comparing to: "We can add it again and make it optimal, but it
requires an order"
Are you guys sure you going correct way?

Ian

**Comment by bpabiszczak** [comment]
If we delete, change, or add anything it is only due to the fact that we considered it the best possible solution for the time being.

The old feature was removed from the system because it was painfully slow and it loaded the same data multiple times. One of our clients tested the performance of our solution and compared it to other systems, therefore we couldn't have just kept that solution. It can be added once again, but it requires writing it from scratch in an optimal way. Until someone orders it from us we won't add that, because we have hundreds of other things to realize.

The problem is not that we removed the feature. The problem is that the community doesn't want to develop it on their own, nor pay someone to write it for them. If you don't want to do it yourself - don't expect us to do it for you, especially that it's not important for us right now. You keep confusing this project with a developer who works for free. Anybody who wants can introduce changes to the system, for example @migoi introduced 200 changes for the past 2 months, and this is what open source is about. Not about providing you with a free programmer. I understand that it's so much better in other projects, and everyone has a free developer, therefore:

1. SuiteCRM has 654 open issues including 430 errors
2. ODOO has 2500 open issies including 1750 errors

This is why I don't understand the outrage, you first have to give something in order to expect something from others.
