### ISSUE TITLE
[Question/Discussion] backup function removed YetiForce 3.5 ?

### ISSUE THREAD

**Issue by ABaumruck** [YetiForceCompany/YetiForceCRM#3896]
@ YetiForce
- It would be a real nice move to let us know what needs to be backed up and restored (what about a short howto?)
- And if keeping the module is too much work for you why not make it a payed option?

Ok, I've recently read in #3688 that the backup function is/will be removed from future YF releases. As this was one of my main reasons to choose YetiForce I feel quite uncomfortabel about it.

YetiForce says:
> The backup module has been removed from the system because the backup should be realized on the operating system layer, not on the application layer.

To some extend I agree. For bigger companies, with IT dept. this might be true. 
For an SME (like me) it is a big disadvantage because I need to keep the administrative tasks (to run YetiForce) as simple and easy as possible. 
The security of my CRM data is my absolute key that is why I would never go live with a system where I do not know (and have tested) how to backup and restore. 

The real pitty for me is, that YetiForce only says the backup module is gone but do not provide a single word about how to solve the problem for the people relying on that functionality.

I only found this #3347 information on how to manually backup the system. 
It is from a user, applies to YF 3.2 and there is no guarantee that this is still true for YF 3.4 and beond.

YetiForce Version used: 3.4.21 -> clean install
Browser name and version: Chrom V 53.0.2785.143
Environment name and version: vServer
Operating System and version: Ubuntu 16.04.1 LTS / PHP 5.6.29

BR Andreas

**Comment by paula-w** [comment]
In order to create backup you have to :
1. Create a backup of the folder where YetiForce is
2. Create a backup of the database used by the CRM

If you want to restore then it’s enough that you overwrite the file and the database, if the CRM location changes then you will also have to change the data for database and site_url and root_directory paths in config/config.inc.php file. 

In principle, YetiForce is a large system [includes more than 800 tables] and the data fills up quickly [a number of elements get added to the tables with each click], which causes many tables to expand quickly. Which means that for many users the backup won’t be created, because it will take too long. This problem also impacts companies that don’t have many users. Whether the module is free or paid, will not solve the main problem, which is that for many people it won’t be executed properly because it will keep stopping. 

Many hostings set their script execution time to 20 – 30 sec. When a backup is launched in the “precise” mode, which means it doesn’t backup entire tables, but only a few hundred lines, then it works 100x slower than when it’s done at the operating system console level. It probably can be solved in some way, but it would require several days of additional tests and problem analysis to know how to solve it most efficiently. 

From the business perspective, small companies should not have any problems with it, because they use hostings, and they create backups on their own. If someone uses a VPS or a decicated server, then the backup should be done at the console level [in CRON]. So if you have a VPN or a dedicated server then the admin knows how to create a backup, he might not know what to backup [the backup in our system can be created the same way like in Joomla, Drupal, Wordpress, etc]. 

You can always order the module or the manual from us.

**Comment by ABaumruck** [comment]
THX for the reply Paula

Let me ask a few more questions for clarification.

- As RoundCube is a seperate Module, how does that affect the backup/restore procedure. Or asked differently, will all my "links" between emails and YF stay as they are?
- Backing up the YF folder means: if you restore it than you can only restore it into the YF version that you have made the backup from, right?
- If, for instance, I need to move the data from a previous version of YF to the most recent (or get data from the production to the test environment) is there a way to migrate the data? Especially in terms of connections to RoundCube and custom fields.


One thing that I did not understand
> You can always order the module or **the manual** from us.

Does this mean you have a written manual? If yes, I would be glad to hear what it will cost and where to buy it.

BR Andreas

**Comment by paula-w** [comment]
Hello Andreas

1. Roundcube is a separate module until you download it. Once you download it, it becomes part of the system like every other module.

2. Roundcube doesn’t store email relations. The scanner downloads the emails into „Corporate emails” and relates these emails to Accounts. The Roundcube module doesn’t take part in the process of auto downloading and mapping emails. You can remove Roundcube anytime, and you will still be able to look through your emails in the system and see all the relations.

3. Restoring the system involves restoring the backup of database and files. It would be best if the database and files were from the same day. We recommend backing up the storage folder less often due to its size [documents, mail attachments].

4. Backup is not migration. If we want to have the latest version of the system then we use the update mechanism, which can only be used when the system is stable and works properly, and there’s nothing alarming in the logs.

5. We don’t have any instructions, we can write them when someone orders them. Due to their low priority we only create them when we don’t have any other, more important tasks to do.

**Comment by easaw** [comment]
@ABaumruck 
Use Cron? Or if you have shared hosting (on which you can also use Cron), they usually have a 30day backup of all your files and you can pay for monthly backups etc.

All the above automatic.

If you want to learn about Cron jobs, you can see this tutorial: [http://broexperts.com/how-to-backup-files-and-directories-in-linux-using-tar-cron-jobs/](http://broexperts.com/how-to-backup-files-and-directories-in-linux-using-tar-cron-jobs/)

Perhaps use this script: [https://github.com/pronoiac/tarsnap-cron](https://github.com/pronoiac/tarsnap-cron)
