### ISSUE TITLE
[QUESTION] Removed Webforms module. WHY?

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3916]
v3.4.1503

removing Webforms module is an unimproved action. Why do you make that decision?

**Comment by bpabiszczak** [comment]
We do not use this module. The module has been removed for security reasons.

**Comment by vctrin** [comment]
What alternative do you suggest to replace lead capture via Webform?

**Comment by bpabiszczak** [comment]
Mail scanner.

**Comment by vctrin** [comment]
Thanks!

**Comment by ezbank** [comment]
How to use mail scanner

**Comment by bpabiszczak** [comment]
You need to add a new action in the scanner.

**Comment by Pietrox** [comment]
The alternative is not sufficient in my opinion. It limits a lot of web based companies where users register via forms.
This type of companies will no longer be able to use updated YetiForce. The only sufficient alternative is to inject users to database and increment indexes in crm_entity - which is high risk. 
Please consider using webforms as an optional module or disabled by default.

**Comment by Pietrox** [comment]
Just to add. Email scanner is limited to what is received via email. We no longer can pass custom field information such as:
- lead source
- campaign
- affiliate 
- country
- origin IP
etc.

This decision practially killed automation on this part.

**Comment by SkavenKF** [comment]
Although I do not use the modul, I find it very critical just before a release, to add, delete or change a module.

**Comment by basanthagarwal** [comment]
Webform is used by us, for 
Leads capture
Tickets Capturing

It is convenient. Please keep it, if possible.

**Comment by kpaulaha** [comment]
This decision for sure ruins our cases with yf. On the other hand we have been more using Mautic to collect leads etc. and push them to CRM.

**Comment by bpabiszczak** [comment]
From the technical side nothing has changed, you got exactly the same capabilities, you just have to look at them differently. Anytime you can write a simple script, that will receive the data from the form and add them to the system via object [it’ll take a few hours max]. You can also write a script to the scanner to parse the mail, and based on that look for the field name in CRM and assign the value. 
The only problem is that someone has to write it [we don’t need it today, so we’ll wait until someone orders it]. You can order it as well, and we’ll write a script, that will automatically recognize column names in the email, and add lead/contact/account.

Webforms were dangerous; your webform can’t be allowed to send data to a file in the CRM. A system like this would never go through a serious security audit.

**Comment by Pietrox** [comment]
You mean object via webservice? Last time I checked the documentation is NULL in the integration section ;)

**Comment by zeostravelling** [comment]
@kpaulaha do it (Mautic) automatic push it to CRM or how do you do it?


> kpaulaha commented 11 hours ago
> This decision for sure ruins our cases with yf. On the other hand we have been more using Mautic to collect leads etc. and push them to CRM.

**Comment by kpaulaha** [comment]
@zeostravelling It can be pushed automatically

**Comment by ezbank** [comment]
pls give back :(

**Comment by PercyP** [comment]
I used webforms too :(

Can't these modules be left in the system (disabled by default) but allow those that want it to enable it? If not, can YF not create the new script or whatever it is that is needed and add it as an extension that we can buy/download from the extension store?

I am starting to worry now that you may remove other things without warning, with no way for us to get them back. Already various features have been removed from the editor etc. like the ability to upload images.

**Comment by waran70** [comment]
It was exercised before. Yetiforce guys doing radical cuts without discussing it with community. It is kind of half open source :-) ... of course they got full right to do what they want, but that's not a perfect way to encourage community and developers. I partially agree with Blazej, that webforms are not perfect, but on the other hand, removing so popular module without replacing it with wise designed alternative one, seems to be not very polite here.
Most important is to allow as many people as possible to use yetiforce, and than, commercial customers will follow. So.... who is working in the marketing department there...  Ha?

**Comment by Pietrox** [comment]
Would be very grateful for an example code on how to send leads that register on a website to the CRM. Still postponing an update here. Is there any documentation for it planned?

**Comment by liberox** [comment]
any news on webforms in YetiForce?

**Comment by ezbank** [comment]
Nothing

**Comment by reeid** [comment]
Blazej, can you let us know the price for rewriting webform module ?

**Comment by Pietrox** [comment]
I don't think they will do that.
We wrote our own cURL based registration, we could offer it for people here to integrate if Yeti guys wouldn't mind. 
So far it's made for Leads module, but adding it to accounts or any other shouldn't be a problem.

**Comment by ezbank** [comment]
@Pietrox  I am very grateful for what you will do.

**Comment by USTMarketing** [comment]
Any news on this? I want to upgrade to 4.0 for all the new features, but I simply cannot live without Webforms. This is how we and I think a lot of companies collect leads, it is simply a must and should be reintroduced.

**Comment by JohnMaverick** [comment]
@bpabiszczak - can you explain why webforms was dangerous? Why sending data through webform is more dangerous than through other API ways?
Webforms create records in modules without possibility to impact on data in any other way. What is dangerous in it?

**Comment by waran70** [comment]
@bpabiszczak 
Blazej, please get some final statement or just close this issue, so we all know destination.

**Comment by paula-w** [comment]
Hi guys,
This is @bpabiszczak’s answer:

Webforms were removed and there is no chance they are coming back in the same form they used to exist in the system.  Creating a new Webforms module would cost around 450 ~ 600€ and if someone orders that feature we will add it to the system. If someone has a ready-made solution – you can send it to us and we will accept it.
The old solution had a lot of flaws:
- Poor quality and vulnerable code
- External app had to access files in the module [right now only API is acceptable, everything else will be removed from the system]

We removed Webforms because we had to face two massive security audits, and Webforms were full of holes [just like we removed Mobile, Our sites, RSS, etc]. We write what we can right away, but unfortunately all the elements that need to be completely rebuilt have to wait until someone orders them.

**Comment by reeid** [comment]
Lets do it together. I declare 50 Euro. Who is next? Once we gather interested parties we will find a way to put money on.... waiting for next

**Comment by USTMarketing** [comment]
If everyone who requested this on this issue alone puts 50€ we'll get it done. I'm okay with this if everyone else is too.

**Comment by reeid** [comment]
100 in place. Waiting for next donor

**Comment by reeid** [comment]
More donors less impact on wallet. Hope everyone interested will pay 10 euro and total will get 800 so yetis will get nicely polished module.

**Comment by kpaulaha** [comment]
+1 
50€ 
Although we use mostly Mautic to collect contacts to systems, it would be great to have one webform integrated into YF.

**Comment by davidporte** [comment]
count me in for $100 USD, seriously, I can't believe they removed it ...I'm seriously starting to question my decision to use and invest in YF.

**Comment by davidporte** [comment]
Actually, scratch that..we have only just implemented YF and so far its been a bit of nightmare to implement, virtually zero online resources, no support..sent an email to yeti 2 weeks ago asking how much to assist with implementation and zero response.I think I've wasted enough time...and the arrogance of the team seems systemic..I would have happily paid for the service but I'm just finding the whole experience draining and defeating..I'm off to install and run with Vtiger..should have done that weeks ago. it has fewer features but so much better support and it's actually logical and intuitive in its layout...and it's visually attractive...and it just makes sense. YF does not and it's not and there's almost nowhere to find out how and what and they don't reply to emails..the only replies I have seen are here and they are typically blunt and dismissive. good luck guys. I would have gladly paid for YF but the website is about as logical as the program..it makes no sense and seems like they have just gotten so far and then they have abandoned it..the whole thing just seems half-baked.

**Comment by bpabiszczak** [comment]
As far as I know, you received an answer from us on Monday! Your question was about the price of 10 support hours in a different currency than the one listed on our website, and it's nothing that crucial, especially that all you have to do is google that, and 2 seconds later you have your answer [the payment would've had to be in € anyway].

I think you are trying to blame us for your own error. When you implement any system you should first:
- describe your business requirements and set the goals
- evaluate to what extent the system you chose actually meets these requirements
- estimate how much adding the remaining requirements would cost
- select the vendor [it doesn't have to be us, any programming company or Vtiger vendor can do that]
- implement the system according to the requirements
- purchase support for the implemented system
- purchase training for the implemented system.

The fact that you installed the program but didn't purchase any support is not our mistake.

We don't claim that our product is ideal, or that we are. However, we think we created a decent product that can be implemented in any company and easily adjusted and developed in any direction. If VtigerCRM or SuiteCRM are better for you - we understand and hope they will meet all your requirements. Just keep in mind that there are several dozen people in here who resigned from using VtigerCRM and SuiteCRM and switched to YetiForce, which means that everybody is looking for something else, and we won't always be able to make everyone happy.

**Comment by davidporte** [comment]
Ok, I have not seen a response from you guys and yes, I had asked for 10
hours as a suggested starting point and was more than happy to pay, much
more if needed but your website is so poorly designed and the packages for
large sums of money have no descriptions whatseover...who the hell is going
to pay a large sum of money on a website for a product or service with no
description...let me guess...you don't get a lot of uptake on those offers
do you? was the web designer drunk when he made that site?. That was
however over 2 weeks ago. I would not consider that a great level of
response time to a question or a client requesting to pay you for services.

As to an error of my own making? Seriously, where are you getting this
from. My complaint is that you have never had anyone with a genuine
English speaking background go through the product and therefore a lot of
the titles you have used are not logical and simply do not make sense.
Somebody who actually speaks English as a first language and understands
the inflections has gone through Vtiger and it does make sense, and its
logically laid out...that is a major difference between your product and
vtigers..and why Vtigers is much much easier to set up....yours has more
going on but fuck me if it is not horrible to try and understand.. you say
just google it and 2 seconds later you have an answer..not a fucking
chance. I have spent hours looking for training on yeti, I was committed to
it and was convinced that I would eventually get through. I even hired 3
freelancers who claimed to be Vtiger and crm experts who eventually gave up
and said they could not understand how to do this or that and could not
find enough online documentation to make it happen. I really and genuinely
tried and i don't often give up on things but this experience has been
truly horrible and its taken around 100 hours of my life so far so i am not
at all pleased to walk away from it.

So here is my main issue; you have created a powerful and seemingly really
great product, but then you seem to have lost interest in taking it
further. the lack of online resources is truly very poor. most of the
documentation on your site is terribly inadequate..don't misunderstand me
please...what you have done so far is good, but you stopped..there are so
many areas where you search for an explanation of what you intend for a
things to do (given its got a strange description) and there is nothing or
a section saying...there is no information for this subject. it just looks
like the documentation guys quite and you never rehired.

The secondary issue, I watch your comments on git and see that you are
dismissive and borderline rude to people, its classic arrogance, and
dismissive behavior. people are genuinely trying to connect with you and
your product and you speak down to them...just like you have to me in this
email. it doesn't matter how good you make the product, if the people
behind it have contempt for the clients, this will show through and people
will take the lesser product than being tied to arrogant people.

So what have we learned, either im a whining fuckwit or I have a legitimate
complaint that you can learn from..that part is up to you but I'm fairly
confident that I know which barrel you will relegate me to. you have a
commercial opportunity to turn this into a Vtiger style success story for
hosting and live services but you don't seem to want to do that. how would
your business look if you had 100,000 users paying you $50-100 each per
month? its such a golden opportunity for you...but you will never get there
while you treat your clients like they are all fuckwits. Please clean up
your website, clean up your documentation and clean up your attitude most
of all and you might have a chance at a high level of success with this
product...

please stop blaming your potential clients because your information and
support is deeply inadequate...you can learn from this or just reinforce
your own bullshit. one of those two will produce a better result and one
will not. Heres the bottom line, you have a good product, we are willing to
pay for it and your services...so make yourselves accessible, become
professionals and don't treat people like fuckwits because they are
struggling with your stuff...fix your stuff before blaming the people, only
amateurs do that.

good luck.
david







<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

On Fri, Nov 17, 2017 at 8:16 PM, Błażej Pabiszczak <notifications@github.com

**Comment by davidporte** [comment]
A quick update, I have just checked both of my email accounts very
carefully and no response was received on Monday or any day this week that
I can see and certainly not before. Again, would have gladly proceeded with
you guys if you had simply replied. I hate walking away from something,
like this as it seemed to have so much potential, but hey, I'm a dickhead
right and what do dickheads know. I'm sure I deserve to have failed with
this installation.

David



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by PercyP** [comment]
@davidporte 

do you have to be so rude and disrespectful? Why use foul language to get your point across? There is a time and place for that and this isn't either. I am from the UK too and don't expect everything to revolve around me, my country, language and 'the way things are done around here'. Yetiforce are NOT Vtiger - if you prefer vtiger then go back to them. What you have to realise is that everyone has to start somewhere. My experience and recollection of vtiger in the early days was pretty much the same when they forked from (I think SugarCRM?). There was very little documentation and very little support to the community. 

Yetiforce is a brilliant product, you have to get to know it. Dedicating time to it is well worth the rewards. Yes, there are some words in the system that are not what you would use, but the system provides things like the Language manager to allow you to rename whatever you want. It is a universal product. 

I think slagging off their website (which is actually very good - and is a work in progress in terms of the documentation) is also pretty childish and again dis-respectful. 

If people like you populate places like github with all your negativity then it wont be long before all these fresh new companies just give up and go home. If someone in your place of work was continuously putting you down, how long before you think 'sod it'? Give them a bit of encouragement, put yourself in their shoes is all I am saying. Also, stop comparing them with Vtiger - they are a different company with a different vision (one I think is great). They are still relatively early days, and need time to get all the things in place that the likes of Vtiger have.

Yetiforce are offering you something here for free. Yes they do offer custom service, but again think about the size of their team - plus the main priority is getting the system right. As was said in an earlier post you can go to other developers (I have done this myself and the developers have had no problem at all developing for yetiforce - so maybe you picked the wrong company/developers?). 

Also, what is that weird mailtrack link in you post. I don't personally think you are genuine and feel you are just trying to put the company down.

**Comment by paula-w** [comment]
@davidporte 

I'm a little confused because I personally sent you a response to the question you sent via the contact form. I'm attaching a screenshot of my mailbox below. I partially covered your email address in order not to disclose your personal information on GitHub. To be honest, I don't know why you didn't receive my response, but I understand that it might be very frustrating.

We don't want to "forcefully" convince you to use YetiForce, and we really want to avoid conflicts with our community members. We understand that you are unhappy, and we see how this situation might have affected your choice of CRM software or vendor.

I don't want to waste any more of your and our time for arguments, as that only delays the release of the next version of YetiForce.

I sincerely wish you good luck.

![email](https://user-images.githubusercontent.com/13310141/32955845-6cd03abc-cbb7-11e7-921e-9045109956f0.PNG)

**Comment by davidporte** [comment]
Ok, it is not my intent to start a Yeti bashing session or that of its
team, the product as I have stated previously seems like a great product
with so much functionality. My frustrations were with the lack of available
resources and the seemingly poor attitude of the people behind it. I do
however understand that it is a free product in its basic form and was
really keen to work with you guys on that.

I was however very frustrated as to how much time I had put into it and got
as far as spending a couple of thousand dollars and over 100 man hours only
to discover that you had removed web forms without community consultation
and then simply said, bad luck, it's done, you will have to create a
workaround. Web forms integration for me is an absolute must as it is for a
lot of people. that is when I lost faith in the direction of the product
and its team. I apologize for the language, it was a moment of upset and
deep frustration and the realization I had wasted my time.

Guys, just one decent walkthrough video on youtube would make all the
difference, truly, just explain what each section does and or means and use
that to promote what you guys can do for newbies like us as well, I promise
you there will be loads of us willing to pay for services, we just need a
replay to our requests.

I am respectful of the fact you have created and released this product for
free, that is seriously awesome and deserves plenty of respect and
admiration. I am however now treating this aspect of my dealings with you
as I would any provider of services who to my mind had not responded to a
request for paid services. Please see the separation of concepts there. I
read some of the posts to others who had asked for clarity on the product
and most of the responses struck me as blunt and for the most part, here's
a snippet of information, you should be able to figure it out from here.
this added to my frustration.

As I have said from the beginning, I am in need of a good CRM product and
after a lot of preliminary research decided on YF based on how good it
looked and seemingly what it had to offer, the fact I as a potential client
who was more than willing to pay was struggling with your website should
tell you something. it's far from a wonderful experience for your potential
clients. I cannot stress this enough, the website offerings make no sense,
there is no detail as to what do i need as a new person, what do you get
for the different packages and what the ongoing costs are or will be.
surely you can just create packages that are customisable on an hourly
rate. I will happily pay for that as will others, I'm sure.

I hate the fact that I lost my enthusiasm for YF as I really like the
product. I am only moving towards VT as a function of desperation. Mr
reference to the language used in the software is one simple fact, no
matter what country you are in, if you are reading it in English, it should
be written in a fashion that makes sense to English speaking people and not
changed to suit an alternate language, as you have stated, there are
language packs for that. all I meant with that comment is that some of the
terms are really obscure and that would not normally be an issue,
particularly as you have pointed out, they are customisable, what makes
this a big deal is that you cannot get documentation that explains these
modules or the intent of the writers because the documentation doesn't
exist and when in my experience, you contact the company, no one gets back
to you.

Anyway, as you have said, let's not waste any more time arguing, I just
wanted to share my feelings on the issue and actually thought I was
responding to you privately on email and not back in the post as this
landed inside my email. remember, I am new to Git and this was my first
post.

I will close by saying that I am sad to be abandoning my first CRM attempt
as I had high hopes for the result and would still be very interested in
working with someone to set it up and work on it with me and I am happy to
pay. all I ever wanted was some service and support for what I believed and
still believe to be a great product.

regards
David






<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by waran70** [comment]
@davidporte 
![fb15](https://user-images.githubusercontent.com/6852348/32976771-1b5a2888-cc51-11e7-9fbc-52100e871aa5.gif)

**Comment by davidporte** [comment]
There's no need to take your own life mate, your life will improve eventually.

**Comment by davidporte** [comment]
So just to close this out before another amoeba brains trust member attempts to add to the conversation, do you guys have any plans for additional documentation or training videos for the yeti product?

**Comment by shop4seo** [comment]
Hello. were you able to make a new form module? it's been a year since people asked

**Comment by LukeLak** [comment]
Any solution available? Or documentation how to connect to yetiforce via mailscanner??

**Comment by mgiammarco** [comment]
I will need form integration in the future. But I do not understand why nobody tries to open a bounty in a site like www.bountysource.com
