### ISSUE TITLE
typos and other (minor) bugs - developing with NOTICE enabled

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#4024]
Hi,

after using my regular loglevel with php and a look into phpErrror.log it seems that developing with e.g. NOTICE disabled is not that good.

After setting the "smarty" messages to zero and making too much noise in that log, some very interesting entries shows up.
To disable the smarty-only notice messages: In file include/runtime/Viewer.php add at line 198
~~~
$this->error_reporting = E_ALL & ~E_NOTICE;
~~~

Most of those messages are really easy to fix. Some may explain why some code never has been run 
before. Fixing those may be also a performance hit, because of triggering notices.

I believe enabling E_NOTICE during development has some benefits (see PHP Runtime Configuration Docs at http://php.net/manual/en/errorfunc.configuration.php):

> For debugging purposes: NOTICE messages will warn you about possible bugs in your code. For example, use of unassigned values is warned. It is extremely useful to find typos and to save time for debugging.

> NOTICE messages will warn you about bad style. For example, $arr[item] is better to be written as $arr['item'] since PHP tries to treat "item" as constant. If it is not a constant, PHP assumes it is a string index for the array.

Here some real-world examples of your latest code (4.0.0):
~~~
if (!$row['isdeafult']) ...
~~~
should be
~~~
if (!$row['isdefault']) ...
~~~

or what about some funny "setters" like that
~~~
		public function setLine($line) {
			$this->line = $this->line;
		}
~~~

also: hard to find, easy to fix.

I've done some of those fixes and ensure of variables being declared before usage. At least one of them could be security related (checking on row level security).

Will you accept pull request that covers those bugs?
Will you make the the NOTICE-level become default at least while developing, so most of such messages are fixed before publishing the code?

Only an empty error log is a good error log.

**Comment by mariuszkrzaczkowski** [comment]
I agree with you, we aim to have error_reporting = E_ALL, and an empty log file, but there’s a lot of outdated Vtiger code that stops us from getting there. 
We keep working on removing these errors. 
We managed to achieve a lot, because the system almost works with E_ALL & ~E_NOTICE.
The requirements are for the production version; for the dev version we currently recommend E_ALL & ~E_NOTICE, and soon we will recommend E_ALL to get rid of errors completely.
Unfortunately we can’t fix everything at once.
You found some typos in the code and fixed them which is amazing, because thanks to contributions like these we can progress, and there will be fewer errors in the system.

**Comment by mariuszkrzaczkowski** [comment]
I created a ready-made package to run and install YetiForce. It's xamp with a ready PHP and MySQL configuration, it's the dev version, not the production version. 
You can test all problems related to update and installation on it. 
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%204.x.x/4.0.0/?upload_just_completed=true
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.0.0

**Comment by migoi** [comment]
do not be scared, but i have > 30 more PR in advance to show up. Just testing if those would not harm my test installation.
