### ISSUE TITLE
Accounts -ENCOUNTERING ERROR

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#4045]
#### Issue

Before updation, all tables were working fine. After updating to 4.0 version ... except Accounts table, everything else.. seems to be ok. 

Following error is encountered with clicking on Accounts ..

#### Actual Behavior

This is Error appearing after clicking accounts page. 

Error!!!
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_campaignrelstatus.campaignrelstatus' in 'field list' Failed to prepare SQL: SELECT `vtiger_account`.`accountname` AS `vtiger_accountaccountname`, `vtiger_account`.`account_no` AS `vtiger_accountaccount_no`, `vtiger_account`.`phone` AS `vtiger_accountphone`, `vtiger_account`.`website` AS `vtiger_accountwebsite`, `vtiger_account`.`fax` AS `vtiger_accountfax`, `vtiger_account`.`otherphone` AS `vtiger_accountotherphone`, `vtiger_account`.`parentid` AS `vtiger_accountaccount_id`, `vtiger_account`.`email1` AS `vtiger_accountemail1`, `vtiger_account`.`employees` AS `vtiger_accountemployees`, `vtiger_account`.`email2` AS `vtiger_accountemail2`, `vtiger_account`.`ownership` AS `vtiger_accountownership`, `vtiger_account`.`industry` AS `v.................................................................
.............................................................

#### Expected Behavior

Please guide me ..

#### How to trigger the error

1. 
2.
3.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Chrome
* Environment name and version: Stable
* Operating System and version: Linux

**Comment by ldgbc** [comment]
Sound like when you upgrade, it failed to update those table. My best guess is due to v4.0 requiring MYSQLND_LIBRARY.

You could also refer to some of these issue and could give you idea on how to solve them.  #3996 and follow the trail of other related issue.

Worse come to worse, you can go into PHPmyAdmin and try add those column.

Finally if all does not work. Either stay with 3.40 or wait for a compatible version. You could try old version/update such as 1472

**Comment by paula-w** [comment]
We need a more detailed description of how to trigger the error.

**Comment by basanthagarwal** [comment]
Let me reinstall by rechecking PHP settings ... 

Thank you so much  ...
