### ISSUE TITLE
[Question]Admin Password reset with databasechange

### ISSUE THREAD

**Issue by ahmido** [YetiForceCompany/YetiForceCRM#4057]
Hello @all,

is there a way to change the Admin Password over phpmyadmin(database)? I can't login into YF4.0. thanks for help

**Comment by fbojan** [comment]
I have the same problem, but already with installation

**Comment by ldgbc** [comment]
Hi @ahmido @fbojan 
You can try resetting the password using instruction from here:  
`https://www.siteground.com/kb/how_to_reset_the_vtiger_administrative_password/`

Please see these other issue #4007 and follow the trail of referenced issue for help. I think you have the same problem as I (webserver requirement not fully met) so even if you do reset the password it won't work. Because it not the password that is wrong but the installation is incomplete.

Good luck though

**Comment by gkArvindr** [comment]
Found the best way to reset password, created another instance of yetiforce, exported the table vtiger_user and imported into the older instance.

**Comment by beppe9000** [comment]
https://raw.githubusercontent.com/YetiForceCompany/YetiForceScripts/master/PasswordReset/PasswordReset.php
