### ISSUE TITLE
config override prozess to build a docker container

### ISSUE THREAD

**Issue by efernau** [YetiForceCompany/YetiForceCRM#4146]
We build a useful YetiforceCRM Docker Container: [https://github.com/efernau/Docker-YetiForceCRM](https://github.com/efernau/Docker-YetiForceCRM) (based on official php:7.1-apache and latest mysql 5.7 and YetiForce Version 4.0)

But we have problems with the automation configuration. It is posible to use a config_override.php to override the config/config.php to override defaults like host_name, database_name, admin_user_name at the installation Prozess?

I think it is not the same way like SugarCRM or vtiger. How the config override prozess works on Yetiforce?

**Comment by mariuszkrzaczkowski** [comment]
It is the same as vtiger. 
install the system normally and see the file
config.inc.php

if you can show as how to use it? it may be we able to help you

**Comment by ldgbc** [comment]
Hi @efernau 
I find this interesting. I'm not sure if I'm understanding it correctly, but could we use this on our hosting that will allow us more freedom that the host limit us on?

For example, it got a MYSQL package in Docker, so using Docker I can use the latest version of MYSQL in my hosting server rather than be stuck with my host's "stable" MYSQL version.

Or will this only work in the same sense as LAMP, WAMP, MAMP type of package software? Or it is for local testing environment/package.

**Comment by efernau** [comment]
Docker Containers are really designed to run one app per container.

Docker is a containerization technology that enables us to cleanly abstract an environment configuration to a file, and run it in a protected, isolated environment on a host. This is similar to, but more performant than, a virtual machine. On a lower level, this secure isolation is achieved via application namespaces, similar to how Linux LXC and BSD jails work. 


Docker Engine runs natively on Linux distributions.


Windows user use Hyper-V to virtualize the Docker Engine environment and Linux kernel-specific features for the Docker daemon



Docker for Mac runs as a native Mac application to virtualize the Docker Engine.



A Dockerfile is a file that contains a set of instructions that describe an environment configuration. For example, if we wanted an environment that ran Ubuntu 14.04, had vim installed, and had port 80 open, the Dockerfile would look something like the following:

```
FROM ubuntu:14.04 
RUN apt-get install -y vim 
EXPOSE 80
```


[Docker Hub](https://hub.docker.com/) is a cloud-based registry service which allows you to link to code repositories, build your images and test them, stores manually pushed images so you can deploy images to your hosts.

**Comment by KatarzynaUlichnowska** [comment]
We will not enable the Docker Container in the 4.3 version and probably not in 4.4. This technology is important to everyone, including us, but for now, it is low priority, because the configuration of environment for small companies is based on hosting, and for medium and large companies these are mostly either servers without virtualization or private clouds where providers configure and adjust everything.
One day, it will change but it doesn't make sense to keep this issue open for the next few months.
