### ISSUE TITLE
Hide inventory table column in PDF only

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4334]
#### Issue

Can you help me find a way to chose an option from the advanced block that only hides the inventory column in a generated PDF? If not what is the alternative?
In my company, we want to view the full details of the inventory table when editing or viewing a quote for example. But we want our clients to only be able to view certain columns  when we generate a PDF.

#### Actual Behavior

At the moment, "Visible in detail view" and "Hidden" hide the columns in a generated PDF. But these also hide the columns in the full edit view which is not the intended outcome.

#### Your Environment

* YetiForce Version used: 4.0.155
* Browser name and version: 
* Environment name and version:
* Operating System and version:

**Comment by WhyNotCrazyTrain** [comment]
Hey! Do you generate that table using a special function? 
Then you can find that "your-function-name.php" file in "modules>Vtiger>pdfs>special_functions" folder and hide it there.

**Comment by ruistrecht-alt** [comment]
Nope. I want to hide some columns from the "Quotes" module in the generated PDF. But I also want the ability for the users to edit all the aspects of the table in full edit, and to view those all the details in the full details view.
E.g. Fill the margin and margin(%) in the table, but in the generated PDF the client can't see both those columns

**Comment by mariuszkrzaczkowski** [comment]
It is best to create your own function to generate the table

**Comment by Rosalems** [comment]
Hi Is there any update on this ticket if this will be implemented soon?
This would be a huge improvement to define what is printed and not as we are unfortunately not free to add our own code on the exports.

We should have a checkbox on the field settings to say yes print or not print and also the order of the field needs to be changeable to my opinion.

I am a Seniour Javascript developer for NetSuite CRM/ERP and know the importance for my customers to have this for my own system. As I want to use Yetiforce for my own company because of pricing I really would like to have this builded in.

Thanks in advance

Arnold Willems
