### ISSUE TITLE
Scan pdf files create records

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4460]
Not a bug however this is request.

Can we scan PDF files and word files to create new records? also having the search function to scan these files too would be a great advantage. 

A developer i know can do this for £450 however i'd prefer if you guys did it and pay you. How much would it cost?

I did send a email last month but not heard anything back. Or is anyone else interested in this module? and would be willing to split the cost with me?

**Comment by waran70** [comment]
You will need to employ Abby OCR engine, so the recognition will be reliable to the acceptable extent.
That would't be 450 but more.

**Comment by mariuszkrzaczkowski** [comment]
So, from the PDF file to create a new record on the system?
Can you describe more about how this works?
How do you map fields?

**Comment by alextovey** [comment]
it would bring up the import from Csv type, where you can add the address etc by selecting the drop down.

**Comment by alextovey** [comment]
Still waiting to hear back before I go for it with the developer however he say's it will use the ocr software and then match fields based on the name which is currently being used in that module such as contacts, it will match exactly the fields and custom fields in there.

**Comment by KatarzynaUlichnowska** [comment]
In general, we don't estimate the cost of this type of functionalities, because they are not adequately described. In order to be able to tell you the price, first, we would need to get copies of document templates which the system will have to proceed. In addition, we would need to have detailed business logic described [e.g. what records should be created, which field types should be handled].
If this developer wants to do it for 450 then, in our opinion, it's a good price because ours would be probably higher.
