### ISSUE TITLE
Improvment: v7 filters

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4537]
Quite like vtiger 7 filters idea. Maybe worth to think of it here?
Task management is cool too

**Comment by JohnMaverick** [comment]
Agree... filters are very often used function.

**Comment by paula-w** [comment]
Gifs and screenshots would be much appreciated, as we don't have the time to look for these features in Vtiger

**Comment by reeid** [comment]
You obviously kidding Paula?

**Comment by bpabiszczak** [comment]
NO

**Comment by waran70** [comment]
@bpabiszczak : If you dont have time to look in those features yourself (pretty surprising that yetiforce developers dont know what is going on in vtiger 7) just close this ticket. Calling for gifs in this  case  is indeed funny

**Comment by JohnMaverick** [comment]
I also had impression that Paula joking, but it turned that @bpabiszczak got a bit black humor. 
My advice is that yetiforce should have ONE only user who communicating with github in the name of yetiforce company. If other developers wanna help, dont let them talk about other than technical things, otherwise clumsy stuff like we can read here will stick to yetiforce  brand and lover down score of trust.

**Comment by mariuszkrzaczkowski** [comment]
I do not understand you, you want free new functionality and do not want to attach a simple screenshot ???
We observe many CRM systems, but your description is generic, in vtiger 7 there are several filter enhancements and you have not described exactly what you mean.
If you want to help develop the system then give full information, then we will not waste time on such discussions, we will focus on the development of the system.
As you can program it yourself you can add it to your system, remember this is opensource.

The more you give, the more you will receive.

**Comment by JohnMaverick** [comment]
Personally I dont want any of above as I DON'T uses yetiforce in any production scenario. On the other hand if somebody suggesting improvement, it doesn't means they want it for free. I watching this project and I also thinking this two mentioned by waran70 vtiger7 features could suit very well here, but again, I am not yetiforce user! 
I dont know what filter enhancement you calling to, but I am sure mentioned was the way of accessing filters. This is what I feel automatically reading leading post.  Hard for me is understand that you may feel differently.... waran70 said:  "Quite like vtiger 7 filters idea." Isn't it clear enough? It isn't obvious that it is about user experience...?
 :-)

**Comment by mariuszkrzaczkowski** [comment]
Here's an example of how we look at other systems https://yetiforce.com/en/news/blog

**Comment by bpabiszczak** [comment]
If @KatarzynaUlichnowska or @paula-w answer you it's my decision the majority of time, unfortunately my English is not good enough to discuss these issues with you myself.

@waran70 you were asked for screenshots and gifs where we can directly from this issue see the functionality that will help the decisive people and then the programmers understand the extension of this functionality. Unfortunately you find this funny because you think we should check it on our own. If you don't have time for something so simple then why should we spend our time to figure it out and add to the system?

Do you think you are giving us some amazing info? We get a hundred of ideas daily for improving this system, but we neither have time nor resources to realize them all. We described it pretty accurately in here: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-development-ideas 

If you don't want to, and don't know how to convince us why this functionality is important and should be added ASAP then it means the issue should be closed.

@JohnMaverick

I'm responsible for GitHub, and regardless of who answers in the issues, it's been to some extent consulted with me. The problem is that my personality is pretty difficult and I'm painfully honest, which it's not the recommended approach as far as public relations are concerned. We can assign someone else to do this, but a new problem will emerge, namely to what extent this new person can make decisions on their own.

Let's imagine that the community is discussing a new feature. The new person from YF keeps talking to you about the feature and whetting your appetite. Some weeks pass, you nicely described what you want the new feature to do and how it should work. However, from the business perspective the company doesn't want, or doesn't have the time to add this feature.

Now let's ponder what form of communication with the community is recommended. What is the problem? Is it the fact that we said "NO", or maybe the fact that apart from "NO" we didn't carefully describe why ["why no" can always be found here: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-development-ideas]? Or maybe the problem is that it's not you who decided whether or not this functionality is going to be added to the system, and if yes, who pays for it?

Notice that waran70 wouldn't even take screenshots to add to his description of this feature... maybe next time he is going to write "I saw a cool feature in a cool system, but I won't tell you what feature and in which system". Respect our time, because we have very little of it, and we still spend more time and energy helping the community than other producers like Vtiger, coreBOS, and Suite, and keep in mind that GitHub is mostly for you to talk to each other, and not for you to request freebies from us.
