### ISSUE TITLE
[Question] Is there a YetiForce forum anywhere?

### ISSUE THREAD

**Issue by UPSduck** [YetiForceCompany/YetiForceCRM#4559]
Is there an official forum for YetiForceCRM? 
I have not been able to find one anywhere. I think this would really help with the learning curve/growth of YF. As I'm learning to use it, I've had a number of questions about using the program that are not really "issues" with the program itself. 

1.) If a forum exist please do tell where and reference it on the site and github.
2.) If not can we get one started so I don't feel bad about posting here.

**Comment by sirwinston1** [comment]
If one does not exist we could just create a subreddit on reddit.com

**Comment by UPSduck** [comment]
That would be great! I don't have enough reddit points to create subreddits so if anyone is able to start it please include a link.

**Comment by sirwinston1** [comment]
I have never created a subreddit before, so I am probably not the best one to admin it, but I have no issues creating one

**Comment by sirwinston1** [comment]
https://www.reddit.com/r/YetiForce/

Yeti Team,  let me know if this is an issue for you and I will take this down.

**Comment by paula-w** [comment]
Hi guys,
this is @bpabiszczak’s answer:

You can create any unofficial YetiForce forums you want. We can’t forbid you from doing that, so you are free to use the subreddit you created. 
Right now we don’t have any official forums because we want to first make sure that our current channels are properly managed. We realize we should spend more time taking care of GitHub issues. Adding a new official channel wouldn’t make that any easier for us, nor for the users. 
Once the mail and GitHub channels are effectively managed we will gradually add more official channels, namely a forum and a chat.
