### ISSUE TITLE
Picklist not saved

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#459]
Setup a fresh v1.4 to avoid issues but ran into new ones:
When I create a custom block and add picklists to it I can add selections
After saving they are gone.
Tried to add them again in de admin/studio and again, they show up after I have entered them, switch few and all gone again. only seems to happen with additional (custom) lists.
Picklists were made in Contact module with custom block

**Comment by MaciejStencel** [comment]
I think I know what is the problem. Probably You entered the field name with capital letters. This resulted with picklists to not display picklist values in edit view.
It was fixed in 1.4.295 revision:
https://github.com/YetiForceCompany/YetiForceCRM/commit/f132df09aa6ca956d868272eb49010e69742d574

If it is not the case please add more informations, for example what data are You typing in the field creation window, we will try to replicate it.

**Comment by nikdejan** [comment]
I don't know if this is the right place for this, but in ver. 2.0.346, in Fields and Layout Editor fields of type Pick List can not be saved.

**Comment by bpabiszczak** [comment]
Please check here: https://gitdeveloper.yetiforce.com/

**Comment by nikdejan** [comment]
Same there. I wasn't able to add Pick list field to Contacts.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1552
