### ISSUE TITLE
Workflow Record Update

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4610]
#### Issue

Hi Team

I am use Workflow to sum two values and update other field with the result in same module (Opportunities), This Workflow ran every Hour, when finish recorded update in "updates" on the OP module. This action change the "modified time" in the record. I have use "Recording Control" to change Color if no update after 3 days for example. The Workflow change "Modified Time" every Hour and the "Recording Control" has Never Apply.

 Do you have any recommendation or code change?.

Thanks in advance.

#### Your Environment

* YetiForce Version used: Latest Stable
* Browser name and version: Latest Chrome and Firefox
* Environment name and version: Lab
* Operating System and version:

**Comment by paula-w** [comment]
I’m not sure I understand you completely, but if the problem is that when you change the field every hour in workflow it changes the modified time, then this is how it should work. If you don’t want it to change the modified time then you will have to do it some other way [for example changes directly in the database] because every operation that goes through Save automatically modifies the “modified time” field.
