### ISSUE TITLE
[Question] Regarding Mailscanner

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#4658]
#### Issue

Mail scanner scans mailbox and import mail to the CRM but does not mark mails as read.

#### Expected Behavior

I think it should mark the mail after scanning and import of mail and continue to scan only unread messages.
As far as mail binding the mail bind action can bind mails that have been read only

#### Your Environment

* YetiForce Version used: 4.0 stable
* Environment name and version: Ubuntu 16.04
* Operating System and version: Ubuntu 16.04

**Comment by KatarzynaUlichnowska** [comment]
There are two options:
1. The scanner logs into user's mailbox - in this situation, the scanner cannot change the status of an email because the user would always see all emails as read. I doubt anyone would like it. 
2. In any other case, it doesn't matter because the scanner knows on which email it stopped regardless of whether it was marked as read or not. 
We don't see the point of introducing this change. Of course, if you want to change that in the scanner script, you can do that.
