### ISSUE TITLE
Why is the editing of a single field not completed by pressing the Enter button?

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [YetiForceCompany/YetiForceCRM#4738]
Why is the editing of a single field not completed by pressing the Enter button?

**Comment by reeid** [comment]
Interesting indeed

**Comment by paula-w** [comment]
Because ENTER is used for different things in different places in the system. For example in multi picklists is used to accept the value, same situation in regular picklists. There are many different fields that work in different ways, the best idea is to add a save button next to the edited field. 
We’ll think of it when we optimize the system template, in several weeks.
