### ISSUE TITLE
Update bug#2 - Missed translation

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4742]
#### Issue

I tried to update from 4.0.0 to 4.1.0 and have found some bugs

#### Actual Behavior

After successful update all my self made or edited translations became missed

Logical to separate standard and user translations and merge them after update to avoid this trouble. 

#### Expected Behavior

Translation of some staff became standard or missed for new variables/labels

#### How to trigger the error

Update from 4.0.0 to 4.1.0

**Comment by mariuszkrzaczkowski** [comment]
All modified translations should be overwritten using the custom directory and the parameter should be enabled:
https://github.com/YetiForceCompany/YetiForceCRM/blob/2522af0826914ca97ee368b1ef2269fe51922263/config/performance.php#L66

If there is a missing translation, you can add it to GitHub, so you won’t loose it after an update. Translations are missing because people don’t want to add them to GitHub and they are gone after updates.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski where must be customized language file stored for module? Like on example for assets module: `// Ex. custom/modules/Assets/Assets.php`
