### ISSUE TITLE
PDFMaker - can I install Its4You paid version in Yetiforce?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4774]
Hi,

I was looking at Its4You PDFMaker and asked some questions of their support and they said PDFMaker should work with Yetiforce. I need the ability to insert related fields from other modules such as Contacts etc. It looks like Its4You PDFMaker paid version does this? Am I right in thinking the PDFMaker in yetiforce is a version of Its4You @joebordes would this be correct? SO if that is the case, could I install their paid versions without corrupting my system?

**Comment by vovpff** [comment]
I'm interested too because I have licence of PDFMaker pro.

**Comment by joebordes** [comment]
I'm sorry, I have no knowledge of Yetforce and no idea if PDFMaker works there or not.

I can say that PDFMaker works correctly on coreBOS, but nothing more.

**Comment by PercyP** [comment]
@vovpff  have you ever tried installing it to see what happens? on a test site I mean.

Sorry @joebordes I thought you were related to its4you :) please ignore me.

**Comment by vovpff** [comment]
@PercyP I tried to test this stuff at 2.x.x versions but there is no chance to use it because YetiForce layout and directories has a lot of changes and there are no ability to use this tool without modification.

**Comment by joebordes** [comment]
@PercyP , I invite you to have a look at coreBOS:

You can run PDFMaker and we also have GenDoc which can do this too.

**Comment by PercyP** [comment]
@vovpff 
thanks for update. It is a shame as for me personally this is a critical feature - if we have related content we should be able to show that in the PDF outputs. The field label in the PDF maker is a little misleading (for me at least) as I believed its purpose was to show the linked data. In my other post a member of YF team suggested it only requires a new function to add this option, if that is the case then it makes sense to add that function as it would add more power to the PDF maker. I did ask how much this would cost to add, but so far not had a reply (guessing they are snowed under right now with the pending new release).
@joebordes thanks for that, will check it out! However I am already heavily invested in YF now so not looking to move away.

**Comment by bpabiszczak** [comment]
@joebordes 
Whenever I look at coreBOS i remember the old times when I started working with Vtiger, it’s almost as if the time stopped. It’s incredible how much we changed in the system in such a short time. I regret that we didn’t manage to start cooperation [we are still open to this idea], because if we work together we would achieve so much more, especially because what is lacking in our system is well done in yours [eg. Documentation]. In my opinion we would complement each other ideally.

Let me ask you if I may:

1. When will you put Sensiolabs in order, because it shows a bit low quality of coreBOS after leaving Vtiger [Lines of code: 530,226, Nb of violations: 35321]:

![image](https://user-images.githubusercontent.com/10197525/29112651-ce47afa4-7cee-11e7-91e8-baddbf4ec44c.png)

2. When will you fix basic security for headers?

![image](https://user-images.githubusercontent.com/10197525/29112725-01e31916-7cef-11e7-917f-10233a0316f3.png)

3. When will you fix dozens of SQL injection errors, XSS, and when will you start following the basic safety rules recommended by OWASP for example? Has coreBOS ever undergone any security audits?

**Comment by PercyP** [comment]
@joebordes @bpabiszczak 

It would be brilliant if you guys did collaborate as @joebordes has some brilliant components that would be excellent in yetiforce :) fingers crossed it happens

**Comment by mariuszkrzaczkowski** [comment]
@PercyP
See what's new we added: https://github.com/YetiForceCompany/YetiForceCRM/issues/4666#issuecomment-321164493

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

just checked it in gitdeveloper - perfect 👍 thank you so much!

**Comment by joebordes** [comment]
just for reference: http://blog.corebos.org:8080/en/blog/corebosyeti

**Comment by PercyP** [comment]
OK, just read your article @joebordes you obviously have lots of issues with Yetiforce which I didn't realise. My apologies. You do both have good products. I think the one we choose depends on which industry we are in . I now feel bad as didn't realise there was bad blood between you. So SORRY!

**Comment by PercyP** [comment]
Can I also say @joebordes that it is sad you cannot both work together. As a user, we dont really care about your history together, all we care about is what works NOW for us individually, we care about the product and you could possibly be part of the process of making it better and also making money from that too - it doesn't make sense to me this animosity?

**Comment by PercyP** [comment]
I think too I was a victim of @bpabiszczak abruptness, but I soon realised it was more my lack of understanding and language barriers. I now 'get it' I think. You both have excellent and very complimentary products - it is such a shame you could not work together.
