### ISSUE TITLE
calendar sync, cron, script and davdroid

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#5074]
Hello :)

Davdroid is installed on our smartphones and has a connection. no mistakes. Set to pick up the appointments every 5 minutes. However the dates are not synchronized. ideas? cronjobs?

Our system runs at a webosting provider called allinkl.com in germany

We also get a feedback about the following script

```
<? Php
Exec ("/ usr / bin / php /www/htdocs/v152410/crm/cron/vtigercron.sh 2> & 1", $ out, $ result);
Echo "Returncode:" $ result. "<br>";
Echo "output of the script:". "" ";
Echo "<pre>"; print_r ($ out);
?>
```

![image](https://user-images.githubusercontent.com/20491699/29824291-6778d4a4-8cd1-11e7-9e14-0a811007981b.png)

thank you in advance ...

**Comment by mariuszkrzaczkowski** [comment]
1. Check if cron is working at all and if all taks finished successfully https://gitdeveloper.yetiforce.com/index.php?module=CronTasks&parent=Settings&view=List&block=15&fieldid=26
2. Find info in closed issues https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=✓&q=is:issue  cron 
3. Check coding of vtigercron.sh file, because problems might be caused by bad coding
4. If you can't call the sh file you can call the php file 
cron/vtigercron.php?app_key=xxx
