### ISSUE TITLE
Question: are you considering plugins to integrate with any accounting software?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5100]
Hi,

in the future, will Yetiforce be looking to add integrations with accounting software such as Quickbooks, Xero, MYOB? Also, Paypal payments?

These would be good 'paid for' plugins. I would certainly be happy paying for them in your marketplace. Don't see why everything needs to be offered free when there are people's salaries etc. to consider.

Maybe my wishlists are too great, be interested to know what other community members and Yetiforce think?

**Comment by paula-w** [comment]
YetiForce wants to expand the system to ERP, so we are not planning any integration for CRM/ERP class systems. Version 5 will most likely have PayPal integration built-in.

Some clients order integrations dedicated for ERP systems [eg. SAP, Exchange, ETL/ESB], but these are individual cases and we’re not planning to publish them as modules, due to the fact that each of these integrations is realized individually and adapted to the client’s environment.
