### ISSUE TITLE
Separate crm logic while installation 

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#5112]
Was thinking if this will be wise to install logic and relevant modules as per business case:
1. Company which selling services and products (standard installation)
2. Company which selling only services
3. Company which selling products only

**Comment by paula-w** [comment]
We know that the system should be simplified, what you described is understandable for us and we want to simplify the installation process as well as enabling/ disabling entire processes in the future. However, right now we don’t have enough time for that, that's why I’m closing this issue and we might come back to it soon, and to other ideas as well.
