### ISSUE TITLE
Would anyone be willing to split the cost for an OCR module?

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5156]
Just wondering if anyone would be willing to split the cost for an ocr module. 

1. Search within documents
2. upload and create records
3. tie in with users already on the system

Just wondering if anyone would be willing,.

**Comment by waran70** [comment]
How much will it cost? What engine?

**Comment by alextovey** [comment]
Not sure of the engine however i've found a developer who will set this up for £400.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
we can roughly estimate it for £300, but to be able to estimate the cost precisely, we need some more info:
Ad. 1  Search within documents - which document formats?
Ad. 2 Upload and create records - how the system should recognise to which folder it should assign uploaded records? And after the upload, which fields should be filled in?
Ad. 3 Tie in with users already on the system - how should it work and again how will the system know to which user it should be tied in?

**Comment by alextovey** [comment]
1. PDF's, DOCx's
2. you get a box on create record/upload to assign which category
3. already tied with users for documents but jsut able to search within them.

Basically upload and select which record to create. Normally it would be the custom module *candidates

Then you can search fields such as job title, education, address from the field.

**Comment by alextovey** [comment]
@waran70 @PercyP

**Comment by alextovey** [comment]
anyone there? do i have to open a new ticket for this? @KatarzynaUlichnowska

**Comment by paula-w** [comment]
This year we received around 100€ from donations… so we’re not very surprised nobody wanted to chip in. And it’s probably better because due to our mistake we posted a wrong estimation of the cost -  the price would’ve actually been about 4.000 – 6.000€. 
We’re closing this issue, maybe in the future it would be good to use some external financing platforms like [kickstarter](https://www.kickstarter.com/ ) for example.
