### ISSUE TITLE
Feature request - ability to deselect the mandatory and enabled option of the default field created during new module creation

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5209]
Hi,

a minor feature request:

When creating a new module we don't always need a text field, but this is the only field type available during the creation process. 

There doesn't seem to be an easy way to get rid of (or disable) the default field that is created (without going in to the database and first making it none mandatory) - it doesn't currently allow us to make it none-mandatory via the Edit module/fields section as when I click on this it does nothing - it is locked on mandatory and enabled. 

I realise there needs to be at least one mandatory field during module creation, so if we were able to then create a new field in the editor, and then be allowed to change the settings for the original default field (or even remove it, it would be good).

**Comment by paula-w** [comment]
Unfortunately, Vtiger didn’t have any documentation for the system, and we don’t have it either [but we’re currently working on it] that’s why you have to be careful not to disable a filed somewhere that is used because the system might stop working. That’s why many fields are marked as system fields and can’t be disabled. You can change it here:  https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/developer.php#L10
then you will be able to disable/enable system fields in field editor, but you might break the system, so please do that only on a testing version. 
Our devs use vtlib to create modules, nobody uses this panel. This panel has a very limited functionality in comparison to vtlib.
