### ISSUE TITLE
[BUG] Lead obtained in Leads

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#529]
If the Leads rename status Lead obtained to the other, then the conversion is not possible to do. Necessary to fix this position so that you can change the name, and make the conversion.

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, we are not able to do anything with this issue, because we don’t understand whether it’s about renaming of a lead name or a lead status.
Please follow the points from this article to describe bugs:
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html
Please open a new issue when you describe it in detail.
