### ISSUE TITLE
Question PBXManager

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#5297]
Hi all!
Question to the development team, at the expense pbxmanager... (not to be confused with pbx)
What is his fate? whether it will be completely removed or it will be supported?
If your plans include fully getting rid of him, could you render it as a separate package? I would find it very helpful, and I think other users comuinity.

I've done some work on this module, starting with version 3.4, at the moment stand changes on 4.2 version in the near future will publish changes to this module if this will be of interest to the community . Has been completely redesigned VAC and large changes to the module (except JS\ Forms)

a small example: 
![default](https://user-images.githubusercontent.com/15871611/31095715-7c062e6a-a7c2-11e7-9667-23055804ad6c.PNG)
![bcxojaw0fp](https://user-images.githubusercontent.com/15871611/31095834-d6902b6a-a7c2-11e7-935f-e0eed6b1aa43.gif)

**Comment by migoi** [comment]
keep it please. I've my modifications inside that module and want to use it in future.

**Comment by alextovey** [comment]
Does this work with sip trunks? using srv records?

**Comment by migoi** [comment]
we have a own voip pbx software. Its working with that (and that one is working with sip trunks).

The module will work together with a pbx software, not replace a pbx software

**Comment by alextovey** [comment]
Does this mean that the PBX needs to be physical? As all our phones are hosted on a cloud platform using firstcom.co.uk or firstcom Europe.

**Comment by migoi** [comment]
no, its working with software pbx like Asterisk

**Comment by bpabiszczak** [comment]
In my opinion [but I did not verify whether that's correct] this module is "old", which means that the code should be rewritten, and additionally, nobody has performed any security audits for this part of the mechanism so that would have to be done. The worst is that the integration must be written from scratch in such a way to make it work with the newest Asterisk version, to fully use Asterisk Manager Interface (AMI).

In my opinion it should be removed from the system and added as a separate module [it can be free]. We don't currently have any plans to integrate with any phonebox because none of our clients needs it. The last client who ordered it used a different phonrbox and we connected through a special API there.
So the question is if we can remove it and you could send us the new module that everyone can install and use?

**Comment by migoi** [comment]
well the problem is not to create a module, but right now the is no "external module concept (import/export)" that i know of. I'am using this module for our kind of PBX (no asterisk).
i can understand why you drop some modules (in past and in future), but without a module / plugin system its quite hard to provide a module.

**Comment by bpabiszczak** [comment]
I don’t understand, there is the panel to create modules in the system and the possibility to import new modules. So I don’t understand, what is missing according to you?

**Comment by migoi** [comment]
e.g.
does it create basic database tables, add fields and so on?
how to add files to the .tpl folders?
How to change basic filetype representations, so that click on a phone number can invoke the PBX to dial?

**Comment by bpabiszczak** [comment]
Regarding the PBX question, it seems to me that I have already answered. PBX is developed by the community, as we will have a deployment  with PBX, so we will most likely remove it and create it again.

Regarding questions from @migoi   - I don't uderstand them. They aren't related to this issue, so if you still have questions, please create a separate issue.

**Comment by kjradv** [comment]
@bpabiszczak , Could you move this module into YF scripts?

**Comment by bpabiszczak** [comment]
@kjradv we will do it when we will want to remove this mechanism, at the moment it is a part of the system, so it will stay. Or maybe do you want us to separate this mechanism?

**Comment by kjradv** [comment]
Within a month I am ready to provide updates on this module with the updated AC for the latest version of the asterisk.
I can post the update version in YF scripts.
a small note: in any case, additional community tests will be required

**Comment by bpabiszczak** [comment]
Remember that there are two mechanisms in the system to make calls.

1. The old one based on PBX [https://gitdeveloper.yetiforce.com/index.php?module=PBXManager&parent=Settings&view=Index&block=5&fieldid=29]

2. The new one that was developed for a customer a while ago [https://gitdeveloper.yetiforce.com/index.php?module=PBX&parent=Settings&view=List&block=5&fieldid=15]

If you create something, try to comply with a new mechanism, which is very simple [example: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/Integrations/Pbx/Mixpbx.php] because the old one will be removed for sure.

**Comment by kjradv** [comment]
Okay, thanks for the info.
