### ISSUE TITLE
OSSMailScanner - YF 4.2 save attachment implementation is broken and has other issues

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#5335]
Hi,
since I upgraded to YF 4.2 all imported emails lost their attachments. The cause is the same as in issue #5333.
Beside the fact that the web/vendor/yetiforce/Fields/File.php function saveFromContent() is broken, I have questions about the following design decisions:

**1. The filepath is hardcoded to the cache folder**
Correct me if I'm wrong but isn't the cache folder for non-persistent data and the storage folder for persistent data. As attachments are quiet important, shouldn't they be saved to the storage folder?
Also shouldn't the filepath be configurable by a config variable?

**2. Saved filenames are not made unqiue.**
If a client, as part of an email conversation, exchanges different versions of a document, the attachments in all emails can have the same name. The current implementation always overwrites the attached document with the latest version.
 
I don't understand the reason for these changes, the YF 4.0 way made sense to me and worked well.

**Comment by bpabiszczak** [comment]
1. As far as I remember, after you migrate to 4.1 [or 4.2] you should download all emails again, because we moved public_html and before that change the paths were hardcoded.
2. In the newest version that we will release [4.3] the error related to file names and storing in cache will be solved.
3. All the changes you described including path changes are due to security issues. The cache folder should be used only for temporary information that the user needs during the session time, the cache folder is cleaned from time to time.
4. The storage folder is a place where you store users' data and we don't delete anything from that folder. It can be separated to an external drive resource because most often it contains email attachments so it's usually quite large.
Are these answers enough for you?
