### ISSUE TITLE
New version of YetiForce Public License

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#5337]
The new version of the system - **YetiForce 4.3** - will be released under a new version of the license. In our opinion, the new version is better and simpler than the previous license which was often ignored. The license that we are suggesting now is based on the MIT license but it has two additional limitations, which we want to discuss with you. 

The first limitation is the **obligatory registration of the product**, by both - the company that uses the system and the company/ies that develops the system. Why is it important for us? First of all, thanks to all the info [once we know who ACTUALLY uses our product] we will be able to better select the scope of changes in the system. The other crucial reason for this is the marketing side - right now YetiForce is used by several large companies worldwide, but nobody knows that. We want to change that, so when companies consider choosing our software they could check the list of companies that already use our solution. This piece of information is certainly important for our potential partners because for them it is another argument that helps them find new clients. 
 
The second limitation (that was also present in the previous license) is the point that **prohibits deleting the footer**. We want to protect the work that we provide free of charge. For us, the footer is kind of a marketing tool and helps us build awareness around YetiForce. In special cases, we allow to delete the footer but it will require our written permission. 
 
Keep in mind that apart from YetiForce Public License v3 there are several different licenses in YetiForce. We will ultimately get rid of all libraries that are released under any other license than MIT/BSD/LGPL/VPL or our own license. However, this is going to be a year-long process. 
 
**New license**: [LINK](https://docs.google.com/document/d/1sejaD8uVB206-KIcDPlQjNmc1kG4aARrvTVUxl-UD-c/edit?usp=sharing)
 
Let us know if you have any questions or comments about the new license.

**Comment by migoi** [comment]
Register data:
You should make clear what is happening with the gained data (e.g. exclusion from reselling).

**Comment by reeid** [comment]
Customization very often requires changing footer. This is a bit too harsh approach to open-source app. I believe registration is enough, as you can target admins but forcing users to see footer might not be seen attractive

**Comment by PercyP** [comment]
I think this is fair, but one problem for me is I want to implement a third party chat component that requires the entire footer area to itself. So is there any other way we can display your marketing/some additional options for placement? For example, how about about at the bottom left of the side menu? Maybe a link to an About page with the yetiforce icon? Or somewhere else?

**Comment by KatarzynaUlichnowska** [comment]
@migoi That's a valid point, we will correct this and ask you to verify it again.

@reeid We don't remember if we have ever changed the footer. If so, it was only because the system template changed but the new template also had the same footer but it just looked differently [the new license allows it]. We have performed hundreds of implementations, so we don't really know what you mean. If somebody really needed to do something with the footer, then they removed it or changed data to their company name... but is it good for the YetiForce community? I doubt it. We treat the footer as a tool for building YetiForce brand unless you prefer paid modules and ads when logging in just like in Vtiger.
We invest from 10.000 - 20.000 EUR a month in this system, if someone doesn't want to leave the footer and doesn't want to write to us for a permission to remove it, then unfortunately, this person will have to adjust and accept it.
You need to support your opinion with more arguments if you want us to consider it.

@PercyP Can you add a screenshot? We don't really know what you mean, so it will be easier if we see it.

**Comment by PercyP** [comment]
@KatarzynaUlichnowska 

I haven't actually managed to set up my third party chatbar yet, but a number of years ago I had it working in a vtiger instance. I am hoping I will be able to do the same in Yetiforce. It basically sits across the entire footer area. What I meant in terms of promoting your brand is could it be included as a side menu link (see image). Or elsewhere on the page?
![yeti](https://user-images.githubusercontent.com/10598886/31708824-0fd694dc-b3e8-11e7-9051-7f0d80de6beb.png)

**Comment by KatarzynaUlichnowska** [comment]
@PercyP Do you want it on the left just because you need the entire footer for the chat? You can use modal windows or something similar to FaceBook or YetiForce (a chat window that you can hide). I haven't seen this specific chat that you're planning to implement, so it's difficult to picture it.

**Comment by PercyP** [comment]
@KatarzynaUlichnowska 
yes, the chat fills the entire footer area, but I was just wondering whether it could be added above or below the existing one - as a new line or something. I am not ready to try integrating it yet, but when I do I will show you. It isn't a standalone chat, it is one that is connected to my external website. I am still using the yetichat for staff etc. but the other chat has a totally different purpose. I can park the idea for now, but just wanted to mention it in case it breaks some requirement of yetiforce for marketing your product. Maybe when I get round to it, you may agree/allow me to add your branding elsewhere.

**Comment by reeid** [comment]
@KatarzynaUlichnowska 
Open Source becoming kind of trap. Everybody used to think: OK I got opensource code and I can do whatever I can with keeping original part of source untouched or mentioned in "source" where is the source of amended code. Now we facing kind of situation where "Open Source" is not really than open as it is taken from the beginning of this philosophy, but is is defended by so many various licences allowing, or forbidding for some particular things. 
Now I can feel we go out of "open source code" as you requesting to "show you up"  in the "front-end of application". How it suppose to be understood? I believe it is kind of AGGRESSIVE marketing with use of modified (born standardized) licenses for the purpose of targeting potentials. 
Is it fair? NO in my opinion. You building too many controversial elements. Think future guys..... stop limits but target new areas with honest approach and hard work (as you do so anyway).
What new surprises you gonna include in new releases?  Aggressive marketing, unpredictable core changes, makes yetiforce a minefield for experienced developers.  If you like that way... carry one than... but this may lead you to nowhere. Self-centered mind is behind your philosophy.
Just to highlight you potential - I screened contributors.  1.  Not many, 2. No great git history, 3. Most of them are language specialists (localization).

Best!

**Comment by waran70** [comment]
Any mechanism to control whether footer has been changed or not will be implemented?

**Comment by KatarzynaUlichnowska** [comment]
@PercyP Why do you want to add chat in the footer and not on the right side like at FaceBook? The footer isn't just the best place for that...

**Comment by PercyP** [comment]
@KatarzynaUlichnowska 

it does make sense when you see it I promise :O). I can put tools and extra links on the bar. BUT maybe in Yetiforce having just the chat bit to the right might actually not be a bad idea!

**Comment by PercyP** [comment]
@reeid
I don't see it as 'aggressive marketing' I see it as 'giving credit where it is due'. What is wrong with that? Having 'Powered by Yetiforce' isn't invasive. With most open Source developers they let you use their product for free which includes displaying their branding in a prominent place. If you don't want this, then you sign up to their subscription package or purchase their full product - why should Yetiforce be any different? Would you prefer they work tirelessly for nothing producing this system? How will they pay their bills, earn their living? They need more clients (just as you/we do) and this is a small way of achieving that. Whilst 'taking', why not also give a little back? It doesn't matter how their community breaks down, whether they are mostly translating etc. (which isn't the case anyway). This community will continue to grow and evolve ... as long as people are willing to support their growth. 
What are you doing with their product? Are you/will you ever make money as a result of it? How would you feel if your customers told you they wanted everything you offer for free - Oh and no - they don't want to tell others how good you are to help you get any other clients!
Sorry, I use lots of open source products, and I value what I use and have built great relationships with some of the developers - it isn't until you hear their stories of how hard/long they work, the financial costs they endure, that you see the true cost of Open Source - it certainly isn't free for them.

**Comment by paula-w** [comment]
We made some changes in the draft (highlighted in the document I linked in the issue). The license now includes the changes proposed by @migoi . Thank you migoi for the great suggestion, we appreciate your feedback.

**Comment by bpabiszczak** [comment]
@Reeid
There are hundreds of different licenses for open source software. Each of these licenses has its pros and cons. Check out SuiteCRM's license, it uses AGPL, one of the worst licenses in the world business-wise. The idea of open source has not changed in our project, you can do whatever you want with the code as long as you register the product and keep the footer. These limitations don't bother 99% of the companies who use the software... and even though they'd prefer the footer to display their company's info I haven't met anybody who'd resign from using the software due to this reason; especially that many open and commercial projects have the same conditions [often resulting from the license].

As I understand the registration of the product where no contact info is sent [only publicly available company data] is not the problem, so I assume the problem for you is keeping the footer. If yes, then it's probably because you change yours, but what benefit has this brought to the YetiForce community? Does removing the footer have any business value for our community? The only companies who remove the footer are either companies who implement this system and want their clients to think it's their system, or big companies that want to remove the footer so that the employees don't know what system they're using. Neither of these reasons convinces me, because if I invest 1.000.000€ over a period of a few years and then there's someone who doesn't even want to keep the footer, then maybe it's better that he doesn't use the system, because it seems he doesn't understand the idea of open source. Or maybe you prefer the AGPL licence of SuiteCRM?

You confuse brand building for marketing. CRM class systems require implementation, and in order to implement anything you need to find a reliable company with adequate experience. If someone already has YetiForce then it's due to the fact that someone, or the IT department installed it for him. Marketing happens before the installation, and brand building happens after the product is already installed, especially that we don't attack people with ads while and after logging in.

Unfortunately, instead of having a substantive discussion you turn it into a dispute without arguments and mud-slinging. We have a much better git history than Vtiger, Suite, Sugar, ODOO, EPESI, coreBOS and hundreds of other open source CRM projects.

Tell us honestly, why does the footer bother you so much, why do you want to get rid of it so badly!

PS.: Let me remind you that you can apply for the consent to remove the footer, which is written in the license

PS2: All our actions realized in YetiForce were dedicated to the good of our community and our clients; the only difference between us and the community is the fact that often people who post here care only about their own needs, not about what's good for the entire project.

@waran

No. Neither will we force people to register the product. We want to remove the registration popups that keep appearing, they are too annoying.

**Comment by PercyP** [comment]
@bpabiszczak 
> No. Neither will we force people to register the product. We want to remove the registration popups that keep appearing, they are too annoying.

Again, this doesn't bother me. Only right now, I am putting my copy on lots of spare domains I have purchased to try different things within the CRM so I don't mess up my main copy, so I don't register them as there is no company attached to them (only me :OD) and this would be misleading yetiforce. 

> PS2: All our actions realized in YetiForce were dedicated to the good of our community and our clients; the only difference between us and the community is the fact that often people who post here care only about their own needs, not about what's good for the entire project.

Also, a lot of open source developers end up becoming 'people pleasers' by trying to keep everyone happy. Its brave to stick to your vision, as afterall, you didn't set up your company to make the product every individual thinks they should have, you set it up because you have ideas of your own. The beauty of yetiforce and other open source is it provides us (the community) with a a baseline and an opportunity to tailor and shape it in to something unique to us

**Comment by setras** [comment]
I agree with @PercyP, for the majority of clients using Yetiforce, a registration and the footer is not an issue. As @bpabiszczak  stated when it becomes an issue, it is either you work with a large organisation or you're creating a public product on top of YF. In both cases you can ask for consent and that's good, may other licenses do not give you this option.
In my humbled opinion, when you make money of other people hard work, they are entitled to a portion of you're earnings.

@paula-w one word of caution, be careful when publishing a companies name based on only the registration. May names are copywrite protected and you'll need the explicit written consent to use them. A registration by itself is not good enough because you don't know if the person who filled out the registration has the authority to give you this consent and legally it is your responsibility to ensure you have the consent from the copywrite holder.
Last year in a similar circumstance one of my clients had to learn it the hard way in court.

**Comment by paula-w** [comment]
Thank you very much for the advice @setras , we will look into that.

**Comment by PercyP** [comment]
@setras 

> In my humbled opinion, when you make money of other people hard work, they are entitled to a portion of you're earnings.

I 100% agree with this. If there was a mechanism to implement this i.e. paying something for each copy we distribute so that yetiforce get something out of it too I think it would be good. I think that is how some other open source developers do it - so you pay some kind of licence fee for each instance of it. 
Me personally, I don't know enough about how open source is supposed to work, so I come up with these ideas without much understanding and consequently may offend people with my suggestions?

Agree with your word of caution.

**Comment by setras** [comment]
@PercyP, I'm not a believer in putting such enforcement in place because it is always in some way annoying.
YF is still quiet young and since the fork from vTiger the YF team made a lot of fundamental changes. Right now this makes it difficult for the community to contribute. More transparency and open discussions about changes in advance wouldn't hurt but I really like their predictable release schedule and code quality.
There are different ways to pay your dues:
- donate
- contribute
- both

Every community has contributors, consumers and leeches and I'm sure the YF team is fully aware of this and treats them accordinly.

**Comment by PercyP** [comment]
@setras 

yes you are right. Also agree what you say about yetiforce updates etc. and communities generally.
I suppose vtiger started by forking was it Sugarcrm? and yeti have forked vtiger (as have coreboss etc.) the list goes on.
I would like to 'give back' financially once I get my own thing going, so I will look at how to do that in the future. I would contribute more, only I don't have the skills yet - other than testing/reporting bugs etc.

**Comment by bpabiszczak** [comment]
@setras

Thank you for the warning, we know about it and we consulted it with our law firm.

@ All 

We've been rebuilding the security and engine for a couple of months now; those are very expensive changes that won't be noticeable for a regular user. However, they are necessary in order for large companies to consider our solution suitable for them, but the most important value is that we reached a new level of programming, which means that in the future all changes will be simpler and easier.

We are very grateful for any donations, modules, and other paid features you are suggesting and ordering, even if they are just a small portion in comparison to what the system is worth today and how much it will be worth in the future. We earned 250.000€ on one deployment, and it's just the first step on our road to large deployments.

You have to trust that we know what we're doing – we think about the development of YetiForce every day and we take into consideration every possible scenario. As you see we are the only company that doesn't try to make small companies pay any kind of fees. We operate in a different way than SuiteCRM, VtigerCRM, or many other systems do. But at the same time we want to build brand awareness and it's our main goal.

I know that you want to take part in discussions about changes in the system, but in order to be able to do that, the community must be more committed to the project, then the community will get the necessary tools to actually influence the direction of our development. Right now the community isn’t very involved [I mean the community as a whole, because there are some members whose contributions are significant] that’s why you have little influence on the system.

Licensing is very important, there are many projects like SuiteCRM for example that has been breaching the license for years, and we want to avoid it in all stages of the project, that's why we simplify the license and get rid of the vague or inconvenient ones, so that we can use them in large commercial projects keeping in mind that the project will always be open source, free, and to make everyone know they are using YetiForce!

**Comment by paula-w** [comment]
The new license has been published, thank you for your feedback, we appreciate your help.

**Comment by waistracloud** [comment]
What are the special cases to remove the footer? Not have any issue with this term but just curious to know.

 @paula-w

**Comment by raviktiwari007** [comment]
This is simply cheating and lying. And Yes, a SCAM.

Yetiforce itself was created by forking someone else's code and now they are charging people to just maintain that code. What is their contribution? If you want money, write your own code from teh scratch.

SugarCRM is a dead project from where all started. So why someone cannot pick Yeti code, forks it and make there own CRM - "FeeltheForce" CRM. How can you challenge him/her? How dare you?

To ensure everyone is aware of the fact: Yetiforce has already lost the battle with the licencing organization... there are still trying to be creative with the words (lying) as they have been creative with the code (stealing) but the licencing body seems to be smart enough. Here is a link for all of you to review:

http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2018-June/003381.html

Now that makes me wonder, can I just fork it and move on (as if I dont care) or shoul I let Yeti team respond here and say, Yes everyone.. you can edit it, as you wish. 

If they say No, I would be tempted to sue them for using the word "Open Source" for illegaly funding their project. I am more than happy for them to open a charity or an enterprise and sell their product. But when you are in open cource zone, behave like everyone else. Writing an article on your website "Does Open Source means Free" does not solve anything - especially when it is not open for people to comment on it.

Pls get out of open source zone ASAP or be ready to be sued. If you want to enjoy the benefit of open source (free codes, free help, free funding) then you better behave like open source community and make your code free for editing and usage. There are millions of open source companies and no one needs moneys to run the company... no one has T&C like you, so stop this nonsense. I am very passionate about open source and therefore I am really angry at this nonse... I might end up seeing you in the court for this white lie, fabricated stuff and the scan that youa re running under the opensource hood.

Thx: Rav

**Comment by bpabiszczak** [comment]
@raviktiwari007 

You wrote a whole lot of nonsense both here and in the email you sent us. You should have consulted your legal team before you started criticizing and spreading misinformation, then the discussion could maybe be more substantive. 

YetiForce consists of more than 100 different libraries, each of them under a different license, including SugarCRM and Vtiger licenses. We selected these licenses in such a way that they can be combined without problems. All VtigerCRM files (30% of the code) or SugarCRM files (0.4% of the code) are licensed under their original licenses. When we fork something we cannot just change the license to anything we want - we have to stick to the original licensing. 

The YetiForce license only applies to the code developed by YetiForce (and nothing else), so as the producer we have the right to share our own code under our own license. Our license is open, and doesn't limit the company in any way (all they have to do is register the product and keep the footer intact). It, however, limits the competitors who would like to “sell” YetiForce under their own brand and remove the footer (we don’t allow it and we have the right to do so).

Our system is open, which means everyone has access to the source code and can freely modify it (minus the footer), this is what open source is all about. In addition to that, YetiForce is also free. Our license is much better than the toxic AGPL and OSL licenses and we’re not planning to change it. Additionally, the license requires registration of the system (all we ask for is the name of the company, website, and address without the street name), it’s nothing confidential or embarrassing. If you’re ashamed of what your company name is and in what country and city it is located in, then I guess this is not a license for you. You don’t even have to provide your name/last name and email address (it’s not obligatory, the popup can be ignored).

I don’t see any reason to debate this any further, unless you get your facts and manners straight.

**Comment by raviktiwari007** [comment]
It is not about providing name and email id... it is about your forcing opensource community to keep your logo. If this is opensource, this is opesource. Period.
If it was a request to use your logo and support grow your brand, I would have loved to do it as a opensource fan/promoter, but if it is T&C, then I have got my rights to question you because if we don’t agree, I can go ahead and pick another software/application – there are 100s of such application out there – may be few of them need help from wider organization to make it better, and that is what opensource community is for.

I fail to understand and agree with the conflicting statement of, "Our system is open, which means everyone has access to the source code and can freely modify it (minus the footer)". How does this make it open?
You know what is open source? Moodle is open-source, Ubuntu is opensource, Webmin is opensource... I am sure you know many more. My gripe with you guys / your company is: you did not code this software, you forked it and now you want money for it... what abt those people who contributed to your code in the first place?
And so when you say: “The YetiForce license only applies to the code developed by YetiForce (and nothing else), so as the producer we have the right to share our own code under our own license”, I agree with you, so pls licence your code and un-license other parts that you forked from opensource… if you can’t do that then you cannot use a blanket licence (in the name of your licence and take credit from thousands of people who contributed to the core code). What are you paying them? Are you sharing your revenue with those developers and testers?

Just like you, why can't I fork your code, make changes and use it as if it is my software and I will have my own open source licence on it - like you have created a special licence for you. I don't care if this is a new thing coming up in the market and people have given up debating and have agreed to use your logo (unless it is a request).

For me, this is not an opensource license, despite the fact whatever nonsense you spread on the internet... I have already provided links where your licence was declined because of the ill-practice that you were trying to bring in.

I understand you have put time and probably money in it and you would like to recover that... so on top pf my head I can think of 3 simple ways you can do that:

1. Request people to use your logo (Not as T&C)
2. Whitelabel it and sell it as a commercial product using your own name and brand.
3.  Put some extra features that is available when someone buys a license/subscription - but that feature should have been developed by your employees and not forked from opensource.

And just so you know, I am not interested in your product as this is against my principle to use such software which basically promotes slavery - gets the job done, pays nothing and makes money by selling it under their name.

If you still don't get the point, then just leave it here because otherwise, I have got loads of time and I can reply back to you in harsher word than what you are trying to do here. Just because I said something that does not match your opinion does not make me less mannered than you. Have some courage to listen to another opinion as well.

**Comment by bpabiszczak** [comment]
@raviktiwari007

You are new here, you come and demand changes because you don't want to respect the established rules. What have you done for the YetiForce project to impose your ideologies?

The license is very simple, you can freely change the system as long as you register it and don't remove the footer. These two principles allow us to build our brand and promote the system in the world, without spending a penny on marketing. It doesn't matter if you agree with it or not, it doesn't even matter if you consider it open source. It's enough for us that this license is great for our customers and other companies from around the world that download and use the system every day. If the license doesn't suit you, then as you wrote, there are a lot of other systems, e.g. VtigerCRM, oroCRM, SuiteCRM. Certainly, other licenses will be better for you.

I will repeat it one more time, only our code that we created ourselves [or in cooperation with partners] is licensed by YetiForce. Is this clear to you? Because I have the impression that I will have to write it a few more times. All other libraries/frameworks used in the application are listed here: https://gitdeveloper.yetiforce.com/index.php?module=Vtiger&view=Credits&parent=Settings. Loading libraries is organized and if you don't want a library, you can always replace it with a different one, just modify these files and change your system to make it compatible with them:

- https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/yarn.lock
- https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/package.json
- https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/composer.lock

When someone installs YetiForce, then they accept our license but also all other licenses of related libraries [there are ~ 150 of them], it was clearly described during the installation. If you don't want any of them, then delete its files [you can even delete all YetiForce files under the YetiForce license if you want] and name your system "small carrot" and release it under the license "small carrot open source" then in the footer you can have whatever you want, even "red carrots are healthier than the green ones." This is open source!

If you want to design your own project, then do what we did 5 years ago, look through all open projects and choose the one which can be easily forked. Our license is one of the best licenses for business [it is much better than the GPL, AGPL licenses, which are "very viral".

In regards to OSI, they claim that writing in the license that employees or private individuals don't have to register the product appears unfair to them. In our opinion, it makes it easier for hundreds of thousands of people who test the system for private use, but for FOSS it is breaking the rules of equality. What are we supposed to discuss with them here? FOSS should be penalized for adding and approving the AGPL and OSL licenses because these licenses were created in such a way that everyone would break the license.

What you wrote is not an opinion, you want to create a fork and cry because you will have to leave our footer. Please note that this is a very good outcome for the YetiForce community [by creating your fork, you are promoting ours!]. Accept it or go somewhere else.

**Comment by waran70** [comment]
"small carrot" bit me down
