### ISSUE TITLE
Reports privileges

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#5440]
#### Issue

No have essentials privileges in this module, for example,edit,  Mass edit, duplicating, export to pdf, etc.

if the user does not have administrator permissions, he cannot edit any report.

![image](https://user-images.githubusercontent.com/3030997/32118985-247345f4-bb2a-11e7-95a3-743b2b336a72.png)

#### Your Environment

* YetiForce Version used: 4.2.419.
* Browser name and version: chrome and firefox (latest version both)
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
¿?

**Comment by bpabiszczak** [comment]
mistake

**Comment by migoi** [comment]
I've implemented basic create / edit / delete. Should I wait for 4.3 before sending pull request?

**Comment by mariuszkrzaczkowski** [comment]
best to send immediately, it will be time for tests

**Comment by bpabiszczak** [comment]
It appears that this module isn't a standard module, so it means that adding an action won't change anything, this action should be implemented.

An even greater problem with the reports module is the fact that it will be REMOVED, as well as the "WORKFLOW" because these two modules are the most outdated in the system [the code is over 10 years old]. In 2018, al lot is going to change in these two modules. 

I will close this issue because the reports mechanism will be rewritten for sure in the near future.
