### ISSUE TITLE
Question - Recording control missing

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5451]
v4.3.433 Are they removed from the system?

![35d25531-30d3-4a20-9adf-20e218528c90](https://user-images.githubusercontent.com/19627226/32257421-9d826b6c-bee7-11e7-8119-a777fc7ff4d1.png)
![690a99c6-709d-48cd-a788-8a022322be00](https://user-images.githubusercontent.com/19627226/32257422-9db6b7b4-bee7-11e7-822a-507a211d1b21.jpeg)

**Comment by kpaulaha** [comment]
That would be a big loss!

**Comment by JohnMaverick** [comment]
Would  be nice and fair to post intention and reason of ANY important changes in system. Don't mean core improvement or adding functionalities but REMOVAL  of modules/functions.
Various processes might depend removed functionalities and people might be left with bad feeling of unpredictable development. Roadmap could help too

**Comment by kpaulaha** [comment]
Roadmap has been asked for a few times during the years, I think not going to happend. It for sure would be great to have one telling what is comming/going as e.g. SuiteCRM has. We have one yf installation in serious use, I think it's 2.3.46 and it has been working well since and never ever will upgrade it. After that we have not had the courage to use yf in any case, because never knowing what is removed from next version and having problems with upgrading existing functions and sure there has been some for us serious bugs also. Now we had one case planned on 4.3-4.4 but this removal ruined it, because one function was built on recording control. So back to the basics. 
Anyhow I like yf a lot, think it can become on of the best, at least if the community (is here a community?) could be heard also. I would also like to have RC versions before the stable. Not much idea to test the developement version, when it updates several times a day. Now every release is a kind of RC. But of course the developers do as they like and we go with that and waiting.

**Comment by waran70** [comment]
Pretty similar actions you can achieve using workflows. I thing better is to enhance workflows module, than overload admin part with various modules of close related functions.

**Comment by ezbank** [comment]
@waran70 I do not think workflow can be done at the present time
![fc99ce0c-f474-4e5b-9bab-d19035a9cc42](https://user-images.githubusercontent.com/19627226/32307007-beae0ec6-bfb0-11e7-8c36-63c5107bc125.jpeg)

**Comment by bpabiszczak** [comment]
The module has been removed due to security issues. Due to wrong implementation [wrong system layer] we can’t do anything with it apart from removing it. We didn’t plan to do that, but it’s a result of an external audit that indirectly forced us to do so.

Just like waran70 said, there should only be one mechanism, and the right one seems to be Workflow, the problem with it is, however, that it’s one of the oldest modules and we either have to rewrite it from scratch, or spend weeks improving and fixing it. The same applies to Reports, Language editor, iCal. We keep thinking what we should do with them. From the business perspective – it’s better to introduce changes now when the system is used by several hundred companies, than in 2 – 3 years when the system is much more popular.

@JohnMaverick – each change we make is for the benefit of the system and its future users! This is our number one priority, it will not change as long as I’m in charge of what the priority is! Nobody suffers from these changes more than we do, which means that we thought them through at least a few times. You can check everything we do on GitHub, nothing can be kept secret, but we won’t discuss changes in the system until the community steps up and starts contributing more to the project. It’s up to you how much you can influence the project.

@kpaulaha – Roadmap in the version of SuiteCRM is not worth much, each time they plan to patch errors but they have more than 520 opened ones. Remember that SuiteCRM is published under AGPL v.3 that is not favorable for the majority of companies.

If you compare the code quality in SuiteCRM and YetiForce the choice will be obvious
If you compare the number of changes introduced by devs in SuiteCRM and YetiForce the choice will be obvious
If you check the module prices for SuiteCRM then choosing YetiForce will be obvious.
If some version is removed from the system and you need it, you should order it so that it would appear in the new version. Holding on to old versions that include critical security errors is not a good solution.

We don’t plan to announce the roadmap because in reality it’s the Clients who decide what the new versions are going to be like!

**Comment by kpaulaha** [comment]
@bpabiszczak I started using sugarcrm and afterwards forks vtiger and sugarcrm in 2004 when was educating os erp/crm in university. Know them quite well. Still working, using and consulting them, because of huge amount of users, add-ons and integrations. I am not a huge fan of them, all of them has own shortages, in program or developers, but the programs are known. 
We users are never satisfied, something not working just as we/they want/need and want it to be done for us for free. Working long with os learns that when you need something special, you must do it your self/have it done and pay for it, and that's ok. 
I was happy as hell when you begun with yf, it was something different in many ways, it had many amazing small features and would like to keep them. I know your incomes come from your customers and that they have influence to the developement of yf and I suppose that incomes from "community" is not much. I have said that we participate with our share when closing cases with yf and also by buying work from your company when needed. So far we do not have many cases, one test company used from 2015 and with no problem. With newer versions I have not been willing to do much consulting mainly because there has been so many unexpected changes in each and some bugs harmful for us (but so in all). So I'am waiting for the "stable" version that sure has bugs, but that the basic features will remain so it can be upgraded with out fear and not being forced to find new alternatives (or coding) for old functions (that might be profitable for us, but customers might not like it in longer run). Maybe it comes, maybe not, thats open source, its great. You have done a great job, please continue, we continue meanwhile testing yf besides other things and contributing this way and working as evangelist at our levels but somehow would be nice to know where the road takes you.

**Comment by elvissaba** [comment]
In workflow, Block edition should be extended on all controls (create,edit,delete...etc).
Notification task of workflow should have Modal window as option.
That should be nice replacement for Recording control.

**Comment by waran70** [comment]
@elvissaba agree. It will create complete workflow blocking abilities what will make happy many admins

**Comment by ezbank** [comment]
@waran70 Can you give me a few examples?

**Comment by elvissaba** [comment]
Blocking can be a task when workflow conditions are met. Depending on workflow type, blocking task prevents create, upfate, delete etc. Alongside blocking task , you can execute other tasks. If. Yetiforce implements modal window task (like in announcements obligatory to accept)  workflow will be complete idiot proofing tool.
