### ISSUE TITLE
 KnowledgeBase: even admin cannot edit / delete record

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5464]
#### Issue

There is no way to edit or delete a record (only via mass-*). 
Test here: https://gitdeveloper.yetiforce.com/index.php?module=KnowledgeBase&view=List&mid=130&parent=63#block_2

**Comment by bpabiszczak** [comment]
The system has a built in mechanism to block records, you can change it by deleting values in this file:
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/KnowledgeBase/KnowledgeBase.php#L13

**Comment by migoi** [comment]
does this really make sense?

**Comment by bpabiszczak** [comment]
Yes :]

**Comment by migoi** [comment]
ok, let me know. "All" other modules can edit / delete their records. This one not.

**Comment by paula-w** [comment]
When we added the mechanism we set it up in several modules, like Knowledge Base, Opportunities, Assets, etc. The community wasn’t really happy about the mechanism so we disabled this mechanism in all modules one by one, and now it’s time for this module. 
It’s just a functionality, it doesn’t really matter for us whether it’s enabled or not, since it's easy to quickly enable/disable it on your own.

**Comment by mjapple** [comment]
Please guide us how then we can change the codes to have the edit option on our  records. now in "accounts" as an example we have no edit for the created records

**Comment by MexasPT** [comment]
Tell us how...
