### ISSUE TITLE
[QUESTION] Type permission of users webservice

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5471]
v4.2.439
when choosing type permission is permissions based on user. There is a difference between the results on crm and postman

![screenshot 79](https://user-images.githubusercontent.com/19627226/32434143-d7804844-c30f-11e7-985a-7e1a6cfb81a1.png)
![screenshot 80](https://user-images.githubusercontent.com/19627226/32434145-d7b98456-c30f-11e7-99c0-f77dbae0d181.png)
![screenshot 81](https://user-images.githubusercontent.com/19627226/32434146-d7ebd172-c30f-11e7-847c-e6f4cb2bb7bb.png)

**Comment by migoi** [comment]
There is no code inside yetiforce to "switch user" on webservice. You can setup to use another user, but it is not used internally (yet).

**Comment by migoi** [comment]
@mariuszkrzaczkowski 
I don't think that's enough. Try by creating more than one user for API. know this userid is different from id = 1. Even more let that API-User also be another user than id=1 (administrator)

If you now do something via API, the selected user (yetiforce) has different id from user API. At least: it should, but there is no code that make use of the different userid's. SImply: it wont work. I did a patch for my code here, so if
- it is from API
- and a alias-user id is set
- make use of that user-id.

Currently: you can access records you should not have access to (when in private mode), because the userids are not properly used. If the API user id = 1, then regardless of the select API alias user, always user id =1 (yetiforce administrator) is used.

Hard to explain, but once you have a test with different userids, you will get what i try to explain.

**Comment by mariuszkrzaczkowski** [comment]
The error you reported has been corrected, I tested it again and everything works fine.
![1](https://user-images.githubusercontent.com/10198654/32785398-b5cbfd2c-c951-11e7-9662-1bc240af3612.png)
![2](https://user-images.githubusercontent.com/10198654/32785405-b9e4ec0c-c951-11e7-8977-097951e45a0e.png)
