### ISSUE TITLE
[Question] Web server requirements

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#552]
Recommend please settings to fix the following problems:

A change in the system, the page freezes and then displays an error message that the server is not responding. On your test site, this is not observed, and the settings do not match the parameters specified in Article https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html

I would like to understand what it takes to correct ...

Debian 7.8
Nginx
Apache 2.2
PHP 5.5
MySQL 5.6

Can show or any configuration files or settings? As I can not cope with the profile editing, otherwise the system is running very fast.

**Comment by waw555** [comment]
When you add a role, is also a problem, the system hangs and you refresh the page after some time, there is the role of 2 instead of 1

**Comment by bpabiszczak** [comment]
Please first check this:
max_input_vars 5000 [important for profile save]
post_max_size 10M

**Comment by waw555** [comment]
![2015-4-18_16-40-13 972](https://cloud.githubusercontent.com/assets/1402355/7215282/9c86fea0-e5e9-11e4-90dc-e643b1dee854.jpg)

**Comment by waw555** [comment]
![image](https://cloud.githubusercontent.com/assets/1402355/7215285/d85668a8-e5e9-11e4-814a-2fc8eacfd8dc.png)

**Comment by waw555** [comment]
![2015-4-18_16-42-23 765](https://cloud.githubusercontent.com/assets/1402355/7215286/e90442f6-e5e9-11e4-8a76-fe85cb9dff0f.jpg)

**Comment by waw555** [comment]
Doing all the link https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html

**Comment by waw555** [comment]
When installing the system, just hangs on the last point, a few minutes later begins to work

**Comment by bpabiszczak** [comment]
Unfortunately I don’t know how I can help you. Your case would require logging to your server and solving the problem either by a developer or an administrator – it depends what kind of problem it is. It won’t help if I write what should be verified because it all depends on the expertise of a person who searches for the problem as well as on the level of knowledge about the application and the server. The problem that you report is probably single and of course we can help you but, in this case, we would have to charge for it.

It can turn out that there will be two people and a few hours needed in order to solve it, but it can also turn out that it’s something small and will be solved within 15 min.
