### ISSUE TITLE
YetiForce named  #1 Most Affordable CRM Software in Capterra's new ranking

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#5538]
### Last week Capterra announced their ranking of "TOP 20 Most Affordable CRM Software" and we are very excited to announce that YetiForce won first place!

There are more than 500 different CRM applications listed in Capterra, so the fact that not only were we included in the list of TOP20 most affordable CRMs, but we were chosen as the Number 1 is an amazing achievement. 

This is a success we share with all our community members, we wouldn't have achieved so much without you, your continuous support, and interest in our work. The entire YetiForce team would like to thank all of you.

According to Captterra, the affordability was determined using an algorithm that awards points for cost, features offered for that cost, and average customer review scores. If you haven't already, you can post your review of YetiForce on Capterra using [this link](https://www.capterra.com/reviews/159123/Yetiforce/new) and help us get to the 2018 ranking as well.

**Once again huge THANK YOU to everyone who's been with us from the very beginning and everyone who joined along the way.** 

The list of all 20 most affordable CRMs of 2017 is available [here](https://www.capterra.com/customer-relationship-management-software/#affordable).

![top20](https://user-images.githubusercontent.com/13310141/33023754-70150cf8-ce09-11e7-98bf-6baba08a91ca.jpg)

**Comment by reeid** [comment]
Based on 17 reviews? It is kind of joke?
You doing quite OK, but please guys love yourself a bit less for sake of peace of mind of those who are conscious. Thanks in advance.

**Comment by reeid** [comment]
!

**Comment by JohnMaverick** [comment]
Jesus Christ! I was about to write exactly the same!

**Comment by PercyP** [comment]
Congratulations! Absolutely well deserved. To get top place is superb. 

@reeid it wasn't actually based on those 17 reviews - it was based on research by the people who produced the report.

**Comment by robygladio** [comment]
I really don't know how they calculate the winner but.. the result is 1st place! it's nice! ;)

Well guys this CRM is very powerfull and FREE so we can only say thanks for now! :) 

Just to be no.1 for millions of review some basic option must be implemented in my opinion. 
like discount into a invoice. Deducibile Taxes etc.. 
Flexibility = instability is well know but good balance is a winner key i blieve

Open Source is not a bief so you have to make profit on personalisation and this is perfect system!
just some basic function cannot be an options or the advanced users cannot even test the system and buy assistence, personalisation etc.. 
This is my suggestion and I will list the option for Italian Market. 

But the work you make is impressive. 
Stay clean, go straight and don't change looking for a small dirty game but look forward to conquest the world!..  so continue as you are doing right now :D  

thanks and Congratulations
Roby

**Comment by robygladio** [comment]
@reeid I agree to keep feet on the ground but when you win a 1st place you are free to be happy and advertise the result! 
Open source, I say again, don't give cash money every morning. generating profit only for commitement of a specific clients for strong personalisation! so every morning you work for free.. 
This is open source. 
Tomorrow maybe somebody need your services.. so you work 10 hours hoping everyday. 

Win a competition is a good way to motivate during the days when the phone doesn't ring ;)

Let them to be happy and flyght for a day ;)

Roby

**Comment by bpabiszczak** [comment]
It’s sad that some of you can’t be happy with a small success and, instead of supporting the direction we chose, keep looking for problems where there aren’t any.

Thank you for your kind words and positive reactions under our posts. The new version will bring a number of great features that will make YetiForce even better. We will do our best to make sure that YetiForce is always the best of the best

**Comment by PercyP** [comment]
@bpabiszczak 
unfortunately there will always be people who see the glass as half empty and others who see it as half full. Just as there are always people who are pessimistic and others who are positive in their thinking. Positive people are usually innovative, and without them we would never grow, change or develop new things. 
I personally don't like to see people who are trying to achieve things, get knocked all the time (when they should be applauded). Even when things go wrong, or there are hiccups, they are still not failures, they are part of a journey towards discovering what works, what doesn't and perfecting and improving things. 

I admire companies like your that are making things happen. I think it is great you have achieved this award. In a industry that provides CRMs (lots out there) to get the number one in any category is a massive achievement and one that should be celebrated! The title is misleading - best free CRM - it isn't because it was free that you won it - it is because it is feature packed, scalable, easy to customise, beautiful to work with, secure etc. etc. SO, WELL DONE AND THANK YOU!
