### ISSUE TITLE
Event's fields not editable

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5542]
#### Issue

I tried to add another field to the "quick create" for Events. Unfortunatly it cannot be edited.

#### Actual Behavior

reason: (modules/Settings/LayoutEditor/models/Field.php)

~~~php

	/**
	 * Function to check field is editable or not
	 * @return boolean true/false
	 */
	public function isEditable()
	{
		$moduleName = $this->block->module->name;
		if (in_array($moduleName, ['Calendar', 'Events'])) {
			return false;
		}
		return true;
	}
~~~

#### Expected Behavior

Is there any drawback to exclude both from beeing editable?
Can that check safely be removed?

**Comment by aljoflo** [comment]
Hello were you able to add another field to the event quick create?

**Comment by migoi** [comment]
@aljoflo: yes

**Comment by bpabiszczak** [comment]
Editing fields in the Calendar module has always been blocked [we inherited it after Vtiger]. Because of the integration of this module with other modules, deleting or adding any field may "break" the entire system and many invisible things, e.g. DAV integration. That's why it is blocked and if someone changes that, he/she should be aware of the risk. It may change in the future when we decide to improve the Calendar.
