### ISSUE TITLE
Bug in Filters

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#5549]
![filterbug](https://user-images.githubusercontent.com/18072100/33121388-d17a36a4-cf89-11e7-9ac6-b270260524ed.gif)

**Comment by vovpff** [comment]
@vahid-jml try any conditions status draft and status in realisation

**Comment by vahid-jml** [comment]
@vovpff  i try any conditions.it's not make sense.
what your mean ???
in the version 4.2 its work like a charm.
can you explain.

**Comment by vovpff** [comment]
@vahid-jml try to add coditions to `any conditions` section. Not to `all conditions`.
Separate conditions!

**Comment by zebrahosting** [comment]
Hope this time it is taken more serious. Conditional filters are still a problem. We got swiped away because we were 'the only ones' with this issue although it was fixed in v2/3 somewhere and now came back for us in 4. Filters with "contain' or "does not contain" keep giving wrong results. We also see the same behaviour like above.

**Comment by paulokruz** [comment]
@vahid-jml 
Your example don't make any sense.

You try make a filter when you want see all Sales Enquires with status "Draft and In Realization" but your example filter is:

Show all Sales Enquires with Draft and In Realization Status, and this is not possible because status only have one value.

You need make your filter with "Any conditions"  and not with All Conditions.
