### ISSUE TITLE
Sum column calculation tip are shaking page

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5561]
#### Actual Behavior

If list of record (as configured) are full sum button tip attempt to shake page.

Check gif

![sumbug](https://user-images.githubusercontent.com/8545791/33171279-a2fac022-d05c-11e7-8dc4-7a78864b59d0.gif)

Solution is to place tip at the top of button

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
There are 2 PCs with same resolution (1920x1080). Browser the same up to date chrome. For one tip shakes, for another one all works well.

**Comment by poradz** [comment]
This bug was already fixed a few commits ago. In the newest version it does not appear, check gif. If the bug still appears after update, please write specific information about Your enviroment.
![5561](https://user-images.githubusercontent.com/31520119/34197618-94645ff8-e567-11e7-9675-390dfdd81708.gif)

Resolution: 1920x1080 ,
YetiForce Version used:  4.2.679,
Browser name and version: Chrome,  63.0.3239.84
Environment name and version:
Operating System and version: Windows 10
