### ISSUE TITLE
RC2: updater 4.2 -> 4.3 should check for file permission

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5603]
The current version does not check for file permissions on create / edit / unlink.

So when those do not match a lot of 
~~~
PHP Warning:  file_put_contents(user_privileges/menu_0.php): failed to open stream: Permission denied in modules/Settings/Menu/models/Record.php on line 221
...
Warning:  unlink(layouts/basic/modules/RecycleBin/ListViewContents.tpl): Permission denied in vtlib/Vtiger/Functions.php on line 630
~~~
are produced.
At the end the system claims: update successful (but I dont believe it)

For me: The update should stop at the first error and report it to the admin.

**Comment by mariuszkrzaczkowski** [comment]
> The current version does not check for file permissions on create / edit / unlink.
> So when those do not match a lot of

The message says you have incorrect file permissions set.
For the system to work properly it must have the correct permissions set.
I tested and I do not see this error.

> For me: The update should stop at the first error and report it to the admin.

That's why you always need to do a test update with full logs enabled.
The update process is not perfect, we know it, we need a lot of time to improve it.
As so-far, nobody helps us with this, I only hear expectations.
