### ISSUE TITLE
Submenu not showing

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5620]
Submenu not showing in My mailbox
![my mailbox](https://user-images.githubusercontent.com/10330264/33553747-94d3e984-d902-11e7-84ad-34d6f582011d.png)

* YetiForce Version used: 4.2.583
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by PercyP** [comment]
Have you checked that the menu items are there in Standard Modules-Menu Configuration?

**Comment by PercyP** [comment]
Just tested on developer version - same problem as yours. When email is open the menu links dont seem to be working

**Comment by thesxw** [comment]
I delete this manu system because it suck as u see above My system works (on click show)

**Comment by PercyP** [comment]
This seems to have been fixed in RC5 :)

**Comment by PercyP** [comment]
@thesxw 

what are we supposed to be looking at?

**Comment by thesxw** [comment]
@PercyP i talk with YF support they arent halpfull, so i will not be same as them (because im not pay for this shet)

**Comment by thesxw** [comment]
But !!! @PercyP  i will be better than them i will give u a hint look for .js file whos using this css

```
.nav li:hover > .slimScrollDiv >.subMenu{
	display: block;
	position: absolute;
	left: 230px;
	top: 0px;
	height: calc(100% - 50px);
}
.nav li:hover > .slimScrollDiv >.subMenu > li > .slimScrollDiv >.subMenu{
	left: 300px;
	top: 0;
}
.nav li:hover .subMenu a{
	color: #000;
}
```

**Comment by PercyP** [comment]
@thesxw 
firstly, thanks for posting this. The current menu is actually great, I just want to make some minor changes i.e. colour changes and have menus open inside (pushing down rather than opening across the screen). There is nothing wrong with how it works/looks now, its just personal preferences and a branding thing.

Secondly, I have experienced a good relationship with the Yetiforce team in terms of support. It is a two way process requiring a bit of give and take. Unfortunately there is a small minority of people on github and in other open source communities who just take, and when things don't work, instead of trying to help provide a solution, they go on the attack. It totally baffles me this, as in the first instance, one of the most powerful CRMs I have come across is actually offered free. Free doesn't mean that everything should be free, including their time. We have to be proactive and try to learn the system ourselves (which is part of the fun actually).

**Comment by thesxw** [comment]
@PercyP i just want alitle hint where to find this because code looks like box full of staff. Anyway this crm is easy to hack  so try to secure it first to not give acces to roundcube all email adresses plus unsecure passwords

**Comment by mariuszkrzaczkowski** [comment]
> But !!! @PercyP i will be better than them i will give u a hint look for .js file whos using this css

Do you think we're not helpful?
Do you use the fantastic and free CRM and you complain about us? Do you work for free?
Think about how much you helped in the development of our system.

> i just want alitle hint where to find this because code looks like box full of staff.

If you want to help give a solution to the problem but not tips
See how the code looks in vtiger and then you'll see it looks like a mess

> Anyway this crm is easy to hack so try to secure it first to not give acces to roundcube all email adresses plus unsecure passwords

What do you mean ?
