### ISSUE TITLE
Missing related items from man tabs

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5633]
running 4.2.529. Thank you for fixing the emails not showing.

Now we have a issue with the company (client)/ manager (contacts) and comments not being displayed on the activites tab even though it shows within the actual file once you go to edit it. Any chance of a little code edit like last time to fix please.

![relations](https://user-images.githubusercontent.com/22075161/33714396-b1eab250-db46-11e7-851c-0bfb0d21b525.gif)

**Comment by alextovey** [comment]
@mariuszkrzaczkowski @vovpff @paula-w

**Comment by alextovey** [comment]
anyone? @bpabiszczak @mariuszkrzaczkowski @paula-w

**Comment by bpabiszczak** [comment]
It's a custom module so it's hard for us to answer. I don't really understand what error you are reporting, because you are talking about comments when you are in a calendar tab. You have to precisely describe the problem, but in a way that we understand it. If you mean the "Comments" column  then I don't know what this column is, how you created it and how it works. It's a weird mechanism that I don't understand from the business perspective.

**Comment by alextovey** [comment]
In the custom modules since the update the relatation between tabs has disappeared. for instance on "contractors" the company name is missing from the dashboard but can be seen once you go in to the record and see it's relation. 

See GIF.

![relations not working](https://user-images.githubusercontent.com/22075161/34219947-b8f4d65c-e5aa-11e7-96fc-ce98de03ba74.gif)

**Comment by alextovey** [comment]
when you select a "Contractor" and then assign them to the "client/account" its not showing up on the "client/account" tab as related. This is happening on non custom modules also. see gif.

![relations not working](https://user-images.githubusercontent.com/22075161/34220279-fc3e7156-e5ab-11e7-86bd-1a3ccfc7174e.gif)

**Comment by KatarzynaUlichnowska** [comment]
You have a modified version, you have not submitted any logs, so we aren't able to help you.

Regardless of the logs, we think that this requires some programming because the relation is wrong [the module is not transmitted in the address but it should be]. If you want us to help, then you have to buy a support package and provide access to the copy of your system.
