### ISSUE TITLE
How to apply SLA while creating a ticket

### ISSUE THREAD

**Issue by hussaingi** [YetiForceCompany/YetiForceCRM#5715]
Pls guide us how to apply Service Level Agreement and an account while creating Ticket

**Comment by hussaingi** [comment]
No response !! ?

**Comment by bpabiszczak** [comment]
"DOWNLOAD SUPPORT ADDONS

YOU ARE HERE:  HOMEKNOWLEDGE BASEDOCUMENTATIONIMPLEMENTER DOCUMENTATIONGITHUBHOW TO REPORT BUGS?

SEARCH

How to report bugs?

Please read the following article before you send us information about a bug. If you don't comply to it, instead of focusing on the development of the system, we may waste a lot of time for things that are trifling or have already been answered. We do our best to help everyone, so the better you are prepared, the quicker you will receive an answer. The following article isn't only about bugs but also about ideas for changes, new functionalities and asked questions. 

1. LANGUAGE OF ISSUESSupport is provided in Polish and English, so YetiForce team will reply to issues in these languages. Please remember that if you want to add an issue in a language that is different to English, it is necessary to add e.g. [PL] at the beginning of issue's subject. We don't mind issues in different languages as long as there are also other participants. If not and no one responds to it, we will close the issue. 
2. THINGS TO DO BEFORE SUBMITTING AN ISSUEa. Check if the problem exists on the latest version [GitDeveloper]CRMhttps://gitdeveloper.yetiforce.com/ [developer version]https://gitstable.yetiforce.com/ [stable version]Portalhttps://gitdeveloper.yetiforce.com/portal/ [developer version]It is important because our team adds new functionalities and fixes from several to several dozen bugs a day. It might be possible a problem, which you want to submit, has already been fixed, so you will be certain that after the publication of a new version, the problem won't happen again. New versions are free, so it will always be possible to update the system. 
b. Check if the problem exists on our server
The above links will guide you to our servers. It is important to test if the problem exists also on these versions because it guarantees that the server has been configured adequately and the system has been installed properly. Additionally, logs are enabled on our testing versions, so it is possible to monitor bugs on an ongoing basis. 
3. INFORMATION THAT HELPS US TO MINIMIZE RESPONSE TIMEA. DOES THE PROBLEM EXIST ON A DEVELOPER VERSION? In as many places as it is possible provide information about tests described above. Unfortunately, we cannot test for some bugs, e.g. installation bugs, because on our servers the system is installed by default. In case of more advanced configurations, i.e. LDAP or Asterisk integration, it might be very helpful to enable the testing environment and sending us via email the access data. 
B. ON WHICH VERSION DOES THE PROBLEM EXIST?It is a very important piece of information for us and many people tend to forget about it. We must know on which versions the problem exists and on which it doesn't. The more information we get, the quicker the solution will be. 
C. WHAT DID YOU FIND IN LOGS?YetiForce is very complex and has a large amount of logs which, in most cases, indicate the base of the problem. Therefore, the person responsible for the implementation of the system in your company should have the expertise to enable logs and know how to read them. A detailed description of how to enable logs can be found in this article: Debugging. Please provide us only with the information related to the bug. Pasting all logs is unnecessary and will only exceed our response time. Remember that logs contain confidential information about your system, so be careful when pasting the data. 
D. HOW TO TRIGGER THE BUG?The best solution is to record it with appropriate software program, e.g. ScreenToGif. It is used for recording actions from your desktop and saving them to a gif looped animation, which might be added to an issue. Other forms are also accepted, such as screenshots or detailed descriptions. However, we prefer videos because it shortens the time of reaction. 
E. ADDITIONAL INFORMATIONIf you have any additional information that will be helpful or you even found a solution to the problem, then include information in your issue. We are open to any suggestions and assistance. 
4. RESPONSE TIME FOR SUBMITTED ISSUES 

We respond when we have a spare moment. We are not able to guarantee a short response time for every submitted issue. We divide our time among projects for our customers, internal projects, development of YetiForce as well as trainings and business meetings. For those that require immediate response we offer a variety of support packages. Critical and security issues also have hight priority.

It is important to properly describe the problem because it shortens our response time. When issues are well documented replies are often within the same day and we usually provide a patch that can be installed by a user. If you have any comments about our free support services, please email us, because your opinion is vital for us. Please note that when you are a community member, you can also solve other users' problems and share the solutions. By helping others, you also take part in the development of YetiForce. "

**Comment by hussaingi** [comment]
Can you provide an hour support(Paid) to discuss the feasibilities of your application?
If so, what is the procedure?

We are in the process of evaluating the open source ERP applications for our business.
We need response as early as possible.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
unfortunately, we don't provide business advice in English as well as we don't offer training in English. This is due to the fact that our technical employees aren't fluent enough in English. It will probably change in 2018.
We can only help if you report a bug and want us to fix it. Then we need a detailed description with screenshots and after the analysis, we inform you which package will be the most optimal for your case. Unfortunately, in cases like training or business advice, we are unable to help for now.
In January 2018, we're planning to change descriptions for our support packages, so it will be easier to know which package is the most optimal for a given task. 
I'm closing this issue because you also sent us emails, so we can continue the conversation via email.
