### ISSUE TITLE
Plans concerning the MODERN theme + small 2018 announcement

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#5723]
We want to move the Modern theme to a separate repository. It needs to be updated and we are not the original authors of that skin, it was sent to us by @ezbank  (thanks for the contribution!) that's why we decided that moving it to a different repository is a good idea. Please let us know what you think. 

Also, **in 2018**, we will put a lot of work and effort into the appearance of YetiForce so the creator of the theme might not be able to keep up with all the changes on an ongoing basis. Therefore, if anybody wants to update/create any themes we think the best idea would be to wait until we finish the new default appearance.

Let me know if you have any comments, all feedback as always will be much appreciated.

**Comment by PercyP** [comment]
Looking forward to seeing the new look when it happens. I think it would be good if we could change colours of the default theme via some kind of settings (to match our own branding) so it doesn't get overwritten each time we upgrade.

**Comment by alextovey** [comment]
@paula-w 
Would be nice. I think having the option to place our own themes in is still needed. All the people we use the CRM for are non profit org's so having this new theme is good. they do enjoy the support you give.

**Comment by KatarzynaUlichnowska** [comment]
The system is developed in such a way that you can create any templates, which can modify any element of the system. However, we believe that if the community wants to add a new template to YetiForce, then it should be a subject to the same rules as the rest of the system, i.e. it must be developed, updated every day and expanded. It's not enough to add a template and change something in it once a month.
Due to the dynamic development, we want to move the template to a separate repository because it does not keep up with the changes in the system. We want to have one template but adjusted perfectly, because in 2018 we will develop the system very intensively.

**Comment by cliquei** [comment]
> The system is developed in such a way that you can create any theme, which can modify any element of the system. However, we believe that if the community wants to add a new theme to YetiForce, then it should be a subject to the same rules as the rest of the system, i.e. it must be developed, updated every day and expanded. It's not enough to add a theme and change something in it once a month.
> Due to the dynamic development, we want to move the theme to a separate repository because it does not keep up with the changes in the system. We want to have one theme but adjusted perfectly, because in 2018 we will develop the system very intensively.

How is this going ? I am interested on helping build a new one for 2019 ..
