### ISSUE TITLE
how to setup a new theme?

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5739]
Hi All,

I want to copy the Modern theme and change the color's i've already changed the color's i want in the style.css but i've placed it in to the public_html/layouts/skins folder but it's not showing up in the system. How can i get this to show up please?

**Comment by alextovey** [comment]
Hi @PercyP You're a star thank you. :) Having to go through now and find some css as the colors are not quite right. but i'l get there. :)

**Comment by PercyP** [comment]
@alextovey 

yes, I use Chrome's inspect tools to identify what parts/colours and css files I needed to change - then I use Microsoft Sharepoint Designer (only because it has sat useless on my pc for some time) basically I create a css file in it, paste in the style sheets and do a find and replace (you can do that in file manager on cpanel's edit file too). Sharepoint designer also lets me select blocks of styles one by one and displays the colours so its handy for me. Sure there are better ways/tools for doing this, but it worked for me :O) On that note, if anyone knows of tools out there that make this process easier it would be good to know. 

Did you see the latest news that the Modern them will be going as they are updating the default theme? There is a recent post about it

**Comment by alextovey** [comment]
@PercyP I did see that. bit strange but will be good if they do update the theme as it's a little old now.

**Comment by alextovey** [comment]
@PercyP did you find the menu css part? 
it's .baseContainer .leftPanel a {

Line 894.

**Comment by PercyP** [comment]
@alextovey 

thank you for that - most useful :O)
