### ISSUE TITLE
Member of....(improvement)

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#5791]
Not sure if my thought is correct but for me it seems that field "Member of" in Accounts should have respective field in Leads module.
Imagine you need to enter whole government offices: Ministry > Department > Subdepartment > Division 1 > ... after conversion organizing whole tree will take great time

**Comment by bpabiszczak** [comment]
Unfortunately, I don't fully understand your question. I think you want us to add a "Member Of" field in Leads, so it will work the same as in Accounts. If this is what you meant, then it is the answer:

From the businness and logic perspective it makes sense, and it might be added, but it isn't essential because the Leads module is kind of a "bin" and noone will enter deparments and subdepartments there because what would be the reason for that? Remember that LEAD isn't a potential customer because a potential customer is an ACCOUNT with an adequate status. Lead is a contact/company and we don't know if they want even talk to us and we don't know if contact data is correct [e.g. you can buy 10.000 records' data base]. If someone wants to talko to us, we convert him to Accounts and create an Opportunity.
