### ISSUE TITLE
[question] about mail scanner

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5806]
Just update to new release 4.3 all works great!
Mail scanner issue #5765 was resolved!
But if my customer send an email to address monitoring, nothing happens. No new ticket created or existing ticket updated on reply to ticket comment.
The folder configuration was done correctly. 
Where I do wrong? 
![screenshot_20171229-170907](https://user-images.githubusercontent.com/5500935/34441468-403bba5a-ecbc-11e7-8937-7c4543e43f88.png)

**Comment by paula-w** [comment]
First of all, check if the access data to the mailbox are OK, if the scanner is searching the correct folders. There used to be an error, if you picked ALL in folders then it ignored the remaining fields (incoming, outgoing, spam)
If this doesn’t help then the only thing that can solve this are logs and a programmer, otherwise it’s just guessing what the problem might be.
