### ISSUE TITLE
Problem with Sales process

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#5810]
I notice that Sales process is somewhat messed up.
Just to remind about standards:
Opportunity → Quotation → Sales order → Invoice
                                                     ↓
                                           Purchase Order

All other modules Like Sales Inquiry, Requirement cards causing confusion and diverting end user to the way approved by Yetiforce, but this is kind of unusual route. For instance we have now Purchase Order and Vendor Enquiry - why? Why we have competition and partners modules? This is like having "My sites" in vtiger.... useless. Adding no value and causing mess... 
Such additional modules should be developed by each user on their demand, if they need it, but sales process (yetiforce) itself needs to be clear and transparent.
Removing those modules will make yetiforce easier to understand and will clearup code for sake of order.
If Yetiforce cannot live without some "extra" modules or process logic, it could be separated and distributed as a additional (free or paid) modules. 
I suggest to concentrate on very professional Accounting module with full set of necessary tools and maybe campaigns module (as it kind of poor right now) as well as more user friendly PDF templater.

**Comment by IanMuller** [comment]
Purchase order should be right under Sales Order.

**Comment by waran70** [comment]
Agree

**Comment by JohnMaverick** [comment]
1000% right. Is others here really don't see that? Pumping stuff just to make it look better is not the correct way. Some modules are really useless, and fact that they exists blinding developer, so he dont see the essential things. It look like yetiforce got great programmers but they never use this system for selling services and products, or environment they do business is not demanding i the meaning of creating correct documentation related to transactions.

**Comment by reeid** [comment]
I agree too. Moreover it would be good to create clear system designation with leading selling services or selling products.

**Comment by waran70** [comment]
Just to kick this up - so, we still don't have Sales Orders in default installation. How you guys gonna deal with it? Quote, Sales Order, Purchase Order, Invoice are the core of both sales and marketing processes (with block of line items). How it possible that this part is messed up? What logic is behind changing name of Sales Orders to Purchase Orders? that's the North and South Pole guys...  
What scares me indeed is that community here is blind on this crucial issue...

**Comment by JohnMaverick** [comment]
Right! Purchase Order is now related to Opportunities and Quotes... can someone explain this unusual relation? Where are Vendors/Contacts? As waran70 said here is no logic and chaotic understanding of marketing and sales process.

**Comment by TonyM15** [comment]
Indeed something is wrong here. In my opinion all core inventory modules what exists in vtiger suppose to be here. They are crucial for most of organizations. Agree also with above that system suppose to be simplified, and unnecessary modules (as mentioned) removed. Stability and access to descent documentation for developer and users should be prioritized. Here is also lack of additional modules. Yetiforce should allow for developing as such, and distribute them on their website (after approval process - same as vtiger, but better is to make it simply and without encryption. Standard user cannot mess with code anyway). Sales Orders and Purchase Orders needs to be properly designed.

**Comment by bpabiszczak** [comment]
@IanMuller
I love your attitude guys… make it paid or additional module. You want paid modules you can find them in Vtiger, there is a lot of paid addons there.

If someone considers a module redundant it’s enough to disable it, it takes a few seconds. To make it simpler you can make the sales process shorter, but that’s an individual matter. In the future we’re going to add a mechanism that will enable or disable modules during installation to make it easier for the user, but it’s not our priority for now.

CRM is a selling tool so I don’t know why would we focus on accounting, it’s not a purely marketing tool either. In the future we will add professional management for logistics, projects, and accounting.. but it’s going to take months if not years [this is the direction we’re heading].

@JohnMaverick

All modules in the system were made for our clients who have ordered them and are using them. Some of them are half finished because they were ordered like this [eg. they were needed for an ERP integration]. The fact that they are in the system doesn’t mean that we consider them necessary for further development.

@All

I don’t know what naming convention problem you mean, for me the process is as simple as 2+2. In the future we will provide a simple guide for the processes to make it understandable for everyone. Like I said before, if you don’t need some of the modules or you don’t understand them – you can disable them, it will solve all your issues.

Each of you has their own idea for your own system, I understand that, but this is a system we make for our clients. If you want to have a bigger impact on the processes or the code then you should put more work in this system. Before we added any of the modules we had a number of internal discussions so I don’t see any reasons to change it.

**Comment by JohnMaverick** [comment]
Sales Order was here, you just renamed it to Purchase Order messing up relations. Never mind... you listen to yourself only anyway...
