### ISSUE TITLE
Users vs. standard module

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#5891]
Amending users module so it is configurable like other modules (adding fields, filters, workflows...etc) will kick up overall usability of system. Imagine that user is  an employee....why not gather all info about one in users module place? What if there is 500 employees and we want to select some who fulfill particular critters? 
What community thinking and how developer see that?

**Comment by bpabiszczak** [comment]
The Users module is a critical module with permissions, and the access to it should not be possible at all because it’s apart of the admin’s panel. If a user should have the access to some fields then he should have a different/independent screen where he can change things.

Right now we’re not planning to to add the option to add custom fields to the users module, if someone wants to do that then it’s possible at the code level.

If someone wants to display info about a user then it’s possible in the employees module.
