### ISSUE TITLE
Create Satisfaction Survey

### ISSUE THREAD

**Issue by michelmarquesrj** [YetiForceCompany/YetiForceCRM#5898]
Hello colleagues!

I am performing a customization on my Yetiforce installation and would like help.

I need to create a module to perform "satisfaction surveys". Basically it would work as follows:
After entering the answer and closing the ticket, the system would send the requesting person an email with a link to answer the questions registered.

For this, I created a module called "search". Now I need every time the ticket has a response and the status is "Closed", the system should trigger email with the satisfaction survey.

I know I need to create a workflow for this. But how to accomplish this? Remember that each survey answered is associated with a closed ticket.

My question is: how to do this? What would be the best solution?

My Yetiforce is 4.3

**Comment by anderpydev** [comment]
It's best if you create field mapping.
Now you can do it like this:

1.
Workflow for your module "Reports".
Option - Any record entry (eg creation, modification) -> Add Condition "Status = Closed".

Now, do the task "Create a record". "Create your own mapping" option. Choose your "Search" module. And map the fields accordingly.

2. You then do Workfolw for the "Search" module.
Option - Creating a record -> Now if you have a status field in the Search module, then -> Add Condition "Status = Open".

Now, do the task "Send email".

**Comment by michelmarquesrj** [comment]
@anderpydev 

Right.

I did not understand the question "Create your own mapping". How do I do this?

Another thing, the creation of the workflow I understand, but the question that continues is: When the ticket is closed and the inquiry sent, how will the person respond?

When I create a workflow for the search that should be sent by email, how will the person respond?

The idea is to have a link when the person clicks, have the questions for the person to respond.

**Comment by bpabiszczak** [comment]
In order to design something properly all the elements of the process should be well described. So you need to know what fields there are in each module [ eg. the ticket module and the survey module], which info [and what info] is supposed to be filled by the user.

There is no problem to do that from the technical perspective [because it can be done in any way you want], but no matter how you want it to work you will need a programmer, and the programmer needs a well described process from the business perspective.

You have to remember that the CRM shouldn’t be available publicly, so a part of the mechanism must be external and can’t be linked directly to the CRM but has to use some secure communication instead. I suggest focusing on expanding API.

In the future we will add a mechanism like this, but for now we can’t tell you when exactly.
