### ISSUE TITLE
[Question] Which fields in the settings are relevant for the type: sent (company mail, mailscanner)?

### ISSUE THREAD

**Issue by worldwidehigh** [YetiForceCompany/YetiForceCRM#6032]
Which fields in the settings are relevant for the type: sent (company mail, mailscanner)?

#### Your Environment
* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Operating System and version: WIN10

**Comment by paula-w** [comment]
Can you clarify a little? we don't understand what you mean. Thanks!

**Comment by worldwidehigh** [comment]
![unbenannt](https://user-images.githubusercontent.com/20869581/39313267-e1a0ff56-4971-11e8-93b5-4dc3c83ec477.png)

How are sent e-mails set by the mail scanner? Which settings/fields are relevant for this?

**Comment by worldwidehigh** [comment]
I can only log into my e-mail account with Username + Password, not with E-Mail address + Password, these are also my login data for the SMTP mailbox. I think that's why the mail scanner does not work properly and binds my sent mails as received.

My question is now, if there are other relevant fields for the mail scanner to recognize the sent mails. Or can I enter my e-mail addresses manually in the code or the database.

**Comment by KatarzynaUlichnowska** [comment]
The system automatically decides whether the email is "sent" or "received" or "internal". It does this based on the email address of the account and on the basis of what is in "From, To, CC, BCC". This is due to the fact that there is no clear definition of sent emails, often users had sent emails in companies in various folders [even in INBOX]. In order to deal with such problems, we created our own algorithm, which determines this.

If for some reason the system incorrectly verifies if the email is sent or received, then you should check ii in the algorithm.
