### ISSUE TITLE
where is fundation?

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#6111]
For the past time observing a lot of issues being passed through, but still dont see ANY input related to totally invalidated sales/marketing process. It will be dumb to me to call particular cases (search it by your own), so I just get this voice again and will see what specialist from the marketing and sales fields of YF will say. I believe you spy on it? No... I am not a user of YF, I am just disappointed with the distance between great programming skills and understanding business process. I am enthusiastic to open source... so things here scarring and hurt me.

**Comment by waran70** [comment]
Seems like bootstrap and related "crucial" stuff is more important than logic of whole system? 
Didn't' hope to see that indeed.

**Comment by bpabiszczak** [comment]
@JohnMaverick
So if this topic has been mentioned before in a different issue why are you making a new one? It won’t sppeed up things, if anything it will only slow them down, because we will have more duplicated issues.

@waran70 
For us the safety and quality of the code come first, the processes come after that, because we implement processes for our clients each time according to a document that includes a very detailed analysis.

**Comment by JohnMaverick** [comment]
>>> For us the safety and quality of the code come first, the processes come after that, <<<<

This logic is not funny at all ....
