### ISSUE TITLE
[BUG] chrome-->export pdf attached new email

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#6123]
Only for chrome browser, when export pdf and attach it on new email, produce a blank page.

**Comment by setras** [comment]
Encountered the same problem. It occurs after the latest updates of Chrome and Firefox and ist related to the Content Security Policy.

Browser console error:
`Refused to send form data to 'https://gitdeveloper.yetiforce.com/' because it violates the following Content Security Policy directive: "form-action 'self'".
`
I tried to set disable the CSP in the security config file but no luck.

![pdf to email - chrome csp error](https://user-images.githubusercontent.com/10443220/37027969-36eef876-2133-11e8-91eb-733fc5d0ade0.gif)

**Comment by rskrzypczak** [comment]
The error no longer occurs in the current dev version
