### ISSUE TITLE
.htaccess and public_html errors

### ISSUE THREAD

**Issue by torqueing** [YetiForceCompany/YetiForceCRM#6186]
#### Issue

The server was setup as a subdomain and has its own .htaccess but no matter how I change the privileges Yetiforce says it cannot access it. It also says it's not in public_html - which it is just under a directory in public_html.

#### Actual Behavior

Security errors

#### Expected Behavior

No errors

#### How to trigger the error

1. install on server
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Chrome 64.0.3282.167 64bit
* Environment name and version: Cinnamon/Windows
* Operating System and version: linux Mint (latest) / MS Server 2008R2

**Comment by paula-w** [comment]
Unfortunately you didn’t provide us with any logs or screenshots so we can’t be entirely sure what the problem is exactly. 

As far as public_html is concerned, the system recommends that the domain doesn’t direct to public_html, but to public_html [server] / public_html [inside YetiForce]. As a result we secure a number of elements, for example files in Storage are not publicly accessible [just like cache, logs, etc]. This is a suggestion when it comes to security.

We don’t understand the issue with htaccess.
