### ISSUE TITLE
pre-installation questions

### ISSUE THREAD

**Issue by cimenta** [YetiForceCompany/YetiForceCRM#6234]
Hi all
before I spend more time and money on YetiForce I would like to ask few questions. I did do my research, I tried demos of Bitrix24, Sugar, Freshsales, c2engine, vtiger, AgileCRM and of course YetiForce. I talked to local vendors of various systems and .... Yeti force is winning.... I guess that YF it's very similar to vtiger but not exactly the same so I would like to ask few questions and then probably for some help to install/set up the system.

Q1) Can one installation manage two different companies? So their data are not visible to each other?
Q2) Is YF GDPR ready? If not how to encrypt all data that is YR using?
Q3) Can I sync YF with with google contacts / calendar? (almost a must have feature)
Q4) Can I run email campaigns and have unsubscribe link/button for each of them?
Q5) Can I set up an utomation that would be triggered 10, 50, 100 days after a certain date? I deliver courses, so I want an email to be sent out automatically after 10, 50, 100 days of course completion
Q6) I would like to know if I can use either system type of events or create new module events (yes I know that I can create new module) in such a way so it can store all participants of the event. Of course they are coming from contacts. Also I would like to be able to email them all with one click. Or easily.
Q7) I know that I can email from the system. Not sure whether the email is attached to the contact's history and the reply email from the contact is linked to the history of contact.
Q8) Can I prevent duplicates of the contacts to be saved? Let's say that the primary key would be first name + last name + city.
Q9) Can I create new field and have access rights set up differently to the rest of the let's contact record? Can I do the same for a section?
Q10) can I set up automatic backup of the system so it's easy and fast to restore if needed?

Thank you so much for your help

Radek

**Comment by KatarzynaUlichnowska** [comment]
Hello Radek,
here are answers to your questions:
Q1) We don't offer a typical multi-company module but you can divide employees into different groups.
Q2) YetiForce will be ready for GDPR in May. At the moment, we are adapting the architecture of the system to new regulations. The system already has a built-in data encryption tool [developer version], so by May it will be ready for use in production.
Q3) YetiForce supports CardDAV protocol, we don't have the integration with Gmail. 
Q4) No, but it should be available in May.
Q5) No
Q6) It requires some programming.
Q7) Yes - it can be done manually and/or automatically.
Q8) You can add a simple action on record saving and it will verify if there is a duplicate. There was such an option in 4.2 and there will be a new mechanism in 5.0.
Q9) It's possible to specify permissions to fields in Profiles [e.g. who can see/edit fields].
Q10) Backup is performed on the layer of the operating system. In order to restore it, it is required to:
- Restore the copy of the database
- Restore copies of files
- If needed, change access data in config/config.inc.php file in case the server changed.

**Comment by webmastergta** [comment]
Hello how are you? Could you help me please, I have a problem with the installation of these two modules, you could give me the steps to do it successfully:

mPDF	vendor/mPDF/	https://github.com/YetiForceCompany/lib_mPDF	


roundcube	public_html/modules/OSSMail/roundcube/	https://github.com/YetiForceCompany/lib_roundcube
