### ISSUE TITLE
DataAccess module

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#6239]
You have deleted the DataAceess module. Why? Is there an alternative?
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by alexandr256** [comment]
How can I now select a record with a color or check the field for unique?

**Comment by KatarzynaUlichnowska** [comment]
The module has been deleted because of security reasons [it was implemented poorly and it was not possible to fix it], currently, missing functionalities will be added in subsequent versions.

**Comment by bpabiszczak** [comment]
Color u can set here: https://gitdeveloper.yetiforce.com/index.php?module=Colors&parent=Settings&view=Index&block=12&fieldid=81

**Comment by cltvchannel** [comment]
@bpabiszczak  Can you provide me all files and database for DataAccess module from version 4.2?
I want to make some changes and try to integrate in Yeti Force 4.3 on my server installation.
Recording Control was a great feature. Now we can't color recording row or text.

Thanks !

**Comment by bpabiszczak** [comment]
Here’s the link to the commit that deletes the module: https://github.com/YetiForceCompany/YetiForceCRM/commit/da527ae6fcc5d5978752aaf0d36c9277fb93fc14 

You can try to restore this module for 4.3 but it’s not a good idea due to security. If you’re missing some feature then the best way to resolve this is to add it to the new version. I don’t understand why you want to waste your time on something that was abandoned and will never come back as it used to be.

**Comment by cltvchannel** [comment]
@bpabiszczak  I miss row color feature. I don't know how to implement that function, and i have considered the best way is to get back DataAccess module.
