### ISSUE TITLE
Unable to install: permission denied

### ISSUE THREAD

**Issue by mishapchen** [YetiForceCompany/YetiForceCRM#6284]
#### Issue
Unable to install YetiForce; when trying to do so I get a 500 error. After looking in the log the following was found:
`[Wed Mar 07 21:54:17.262894 2018] [proxy_fcgi:error] [pid 13591:tid 139692376606464] [client 94.214.171.93:59985] AH01071: Got error 'PHP message: PHP Warning:  require(include/RequirementsValidation.php): failed to open stream: Permission denied in /home/admin/domains/mmsys.nl/public_html/fourfloor/index.php on line 13\nPHP message: PHP Fatal error:  require(): Failed opening required 'include/RequirementsValidation.php' (include_path='.:/usr/local/php70/lib/php') in /home/admin/domains/mmsys.nl/public_html/fourfloor/index.php on line 13\n'`

However, when I try to chmod the file I also get a permission denied.

I am running the scripts on a Debian 9.3 VPS.

Any ideas on how to fix this?

**Comment by mariuszkrzaczkowski** [comment]
No information about the environment
No information about the CRM version
There is no information about where you downloaded the version

**Comment by mishapchen** [comment]
Environment as in..?
Downloaded the latest version of YetiForce from GitHub directly through my VPS and extracted in the designated sub-domain folder

**Comment by mariuszkrzaczkowski** [comment]
> latest version

4.3.0 ?

> Environment as in..?

PHP, apache, OS, configuration information https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

**Comment by mishapchen** [comment]
Yes, I downloaded 4.3.0

System information:
Processor Name | Common KVM processor
Vendor ID | GenuineIntel
Processor Speed (MHz) | 2399.996
Total Memory | 1020380 kB
Free Memory | 242252 kB
Total Swap Memory | 0 kB
Free Swap Memory | 0 kB
System Uptime | 0 Days, 8 Hours and 5 Minutes
Apache 2.4.29 | Running
DirectAdmin 1.52.1 | Running
Exim 4.89 | Running
MariaDB 10.2.12 | Running
Named 9.10.3 | Running
sshd | Running
dovecot 2.3.0.1 (ffd8a29) | Running
pure-ftpd 1.0.47 | Running
Php 7.0.28 | Installed

I've created a php file with just phpinfo():
[http://mmsys.nl/php.php](url)

Hope this helps

**Comment by slawekk87** [comment]
Compare user and group, that owns files with user and group used by php fpm/apache to execute scripts. Chmods can be good but user/group must also match in some configurations.

**Comment by KatarzynaUlichnowska** [comment]
If you get a 500 error, we recommend reading this article: https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/apache-500-internal-server-error-3

If you can't change permissions to files and folders, you need to contact your server admin because it isn't a problem on the YetiForce side.

In 4.4 version [testing version] we have significantly improved the entire installation process, so please check if this problem also appears on this version https://download.yetiforce.com/developer.zip

Your problem is specific to your server if you expect to receive direct support and want us to log in to your server and check what's wrong), then it is a paid service.
