### ISSUE TITLE
Customer Portal Instalation

### ISSUE THREAD

**Issue by vinnyparker** [YetiForceCompany/YetiForceCRM#6290]
Hi, I'm new at YetiForce CRM  and I installed it by softaculous. I'm testing. So where can i find Documentation about the customer portal installation?

**Comment by PercyP** [comment]
Hi,

I don't think it has been released yet. There was a post that suggested it would be released with version 5 at beginning of 2018 but that date has passed and 4.4 isn't due to be released at the end of March : https://github.com/YetiForceCompany/YetiForceCRM/issues/5447

Maybe one of the Yetiforce team can let us know where it is at?

**Comment by vinnyparker** [comment]
thanx

**Comment by Pablo010** [comment]
Hi,
I wont to use Customer Portal too.
When it will work?

**Comment by paula-w** [comment]
The Portal will be released together with YF version 5.0

**Comment by santyabreu** [comment]
Hello

Any docuentation about implementing customer portal for YF 5? I still cannot find any doc
Tnx

**Comment by one-use** [comment]
> The Portal will be released together with YF version 5.0

Well, its July 201**9**. How do I enable/install Customer Portal?
