### ISSUE TITLE
Extended menu

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6339]
#### Issue

When put mouse over menu, the menu is extending.

#### Actual Behavior

On Modern theme when put mouse over menu, the menu is extending faster. But on Twilight theme the menu is extending slower. 
#### Expected Behavior

How i can make menu extending faster like in Modern theme?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.30
* Browser name and version: Google Chrome
* Environment name and version: cPanel
* Operating System and version: CentOS

**Comment by KatarzynaUlichnowska** [comment]
In such cases, the best thing is to record a video. Every element matters [screen resolution, browser, operating system], it is best to fix it directly on the computer on which the error appears. If you want us to fix it in our system, then you must provide all necessary information [e.g. operating system, browser, resolution] so that we can trigger it.

In the new version, there will be a new menu.
