### ISSUE TITLE
Incorrect request Illegal value in field language (en) when edit/add users

### ISSUE THREAD

**Issue by crpak** [YetiForceCompany/YetiForceCRM#6406]
1. When I use any button of "accounts""contact""Leads".. of ossmail system, I get the error of 403.
Forbidden

You don't have permission to access /index.php on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

2. The emails can't be displayed on the details page of Leads / Accounts

3. I have add some users when I finish fresh installing. After I add some records and change the roles of one of them, I get an error which I have met many times even I don't know how it happened.  Then displaying the error mesage as subject " Incorrect request Illegal value in field language (en) ". 
Software configuration > Permissions > Profiles > System settings

Incorrect request Illegal value in field language (en) 

Generated by YetiforceCRM ver. 4.3.0
PHP: 7.0.23

Server configuration errors:
innodb_lock_wait_timeout: 50
interactive_timeout: 10

**Comment by paula-w** [comment]
The 403 error says that either the file doesn’t exist (in this case it’s a Roundcube file in its main folder), or you have no permissions for this file. As if the email module wasn’t installed. You have to check it on your own because it’s an individual issue on your server. Remember that you have to install the mail module yourself because it’s released under GPL and we can’t install it together with the CRM.
