### ISSUE TITLE
Duplicate prevention

### ISSUE THREAD

**Issue by Jibe9191** [YetiForceCompany/YetiForceCRM#6532]
We are currently running on Yetiforce ver 4.3, which does not have Record control any longer.  What is the best way to prevent the creation of duplicate record for any of the module?

**Comment by cltvchannel** [comment]
me2 i'm interested.

**Comment by bpabiszczak** [comment]
We used to have a mechanism that made sure there were no two clients with the same VAT EU, it was unfortunately removed together with DataAccess. Now we do it individually for our clients because they have different needs (some need it based on VAT EU, some based on VAT EU and name, some also consider the address).
This validation should be performed in two steps:

1. JavaScript (should inform the user that a duplicate exists)
2. Handler (or workflow) that won't allow to save on PHP layer

Each time it must be done by a programmer but it shouldn't be much work. Depending on the fields and modules i estimate it to be 1-4 working hours

**Comment by ldgbc** [comment]
Seem like the only way currently is to do it manually.
