### ISSUE TITLE
OSSMailScanner actions dont work

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#6598]
#### Issue
If create in Software configuration -> Mail tools -> Mail – Scanner any action and run cron/vtigercron.sh nothing happens. 
Action run only if go inside the email message in module OSSMail

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by alexandr256** [comment]
Some problem

**Comment by bpabiszczak** [comment]
In order for the scanner to work properly you need to enable the "Create email message" action in the scanner, active folders that are to be scanned and enabled CRON. Don't forget about uploading all the changes for version 4.3. If it still doesn't work then we'll need logs, screenshots or a short video (where we can see the configuration and scanner logs)

**Comment by varlog11** [comment]
Ok, I'll do it today

**Comment by SALITEL** [comment]
I have same problem. Impossible define folders of account, show "Incorrect data access".
On Roundcube show the email of the first time of sync, but later not update.

**Comment by PercyP** [comment]
I also have the same problem

**Comment by varlog11** [comment]
I did some tests. OSSMailScanner only if i used php7.1. With php5.6 and php7.0 does not work

**Comment by varlog11** [comment]
After several hours, I tested again on the same server with php7.1 and the OSSMailScanner stopped working (

**Comment by paula-w** [comment]
Mail scanner is a complex tool. You have to keep in mind that CLI has an individual PHP configuration and CRM administrators often forget about it. Remember that CRON should not be executed when someone is preforming a database backup and blocking tables. You can trigger the scanner manually in the panel.
In order to solve the problem we would have to access your server, and this is unfortunately something we charge for.
