### ISSUE TITLE
 Open Street Map integration

### ISSUE THREAD

**Issue by fricgabriel** [YetiForceCompany/YetiForceCRM#6826]
Hello ! 

How to configure Open Street Map integration?

Thks

**Comment by PercyP** [comment]
I too would like to know. I cannot get the maps to display anything (including on Gitdeveloper version of yetiforce). I set it to Googlemaps but nothing appears. Did you manage to get it working?

**Comment by SALITEL** [comment]
The integration of OpenStreetMap in version 4.30 is correct. The problem is that OpenStreetMap is very demanding with the address and many streets are not.
The perfect integration with OpenStreetMap would be to consult several times until you get the position coordinates.
1. With all the address data.
2. If it does not exist, check with the postal code, city, etc.
3. If it does not exist, consult only with the city, etc.
It's better to locate the city than not to locate anything.

If the location fails you, try looking for it at https://www.openstreetmap.org, it is most likely that you will not find it.

**Comment by paula-w** [comment]
In order for the maps to work you have to enable CRON (actions: Get coordinates, Update coordinates), you can additionally set up fetching localization into the map and calculating routes using this file: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/OpenStreetMap.php
There’s another integration with OSM used to suggest addresses https://gitdeveloper.yetiforce.com/index.php?module=ApiAddress&parent=Settings&view=Configuration&block=5&fieldid=61
