### ISSUE TITLE
[PL] Pierwszy dzień tygodnia

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#683]
Poprawić pobieranie pierwszego dnia tygodnia w miejscach gdzie jest na sztywno określony (filtry,raporty)
modules/⁠Vtiger/⁠models/⁠Field.php:555:            $lastweek0 = date("Y-⁠m-⁠d",strtotime("-⁠1 week Sunday"));
modules/⁠Vtiger/⁠models/⁠Field.php:557:            $lastweek0 = date("Y-⁠m-⁠d", strtotime("-⁠2 week Sunday"));
modules/⁠Vtiger/⁠models/⁠Field.php:558:            $lastweek1 = date("Y-⁠m-⁠d", strtotime("-⁠1 week Saturday"));
modules/⁠Vtiger/⁠models/⁠Field.php:636:            } elseif ($type == "lastweek") {
modules/⁠Vtiger/⁠models/⁠Field.php:637:                    $dateValues[0] = $lastweek0;
modules/⁠Vtiger/⁠models/⁠Field.php:638:                    $dateValues[1] = $lastweek1;
modules/⁠Vtiger/⁠models/⁠Field.php:722:           'lastweek' => array('label' => 'LBL_LAST_WEEK'),
modules/⁠Reports/⁠ReportRun.php:1584:            $lastweek0 = date("Y-⁠m-⁠d",strtotime("-⁠1 week Sunday"));
modules/⁠Reports/⁠ReportRun.php:1586:            $lastweek0 = date("Y-⁠m-⁠d",strtotime("-⁠2 week Sunday"));
modules/⁠Reports/⁠ReportRun.php:1587:             $lastweek1 = date("Y-⁠m-⁠d",strtotime("-⁠1 week Saturday"));
modules/⁠Reports/⁠ReportRun.php:1683:             elseif($type == "lastweek" )
modules/⁠Reports/⁠ReportRun.php:1686:                     $datevalue[0] = $lastweek0;
modules/⁠Reports/⁠ReportRun.php:1687:                     $datevalue[1] = $lastweek1;
modules/⁠Reports/⁠Reports.php:852:                "yesterday","today","tomorrow","lastweek","thisweek","nextweek","lastmonth","thismonth",
modules/⁠Reports/⁠Reports.php:967:                $lastweek0 = date("Y-⁠m-⁠d",strtotime("-⁠2 week Monday"));
modules/⁠Reports/⁠Reports.php:968:                $lastWeekStartDateTime = new DateTimeField($lastweek0.' '. date('H:i:s'));
modules/⁠Reports/⁠Reports.php:969:                $lastweek1 = date("Y-⁠m-⁠d",strtotime("-⁠1 week Sunday"));
modules/⁠Reports/⁠Reports.php:970:                $lastWeekEndDateTime = new DateTimeField($lastweek1.' '. date('H:i:s'));
modules/⁠Reports/⁠Reports.php:1123:                } else if( type == "lastweek" ) {
modules/⁠CustomView/⁠CustomView.php:493:                  "lastweek","thisweek","nextweek","lastmonth","thismonth",
modules/⁠CustomView/⁠CustomView.php:521:                  "lastweek" => "" . $mod_strings['Last Week'] . "",
modules/⁠CustomView/⁠CustomView.php:583:          $lastweek0 = date("Y-⁠m-⁠d", strtotime("-⁠2 week Monday"));
modules/⁠CustomView/⁠CustomView.php:584:          $lastWeekStartDateTime = new DateTimeField($lastweek0 . ' ' . date('H:i:s'));
modules/⁠CustomView/⁠CustomView.php:585:          $lastweek1 = date("Y-⁠m-⁠d", strtotime("-⁠1 week Sunday"));
modules/⁠CustomView/⁠CustomView.php:586:          $lastWeekEndDateTime = new DateTimeField($lastweek1 . ' ' . date('H:i:s'));
modules/⁠CustomView/⁠CustomView.php:736:                          } else if( type == "lastweek" ) {
modules/⁠CustomView/⁠CustomView.php:1537:            $lastweek0 = date("Y-⁠m-⁠d",strtotime("-⁠1 week Sunday"));
modules/⁠CustomView/⁠CustomView.php:1539:                 $lastweek0 = date("Y-⁠m-⁠d", strtotime("-⁠2 week Sunday"));
modules/⁠CustomView/⁠CustomView.php:1540:         $lastweek1 = date("Y-⁠m-⁠d", strtotime("-⁠1 week Saturday"));
modules/⁠CustomView/⁠CustomView.php:1614:         } elseif ($type == "lastweek") {
modules/⁠CustomView/⁠CustomView.php:1616:                 $datevalue[0] = $lastweek0;
modules/⁠CustomView/⁠CustomView.php:1617:                 $datevalue[1] = $lastweek1;
modules/⁠CustomView/⁠models/⁠Record.php:655:               $lastweek0 = date("Y-⁠m-⁠d", strtotime("-⁠2 week Sunday"));
modules/⁠CustomView/⁠models/⁠Record.php:656:               $lastweek1 = date("Y-⁠m-⁠d", strtotime("-⁠1 week Saturday"));
modules/⁠CustomView/⁠models/⁠Record.php:719:               } elseif ($type == "lastweek") {
modules/⁠CustomView/⁠models/⁠Record.php:720:                       $dateValues[0] = $lastweek0;
modules/⁠CustomView/⁠models/⁠Record.php:721:                       $dateValues[1] = $lastweek1;
modules/⁠CustomView/⁠models/⁠Record.php:805:             'lastweek' => array('label' => 'LBL_LAST_WEEK'),

**Comment by MaciejStencel** [comment]
Fixed generation of date time ranges. Refactored code, cleaned it and optimised to ran faster. Code now runs only for specified range type, not on every avaible type and returning just chosen one. Mostly used in custom views, reports and workflows.

Fixed wrongly generating two types of date ranges, mainly years and quarters.
Year was generated with range:
From: Y-01-01  to Y-12-*present day number*

So if someone tried to create view in module showing records filtered by dates in rage of present year and someone opened that view for example today (2015-08-13) he would see records from range 2015-01-01 to 2015-12-13. Records from the second part of the december would not be seen.

Another error was with date range type quarters. The avaible quarter types are previous, present and next quarter. Vtiger and up till now YetiForce were returning not quarter of a year but third half of a year! So for example if we would try to return records from present quarter we would get records from 2015-05-01 - 2015-09-30, instead of 2015-07-01 - 2015-09-30. 

Getting records from previous/present/next week is now based on user settings of "Starting day of the week" and not hard coded "Sunday - Saturnday". If user has start of a week as Monday, and chosen to see records from this week he would see records from Monday to Sunday.

Now filtering by date takes into account users set time zone, and not just servers settings. So now if someone from Pacific has server in Europe, and he is ahead of server by 1 day, then he sees records from his time not european time. The same can be if settings of server and company location time is synchronised, but the system users are from all over the world then they can see records from their time zone, or set time to the companys time zone and see records as everyone.
