### ISSUE TITLE
Barcode and business card scanners

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6897]
Hi,
I am researching a barcode scanner with the possibility of integrating it in to my yetiforce instance and wondered if this sort of thing would be of interest to others. I suppose if you need stock control i.e. to quickly scan in pallets etc. it would be useful?

For me I want to scan in documents with barcodes/ QR codes etc. i.e. utility bills which now come with barcodes. So far I have found the following which are designed for Vtiger (I am guessing if they work with that they could potentially work with yetiforce)?

https://apiant.com/connect/vTiger-CRM-to-Barcode-Scanner

https://www.integromat.com/en/integrations/barcode/vtiger

I am also looking at business card scanners (populate contact/company details) something I found is here:

https://magneticonemobile.com/

In an ideal world this sort of thing would be better built by Yetiforce, but it is whether it is a path they would want to go down.

Just putting this out there to see what others think

**Comment by kpaulaha** [comment]
I have the barcode scanner on my checklist for one customer but have not had time to do anything yet. Sure I find it interesting.

**Comment by paula-w** [comment]
The modules that you linked can’t be used for barcode management, unfortunately neither demos not videos work so we can’t confirm that.
To make barcode management work properly it should be implemented in the core, ie you must implement auto switching between fields in the block with products and services and auto creating new rows (especially if you want to add products to a document).
Then the system must support barcode management on printouts and in search engines, it can’t be done without changes in the core. The modules that you mentioned seem like a waste of money. 
In theory YetiForce supports barcodes at the PDF and block with products/services level, we tested it with a scanner; unfortunately we’ve never implemented that into any production version because that’s only needed when someone uses the system as ERP or storage management, and we don’t have any clients like this. 
A decent integration would cost around 10k €

**Comment by PercyP** [comment]
Hi Paula thanks for reply.

In hindsight the scanner is probably not needed (for now at least) but it is good to know it could potentially be done and the likely cost so we can plan :)

Many thanks
