### ISSUE TITLE
Same Contact for two Accounts? How to do it?

### ISSUE THREAD

**Issue by thebravoman** [YetiForceCompany/YetiForceCRM#6949]
#### Issue

I would like to have the same contact associate with two different accounts. Because I have the same contact representing two organization - an LLC and an NGO and we could offer a service for both of them. It makes sense to have them as two separate accounts and a common contact. 

#### Actual Behavior

Being able to add same contact to two different accounts
#### Expected Behavior

Can not do it
#### How to trigger the error

1. Create account
2. Go to contact
3. Want to search for contact and add a contact to the account

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by KatarzynaUlichnowska** [comment]
We understand that there are situations like that but in our system one Contact needs to be related to one Account. If you want to have it as described, you need to create two contacts.

**Comment by ldgbc** [comment]
@thebravoman Yetiforce isn't design for that. There is numerous Issue talking about this. One method is to create a new 1:M field to added the second Contacts.

Otherwise you be looking at $10,000+ for it to be implemented.

**Comment by thebravoman** [comment]
Well thank you guys. I tried a couple of others CRMs and they are also doing it in this way. It seems the "not so good decisions" were made once during the implementation of a kind of old CRM and people just keep re-implementing it in the same way :)

**Comment by ldgbc** [comment]
@thebravoman I seen quite a few of them that actually let you easily add them and link them.

For example, let say the company have 3 Phone numbers, you can just Enter 1, then click "+" and enter another, and enter as many as you want (I think there a limit of course).

There is no need to go into "Setting" and create another field call "Phone 2:" and "Phone 3:", if you are unlucky with a company that have 4 phone, then go to the setting. Which is what Yetiforce current design is like. Probably due to VTiger. I wonder if they fixed this issue yet.

Anyway, I wonder if it possible to still have the same current programming but add in a "Delimiter" or "Separator". For example, Yetiforce will read anything after an ";" as a second value. 

Member of: Company1; Company5; CompanyABC

See my other post here, @PercyP giving me hint on how it can "be done" as a work-around solution. 
https://github.com/YetiForceCompany/YetiForceCRM/issues/6973
