### ISSUE TITLE
Workflow block edition

### ISSUE THREAD

**Issue by lelethered** [YetiForceCompany/YetiForceCRM#6958]
#### Issue
is possible to use block edition WF (that work perfectly), but create a rule to exclude certain "special user" to grant access to record blocked and read only in order to review and change the same records if necessary?
I try in 4.0 and 4.3 version but i'm not able to do it

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0 - 4.3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
We are going to add this mechanism soon.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/41001988-c631b16e-6912-11e8-94f7-8b07efcfc332.png)

**Comment by lelethered** [comment]
Hi @mariuszkrzaczkowski, thanks,
i apply this condition on Workflow and works fine, but my question regard the exception to the functionality; grant access to specific user to modified the records "freezed" by the WF block edition in order to modify some values on the same record
Best regards

**Comment by paula-w** [comment]
In order to unlock a record you have to use the locking mechanism based on Picklist
Software configuration > Standard modules > Fields – Picklists

![2018-11-19_14-24-19](https://user-images.githubusercontent.com/10198654/48709791-d5756680-ec06-11e8-8d3f-441bed0e3016.jpg)

Then you will see a button that unlocks a record, given that the user has the right permissions.
