### ISSUE TITLE
Advanced block to quick create

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6984]
#### Issue

I see that now will have advanced block to related module widget, but one more needed feature is to have the posibility to add advanced fields to quick create.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: gitdeveloper version
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
In modules that include a block with products and services there is no quick create option (you should always use full edit mode). The full edit mode has been improved and looks a bit different (you can’t see it on the dev version because it still uses the old configuration, but you will be able to test it in a couple of days). 
Right now we’re not planning to introduce any changes into this functionality.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/45091357-7a0cff80-b112-11e8-96b8-4e06a1f71118.png)

**Comment by vovpff** [comment]
@bpabiszczak @paula-w looks cool. This is optional view or replace old type?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/2bee7eeab4698d30f5475566594786405fb638e2/config/performance.php#L94-L95
