### ISSUE TITLE
The developer version doesn't work well in other browser except Chrome

### ISSUE THREAD

**Issue by Tingfe** [YetiForceCompany/YetiForceCRM#7114]
#### Issue

I tried in Eage, 360 Browser etc. .
When we enter Detail view to most of modules(such as leeds, accounts, etc.), We can only stay summary tab, cannot change to other tabs, and any quickcreate function on the right side doesn't work. 

#### How to trigger the error

1. visit gitdeveloper.yetiforce.com via Eage browser.
2. Choose Leed module
3. Select any record

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rafalpospiech** [comment]
This is because those browser doesn't fully implement ECMA Script 2015 Standard.
For example [spread operator](https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Operatory/Spread_operator) which is standard now.
We are debating right now on supporting older browsers, but you now, times goes on and new standards have a lot of useful tools. The more that we do not use the newest syntax (drafts etc) - only standards that were defined a few years ago. We cannot sit in past all the time.
We are thinking on babel too.
This is only my personal opinion but I don't know exactly what will be decision in this matter.
Keep in touch

**Comment by Tingfe** [comment]
@rafalpospiech But in my opinion, it should be compatible with most pupolar browsers, like Firefox, Eage. We can not ask everybody use Chrome who want to use this wonderful CRM. 
And, I tried the stable version, it works fine .

**Comment by ldgbc** [comment]
Never realized how much of an issue that is. Is it only v4.4 that Chrome is the "BEST" way to go? or it has been the case ever since v3.4? v4.0?

I guess I give it a try on Chrome to see if there any magic.

**Comment by Tingfe** [comment]
I checked my firefox version, it's 52.3. and should out of date.
I tried the latest version 61. works very well.
@ldgbc @bpabiszczak

**Comment by rafalpospiech** [comment]
I think that browser should be updated regularly not only for features but mainly because of security patches. Very often older browsers has major vulnerabilities that are known widely and documented online.

**Comment by bpabiszczak** [comment]
Let’s not kid ourselves, IE & Edge are not browsers. The fact that they are still visible in the statistics is related, among others, to Microsoft’s bad practices, ie. in Windows links can only be opened using Edge. These practices should be eradicated, and browsers like these should be boycotted.

When we finish WCAG 2 and RWD then we’ll think about full support for Safari, because that’s the second browser worth paying attention to due to its 13% market.

**Comment by poradz** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/7221
After those changes we are able to generate min.js files with babel (we use rollup api), which makes system compatible with other browsers. I've already tested it with Edge and Safari and it works and looks just as in Chrome.
