### ISSUE TITLE
Can Not Edit Leads or Contacts

### ISSUE THREAD

**Issue by erik7777** [YetiForceCompany/YetiForceCRM#7208]
I have the same issue as the person in Issue #6561 which is marked closed but I do not see the solution / or resolution.

There is a Wrench Icon next to the Contact and Lead Records that can not be accessed because there is a Pop Up of "Quick Preview / Complete Details" Buttons that Blocks Access. 

It is very difficult to test or use a CRM / ERM solution if the records can not be edited.

Issue

Fresh installation of Yetiforce CRM 4.3 using Softaculous via cPanel on A2 Hosting. Immediately after successful install, log in and create a Lead. Save the Lead, view the Lead, cannot edit any fields of the Lead.
Actual Behavior

When viewing a Lead or Contact, mousing over any field does not reveal the pencil icon to edit. It is not possible to edit anything. Behavior is the same in latest version of Chrome, Firefox, Waterfox and Edge.
Expected Behavior

Existing installation of 4.2 works as expected. When viewing a Lead or Contact, mousing over any field reveals the pencil icon and information can be edited.
How to trigger the error

    Install Yetiforce using Softaculous.
    Create a Lead.
    View the Lead and mouse-over an editable field and look for pencil icon.

Your Environment

    YetiForce Version used: 4.3
    Browser name and version: Firefox, Opera
    Environment name and version: cPanel / A2 Hosting
    Operating System and version: Windows 10

**Comment by bpabiszczak** [comment]
> I solved the problem by removing "pdo_mysql" from the server configuration and setting "nd_pdo_mysql".

**Comment by erik7777** [comment]
I do not understand your response.  Every person who installs the latest version of this software needs to change a Server setting to be able to use the software.When is this software going to be patched so it is no longer an issue?9:19 PM, July 11, 2018, "Błażej Pabiszczak" <notifications@github.com>:
I solved the problem by removing "pdo_mysql" from the server configuration and setting "nd_pdo_mysql".

**Comment by bpabiszczak** [comment]
The application requires the server to be properly configured! If the server has a different configuration than the one we require then why are you surprised the app doesn’t work? Softaculous is responsible for server and app configuration (if you’re using their installer). If you install it on your own you have to follow the manual on our website.

**Comment by bpabiszczak** [comment]
If changing a parameter that takes 30 seconds is too difficult for you and at the same time you don't plan to add any fixes to the system on your own, so that you wouldn’t just 'take' from open source but you would 'give' something as well, then I have no good advice for you. 

If the software doesn’t meet your expectations then I recommend switching to OODO or SuiteCRM, there you’ll certainly find what you’re looking for.

**Comment by erik7777** [comment]
Your lack of Customer Service skills is really shocking.  My Server does not need to be fixed.  Yetiforce has released an inadequately tested version of Software that needs to be patched as soon as possible.I can not see how any commercial customer could possibly use this Software in a production environment.  If your poor attitude is representive of the type of support a Yetiforce customer would receive, it would definately be a good idea to install one of the many better functioning alternatives that you recommend below.9:08 AM, July 12, 2018, "Błażej Pabiszczak" <notifications@github.com>:If changing a parameter that takes 30 seconds is too difficult for you and at the same time you don't plan to add any fixes to the system on your own, so that you wouldn’t just 'take' from open source but you would 'give' something as well, then I have no good advice for you.
If the software doesn’t meet your expectations then I recommend switching to OODO or SuiteCRM, there you’ll certainly find what you’re looking for.

**Comment by bpabiszczak** [comment]
You confuse customer service and honesty. I’m not here on GitHub to pat people on their backs, I’m here to help people fix their problems. The solution to your problem is changing one parameter and it doesn’t matter if that’s the right approach or not, the app’s requirements are listed on the website and during the installation.

I think our support is one of the best, compare us to our competition where you’ll find hundreds or thousands of open issues that are completely ignored by the producer. We’ve got 5 open issues out of ~4500 total issues, which means we’re one of the best.

As far as the quality is concerned I wouldn’t be too worried if I were you. YetiForce has been chosen for one of the biggest deployments in Europe for more than 12000 users, and additionally, we meet 111 criteria monitored by https://insight.sensiolabs.com/what-we-analyse.

Once you find your ideal CRM let me know, I’ll gladly learn something new from our competition.

**Comment by erik7777** [comment]
You have completely convinced me to uninstall Yetiforce.  Congratulations.  If the other Yetiforce employees are equally as obnoxious, I doubt your company will be in business for much longer.Learn how to program and perform adequate quality control prior to releasing new versions of your software.10:44 AM, July 12, 2018, "Błażej Pabiszczak" <notifications@github.com>:You confuse customer service and honesty. I’m not here on GitHub to pat people on their backs, I’m here to help people fix their problems. The solution to your problem is changing one parameter and it doesn’t matter if that’s the right approach or not, the app’s requirements are listed on the website and during the installation.
I think our support is one of the best, compare us to our competition where you’ll find hundreds or thousands of open issues that are completely ignored by the producer. We’ve got 5 open issues out of ~4500 total issues, which means we’re one of the best.
As far as the quality is concerned I wouldn’t be too worried if I were you. YetiForce has been chosen for one of the biggest deployments in Europe for more than 12000 users, and additionally, we meet 111 criteria monitored by https://insight.sensiolabs.com/what-we-analyse.
Once you find your ideal CRM let me know, I’ll gladly learn something new from our competition.
