### ISSUE TITLE
What is the correct length for a custom currency field?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#7327]
Hi,

when creating currency fields, what is the correct value that should be put in the field length box? I see the decimal field has 5 in it. I have never really known what the field length should be - I want for it to be the same as all the built in currency fields in yetiforce - for consistency.

Thanks in advance

**Comment by paula-w** [comment]
We’ve never really analyzed it in depth, when we develop ERP then probably we’ll spend some more time on it.
Here in Poland only it’s enough for the decimal field to be only 2 digits, however I think there are 5 digits in the base. We’re not planning to change it for now because we first have to check if it causes any problems, until then we’ll leave it as it is.
