### ISSUE TITLE
Disable or Skip - "Send statistical information" in Admin Setting [question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7357]
#### Issue
I am using multiple testing system (since I always break stuff) and don't quite want to send "Send statistical information" and would like to skip or bypass that. Where can I go to do that?

#### Actual Behavior
Popup each time.

#### Expected Behavior
Able to skip, or never send.

#### How to trigger the error
1. Log out.
2. Log in Admin account.
3. Go to /index.php?module=Vtiger&parent=Settings&view=Index
4. Get this popup.
![issue - skip send stat info](https://user-images.githubusercontent.com/1805303/43353236-5fc94c7e-9276-11e8-85cc-e4691b39f51f.png)

#### Your Environment

* YetiForce Version used: v4.3
* Browser name and version: Firefox 61
* Environment name and version: XAMPP
* Operating System and version: Windows 7

**Comment by vovpff** [comment]
i'm interested too

**Comment by paula-w** [comment]
According to our [license](http://yetiforce.com/en/yetiforce/license) - „The Software used for more than 14 days must be registered via the built-in form.”
You can disable the popup in code but when you use the copy for more than 14 days you have to register it anyway.
We’ll make these notifications less annoying, they’ll pop up every couple of days instead of every day.

**Comment by vovpff** [comment]
@paula-w my system already registered 1-2 years ago. For some tests I make full copy of system and need to register every copy but usually this come to trash bin after ~one week. Is this not enough to register once for example for  one domain?

**Comment by ldgbc** [comment]
@vovpff Hi, do you have any luck with it?
I manage to find this file: 
YetiForceCRM/app/SystemWarnings/YetiForce/Stats.php

Still trying to figure out which part to comment.

**Comment by vovpff** [comment]
@ldgbc I found solution but this is not good to use it because licence.
@paula-w I think system must check domain name before request registration. If domain already in your database there must be no pop up. Or at first registration user need to put value of copies of system what will be installed on this domain. Something like this.

> We’ll make these notifications less annoying, they’ll pop up every couple of days instead of every day.

Now pop up appears every admin login. I have 4 systems: production, developer, update test 4.3 to 4.4. and for training (testing) for my colleagues. Every time when I login by admin I has this registration form.  Every re-logging from admin to user and back I has registration form too. This is funny but not for 4 systems at one server.
