### ISSUE TITLE
[IDEA] Inventory module

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#739]
You can in the future add a module inventory in large companies often keep records of inventory, it would not be very good to have such a module in the CRM system

**Comment by KatarzynaUlichnowska** [comment]
Hello!
Ultimately, the system is meant to be something more than a simple CRM, it will be a complex system for companies and will contain functionalities from systems such as ERP, DMS, CRM. However, this will be developed in stages and will be very advanced. That’s why I will close this issue for now, because it is a long-term process and the ticket would have to be open for the next year.
