### ISSUE TITLE
Merging records issues

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7480]
Thanks a lot for "duplicated" option in filters. I found a lot of duplicatest in my system. Another one cool function is "Merging records". Works perfect with contacts, accounts and etc but some issues has been found.

#### Issue 1

Not possible to merge products. I don't understand real reason but I think problem is product quantity. This value can't be edited by user.

Really for product quantity should be option like sum quantity of selected products.

**Upd 1:** there is no any data appears for advanced modules table for deleted product. 

#### Issue 2

If advanced module records merged then product tables from different records really not merged. Only basic fields merged.

**Upd 2:** Using merging function accepted (I mean protected) records can be merged. Protection not works proper in this case.

#### Issue 3

After merging in updates tab appears line about record modifications but in reality would be coll to have some indication what record was merged instead updated and short data about deleted record (for contacts First name,  Last name, Member of as example).

**Comment by mariuszkrzaczkowski** [comment]
Always add separate issues
1. Non-editable fields can't be merged.
You have an interesting idea for summing values, we'll keep that in mind. However, we don't have plans to add it, we'll wait for a person who orders it.

2. An advanced block isn't merged as it's difficult. It would require additional configration. We don't have plans to change it, we'll wait for someone to order it.

Protected records are non-editable and therefore not merged.Unblocking it could expose data to the modification. It is blocked to avoid changing it.

3. Records that were merged are moved to the recycle bin and should disappear from the system, so whowing them in the history isn't possible because they don't exist.

![image](https://user-images.githubusercontent.com/10198654/48759327-0efbaf80-eca3-11e8-846b-a314e0810d84.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks for your explanations. In my understanding
1. There are no ability to merge product because qty will be missed after merging.
2. Advanced modules can't be merged perfect because product table will be missed
in this case merging is not useful tool because there are needed a lot of actions to avoid data missing
