### ISSUE TITLE
After we add a product to an After we add a product to an opportunity, we cannot find this opportunities from vendor imformation, we cannot find this opportunities from vendor information

### ISSUE THREAD

**Issue by Tingfe** [YetiForceCompany/YetiForceCRM#7669]
#### Actual Behavior

After we add a product to an opportunity, we cannot find this opportunities from vendor information. 
#### Expected Behavior

After we add a product to an opportunity, we should find this opportunities under vendor information, because product is belong to vendor. So that we can easily see how many opportunities are related the vendor. 
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.4.0
* Browser name and version:Chrome
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@Tingfe you can add relation 1:M between Opportunity and Vendor. In this case you get additional tab in Vendor module what contain all opportunities related to this vendor

**Comment by Tingfe** [comment]
@vovpff Hi, but the relation is fixed in CRM system. How can I add relation 1:M between those two module? Add additional code?

**Comment by Tingfe** [comment]
@vovpff What's more, there is already relation between Opportunity and Vendor, and we can find Opportunity tab in Vendor module, but the Opportunity can not list there automatically.

**Comment by vovpff** [comment]
@Tingfe sorry, my mistake. You need to change config file:
https://github.com/YetiForceCompany/YetiForceCRM/blob/a83c8efe7e5a1959d20d3fb0245fa7baab492cf8/config/developer.php#L18

I think this is M:M relation already established. In Vendor module you can select/add Opportunities.

You can add field to opportunity

![image](https://user-images.githubusercontent.com/8545791/44193762-9aadef00-a13c-11e8-99c2-3195cd96373c.png)

After that you will achieve 2 Opportunities tabs in Vendors module. One of this tab you can hide* (old one). In this case in opportunity you need to fill Vendor filed with vendor name. This will work!

* I'm not sure what happens if you remove old relation but you can try it.

**Comment by Tingfe** [comment]
@vovpff Thanks, Vovpff.
I'v tried what you said, yes I can add new relation. but only can choose records manually. What I want to know is:
is it possible when I create an new Opportunity, and relate a product to this Opportunities, then when I open the vendor which contain that product, I can see the Opportunity. But at present, I have to add Opportunities manually in Vendor module.

**Comment by vovpff** [comment]
@Tingfe are you try this on your local system or gitdev?

**Comment by Tingfe** [comment]
@vovpff I tried it on my local system, version 4.4.0

**Comment by vovpff** [comment]
@Tingfe pls give me some time and I will explain you how to achieve it (there are some limitations...)

**Comment by Tingfe** [comment]
@vovpff That's perfect! Thank you so much

**Comment by vovpff** [comment]
@Tingfe dev 4.4.20
![rel-oppo-ven-44-20-1](https://user-images.githubusercontent.com/8545791/44211638-1e360300-a172-11e8-9c85-680a429f9242.gif)

2 hours ago this actions not works in gitdev. Maybe devs fixed something.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
today we switched GitDev to PHP 7.2 and error_reporting = E_ALL.
This may cause errors in the functioning of the application. We want to find all the errors and fix them.

**Comment by vovpff** [comment]
@KatarzynaUlichnowska @mariuszkrzaczkowski some hours ago I tried actions on gif and after step when I add 1:m field to Opportunity module to Vendors I achieved opportunities tab with relation M:M not 1:M. Sorry because I unsaved this gif...

**Comment by vovpff** [comment]
@KatarzynaUlichnowska sorry for off topic, looks cool:

![image](https://user-images.githubusercontent.com/8545791/44212575-5b9b9000-a174-11e8-8ad4-51a25a6a0bc0.png)

**Comment by Tingfe** [comment]
@vovpff is it possible when we add product in Opportunity, then we can find the related information in Vendor module? As we know the Product is related to Vendor.

**Comment by vovpff** [comment]
@Tingfe I'm not sure what you can do it without system modification. Maybe Yeti crew can advice somrthing

**Comment by mariuszkrzaczkowski** [comment]
It is possible to show related information but you will have to add a widget with this information on the Opportunity. You can also use a quick preview on the record list. Please see below:

![image](https://user-images.githubusercontent.com/10198654/48842049-8446ad80-ed93-11e8-943d-beef865d66c4.png)

In order to see all Products related to this Vendor, you would have to create a customized relation and a query that shows it.
