### ISSUE TITLE
Import/Export all data & config [enhancement]

### ISSUE THREAD

**Issue by SALITEL** [YetiForceCompany/YetiForceCRM#7783]
#### Enhancement

I am having problems updating to version 4.40 but on the same server I was able to install a clean installation of the new version.

That's why I suggest:

An option to export all the data and customized configuration of the CRM to be able to import in another installation with the same version or with another one.

This would facilitate updates, server transfers, etc.

#### Actual Behavior

This option does not exist (or I do not know where it is)

#### Expected Behavior

To be able to export and import independently of the installed version.

Inside of exported file would be the version original with which it was exported so that it can be treated correctly when importing it.

#### Your Environment

* YetiForce Version used: 4.30
* Browser name and version: Google Chrome
* Environment name and version: Server: CentOS / Client: Windows

**Comment by vovpff** [comment]
@SALITEL i think this is difficult to implement one click export of system data what contains self-made modules, fields, relations, handlers and etc.

Usually for migration you need dump of database and copy of system folder. It this cane you don't need to import something to another installation.

**Comment by ldgbc** [comment]
That would save lots of headache but due to the nature of the design of the current coding and based on previous issue reading this is currently not possible at the moment. Yetiforce team can probably do it since they write thing and have understand of it, just have to fork out the dollars.

You will still need some programming knowledge to properly create such a backup and to import it back. It isn't as simple as export myphpadmin table (I tried that once, got scare).

Currently I'm trying to learn to use Git and Github, that way I can patch bug early instead of waiting for the next stable release which is usually 6 months or longer. But good news that is Yetiforce is consider Feature Finalized, they won't be adding or removing or doing anything major changes (don't quote me on this, it might be v4.5 when that is true).

In term of backup for your own safely, I suppose there is a few one, (1) data dump like vovpff said, (2) automatic database backup (if your server allow it, usually they do). (3) work on XAMPP or offline or local environment. (4) export and import of CSV or Excel.

**Comment by PercyP** [comment]
For me, the ability to export custom modules (built from scratch using yetiforce module/field creators) and/or customised modules i.e. in my case I customised the existing module Competitors to have a different purpose.

Then after that I could simply export then import the data. 

It would also be good to have a way of safe-guarding 3rd party custom work and also the customisations yetiforce themselves provide in their paid services so these go through more smoothly and we don't have to have them re-built or re-integrated each time. 

I am not sure how Vtiger handles this with all the 3rd party developers etc. I suppose the 3rd parties have to provide the patches so that their applications continue to work when the updates become available for the CRM - just like it does with other platforms like Wordpress, Joomla etc.

**Comment by paula-w** [comment]
Right now we're not planning to change how import/export work, but in the future we will expand these functionalities.
