### ISSUE TITLE
filters not showing in the module when widgets added

### ISSUE THREAD

**Issue by BraulioBracamonte** [YetiForceCompany/YetiForceCRM#7870]
#### Issue

Hi, the filters created by a user are not shown from the module after the creation of widgets from those filters

#### Actual Behavior

user go to "home" and can see the widget from his filters (and works great), but if user clicks the module, there are no filters (this user created the filters).
if i click on the "get total amount of records, and click again, then i can see the filters.
i found that if i take away "&mid=155" from the url, then i can see the filters.

#### Expected Behavior

the user must be able to use his own filters when he is in the module and not only from the widgets without having to modify manually the url each time

#### How to trigger the error

![001](https://user-images.githubusercontent.com/35633915/44801680-4fa1cc00-ab7f-11e8-9590-c94bdb11d2ac.gif_2)

#### Your Environment

* YetiForce Version used:4.3.0
* Browser name and version: google chrome  68.0.3440.106 (Build oficial) (64 bits)
* Environment name and version:
* Operating System and version:

**Comment by adudekyeti** [comment]
This happened, because probably you have wrong configuration in "Settings -> Menu - Configuration". There you can easily select available filters accessible after clicking module from menu.
![issue 7870-1](https://user-images.githubusercontent.com/39482453/48843605-cf62bf80-ed97-11e8-897e-717fdb3a6fca.PNG)
Then you can select filters:
![issue 7870-2](https://user-images.githubusercontent.com/39482453/48843618-da1d5480-ed97-11e8-9b79-0808e1419b0a.PNG)
