### ISSUE TITLE
Auto-populate a field

### ISSUE THREAD

**Issue by webfacehu** [YetiForceCompany/YetiForceCRM#8082]
Hi!
Is there any way that auto-populate a field based on same module input field?
I mean eg. when i entered numbers in the zip code field, the City name appear automatically in the City - field?
Thanks for your help!

**Comment by paula-w** [comment]
Yes, it’s possible. There is a built-in integration with Google Maps and Open Street Maps in the system, you can find it [HERE](https://gitdeveloper.yetiforce.com/index.php?module=ApiAddress&parent=Settings&view=Configuration&block=5&fieldid=61 ).
We created 2 modules that can do that, you can take a look at them in [our store]( https://yetiforce.shop/index.php?option=com_djcatalog2&view=items&cid=6:modules&Itemid=1071), however, they only work in Poland because they connect with polish offices.

**Comment by webfacehu** [comment]
Hi Paula,

 

Thanks!

 

If you wish, i will make hungarian versions of these modules.

 

Regards,

 

Laszlo

**Comment by paula-w** [comment]
Thanks! We don't have a Partner program yet, we'll launch it soon, but please send us an email (info@yetiforce.com) and we can definitely figure out the details!

**Comment by mariuszkrzaczkowski** [comment]
> Hi Paula, Thanks! If you wish, i will make hungarian versions of these modules. Regards, Laszlo

That's great that you want to help us, you can do it easily by creating a file like these ones:
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/app/Map/Address
and it will automatically appear in the search.
