### ISSUE TITLE
yetiforce Error!!!  DateTime::__construct(): Failed to parse time string (04-2018-10 08:00:00) at position 0 (0): Unexpected character

### ISSUE THREAD

**Issue by webmastergta** [YetiForceCompany/YetiForceCRM#8187]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by webmastergta** [comment]
please help me

**Comment by acsinsurancegroup** [comment]
I'm getting this same error in this format:

DateTime::__construct(): Failed to parse time string (21-2018-11 12:00:00) at position 0 (2): Unexpected character

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/48611586-e4e67c80-e986-11e8-8c9d-da63bbba08d0.jpg)

**Comment by acsinsurancegroup** [comment]
Issue - Will not save date correctly in calendar when MM/DD/YYYY format is used in any combination

Actual Behavior - The error I posted above

Expected Behavior - It should easily save accordingly no matter what date format is selected

How to trigger the error - Trying to create an event or edit it

Screenshot of configuration - Not required just throws error I posted above

PHP/Apache/Browser Logs

Your Environment - Plesk Onyx Panel server version 17.8.11 using CentOS 7

YetiForce Version used: 4.4.0

Browser name and version: Chromium most recent and same issue with Firefox latest

Environment name and version: Plesk Onyx Panel server version 17.8.11 using CentOS 7

Operating System and version: CentOS 7 on server and Linux Mint 19 Tara on my desktop

Also my PHP version on the server is 7.2.12 and all settings are as required for YetiForce to operate and some set even higher.

When I changed the date format to dd-mm-yyyy it will save and edit events with no issues whatsoever. I can use any other combination of mm-dd-yyyy or mm/dd/yyyy or mm.dd.yyyy doesn't matter which combination I use it throws that parse error. Therefore I'm convinced it's a system bug and not anything to do with the environment anyone is using. Every single other date format available works just fine.

Thank you :)

**Comment by slawekk87** [comment]
Please check this on developer version:
https://gitdeveloper.yetiforce.com/

**Comment by TomaszQr** [comment]
Duplicate #8403

**Comment by acsinsurancegroup** [comment]
Did that as well and all it does there is get stuck with saving data icon
and never saves. It's stuck in loop.
