### ISSUE TITLE
recurring invoices - coming

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#844]
would it be possible to create a report that shows coming creation of recurring invoices from sales order module.

either as a report.
but also on the organizatin card - create a tab "coming invoices" ?
to get a clear overview of the expected revenue

**Comment by bpabiszczak** [comment]
This kind of report can be quickly created because in the section responsible for creating of recurring invoices [on orders] you define a status with which invoices will be created.

In the future we are planning to change this logic a bit because there cannot be info about how it was generated as well as it shouldn’t be a status field that is there for a completely different reason. We will develop it soon.
