### ISSUE TITLE
Migration SQL dump between Yetiforce versions

### ISSUE THREAD

**Issue by krispom** [YetiForceCompany/YetiForceCRM#8629]
Is there possible to make SQL dump on 4.3.0 version of Yetiforce and recover to 4.4.0 or I have to update from 4.3.0 to 4.4.0 then make a SQL dump?

**Comment by SALITEL** [comment]
That suggestion I already made it in #7783 

It is very useful

**Comment by paula-w** [comment]
@krispom Unfortunately it won’t work. Due to the fact that 95% of all information (apart from eg. storage, user privileges folders) is in the database, it will be easier to copy a few folders to a clean 4.3 version and start from scratch by migrating from 4.3 to 4.4. From what I understood you don’t have a copy of the files, you only have a copy of the database.
