### ISSUE TITLE
Check Rouncube settings

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#8657]
Check Rouncube settings.<br><br>I have configured the stmp of two mails of different domnios. The system has sent me the message that the configuracions is correct. But when I try to configure rouncube, for the second of the emails I'm not sure how to put the user and password in the configuration panel, because when I give it to save it does not save it.<br><br>I would like to insert it manually in Ossmail.php<br><hr>Generado por YetiforceCRM ver. 4.4.0<br>PHP: 7.1.24<br><br><strong>Errores de configuración del servidor:</strong><br>error_reporting: E_ALL<br>output_buffering: 4096<br>default_socket_timeout: 60<br>memory_limit: 50 MB<br>max_input_vars: 1500<br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br>

**Comment by joelbcampos** [comment]
[OSSMail.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2605392/OSSMail.txt)

**Comment by rskrzypczak** [comment]
First of all: 
   error_reporting: E_ALL & ~E_NOTICE

Secondly:
   If you leave login credential in this form 
![image](https://user-images.githubusercontent.com/10221999/49081952-b13e0900-f248-11e8-8b23-2159fcdb7be8.png)
you will be asked for a login and password when you open 'My mailbox' ([link](https://gitdeveloper.yetiforce.com/index.php?module=OSSMail&view=Index&mid=113&parent=44))
and smtp data will be loaded from the logged in user.
If you enable autologin you won't have to do it again. 
![image](https://user-images.githubusercontent.com/10221999/49082051-01b56680-f249-11e8-99fd-488b4223deec.png)
Otherwise  there can only be one set of credentials in roundcube configuration.

Third thing:
If you have active apcu the data after modification will be displayed after a while. 
It was fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/8697/commits/0c6cb64cd5da7cdb6aa3f162871d0859ed8f718e
