### ISSUE TITLE
Invoice, payment and marketing

### ISSUE THREAD

**Issue by kimborg** [YetiForceCompany/YetiForceCRM#8770]
I have a few questions regarding invoice and payments:
1. I don’t sell to companies, but to consumers. As the contacts module seems to be the only module that contains “First name” and “Last name”, it seems to fit better than leads and accounts modules. But is it possible to invoice contacts rather than companies/accounts?
2. Is there a way two follow up invoices that have an outstanding balance? I assume I can assign an incoming payment to a specific invoice, and in that case I would need a detailed report on customers that have an outstanding balance.
3. I run a yoga studio, so I sell yoga courses. I’m not quite sure what the difference is between YetiForce’s “services” and “paid services”, but would like to know if I can mail customers based on their invoiced purchase history as in the following example: Mail customers who purchased course (service or paid service) A last year, but not this year.

**Comment by paula-w** [comment]
1. The Accounts module can be used for more than just companies; you can use it to enter data of consumers, for example as the account name. If you need a completely different set of fields for a consumer and for a company then it’s enough to change the system configuration. Relating invoices to contacts instead of accounts will cause problems in the future because it won’t be working according to the logic hard-coded in the system.

2. It’s enough to relate payments-in to invoices in order for the system to automatically show invoice balance and account balance. You can set simple filters that will show you whether or not someone paid on time, and you will be able to send automatic notifications. It might need some programming work to make sure everything is calculated correctly.

3. Services is something you sell/offer, and sold services is something you already sold. It works well if you automatize the process, for example: after an invoice is paid the system generates sold products and services, and then, on the basis of these sold products and services you can generate reports/analytics. The system will also be able to remind you that someone bought something a year ago and will automatically create a sales opportunity a month before that.

**Comment by kimborg** [comment]
Regarding question 3: Based on their purchase history i want to mail customers who "bought product A in year x, but not this year. In vTiger I had two options:
1. There was a 3rd party advanced report module that could perform this query and produce a spreadsheet. I could then use that as a mailing list.
2. I could make custom fields for each year, import sales from my webshop and map those to the proper vTiger field. Then I could use the vTiger lists to perform the query. Tedious, but it worked.
So my question remains: Is it possible to generate a mailing list with people that bougth item a in year X, but not this year?

**Comment by paula-w** [comment]
If you add a sold product or service you should fill the fields in such a way to make it easier in the future to filter, group, and sort data. Additionally, you can use the functionality that is built into the filters (displaying fields from a related module). From the technical perspective you can do that in many ways, unfortunately we don’t give advice as far as system design is concerned here on GitHub.
