### ISSUE TITLE
NO SOLUTION GIVEN

### ISSUE THREAD

**Issue by Thirdy-jea** [YetiForceCompany/YetiForceCRM#8829]
It's  me again. I was unable to get the required information to get the CRM running. 
![image](https://user-images.githubusercontent.com/40558801/49769382-e4899900-fd1a-11e8-9518-e29943aa9706.png)

As seen on the picture, there was no real conversation that happened. Can someone please help me resolve this issue?

**Comment by mariuszkrzaczkowski** [comment]
no required information about the environment, configuration and logs
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/developer.php

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?q=is%3Aissue+developer+mode+is%3Aclosed

**Comment by paula-w** [comment]
We don’t know how you launch this version because the screenshots show us different information, for example, you use WAMP, you downloaded a version that requires data to be loaded from composer, other screens show that not everything was loaded from composer.

Get the stable version, you can download it from here:  https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.4.0  and run it on a server that meets these requirements: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

If you want to report an issue it has to be described in detail, otherwise we will have to close it.
