### ISSUE TITLE
Where to Send The Translated Greek Files

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#919]
The Language is missing from the test site.
Hopefully i have saved it in my hard disk!

Because i dont want to do the same process again
Tell me where to send you the files to upload it to the test site.

So i can continue the translation.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
everyone who translates language packs should do it on his local version of YetiForce and then add the translation to YetiForce fork on GitHub. When the translation is ready, you send a request to us to adjust changes in Master branch so the translation might be available for everyone [it can also be sent to us as ZIP]. It would be best if you could learn how to use GitHub because it’s a very powerful communication tool. 
Testing version is for tests so it is restored every dozen/several dozen hours. When it’s restored, everything what was modified is deleted and a basic version is restored. Use a testing version for verifying whether an error that you found on your version exists also on a testing version, it shouldn’t be used for anything else.

**Comment by eptapsyxos** [comment]
Ok katarzyna thanks

**Comment by nikoup** [comment]
> 
> 
> Ok katarzyna thanks

Do you have the Greek Language my friend?>

**Comment by bpabiszczak** [comment]
https://crowdin.com/project/yetiforcecrm
