### ISSUE TITLE
Prevent Duplication in leads and custom modules 

### ISSUE THREAD

**Issue by AhmedABELFATTAH** [YetiForceCompany/YetiForceCRM#9242]
I want ask when Prevent Duplication Will be released when ?

**Comment by paula-w** [comment]
If a client needs this functionality then one of our developers can implement it for him in 1 ~2 hours. In order to add it as a fully configurable feature it would require writing an entire mechanism and we simply don’t have time for that right now. The main problem is that each company expects it to work a little differently for various fields.
