### ISSUE TITLE
Softaculous 

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#927]
Do you have in your roadmap to add yetiforce on softaculous?

It will be easier for average users to install it...

**Comment by bpabiszczak** [comment]
I don’t see any benefits from this tool. I understand that hosting receive a ready-mage tool in order to install many applications with a single click but there is no difference for a regular user who wants to install YetiForce. We can add this integration in the future as part of “the promotion of YetiForce”.

**Comment by eptapsyxos** [comment]
thank you in advance.is time saver.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
the good news is we contacted Softaculous and they agreed to add YetiForce. 
We provided all the required information and today we received a reply that they will start the works soon.

**Comment by eptapsyxos** [comment]
That's fantastic news!!!!!thank you very much!!!!!!

**Comment by bpabiszczak** [comment]
http://www.softaculous.com/apps/erp/YetiForce_CRM

**Comment by eptapsyxos** [comment]
You are the best.i love you

**Comment by bpabiszczak** [comment]
sorry, I already have a wife ;) @apabiszczak

**Comment by nikdejan** [comment]
@bpabiszczak likes open source, but his wife does not ;-)
