### ISSUE TITLE
Wrong PHP version, recommended version >= 5.4.0

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#930]
I am trying to install but i get this messsage
Wrong PHP version, recommended version >= 5.4.0

Whats wrong?

I read on site this

PHP 5.5 - works also fine with previous versions, i.e. 5.4, 5.3 (the latest versions are recommended).

I am running Apache Version	2.2.29
PHP Version	5.3.29
MySQL Version	5.5.42-cll
Architecture	x86_64
Operating System	linux

Any suggestions?

**Comment by amicheals** [comment]
@eptapsyxos php 5.4 did not work for me. I had to upgrade to php 5.5 for the installation to work.

I would suggest updating your php version.

**Comment by eptapsyxos** [comment]
I am on cloud server and i can not upgrade i have to move to vps server.....

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
the latest version of the system requires PHP 5.4 or higher [if you find somewhere a description about a version lover than 5.3 send us a link and we will fix it]. Recently, there has been a small error with 5.4 version and we are fixing it atm, the system works fine with 5.5 and 5.6.
Cloud versions must have an option that allows to change PHP version to higher, because 5.3 is outdated. Ask your administrator.

**Comment by rrajan94** [comment]
![screenshot 252](https://user-images.githubusercontent.com/25589618/43945679-8309234c-9ca0-11e8-9e6a-abacb0125bc3.png)

I saw this error on page page load & in log file this error

[10-Aug-2018 07:38:09 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/sample/sample_crm/include/RequirementsValidation.php:9


How to resolve this

**Comment by vovpff** [comment]
@rrajan94 latest version 4.4.0 works stable with PHP ver. 7.1.x. Let's update your PHP at first.

**Comment by paula-w** [comment]
Please take a look at the latest [system requirements](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements).
The recommended PHP version is 7.1
