### ISSUE TITLE
"Your PHP MySQL library version 5.0.77 differs from your MySQL server version 5.6.21. This may cause unpredictable behavior."

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#951]
Trying to figure out what is happening here.
For my hosting provider they said me that is using the latests versions
I am on php 5.6

I hired freelancer to install it for me.
But we stuck here

www.medicross.gr

PLEASE DONT COPY PASTE ME THE LINK OF THE WEB REQUIRMENTS I HAVE ALREADY READ IT .

HELP AND INSTRUCTIONS AND FINALLY A SOLUTION

**Comment by amicheals** [comment]
@eptapsyxos seems like you have a file called index.html in your directory. Delete that for and try to do the installation.

If you need help, I can install it for you

**Comment by eptapsyxos** [comment]
thanks amicheals for the help.
you can contact me at mporeli1987@hotmail.com to provide you the passes of the server.
You can give it a try for me if you can.
Please send me an email to respond to you on the email address i ve mentioned before.

Thanks a lot!

**Comment by KatarzynaUlichnowska** [comment]
In Google they write everywhere that it’s related to the configuration of the server and has nothing to do with the application.
Individual problems [such as yours] with the server are difficult to analyze because they cannot be easily reproduced. To solve this problem it’s not necessary to have a good developer or YetiForce specialist but a good administrator who will explain you what is the reason and suggest a solution. Unfortunately, the services of our administrator aren’t free. 
YetiForce should work without any problems on professional hosting services that allow the basisc PHP configuration.
