### ISSUE TITLE
[bug] 5.0.0 PDF broken?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9512]
# 🐞 bug report

### ⁉️ Describe the bug

Every (standard, selfmade) available PDF template cause error:

```
Call to undefined function YetiForcePDF\bcadd()
```

### 👎 Actual Behavior

Error - no PDF

### 👍 Expected Behavior

PDF

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by neuronetio** [comment]
PHP BC Math extension is required.
http://php.net/manual/en/book.bc.php

**Comment by vovpff** [comment]
I will check it

**Comment by vovpff** [comment]
@neuronetio thanks. It works! Any ideas how to force pdf opening instead downloading?

**Comment by rafalpospiech** [comment]
For now it is tricky because pdf is generated on the fly, basing on post request, and there are some problems with downloading if it was opened in browser (post data is lost).
I'm adding this topic to our TODO list and we will think of it, maybe we do something to implement this behavior. We will see. I will write here if I will know something about this. For now I'm closing this issue, but feel free to respond here.

**Comment by vovpff** [comment]
@rafalpospiech thank a lot for info! I will wait your solution!
