### ISSUE TITLE
[bug] cant upgrade from 4.4 to 5

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#9517]
### ⁉️ Describe the bug
While executing the upgrade to version 5 from 4.4, I got the following: Error!!!
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'default' in 'where clause' Failed to prepare SQL: SELECT * FROM `s_yf_companies` WHERE `default`=:qp0 LIMIT 1

### 🔥 How to trigger the error
![upgrade](https://user-images.githubusercontent.com/23698008/52871856-4f0bea80-314b-11e9-9555-cde12474e10c.jpg)

1. Go to 'Standard modules >> Modules – Installation '
2. Click on 'Install from file'

### 📷 Screenshot of configuration
![yetiforce_settings](https://user-images.githubusercontent.com/23698008/52872053-cd688c80-314b-11e9-9942-35e25555fee2.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
nothing generated about the error in the log file. Debugging is active

### 🌍  Your Environment 
I'm using a local test installation with AAMPS on windows 10

**Comment by z0lo13** [comment]
I had that issue as well- just by retrying several times it finally went through

**Comment by Luxx99** [comment]
How could you retry? to go ahead I've to restore the DB to a previous version - to have the version 4.4 working again - and than retry to upgrade YF. Is this your process?

**Comment by sbouillon** [comment]
Yes, restore and try again. The past upgrades went through without a hitch but this upgrade 4.4->5.0 release was not ready for prime time. It felt rushed and thrown together last minute. I had 25 installs fail out of 34 that I upgraded. Granted, 13 of those failed since the web server requirements website wasn’t updated (needing PHP-Intl)

**Comment by z0lo13** [comment]
absolutely same - nearly half of my installs were failing due to different factors, also cleaning up the database from excessive cache data helped. This update so far is very unstable and risky for applying on production, also new pdf maybe has better interface now but, does not support float rules, WYSIWYG is broken...
