### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#953]
I feel like I need kind of personalized (for each user) bookmarks, so every user can drop its favorite item (project, contact, other stuff).
How do you think guys?

**Comment by bpabiszczak** [comment]
this functionality has been in my mind for a long time. It’s not problematic to add it but to make it work well with other mechanisms because there are things in the system like defining the importance of a customer, a ticket etc. and adding something to your favourites means you want to monitor it. There are also labels that are similar. I will mark it as something for realization in the future, but it requires a lot of planning and needs to be well-thought.

Maybe you have a good idea of how this should function?

**Comment by bpabiszczak** [comment]
At the moment we simply don't have the time to add this functionality. We know we should add it, but it's low on our list of priorities.
