### ISSUE TITLE
Integrate yetiforce and freepbx

### ISSUE THREAD

**Issue by groupgloval** [YetiForceCompany/YetiForceCRM#9575]
I need to integrate yetiforce with FreePBX, what should I do?

**Comment by paula-w** [comment]
There is a built-in Asterisk integration in the system but we don’t use it (we saw some on GitHub using it though), it will ultimately be removed and substituted with a new one. Unfortunately, for the past few years nobody ordered full integration so it’s not in the system even though questions about it keep popping up on GitHub every now and then. We created a fundraiser campaign at Open Collective in order to collect funds for such functionalities, there is even a dedicated tier called “PBX contribution”. You can be the first to donate and maybe in a few weeks we’ll have enough donations to start working on the integration. 
Our Open Collective page: https://opencollective.com/yetiforcecrm
