### ISSUE TITLE
MH in Calculations

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#97]
Why do I need a column in the calculation of MH
What function it performs?
![calculations](https://cloud.githubusercontent.com/assets/1402355/5740733/f7d823ee-9c27-11e4-877a-019f1e223ea5.PNG)

In the rightmost column, you must add the name of the column DESCRIPTION

![calculations descriptions](https://cloud.githubusercontent.com/assets/1402355/5740785/98653568-9c28-11e4-88ef-052995f502fc.PNG)

And to add the unit next to the number

![calculations unit](https://cloud.githubusercontent.com/assets/1402355/5740798/ad0afb88-9c28-11e4-8dcd-c02c20187689.PNG)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
regarding your question about a column with MH... That's the place where you enter man-hours that are required in order to provide a service (by default it will be available only in services) and then on their basis tasks in projects will be generated and will define the estimated time needed to complete a project.
