### ISSUE TITLE
[Question] Removal procedure

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9726]
The client asked me: What module(s) will be removed in oncoming versions?
Well, do you have any plan like that? I guess someone wanna long term assurance of stability..

**Comment by paula-w** [comment]
This is @bpabiszczak  ‘s answer:

“If I had asked people what they wanted, they would have said faster horses.” - Henry Ford

It’s very similar in our case. If I had asked 5 years ago what the community needed, everyone would have wanted some extension or functionality. Nobody, except for the producer, thinks where the system is going to be in 2, 3, or 5 years. Nobody wants to spend their money on rebuilding the engine, increasing the quality, or optimizations…

Even if we remove something from the system, we believe this to be the better solution, than keeping that functionality. In this case our view will always be different that the end user’s view, because our goals are different. What matters for the user is that the module exists, and what matters for us is security and overall quality of the system. Sometimes we manage to achieve both when we replace an old module with a new one, but sometimes we don’t have enough time for that, or we know that sooner or later a different functionality similar to the removed one will be created anyway.

So to answer the question what will be removed from the next version [5.1] I have to say – NOTHING. This version will be released in a few days and it mostly fixes errors.

To answer the question about modules that we plan to remove in the future, the following modules will have to be rewritten due to their quality: 
- Workflow
- Vtlib (module installation)
- other small modules

We assume new versions of these modules will be released at the same time. 

We’re currently working on some significant changes in the appearance (many months of work) and even though the new appearance will be “raw”, the entire system will work and look brand new. Together with the new appearance we will fix and optimize all modules. Version 6.0 will include the new look, and in 2 – 3 weeks you will be able to see the progress online.
