### ISSUE TITLE
[bug] Relation broken

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9728]
Using Modules-Relation I added relation m:m Reservations > Employees. 
The result is I cannot use SELECT record (Employee) as it not showing on the list.

Cannot reproduce on YF test app as have no access to config files. If you can allow for adding relation we can see if we can trigger the same.

PHP 7.2, Debian 9 all extensions installed

**Comment by mariuszkrzaczkowski** [comment]
gitdev has the ability to add relations enabled
![image](https://user-images.githubusercontent.com/10198654/53713228-6dabfa00-3e4a-11e9-960d-d309421b8e43.png)

**Comment by waran70** [comment]
dev version works OK, but I am on v5 Stable. OK, will investigate and report back...

**Comment by konadrian** [comment]
This button doesn't exist in the stable version because adding relations between modules is:
- disabled by default
- is an increased risk activity

**Comment by waran70** [comment]
Gonna get it again. So, I installed again fresh 5.0 and got the same issue.... employees cannot be selected in other modules related lists, but can be added and then they are visible in the related list. 
The same is with UI10.. can add employee but not select... as the list of employees shows empty. 
Can you guys guide me?

**Comment by elvissaba** [comment]
Go to a file >>>> rootdir > config > developer.php

And edit to
....
'CHANGE_RELATIONS' => true,

**Comment by JohnMaverick** [comment]
Here is the same. I did create relation and when I try select employee from the related list it not showing any records. How to debug this? Logs showin nothing :(

**Comment by acsinsurancegroup** [comment]
@JohnMaverick Thank you I'm having the exact same issue in version 5.1 The issue I am having is using the Time Control module which we renamed Time Tracking for our purposes. In the Time module under the relation Company it has the Employee option which we use to associate the Time entry with a particular employee as well. The issue is when we go to the employee record and under the Time module in the summary area when we click on Time none of the Time records that we associated with that employee show up at all. See attached screenshots. 

![Screenshot from 2019-05-14 01-11-35](https://user-images.githubusercontent.com/42642523/57677584-c935f900-75ec-11e9-803b-d2fe0197a5df.png)

![Screenshot from 2019-05-14 01-12-46](https://user-images.githubusercontent.com/42642523/57677613-d7841500-75ec-11e9-8871-cc99fe082ca3.png)

![Screenshot from 2019-05-14 01-13-14](https://user-images.githubusercontent.com/42642523/57677630-e36fd700-75ec-11e9-8ac9-8c697c66162c.png)

How can I correct this, anyone?

**Comment by konadrian** [comment]
@waran70  @JohnMaverick Make sure that you set "Employed" status on records only when employees are visible

@acsinsurancegroup One issue one bug please create a new one

![image](https://user-images.githubusercontent.com/3193498/61197637-5fae9580-a6d6-11e9-9a47-9b4316b0f5a9.png)
