### ISSUE TITLE
Outgoing Server Can not support many smtp server

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#973]
I test many smtp server,but only one smtp server can be used.I do not know what 's the problem.but I test many smtp server at vtiger 6.2,it work well.

**Comment by mariuszkrzaczkowski** [comment]
1250572980@qq.com:
I test many email smtp server at  outgoing server of vtiger 6.2,it work well.I only test one success which is :
smtp.qq.com
1250572980@qq.com

YetiForceCRM is a great product,I am interest in it very greatly,maybe I have poor profession skills to set up the CRM.Iif YetiforceCRM config like Vtiger,I am glade to use it .

**Comment by bpabiszczak** [comment]
The outgoing mail server works properly, we configured it on hundreds of different servers, the most common problem is an incorrect server address [should be in this format:  protocol://serveraddress.com:port] as well as not entering an email address in From field. Besides, this issue is incorrect and doesn’t comply with the standards described here:

https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html 
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/115-debugging.html
