### ISSUE TITLE
filters + widgets substitute the old module in 95% [Question]           

### ISSUE THREAD

**Issue by cakrina** [YetiForceCompany/YetiForceCRM#9788]
@bpabiszczak commented "We expanded the filter mechanism to allow users to display data from other modules. On top of that, charts can handle data from other modules than the main module.In our opinion both mechanisms (filters + widgets) give you the old reports functionality (of course it’s not exactly the same thing, but it can substitute the old module in 95%)"
2 questions 
1. Not importent, just curious how did 95% was calculated.
2. Is there a documentation on using modules other the main. For example I tried to create either filter or widget to show Opportunities by Sold product, but failed as there is no way select linked products in Opportunities. This is very common for sales to current customers and this is just one. 
Or Opportunities Contact type. 
By the way there seam to be a bug as I cannot click on "Account - Accounts - Contact Info" in "Choose columns and order" when typed Contacts - selection is displayed but not clickable pls see attached screen ( this is on https://gitdeveloper.yetiforce.com/index.php?module=SSalesProcesses&view=List#)
![accounts_contact_screenshot](https://user-images.githubusercontent.com/42490929/53935595-f6d26380-40cc-11e9-9746-19a17f3fb798.png)

**Comment by paula-w** [comment]
This is @bpabiszczak  ’s answer:
1. Long term research conducted by Australian scientists ;)
2. Please describe how it used to work with the old reports module so we will be able to tell you if it’s possible to achieve the same result using charts and widgets, and how.
3. It’s not a bug, the names you see there are block names and you can only select fields.

There is no documentation right now, we’re planning to add it but we can’t tell you exactly when it’s going to be published.

**Comment by cakrina** [comment]
@paula-w
Considering how fast tickets are answered and closed without confirmation, I can only assume that Yetiforce company use response time and tickets closed per day/week as main KPI :) Can't even have conversation. 
@bpabiszczak asked "Please describe how it used to work with the old reports module so we will be able to tell you if it’s possible to achieve the same result using charts and widgets, and how." But the issue is closed, is this a normal procedure to resolve issue while it's closed ?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs

Yes, if we add questions. if we do not answer all your questions or misunderstand, then you must clarify the question, do not be afraid to ask. describe exactly what you need, we will understand it better and we will be able to help you

**Comment by cakrina** [comment]
The issue is not a bug. Link you've included is irrelevant.

The critical feature is missing.
Contradictory information is given on when it will be available and will it be available at all.
When requested information on how to use suggested workarround, there is no documentation or explanation for the simplest usecase.
Issues closed while question is unaswered.
Continue conversation in a CLOSED issue this one is not the first one. 
Developers reply with unexpected questions ( How did it use to work? ) I have no clue how it use to work. You're the developers you expected to know how it use to work. I'm a new customer and simplest usecase I described is unanswered. I can tell how it works in Salesforce, Bitrix24 and SuiteCRM, but not in Yetifoce because it's so "intuitive" that even developer doesn't really know.
I will not even mention details on 
![its_not_a_bug](https://user-images.githubusercontent.com/42490929/54016520-42f2d600-41a9-11e9-9824-fb84b3fcf953.jpg)
the classic "Its not a bug it's a feature..." 
Anyway, forgive my grumpy attitude. It's just very dissappointing to get a nicely looking cookie just to find out it's half way baked. Your assumption that "extended" filters replace 95% of report module is wrong. Expected tool whatever it may be filter/widget/report is one should be able view all information related to the module and even related to related module, in other words if there is a relation there should be a way to view it and record by record. Current filter show  very limited fields from related modules. So without reports Yetiforce is like a Car with good engine but without tires. 
In my opinion creation of Widgets/Dashboards based on filters is a poor disign it should rather be based on reports, unless filters would completely replace reporting functions. In other words if "filters" becomes "reports" then it's great.

**Comment by paula-w** [comment]
@bpabiszczak 's answer:

1. It doesn’t matter if the issue is closed or not, what matters is that we answer and want to help. Sometimes we close them „routinely”.  Instead of describing what we asked for, you focus on the issue status. What’s the difference if we talk in a closed issue? Perhaps there was nothing interesting enough in the discussion for us to reopen the issue. Remember that many people on GitHub (also people who are not our employees) can change statuses and open previously closed issues.
2. If you want to receive a substantive answer, please follow our instructions and instructions from issue templates. Unfortunately, the majority of what you wrote is you being „grumpy”.
3. So the steps are:
- describe in detail (from the business perspective) what you are trying to achieve (what data with what columns and from what modules you want to display)
- record a gif (using  https://www.screentogif.com/ for example) and show us how you are trying to do that.
Once you do that we will tell you if what you are trying to achieve is possible, and if it is, we will give you instructions on how to do that.

**Comment by cakrina** [comment]
I decide what's matter and what doesn't. I haven't settled on what CRM will be implemented and currently trying few CRMs (Bitrix24, SuiteCRM, Yetiforce). I don't want to invest time and money in product developed by team lacking support skills. As a potencial customer I'm not at all satisfied with issue handling. 
1. Important module is anounced to be work and progress and forcasted to be available in 4.5, 5.0 in one ticket, moved to 5.1 in another and declared not to be worked on in 3rd. As a result if I was initiator of the 1st ticket I would not get update on initial inquiry and would not know that feature is abandoned. Also I asked about the forcasted release date in order to find out that work is abandoned - so if i'm patient customer awaiting for the promissed feature I'd be waiting forever.
2. My question on use of "expanded" filters was generic and I used product-opportunity relation only as an example just to show how this "expanded filters" nowhere close to reports. When you claimed fields from other modules available - all related modules and preferably even all related to related modules should be available. But only limited fields from limited modules available. I'm not a tester to give you all user cases where "Expanded Filters" wouldn't cover business process.
3. Thanks for wanting to help, but at the moment I feel other way around - I want to help and not being taken seriously. My feedback is taken as grumpy complaint instead of constructive criticizm. 
4. For now I giving up on Yetiforce in favor of SuiteCRM. I have couple month before my input data is ready, will reconsider if reports will show up soon.
If you care to know my experience
1. Imports - poor, took a lot of try and fail in order to figure out the issues with date format, failures even using supplied by Yetiforce sample import file due to not matching user date settings with sample, only format supplied in sample and matching user date settings works.
2. Interface and customization - **excellent**. Love the menu customization per role!!!
3. Automation/workflows - poor, don't remember details but fields weren't updating on trigger and it wasn't intuitive
4.Report/Dashboards - poor reports module is missing, Dashboards built on top of filters instead of reports and thus missing data from related modules. There is only limited 1 level of relation, in other words no related to related information.
5. Documentation and community support - very poor. Feels like Yetiforce doesn't have too many users to share their experience
6. Customer support - poor, the only good I can say is fast response time...
7. Considering that this opensource project is run more by company and less by community and "it won't happen unless somebody pays" attitude gives me a feeling that this project can turn into commercial closed source product anytime. Which is not a big deal unless you've invested time and money implementing it to your company expecting open source and will have to either pay for the product or pay again to switch to another.

And lastly grumpy comment, I don't remember exactly who of your company mentioned that opensource is not free as there are costs of implementation etc. I heavily disagree with this statement as happy Linux user since 2002 I've personally used numerous linux projects and products without a dime invested in anything except for time learning but no more then any other payed product.

**Comment by paula-w** [comment]
@bpabiszczak 's response:
You decide what matters for you, we decide what matters for YetiForce and for the community; not from a single person perspective, but from the perspective of the entire project. 

On one hand you’re saying support is important for you and you feel disappointed with our support, on the other hand you’re saying that you chose Suite CRM, which has terrible support. Look at their GitHub, they have 750 opened issues (which is 25% of all the issues), some of them are 5 years old, and there are 500 issues labeled as errors. It doesn’t stop them from releasing versions marked as stable and LTS. Secondly, Suite is the worst choice because they breach license terms they inherited from SugarCRM. This product is released under one of the worst licenses business-wise, namely AGPL (more about AGPL here: https://github.com/YetiForceCompany/guides/tree/master/en/licenses). There are other, much better open source projects such as VtigerCRM or oroCRM. I wouldn’t recommend SuiteCRM to my worst enemy. 

YetiForce has 95% of the possibilities that reports used to provide, all relations that were available in the reports module are currently available in filters, the only difference is that in reports you first selected the main module and then subordinate modules, and in filters it works the other way round – from a subordinate module you can display fields from main modules (same outcome). 
For example, in Quotes you can display fields from Opportunities and Accounts. Then you can sort by any field, filter data, and export it to Excel, CSV, XML, even PDF. To be honest, the current solution gives you better possibilities than the reports module used to (for example relations between modules on more than two levels). What’s missing is a schedule for mailing reports and grouping reports (although grouping didn’t work properly in reports). If you have a business need like that, you can create many filters, add a new menu position labeled “reports” and add links directly to filters (what other system gives you these options?).

It already happened a few times that people came to GitHub to complain about our project, then went to complain about some other projects  (Suite, Vtiger), unfortunately it rarely ever helped and these people disappeared, probably to complain elsewhere. We try to help everyone, but some people don’t want our help, they just want to complain because that’s who they are. It’s up to you if this product gets even better and if you focus on what’s already there or on what’s not yet there.

We respect your decision as far as choosing SuiteCRM is concerned, and we wish you all the best!
