### ISSUE TITLE
phpError.log

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#981]
a lot of errors in the log

![errorlogc php](https://cloud.githubusercontent.com/assets/1402355/7929888/7c037572-091c-11e5-8eed-cc27de5fd02b.JPG)

**Comment by bpabiszczak** [comment]
We are aware of the amount of bugs related to php strict standards, they were inherited from Vtiger's engine and we are planning to remove them. These changes are related to plans that involve updates of the system to the most up-to-date standards.

**Comment by waw555** [comment]
How to turn off logging, and then one day accumulated 52GB

**Comment by mariuszkrzaczkowski** [comment]
The description of how to enable debugging can be found here: https://yetiforce.com/en/ideas,-changes,-bugs/bugs/115-debugging.html   But bear in mind that logs should be enabled on developer or testing version and should be disabled after the verification of an error because otherwise all actions performed in the system will be saved in logs. We constantly develop the mechanisms responsible for logs and they will take more and more space. Enabliing logs slows down the system.

**Comment by waw555** [comment]
How to disable logging?

in the php.ini file is written as follows

error_reporting = E_ALL & ~ E_NOTICE & ~ E_STRICT & ~ E_DEPRECATED
display_errors = Off
log_errors = Off

and still maintained a log

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/115-debugging.html

**Comment by mariuszkrzaczkowski** [comment]
We updated description of debugging, check the parameter display_errors  in file .htaccess
