### ISSUE TITLE
Ticket Marked "Closed"but issue not Resolved

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#9833]
I have a ticket that has been marked "Closed" but the issue has not been resolved ticket number - #9821

I was provided with a solution on this link (https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue++Locale) but when i click on the link, I get redirected back to the Question Tab or Page, and not to the fix.

My original question was for a fixed to: "Class 'Locale' not found" after I had reinstalled YetiForce.

**Comment by adudekyeti** [comment]
Hi,
You have closed ticket because your problem was a duplicate. This link show you all issues with the same problem. **To resolve your problem you have to install / turn on "intl".**

**Overthere you have all server requirements:**
List of mandatory libraries you can find below _"THIRD PARTY LIBRARIES CONFIGURATION"._
[https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)

Duplicate:
#9482
#9520
