### ISSUE TITLE
I can't upload the logo image or even add pictures to pdf templates

### ISSUE THREAD

**Issue by rtorrescodes** [YetiForceCompany/YetiForceCRM#9945]
Can someone help me please?  It dosent seems to be a permission folder issue. Yetiforce show folders permissions ok.  I tryied with different browser. When i choose the logo and click on update it just takes me back to the company info page but there is no logo changed.

Also, when i try to add a picture on the pdf template, i can see it on the preview, but when i save it, that html code is gone.  

I added my main domain to the $PURIFIER_ALLOWED_DOMAINS list (just the domain name, because YetiCRM is installer under domain.com/crm folder.

Any ideas please?

**Comment by z0lo13** [comment]
@rtorrescodes try to enter the code directly to the database

**Comment by rtorrescodes** [comment]
I dont think thats the best way to fix this problem. Any other idea?

**Comment by mlorencik** [comment]
The best way is go to Company > Departments and upload a logo in one record, then on the pdf template set logo from variables, somethink  like $(organization : 1|logo)$ where 1 is ID of your Department

**Comment by acsinsurancegroup** [comment]
Hello all. I am having an issue with the 5.1 latest version install not even displaying the YetiForce logo on the Login screen or inside once you login at the top left corner by the company name. Just shows a broken code type image and the word Logo underneath.

I right click on the where the image file should display and copy the image address which leads me to /public_html/layouts/resources/Logo/logo but at the end where it says logo there's no file extension whatsoever. Is that the issue and were would I change that so the Logo's show up?

Also, to clarify. I'm talking about the main business logo. Not based on departments or multi companies or anything like that. The Logo file you see when you are at the login screen and the logo file at the top left corner inside the dashboard.

Ever since the registration step was added this has been an issue. I believe that 4.4.0 was the last version that allowed you to properly setup your company Logo without issue. Surely this is an easy fix or am I the only one having this issue? Thanks :)
